### ISSUE TITLE
Changing Perspective 

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#100]
Great tool, Really! Thanks a million.
I couldn't  change perspectives objects (for example I wanted to add a measure to a perspective), is there any way to do this in TabularEditor?
If not, Do you have any plan to enable users to change perspective objects in TabularEditor?

Thank you in advance,
Arman

**Comment by otykier** [comment]
Hi Arman,
Glad you like the tool! You can change which perspectives an object is visible in, by selecting the object in the explorer tree (you can also multi-select by holding down CTRL or SHIFT), and then expand the "Shown in Perspective"-property in the property grid:

![image](https://user-images.githubusercontent.com/8976200/31374417-2d7116fc-ad9e-11e7-9552-10bfe789ba5c.png)

Alternatively, you can right-click the object and choose "Show in Perspectives" or "Hide in Perspectives":

![image](https://user-images.githubusercontent.com/8976200/31374440-4a83b128-ad9e-11e7-9e46-ab5e46898d7a.png)

This works for tables, columns, measures and hierarchies. If you have any further questions, don't hesitate to ask :-)

**Comment by ArmanFalah** [comment]
Perfect! Thanks for your detailed respond 
I was looking for a tool just like yours, I am glad that find TabularEditor.
Thanks again :)
