### ISSUE TITLE
Model.asdatabase file for deployment wizard

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#102]
Hi agian :)
I think it's a good idea to add a feature for creating Model.asdatabase file for deployment wizard.
sometimes you just have remote access to production server so if this is the case you cant deploy to production servers directly and I guess the only way is to transfer model.asdatabase file to the server and deploy it by Analysis service deployment wizard.

regards,
arman

**Comment by otykier** [comment]
That's a very good point and a great suggestion. I think the best way to handle this, would be a new option in the Tabular Editor Deployment Wizard, next to the "TMSL Script" button, such as this:

![image](https://user-images.githubusercontent.com/8976200/31459617-faabda82-aec3-11e7-9e7b-441d31cfce03.png)

I would also add this option to the Command Line for Tabular Editor. This would allow developers who prefer the "Save to Folder"-functionality of Tabular Editor, who are therefore unable to open and build the model in Visual Studio, to build their model using the Tabular Editor command line, and then deploy it using MSBuild or the AS Deployment Wizard.

**Comment by ArmanFalah** [comment]
Great, I think it is perfect!
By adding this option, TabularEditor covers all the ways to deploy a model and we can choose how to deploy model in different situations.
The other two file are really useful for developers who use Visual studio.
I'm looking forward to trying next release.
