### ISSUE TITLE
TFS / GIT / VSTS Integration with multiple json file CI build/release

### ISSUE THREAD

**Issue by JT-Brown** [otykier/TabularEditor#104]
I for one would be all for a TFS / VSTS / Git integration.  One thing that I can see right away (and has been mentioned on the roadmap) is the plan to break up the model.bim file into smaller json files for source control.  We have been absolutely struggling with this issue currently.  I am the senior architect for a vast number of content creators who are using Visual Studio to do their modeling and its a real hassle having to deal with changes to model.bim across a large number of contributors on multiple projects.

We've set up VSTS automated build / release agents so that any changes to the master branch in Git will automatically deploy to the pre-production test servers for internal SSAS development across several projects.  Having the ability to control the source like a database project (.dbproj) structure does would be absolutely awesome.

And to have that ability while being able to pull, branch, commit, push, pull request all within the tool in Git while being able to continue to do our CI automation would be phenomenal.

**Comment by marcosqlbi** [comment]
It would be nice to discuss with MS a standard to split the files, so that a possible future implementation of the same technique in SSDT would use the same standard.

**Comment by TabularEditor** [comment]
Adding to Marco's comment, I would also point out that source control integration is unfortunately one of those features, where the effort to implement is far larger than the benefit of having it directly in Tabular Editor, in my opinion. Don't get me wrong - I would love to see Tabular Editor become the one-stop-shop for Tabular modelling, but I think that right now, effort is better spent on other features.

If you don't mind switching between applications, you can actually set up a pretty good CI process today, by using Tabular Editor's "Save to folder"-functionality, while doing all check-ins/commits from Visual Studio's Team Explorer (or any other source control tool, that lets you work with files/folders). At some of our clients, we have set up automated build on check-in using VSTS, which uses the Tabular Editor command-line to automate the process of merging the "exploded" Model.bim folder structure into a Model.bim file, that is then subsequently deployed (also using Tabular Editor's command-line). This has the added benefit, that Tabular Editor outputs information about validation errors (for example, DAX syntax errors) during deployment, unprocessed objects and objects that don't conform to our Best Practice Rules.

A blog post with more details about how to establish CI with Tabular Editor and Visual Studio Team Services is in the brewing. In the mean time, if you have more questions about this, just shoot!

**Comment by otykier** [comment]
Adding to Marco's comment, I would also point out that source control integration is unfortunately one of those features, where the effort to implement is far larger than the benefit of having it directly in Tabular Editor, in my opinion. Don't get me wrong - I would love to see Tabular Editor become the one-stop-shop for Tabular modelling, but I think that right now, effort is better spent on other features.

If you don't mind switching between applications, you can actually set up a pretty good CI process today, by using Tabular Editor's "Save to folder"-functionality, while doing all check-ins/commits from Visual Studio's Team Explorer (or any other source control tool, that lets you work with files/folders). At some of our clients, we have set up automated build on check-in using VSTS, which uses the Tabular Editor command-line to automate the process of merging the "exploded" Model.bim folder structure into a Model.bim file, that is then subsequently deployed (also using Tabular Editor's command-line). This has the added benefit, that Tabular Editor outputs information about validation errors (for example, DAX syntax errors) during deployment, unprocessed objects and objects that don't conform to our Best Practice Rules.

A blog post with more details about how to establish CI with Tabular Editor and Visual Studio Team Services is in the brewing. In the mean time, if you have more questions about this, just shoot!

**Comment by openStove** [comment]
Is there a way in the meanwhile to save the modell configuration automatically locally before each deployment ?
This could be a workaround having the changes being tracked... until a nice Git integration is done...

**Comment by otykier** [comment]
> Is there a way in the meanwhile to save the modell configuration automatically locally before each deployment ?

Not sure I understand this question. Are you asking if it's possible to save the model *metadata* before each save or deployment? In that case, there's actually a very simple albeit limited solution: If you go to FIle > Preferences > General, and then check the "Save Model.bim backup" option (see screenshot below), Tabular Editor will store a zipped version of the .bim file in the specified folder (using the current date and time for naming the file).

![image](https://user-images.githubusercontent.com/8976200/55864553-0423b780-5b7d-11e9-8a0b-d95726559211.png)

This is by no means ideal, but if you just want to make sure to keep a version of the model metadata for every database save/deployment that is done from within the UI, then it could be useful.

In the short term, I want to improve this feature, so that you can deploy your model metadata to a server **and** save your model metadata back into the file structure (which would be under source control) simultaneously. See the discussion on #230 for more information.

> Any Idea when a git Integration could come ?

This is relatively low priority because we have existing tools to do the job (Visual Studio Team Explorer, TortoiseGit, Git Commandline).

**Comment by openStove** [comment]
I really would appreciate that feature too... since if a couple of people are working on the same model, its really needed.

Would it be possible as quick win, to push automaticallry the file in git after saving the backup ?
If a couple of developper are involved, it is difficult to ensure that everybody click on the commit button from git, would be better if tabular editor could take this part...

**Comment by otykier** [comment]
I am considering some improvements in this area. While I would like to avoid building specific Git functionality into Tabular Editor, I'm thinking to do something like this:

When you open a Model.bim file or folder structure, Tabular Editor will ask you if you want to connect to a "workspace" database - similar to Visual Studio. The idea is, that every time you click "Save", Tabular Editor will then simultaneously save to the file/folder AND the database.

For integration with version control, I'm going to improve the scripting functionality such that you can call external programs (git.exe) with parameters (current file/folder path), and display prompts to the user (commit message). See where I'm going with this? That way, users are free to create their own scripts that will enable them to git add/commit/push directly from within Tabular Editor. These scripts can then be saved as custom actions at the Model level, which will make them invokable through the UI. It will be possible to assign shortcut keys to custom actions as well.

The advantage of this approach, is that I don't force people to use git - any version control environment that has a CLI could be integrated. Think of it kind of like the "External Tools" functionality in Visual Studio.

**Comment by otykier** [comment]
Closing this issue, as this functionality will not be making its way into the open-source version of Tabular Editor.

However, Tabular Editor 3 will feature "workspace mode" from day 1 with Git integration planned later this year.
