### ISSUE TITLE
Name of data types

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#107]
Using the names of data types int64 / double / decimal is confusing.
Everybody understands int64, but decimal is currency in Pivot Table and Fixed Decimal Number in Power BI. Double is decimal in both Power Pivot and Power BI. 
It could be useful adding aliases, e.g.:
int64 / Integer / Whole Number
decimal / currency / Fixed Decimal Number
double / floating point / Decimal (Number?)

I'm not sure about the format, but Power BI users are incredibly confused here.

**Comment by otykier** [comment]
...and when you consider the localisation of Power BI / Power Query, things get even more confusing. I propose to show it like this, in Tabular Editor:

![image](https://user-images.githubusercontent.com/8976200/32047038-134aebf0-ba45-11e7-94cb-a3528f9276dc.png)

**Comment by marcosqlbi** [comment]
Great - I would add "Boolean / (true/false)" and "String / Text"!
