### ISSUE TITLE
Automatic Relationship Names

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#108]
One issue that we have been having is that relationship names are defaulted and can clash when two developers both create new relationships in their own branches, then merge into the develop branch. (We are using the folder method of serialization)

In order to solve this could we have TabularEditor automatically create a new name on creation / edit.

VS just creates a GUID, which may be the best option. However perhaps it would be better to name it in a descriptive way. E.g. Table1 - Table2 (Table1Field - Table2Field). This would always create a unique name even with multiple relationships between the same tables.

This descriptive method would then work the same way as all the other measures/columns in the model so I don't think this could cause any issues?

**Comment by otykier** [comment]
This is a good point. The TOM API used by Tabular Editor does not uniquely name a newly created relationship like VS does, and the Tabular Editor UI does not allow you to set the name of a relationship explicitly. The name shown in Tabular Editor, is not the actual relationship name, but just a value that shows which columns are involved and how they are related.

To make it consistent with VS, I will make sure that a new GUID is assigned as the internal relationship name, without changing anything in how the object is displayed in Tabular Editor.

As a temporary workaround, I noticed that if you cut (ctrl-x) a Relationship from the Tabular Editor tree, and then paste it back in (ctrl-v), the TOM API will actually assign a new GUID as the name of the re-inserted relationship. Not sure if this is a bug or a feature :-)
