### ISSUE TITLE
How can I import data from a file into Description/Annotations for a whole model

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#109]
Hi, not sure if this is possible with Advanced Scripting or not so just wanted to check. 

We are considering populating the Description or Annotations (not sure which just yet) from an external file into our SSAS model. Would this be possible using Advanced Scripting? If so any tips on how to get started? Thanks!

**Comment by otykier** [comment]
With the next version, this will actually be possible to do using just a single line of code in the Advanced Script editor. See [issue #106](https://github.com/otykier/TabularEditor/issues/106) for more details. I will post some sample code as well, when this version is released.

In the mean time, you can consider "generating" the script using something like Excel. So if you have a list of table names, measure names and the descriptions you want to add to the model, you should concatenate these into code that looks like this:

```csharp
Model.Tables["Reseller Sales"].Measures["Reseller Total Sales"].Description = "This measure is used for xxx...";
Model.Tables["Reseller Sales"].Measures["Reseller Total Sales Last Quarter"].Description = "This measure is used for xxx...";
Model.Tables["Reseller Sales"].Measures["Reseller Total Sales Last Year"].Description = "This measure is used for xxx...";
```
You can drag and drop an object from the Explorer tree into the script editor, to see what the code to access the particular object should look like. When you put a "." (dot), the script editor should show a list of properties you can access:

![image](https://user-images.githubusercontent.com/8976200/32173828-6a2ecb76-bd3d-11e7-85d1-db2eefa9d156.png)

You can also set an annotation value on an object by calling:

`Model.Tables["Reseller Sales"].SetAnnotation("AnnotationKey", "AnnotationValue");`

Hope this helps :-)

**Comment by o-o00o-o** [comment]
Really helpful thanks!
