### ISSUE TITLE
Detect conflict between RLS and OLS

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#113]
If a user belongs to two roles applying filters on the same table with row level security (RLS) in one role, and object level security in another role (OLS), the connection is not possible by design.

> you can’t have RLS and OLS on the same table in different roles – that would prevent the connection from being opened

A Best Practices Analyzer rule could identify the presence or roles applying different filter types (RLS/OLS) over the same tables. If the developer knows that this will never happen (because a user cannot belong to two incompatible roles), there should be a way to disable the BPA (what could we use for that? Special annotations?).

**Comment by otykier** [comment]
This issue was moved to TabularEditor/BestPracticeRules#6
