### ISSUE TITLE
Accessing Child Classes in Best Practice Analyzer

### ISSUE THREAD

**Issue by Gezahegne** [otykier/TabularEditor#115]
I am wondering if there is a way to access child classes in Best Practice Analyzer. For example, I want to create a rule for my Connection String. I know the property is available in the ProviderDataSource class which inherits from the DataSources class. Can you please advice on how to achieve this?

**Comment by TabularEditor** [comment]
[Dynamic LINQ](https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions) does not currently support casting, which means we cannot access properties of derived classes in the current build. I will provide a workaround in the next release.

**Comment by otykier** [comment]
You can now create rules for ProviderDataSource and StructuredDataSource directly, which should hopefully solve the problem for now.
