### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#117]
In a few cases, I've seen Tabular Editor run to very high CPU usage - even when idle. For example, when a user is logged into a terminal server, spins up Tabular Editor, opens a model and then subsequently disconnects from the server. After some time, the CPU usage of Tabular Editor will be high even when the user is disconnected.

Has anyone else noticed something similar? @SQLBent perhaps?

**Comment by dmgdotnet** [comment]
I'm seeing this as well at all times while Tabular Editor is open. Seems to hover about 16% on XEON cpu.

**Comment by otykier** [comment]
Located the issue. Tabular Editor's UI uses an [ActionList](https://github.com/lextm/ActionListWinForms) to manage the state of toolbar buttons, menu items, etc. This state is updated in an `Application.Idle` event handler, which calls the `Update` method on each Action that has been added to the ActionList.

In the `Update` method of an Action, we should make sure that the code does not add additional messages to the queue, as this would cause the `Application.Idle` event to fire over and over. Unfortunately, [this code](https://github.com/otykier/TabularEditor/blob/master/TabularEditor/FormMain.cs#L495-L516), which updates the icon on the Save button, does exactly that. The code has been moved elsewhere, as there is no reason to examine the value of `UI.File_SaveMode` on every `Application.Idle` cycle. On my machine, this causes Tabular Editor's CPU usage to drop to 0% when idle.

New release containing this fix will be published soon.
