### ISSUE TITLE
Corrupt Model.bim

### ISSUE THREAD

**Issue by simonnuss** [otykier/TabularEditor#119]
Hi guys

I tried using the tool today for the first time and it corrupted my model.  I can still load it in Tabular Editor which is great (I actually prefer it over VS!) but VS2017 15.4.5 outputs the below error message.  I can provide the model.bim if requested.

============================
Error Message:
============================

An error occurred while opening the model on the workspace database. Reason: Must specify valid information for parsing in the string.

============================
Call Stack:
============================

   at Microsoft.AnalysisServices.VSHost.VSHostManager.PrepareSandbox(Boolean newProject, Boolean& isRefreshNeeded, Boolean& isImpersonationChanged, Boolean& saveRequired, List`1& truncatedTables, Boolean isRealTimeMode, Int32 clientCompatibilityLevel)
   at Microsoft.AnalysisServices.VSHost.Integration.EditorFactory.CreateEditorInstance(UInt32 grfCreateDoc, String pszMkDocument, String pszPhysicalView, IVsHierarchy pvHier, UInt32 itemid, IntPtr punkDocDataExisting, IntPtr& ppunkDocView, IntPtr& ppunkDocData, String& pbstrEditorCaption, Guid& pguidCmdUI, Int32& pgrfCDW)

============================

Thanks,
Simon

**Comment by otykier** [comment]
This can happen when the Model.bim.layout file gets out of sync with the content of the Model.bim file. If you delete the Model.bim.layout file prior to opening in Visual Studio, you should have no issue (although the layout of measures in the grid will be reset).

**Comment by otykier** [comment]
If deleting the Model.bim.layout file doesn’t help, it could also be a synchronization issue between the Model.bim file and the workspace database. In that case, try to deploy your Model.bim file to the workspace database from Tabular Editor, before opening in Visual Studio. If using an Integrated Workspace, you should set the Workspace Retention to “Unload from memory”, and then restart Visual Studio (to make sure your model is loaded from the .bim file only the next time you open it, ie. no workspace sync).

**Comment by simonnuss** [comment]
Neither solutions worked unfortunately.  I'm happy to supply the model.bim if you'd like to check.  It's DirectQuery so it's only ~200KB.

**Comment by otykier** [comment]
One more thing to try first, please: Create a new Tabular solution in VS, and replace the empty Model.bim file with your file before opening it.

**Comment by simonnuss** [comment]
Same error, unfortunately.

**Comment by otykier** [comment]
Ok, that's something new. Could you mail me the model: otykier@gmail.com ?

**Comment by simonnuss** [comment]
Sure, sent.

Thanks for assisting Daniel!  Don't worry if you can't recover it because I can redo the work.  I just wanted to highlight something unusual.

**Comment by otykier** [comment]
Yea, it's weird though. I can easily deploy the model to an AS instance through Tabular Editors, but then if I try to create a new VS project by importing the deployed model, I get the same error. So I'm thinking this is more a bug in VS actually, since the AS server didn't throw any errors when deploying. If you try to deploy the model through Tabular Editor, are you able to process the model and subsequently query it?

Can you remember what change you made in Tabular Editor that caused the file to become unloadable in VS?

**Comment by simonnuss** [comment]
I can't remember what change I did to make it unstable, sorry mate :(

I can query the model when deployed using Power BI with no problem.
Process Full in SSMS results in an error though (i only just noticed this
when you suggested it):

===================================

Must specify valid information for parsing in the string. (mscorlib)

------------------------------
Program Location:

   at System.Enum.TryParseEnum(Type enumType, String value, Boolean
ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at
Microsoft.AnalysisServices.BackEnd.ImplicitMeasureParser.GetAggregation(String
expression)
   at
Microsoft.AnalysisServices.BackEnd.DataModelingMeasureCollectionTabular.LoadMeasure(Measure
tomMeasure)
   at
Microsoft.AnalysisServices.BackEnd.DataModelingMeasureCollectionTabular.<ReadFromServer>d__0.MoveNext()
   at
Microsoft.AnalysisServices.BackEnd.DataModelingObjectCollection`1.Load()
   at
Microsoft.AnalysisServices.BackEnd.DataModelingMeasureCollectionTabular..ctor(DataModelingSandboxTabular
impl)
   at
Microsoft.AnalysisServices.BackEnd.DataModelingSandboxTabular.InstantiateMeasureCollection()
   at Microsoft.AnalysisServices.BackEnd.DataModelingSandbox.Open(String
precachedErrors, Boolean lightweight)
   at
Microsoft.AnalysisServices.ManagementDialogs.ImbiProcessDialog.DoPreProcessExecution(RunType
runType, ExecutionMode& executionResult)
   at
Microsoft.SqlServer.Management.SqlMgmt.SqlMgmtTreeViewControl.DoPreProcessExecutionAndRunViews(RunType
runType)
   at
Microsoft.SqlServer.Management.SqlMgmt.SqlMgmtTreeViewControl.ExecuteForOlap(PreProcessExecutionInfo
executionInfo, ExecutionMode& executionResult)
   at
Microsoft.SqlServer.Management.SqlMgmt.SqlMgmtTreeViewControl.Microsoft.SqlServer.Management.SqlMgmt.IExecutionAwareSqlControlCollection.PreProcessExecution(PreProcessExecutionInfo
executionInfo, ExecutionMode& executionResult)
   at
Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.RunNow(RunType
runType, Object sender)


Simon

**Comment by simonnuss** [comment]
I just dug through my source control (OneDrive :) ) can found the most
recent working version.  Please see attached.

**Comment by otykier** [comment]
I think I located the issue.

For some reason, the "Simple Measure" property on the [Min Date] measure in your 'Date' table was set to True. This doesn't seem to be supported in VS, or perhaps VS expects some annotation to be set as well when using simple measures. Setting the property back to False in Tabular Editor, and the model loads without issue in Visual Studio.

**Comment by simonnuss** [comment]
Wonderful, thanks mate!

I do remember looking at that thinking, "what on earth is a Simple Measure", around about the time that the model broke.  I don't think I changed anything although evidently I must have.

**Comment by otykier** [comment]
I must admit, I have no clue what they are used for either (the property grid simply exposes all public properties of the object selected in the tree). [IsSimpleMeasure is documented here](https://msdn.microsoft.com/en-us/library/microsoft.analysisservices.tabular.measure.issimplemeasure.aspx) but I'm none the wiser. Perhaps I should change the description in Tabular Editor to: "If you set this property to true, Visual Studio will no longer load the model." 😃 

@marcosqlbi - do you have any idea what the IsSimpleMeasure property is used for? Would it make sense to hide it in the property grid?

**Comment by simonnuss** [comment]
Ah, they're implicit measures!  These are measures generated by clients tools, e.g. Power Pivot, when a user drags a column into the "Value" box.  In these instances Vertipaq thinks, "Oh the user dragged something into the Value box, so I'm going to make a measure for it and hide it in their model because I'm a jerk".

**Comment by otykier** [comment]
Hiding the "Is Simple Measure" property in 2.7
