### ISSUE TITLE
Cancelling a deployment

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#120]
If accidentally deploying to a model that is currently being processed, Tabular Editor will just hang (with the spinning "Deploying..." dialog) until the model has finished processing. It should be possible to gracefully cancel the deployment in this case, instead of using Task Manager to kill Tabular Editor.

Also - the "Deploying..." dialog should not show on top of all other applications... 😆

**Comment by otykier** [comment]
Fixed in 2.8.1. Thanks @albertospelta !

**Comment by albertospelta** [comment]
Glad to help! Thank you for your wonderful job with this tool!
