### ISSUE TITLE
Missing Format Types

### ISSUE THREAD

**Issue by simonnuss** [otykier/TabularEditor#122]
In Tabular Editor, selecting a measure and navigating to "Format String" -> "Format" yields the following: Custom, General, WholeNumber, DeciminalNumber, Currency, Percentage, Scientific.

VS, however, provides the same options but also "Date" and "TRUE/FALSE".

Can you please add these extra options to Tabular Editor?

Thanks,
Simon

**Comment by otykier** [comment]
Hi Simon,
These are the formatting options available for numeric data types (Int, Currency, Float) and for the "Unknown" data type. For columns with data type DateTime, you will have the following options:
![image](https://user-images.githubusercontent.com/8976200/33490844-aefb5b9a-d6b8-11e7-9e18-d48bccab4797.png)
For Boolean columns, I'm not sure that the format string has any effect at all.

**Comment by simonnuss** [comment]
No worries, I just thought the difference between the two tools was unusual.  FYI, my example was on a measure (not a column) of  Data Type = Unknown.
