### ISSUE TITLE
Saving as PBIT file results in an corrupt file

### ISSUE THREAD

**Issue by jaapp** [otykier/TabularEditor#123]
When opening a BIM-file and saving it as a PBIT file a corrupt PBIT file is created.

The exported PBIT file is not a zip-archive with the expected content(DataMashup, DataModelSchema, DiagramState etc. etc.), but is only a JSON file with the model-definition inside it.

I tried to copy this exported PBIT file into an empty PBIT I generated with PBI Desktop, by replacing the DataModelSchema file but this didn't result in an valid file as well. (FormatException: Input file or data stream does not conform to the expected file format specification.)

**Comment by marcosqlbi** [comment]
I think you should save as PBIT only a file you originally created as PBIT from Power BI Desktop. Maybe a restriction should be implemented in the UI so that you will not create a wrong file this way.

**Comment by jaapp** [comment]
That's too bad. We're trying to convert a model created in visual studio (live connection) to a model inside a report (using import mode). So this might not possible using TabularEditor? Any idea ho I could achieve this goal?

**Comment by otykier** [comment]
Unfortunately, Power BI does not provide an API like Analysis Services does, so I don’t think there’s any “safe” way of creating a .pbit file from scratch or through any kind of scripting/automation.

What you could consider, is to create import the base tables using PBI Desktop, then save as a .pbit and then do the fine-tuning in Tabular Editor: That is, create measures, add calculated columns, hierarchies, etc. to the data model. You can copy and paste these objects between two instances of Tabular Editor, but note that some properties (DisplayFolder for example), might cause issues in the .pbit file.

**Comment by jaapp** [comment]
I also haven't had any success saving a altered model based on an existing PBIT back to the file. The end result is always a ASCII file, not a zip-archive.

**Comment by fmms** [comment]
@jaapp  For producing the PBIT file and extracting it, you might want to look at https://github.com/kodonnell/powerbi-vcs

**Comment by marcosqlbi** [comment]
Tabular Editor already uses that technique - the library you referenced doesn't solve the problem of creating a PBIT from scratch.

**Comment by otykier** [comment]
Removed the "*.pbit" option from the "Save As..."-dialog, as it is not currently possible to create a .PBIT file from scratch (opening an existing .PBIT file and using the regular "Save"-option will still work, however).

**Comment by marcosqlbi** [comment]
Well, if you open a PBIT file how do you save it with another name? It seems to me that now you are forced to rename the PBIT in advance. Would it be possible to remove the *pbit option only if you don't open an existing PBIT?

**Comment by otykier** [comment]
You’re right. “Save As...” should work for PBIT when such a file was opened in the first place. Will provide a fix shortly.
