### ISSUE TITLE
[Enhancement Request] Ability to copy/move a measure from 1 table to another

### ISSUE THREAD

**Issue by byobi** [otykier/TabularEditor#124]
As a developer, I'd like to be able to quickly copy (several hundred) measures (across 3 fact tables) to a new "measures" table in order to control the presentation order in the field explorer window of my target reporting tools (Power BI)

**Comment by otykier** [comment]
Hi Bill,

You can already copy measures using CTRL+C / CTRL+V. It works with multiselect and across tables. Even between instances of Tabular Editor.

Or maybe I’m misunderstanding your request?

Best regards
Daniel

**Comment by byobi** [comment]
No, you're probably not misunderstanding... I tried dragging a measure from one table to another and it didn't work.

I'll try ctrl c/v when I get back home.

Thanks for the quick response and awesome tool!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by byobi** [comment]
amazing! Copypasta works! my newest favorite tool!

**Comment by otykier** [comment]
Glad you enjoy it - let me know if you think of any other improvements or encounter any bugs :-)
