### ISSUE TITLE
Paste with replace tables wrongly renames table names in measures referencing it

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#128]
If I replace a Date table using the Paste command, I see that measures referencing Date[Date] are broken. This is the code I found:
'Date-ed5ea3c1-20ac-4220-bd5d-0cc085fef8eb'[Date]

Such a table name doesn't exist. Is here some other issue I cannot see?

**Comment by otykier** [comment]
Oh bugger - seems I didn’t test this well enough. This happens because the original table is renamed prior to the insertion of the new table, so Formula Fix-up screws up all existing references. Should be easy enough to fix, so I will get on it ASAP.

**Comment by otykier** [comment]
Fixed in [latest build](https://github.com/otykier/TabularEditor/releases/latest).
