### ISSUE TITLE
2.7 deploying to existing database

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#130]
When deploying to an existing database, it renames the database to 'SemanticModel'. Deploying to create a new database does not have this issue. This was not an issue in 2.6 but is an issue in 2.7

**Comment by otykier** [comment]
Hi kalmenk. Thanks for reporting this - I uploaded a [new build of 2.7](https://github.com/otykier/TabularEditor/releases/tag/2.7) where the issue has been fixed.

**Comment by kalmenk** [comment]
@otykier Thanks for the quick fix! Tried it out and all is well in the new 2.7.
