### ISSUE TITLE
Open from folder

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#132]
We have 1 user that has an issue with the UI when opening from folder but it works fine when opening from File. Other users have no issue with open from folder. Here are some screenshots, let me know what other info you need.

**Open from Folder**
![openfromfolder](https://user-images.githubusercontent.com/2540043/36653937-c412148e-1b04-11e8-8449-cb9fbdd13ecf.png)

**Open from file**
![openfromfileordb](https://user-images.githubusercontent.com/2540043/36653977-0ceb2470-1b05-11e8-8ae1-1cbae0b40400.png)

**Comment by otykier** [comment]
That’s weird! I assume this particular user is using the same build of Tabular Editor as those of you who are not seeing the error?

Things to try:

* Delete the Preferences.json file in the %AppData%\Local\TabularEditor folder
* Create a new (blank) model, add a few tables and then save to folder. Does the bug also happen when loading this model from folder?
* Delete the TOMWrapper.dll file in the %ProgramData%\TabularEditor folder and if that doesn’t help, reinstall Tabular Editor

Let me know how it goes!

**Comment by dmgdotnet** [comment]
Thanks! We'll give this a shot and report back. We are all on the same version yes. We were minor version behind the latest but all updated now.

**Comment by dmgdotnet** [comment]
We tried all these steps but still have the same issue.  Also confirmed on another machine (4th total now) that this issue wasn't happening so looks specific to the one installation. Not sure how best to debug this one, very strange issue indeed!

**Comment by otykier** [comment]
What was the result of creating a blank model?

**Comment by dmgdotnet** [comment]
Same result unfortunately, created a new blank model and saved to folder, open from folder and still have the blank tree.

**Comment by dmgdotnet** [comment]
Looks like we found an obscure resolution for this. We changed the windows scaling from 150% to 100% and this fixed the issue. Wasn't an immediate consideration for us as the display was fine opening from db or file.

**Comment by teasot** [comment]
I was able to reproduce this issue by increasing my scaling. 
There is something about "Open From Folder" which specifically causes the entire window to rescale.

For example, here is me about to click the "Open From Folder" button. Note the large font size as a result of the scaling.

![image](https://user-images.githubusercontent.com/8462929/38593639-bd0917c0-3d85-11e8-89ab-b39cedba6596.png)

Once I click the button (when the window for selecting the folder appears, before I open the folder itself), the window itself changes its scaling to a different size and location (I have tried to keep the screenshot below covering the same real-estate, to show the different scale):

![image](https://user-images.githubusercontent.com/8462929/38593661-e1eb970c-3d85-11e8-9aa9-9c4ebd60761c.png)

I am presuming that some code called by the button is forcing the scaling of certain elements of the window to change, causing the issue.

Please note, that one workaround is to not use the open from folder, but instead open the .bim file contained in the folder, which will load from the folder without causing the scaling issues.

**Comment by otykier** [comment]
Thanks a lot for looking into this! I must admit that I haven't done any testing in a high-DPI environment, and since this is a WinForms application the scaling issues are not really surprising. I will see if there is a compile option or app.manifest configuration that can be used to keep the scaling even when using [components from the Windows API Code Pack](https://github.com/aybe/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Shell/CommonFileDialogs/CommonOpenFileDialog.cs).

**Comment by otykier** [comment]
Looks like all I had to do was to set the following in the app.manifest file:

```xml
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
  </windowsSettings>
</application>
```

Testing this on a high-DPI environment, everything looks good, even after invoking the "Open from Folder" dialog:

![image](https://user-images.githubusercontent.com/8976200/38620101-84db5c06-3d52-11e8-812f-b63837176886.png)

**Comment by otykier** [comment]
I created a [pre-release with this fix included](https://github.com/otykier/TabularEditor/releases/tag/2.7.6675). @dmgdotnet @teasot - it would be helpful if you have a chance to download it to see if this solves the problem on your environments as well.

**Comment by teasot** [comment]
I can confirm that at least the scaling does not change when opening the "Open Folder" dialog, which is a very hopeful sign.

I will confirm the issue is resolved once I get to work tomorrow - it turns out my home computer does not acknowledge the AMO classes I have installed on it!

**Comment by teasot** [comment]
I have tested the new build, and both the open file and open folder dialogs cause no issues when opening at either 150% or 100% scaling. 

Thank you for your assistance with this! Although it does not affect me (I use 100% scaling), my co-workers computers are all 150% by default, which could cause issues if we choose this option for managing the models, so I am very happy it is resolved.

**Comment by dmgdotnet** [comment]
This is solved for our user as well, thanks!
