### ISSUE TITLE
Database compatibility level Error 

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#141]
We have an issue with 1 of 3 users, the error happens when navigating to a measure in the tree and selects a measure.  We are using compat level 1200 and have never used 1400 on the machine in question.  Machine is using SQL 2016 sp1.

************** Exception Text **************
System.InvalidOperationException: The database compatibility level of 1200 is below the minimal compatability level of 1400 needed for [model 'Model'].[table 'Fact_Orders']::[DefaultDetailRowsDefinition].
   at Microsoft.AnalysisServices.Tabular.MetadataObject.ValidateCompatLevelRequirement(Int32 compatLevelRequest, String requestingPath)
   at Microsoft.AnalysisServices.Tabular.Table.set_DefaultDetailRowsDefinition(DetailRowsDefinition value)
   at TabularEditor.TOMWrapper.Table.set_DefaultDetailRowsExpression(String value)
   at TabularEditor.TOMWrapper.Table.set_Expression(String value)
   at TabularEditor.TOMWrapper.Utils.DaxDependencyHelper.SetDAX(IDaxDependantObject obj, DAXProperty property, String expression)
   at TabularEditor.UI.UIController.SetText(String value)
   at TabularEditor.UI.UIController.ExpressionEditor_AcceptEdit()
   at TabularEditor.UI.UIController.ExpressionEditor_Preview()
   at TabularEditor.UI.UIController.TreeView_SelectionChanged(Object sender, EventArgs e)
   at Aga.Controls.Tree.TreeViewAdv.OnSelectionChanged()
   at Aga.Controls.Tree.TreeViewAdv.set_SuspendSelectionEvent(Boolean value)
   at Aga.Controls.Tree.NormalInputState.DoMouseOperation(TreeNodeAdvMouseEventArgs args, Boolean focusOnly)
   at Aga.Controls.Tree.NormalInputState.MouseUp(TreeNodeAdvMouseEventArgs args)
   at Aga.Controls.Tree.TreeViewAdv.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.7.6655.17917
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.5.6655.13206
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.11.0
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.5.0.0
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.7.6655.17917
    CodeBase: file:///C:/Users/mus/Desktop/TabularEditor%20(2).exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.800.117 ((BI_ASEngine_Dev).170802-0900)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.AnalysisServices.Tabular/v4.0_14.0.0.0__89845dcd8080cc91/Microsoft.AnalysisServices.Tabular.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.800.117 ((BI_ASEngine_Dev).170802-0900)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.AnalysisServices.Core/v4.0_14.0.0.0__89845dcd8080cc91/Microsoft.AnalysisServices.Core.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by otykier** [comment]
Thanks for reporting this - a fix will be published very soon.

**Comment by otykier** [comment]
Repro steps in #143
