### ISSUE TITLE
Store References to "additional" DLLs in Custom Actions

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#142]
Currently, **System.dll**, **System.windows.forms.dll**, **System.Core.dll** and the native Tabular Editor DLL are available for use in custom actions. 

While these are useful (I am currently using it to create a TOM model from the existing TOMWrapper object and comparing it to an external TOM model), it would be great if we could reference a number of traditional DLL files such as **System.Data.dll** and **System.Xml.dll**.

Modifying the "**TabularEditor\Scripting\ScriptEngine.cs**" file, I am able to manually add these DLL's to my custom actions, to allow things like SQL calls and XML parsing. 

However, modifying the source code every time I want my Custom Actions to reference a new dll is hardly convenient - I was wondering if there was a way for the (custom) referenced dlls to be stored in the custom action itself, and then these merged with the "Core" dlls ( **System.dll**, **System.windows.forms.dll**, **System.Core.dll**  plus the Tabular editor DLLs)?

I know this seems like a complex requirement, but it will effectively allow us to develop our own features on an ad-hoc basis. For instance, we could add an action to deploy the model, then set up a job to process it daily on a preset SQL server, or fetch/synchronise metadata from a web service...

**Comment by teasot** [comment]
After raising this issue, I discovered plugins, which satisfy pretty much all of my needs.

As a result this is a far lower priority, although it would still be convenient (a good example would be using an external DLL to fetch data from an arbitrary data source based on its type).

**Comment by otykier** [comment]
Hi teasot. I'm really impressed with what you managed to figure out on your own - as you no doubt have realised by now, this stuff is very poorly documented.

Now, I was indeed going to suggest that you use plugins for this kind of stuff. On the roadmap, I plan to add support for [CSX scripts](https://msdn.microsoft.com/en-us/magazine/mt614271.aspx), to provide more flexibility for users of the Advanced Scripting functionality.

Using CSX, you could write something like:

```csharp
#r ".\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll"
using System.Windows.Forms;
using Newtonsoft.Json;

public class MyClass {
    public void DoSomething() {
    // ...
    }
}

var myClass = new MyClass();
myClass.DoSomething();
```

As you can see from the code above, this lets you import any DLL's you need, and at the same time you will have access to the entire .NET framework. CSX is gaining more and more popularity - it's also being used by [Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp), so I believe this is definitely the right way to go. And also, it would be "backwards compatible", with the current scripting engine, so any existing scripts users have today, will still work after I switch the script engine to CSX.

Kindly let me know your thoughts :-)

**Comment by teasot** [comment]
This satisfies my needs perfectly.

Thank you very much - I am perfectly willing to wait for the relevant release.

**Comment by otykier** [comment]
Closing this issue, as the CSX feature is already on the backlog :-)
