### ISSUE TITLE
Additional Hourglass for Save to folder action

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#145]
An enhancement suggestion for the UI when saving to folder is to add an extra hour glass for this action. While the action is usually pretty fast, <2 secs or so, there are instances when this can take longer due to high resource usage on local machine from other applications.

![image](https://user-images.githubusercontent.com/2540043/38798500-ad42a9a0-4159-11e8-90ef-abe5e47abc91.png)

**Comment by otykier** [comment]
Thanks for this suggestion. Added it to 1.7.1 which will be published later today.

**Comment by dmgdotnet** [comment]
Great and thanks!

PS, would you prefer a pull request for minor suggestions such as these?

**Comment by otykier** [comment]
Pull requests are always more than welcome. No need for this particular issue, but if you encounter anything else - feel free!
