### ISSUE TITLE
Add support for 1103 Compatibility Level models

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#148]
As discussed in issue #147, we are both keen to add support for 1103 (and possibly 1100 models, though do not hold your breath) models.

I am raising this issue to keep track of my progress in adding this feature, and to allow discussion of code standards etc, as well as unique requirements such as compatibility with BIDS, Tabular Actions, and compatibility with Visual Studio.

**Comment by teasot** [comment]
Firstly, progress is going smoothly. I have the ability to save 1200 and 1400 models (although, only valid features from them) to 1103, and now am moving onto the far simpler task of opening the model from the file.

Secondly, here are some discussion points to ponder:

1. Unlike in 1200, Visual Studio does not natively support valid 1103 models (astonishingly!). Instead, it reads a large amount of information through custom annotations. These significantly increase file size and make source control an utter nightmare. As such, these annotations, including compatibility annotations like BIDS (needed for display folders, etc) and query serialisations will have the option to be ignored, for a more compact BIM file. I still need to experiment to see if the build succeeds, but I can confirm that the models can be deployed directly.

2.  I will be creating a github project with the same functionality (TOMtoAMO). Do we want to reference a DLL to this once I create it, or simply copy the code? I am leaning towards the latter (otherwise, we need to keep .NET and references in sync). The argument for using the DLL instead would be that reading from/writing to 1103 is needlessly complex and having you maintain it may be a hassle (though you could just copy the code every so often to get the latest). I will create the library before adding it to TabularEditor.

3. Some features like HideMemberIf and Tabular Actions were actually removed in 1200+. Do we want to support these in annotations?

4. Others, like comments in measures, are perfectly valid, but not supported for some absurd reason. Should we give warnings about this?

5. Some supported features, even when created natively in 1103, can cause issues. Already, while testing this, I am unable to set the format of KPIs. Do we want to provide warnings if the user uses these features?

5. 1103 is not recommended to be used if 1200 or above is available. I feel it would be worthwhile warning users of this if they attempt to create an 1103 model (and give them a chance to back out, even!) although obviously not when opening them

6. Because this will effectively allow downgrading/upgrading models, perhaps we should be a bit more liberal with the version, allowing them to freely downgrade or upgrade their database via the properties panel, albeit with the deletion of stuff which is not valid for the new version, and a warning that we will be doing that.

7. We should look at retaining open from folder functionality for 1103.

8. Command line option for upgrading/downgrading .bim files and/or solutions.

**Comment by teasot** [comment]
On the note of converting PBIT to Tabular, I have actually previously taken the nasty route of migrating PBIX files to Tabular 2017.

You can extract the M queries from the DataMashup file - it is cannily hidden away as metadata, rather than as a file in the zip

![image](https://user-images.githubusercontent.com/8462929/38936506-46bb40a4-4364-11e8-88fc-f94561eeb941.png)

Once you parse this (enjoy parsing XML in a non XML document :-D) you have the M queries (and hence the partitions), the tables, and the measures/columns/hierarchies.

This only leaves the datasources. Now, PowerBI has completely different data sources to Tabular 2017. However, as they share M queries as the method of fetching data, you actually can detect, by parsing the m query, what data sources are required to create a functioning 2017 model.

Parsing m queries is not fun at all, but certainly is possible, and I have successfully migrated several to Tabular via this method.

But this is another discussion for another day!

**Comment by teasot** [comment]
[Deleted previous comment as off topic]

As an update, I have managed to open an 1103 model (with only tables, hierarchies, levels, columns, measures and translations being loaded).

Firstly, as 1103 and below is a unique case, and unable to be directly stored in the metadata (setting the compatibility level of a TOM database to 1103 or below causes an error), do we want a version annotation to be added if it is 1103 or below? That way, when we go to save, we know to save to an AMO or TOM database.

Secondarily, when opening from an 1103 model, I have encountered a column being highlighted blue, of all things. Have you seen this before?

![image](https://user-images.githubusercontent.com/8462929/39227306-48c21f12-489b-11e8-90cc-57a20cb84da8.png)

**Comment by otykier** [comment]
Nice work, Anthony!

In the TOMWrapper, we can control which properties are shown in the PropertyGrid through the IsReadable and IsEditable methods. Some objects use the Compatibility Level setting to ensure that 1400 features are not visible in 1200 models. I'll make an update to the TOMWrapper, that will allow it to seemingly support 1100 / 1103 compatibility levels, without attempting to set the value in the underlying TOM. This will let us control which features are available for the entire range of Compatibility Levels.

Regarding the highlighted blue column: Text turns blue when an object has a translation applied. Also, a key column on a table will have its name shown in **boldface**.

**Comment by teasot** [comment]
Out of interest, how much do people need support for the following in 1103 models?

- Direct Query
- KPI's

These are the only things I have never really researched in 1103, and as such am likely to add support for them right at the end.

Although I have never needed to manipulate the lesser used properties of datasources, like timeout, I am more confident in my ability to guess wildly on how to implement them.

**Comment by marcosqlbi** [comment]
My personal point of view: someone might use KPIs, but I wouldn't be worry about DirectQuery in 1103 (I consider adoption here - if you use DirectQuery in 1103 the performances are too bad and who had that need certainly upgraded already).

**Comment by teasot** [comment]
Thanks for your input - I will focus my efforts more on KPI's, and leave Direct Query for a rainy day!

**Comment by teasot** [comment]
I have created a separate GitHub project, mainly for this issue, at:
https://github.com/teasot/tom2amo
Once it is complete, I will make a pull request, and merge the code into Tabular Editor.
I will add the results of this discussion to the project, to keep track of the requirements.

**Comment by otykier** [comment]
Closing this as we no longer expect that support for 1103 models will be needed by many.
