### ISSUE TITLE
Is there a way to Paste Excel Data into new table?

### ISSUE THREAD

**Issue by seedjay1** [otykier/TabularEditor#149]
That would be cool, if there isn't.

-cdj

**Comment by otykier** [comment]
Hi @seedjay1 . Can you clarify what you mean by pasting Excel Data into a new table?

Tabular Editor does not deal with any kind of _actual data_ within the Tabular Model tables. It only deals with the model metadata (that is, tables, column, measures, hierarchies, etc.).

If you're thinking of using Power Query to automatically import a table from Excel to a Tabular model, that is unfortunately only possible through Visual Studio / SSDT. In Tabular Editor, you would have to create a Table object and populate it with Data Columns manually (remember to set the Data Type and Source Column property of each column). Finally, you would need to provide the Power Query (M) expression to extract the data from the Excel file, for the table partition.

Let me know if you have any further questions.

**Comment by seedjay1** [comment]
I meant the copy (excel cells -> edit menu in VS -> paste) functionality. :)

No biggie - there's also the handy DATATABLE function that i can use within your tool!

Thanks!

**Comment by otykier** [comment]
I see - I was actually unaware of this feature in VS. Will consider for a future release.

**Comment by otykier** [comment]
Will not be supported. Use DATATABLE or the DAX [table constructor](https://docs.microsoft.com/en-us/dax/table-constructor) syntax instead.
