### ISSUE TITLE
Open from folder button on toolbar

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#150]
This is more of a question about not having the open from folder button on the toolbar. Is it not there because the open from folder support is still considered experimental?

![image](https://user-images.githubusercontent.com/2540043/39051113-9feb60f0-449f-11e8-919a-d6e7c11398f7.png)

**Comment by otykier** [comment]
At this point, I know a lot of people are using it, so I guess we can't really treat it as "experimental" any more :-)

Anyway, did you know you can still use the regular "Open" mechanism to open a model from folder? Just point to the "Database.json" file at the root of your folder structure...

**Comment by dmgdotnet** [comment]
I did not know that, thanks! Seems so obvious now, i think my file path still had the 'Model.bim' value there from before we serialised and I kept getting the 'file not found' message.
