### ISSUE TITLE
Can't seem to create & populate a new table?

### ISSUE THREAD

**Issue by seedjay1** [otykier/TabularEditor#155]
Hi,

I added a table to a model via your tool, and I *think* I did everything that the other tables (created in SSDT) have, property-wise. It saves-to-cube fine (apparently), and it shows up in SSMS. I go to NewTable's partitions, and select the one there, and hit Process Full - SSMS reports "success", but 0 rows loaded.

Is there something obvious-once-you-know-it that needs to be done?

**Comment by otykier** [comment]
Hi seedjay1.
Couple of things to check:

1. Did you specify a partition query for your table? Screenshot below shows a query for an OLE DB data source - but if you're using Compatibility Level 1400 with structured data sources, you probably need to specify a PowerQuery (M) script.
![image](https://user-images.githubusercontent.com/8976200/39615748-26f13b78-4f78-11e8-935d-edf9ea44da43.png)

2. Did you map the Source Column property for all the data columns on your table?
![image](https://user-images.githubusercontent.com/8976200/39615830-85aca328-4f78-11e8-8117-473aaa339eea.png)

Let me know if you still have any issues.

**Comment by seedjay1** [comment]
Thanks for reply!

I did populate the M query - copped it from another model table and altered it for the new one.

I did not map source column property, because there are no columns on the new table showing in tabular editor. I had assume they would be inferred upon data load? Or do I have to manually specify columns in some manner?

**Comment by seedjay1** [comment]
Ok I guess I got it to work: manually added a Data Column, set properties - process full then downloaded the rows. Now to manually add the other 30 columns. :(

Would be nice to have the columns auto-populate if not specified to a "select *" based on the supplied M query. :)

**Comment by otykier** [comment]
> Would be nice to have the columns auto-populate if not specified to a "select *" based on the supplied M query. :)

I agree 100%. Unfortunately, there is currently no supported way to parse the M query to infer the metadata returned from it. For tables using the (legacy) Provider Data Source, [we have an easy way to auto-populate the table](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#creating-data-columns-from-partition-source-metadata), but this technique won't work for the Power Query-based Structured Data Sources.

> Now to manually add the other 30 columns. :(

Don't forget to use scripting to automate this as much as possible, though. For example, if you can create a list of column names and their data types in Excel, it's quite easy to generate the script that would add the columns to the table:

```csharp
var table = Model.Tables["MyNewTable"];
table.AddDataColumn("Column1").DataType = DataType.Int64;
table.AddDataColumn("Column2").DataType = DataType.String;
table.AddDataColumn("Column3").DataType = DataType.DateTime;
// ... add additional columns here ...

// Use the column name as the SourceColumn property:
foreach(var col in table.Columns.OfType<DataColumn>)
    col.SourceColumn = col.Name;
```
