### ISSUE TITLE
Expand tree by default when filtering

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#156]
When you search for an item in the tree using the filter box the tree collapses by default. I think it would be a better experience if all folders expanded by default when using the filter/search box.

Edit: for clarity & typo

**Comment by otykier** [comment]
I agree - this is actually a bug introduced in 2.7.1. Working on a fix.

**Comment by otykier** [comment]
Bug fixed in [2.7.3](https://github.com/otykier/TabularEditor/releases/tag/2.7.3)
