### ISSUE TITLE
Error loading Model from disk

### ISSUE THREAD

**Issue by simonnuss** [otykier/TabularEditor#157]
I have a PBIT file that I can load in Power BI with no issues, but it returns the following error when loading it in Tabular Editor, "This file is not a valid PBIX / PBIT file.". 

Daniel, I'll forward the file to you via email.

**Comment by otykier** [comment]
The issue here, was that the .pbit did not contain any model metadata, since a live connection to Analysis Services was used. Measures defined on top of live connections cannot be viewed using Tabular Editor.
