### ISSUE TITLE
Shade "Invisible" Folders

### ISSUE THREAD

**Issue by simonnuss** [otykier/TabularEditor#158]
Invisible tables show as a light grey colour in the tree view. Can you please extend this functionality to folders as well?

The reason I ask is because I currently have a large model that contains ~30 folders at the same level in the folder hierarchy.  Many of these folders are not visible in Power BI because all of their contained measures are invisible.  Unfortunately, it's very difficult to navigate this list of 30 folders in Tabular Editor because they all render in the same colour.

**Comment by otykier** [comment]
Stay tuned for v. 2.7.3 :-)

![image](https://user-images.githubusercontent.com/8976200/42378301-1fa9d11e-8127-11e8-8a0d-5c13047eea5e.png)

**Comment by otykier** [comment]
Fixed in [2.7.3](https://github.com/otykier/TabularEditor/releases/tag/2.7.3)
