### ISSUE TITLE
Scripting detailRowsDefiniton

### ISSUE THREAD

**Issue by bobduffyie** [otykier/TabularEditor#159]
Hi,

I am wondering if the Advanced Scripting can support the adding of the Detail Rows Expression in SQL 2017?

I have tried a few flavours of code, but cant; seem to get the detailRowDefinition as its not a simple attribute (maybe an object). Example script is below:

var m =Model.Tables["Store End of Day"].Measures["SvP Fails"] ;
m.DetailRowsDefinition.Expression ="";

Thx for the awesome tool BTW. I have got over 1,000 measures generated with the Advanced Scripting and it works so well ;-)

Best Regards,
Bob

**Comment by otykier** [comment]
Hi Bob,
Glad you like the tool. For some properties, I took the liberty of simplifying them slightly compared to the TOM,
so if you want to set the DetailRowsDefinition of a measure, you should simple write:

```csharp
Selected.Measure.DetailRowsExpression = "CALCULATETABLE( ... )"
```

Similarly, Table objects have a `DefaultDetailRowsExpression` property.

I’m sorry it’s not better documented. Let me know if you have any other questions.

**Comment by bobduffyie** [comment]
Awesome thx. That does make it easier to script out the changes ;-)
