### ISSUE TITLE
Unexplained 1400 vs 1200 Compatibility Issue

### ISSUE THREAD

**Issue by nbahmanyar** [otykier/TabularEditor#160]
I'm currently running the tabular editor 2.7 and trying to work with a 2016 SSAS database (compatibility level 1200).

After connecting to the DB in the Tabular Editor, I try to navigate to one of the columns in a table, and it says

> The database compatibility level of 1200 is below the minimal compatibility level of 1400 needed for [model 'Model'].[table 'Calendar']::[DefaultDetailRowsDefinition]

The funny thing is that my coworker is running Tabular Editor 2.6 and he never ran into this problem.. any help would be appreciated.

**Comment by dmgdotnet** [comment]
I believe this is fixed in the latest version, 2.7.1. Have you tried with that?

https://github.com/otykier/TabularEditor/releases/tag/2.7.1

**Comment by nbahmanyar** [comment]
Thanks, I tried with 2.7.1 and the issue is resolved.
