### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by atlanthony** [otykier/TabularEditor#161]
Hello,

I am trying to install from your tabulareditorinstaller.msi. I have followed the instructions and installed the MAMO 15.0.600.141. however i still cannot run the installed. i still received the message to installed the MAMO. I have tried this on my windows 10 laptop and my windows server 2012 vm. Is there something that i am doing wrong?

**Comment by tonythedataguy** [comment]
I had the same issue. I was only able to install after I logged in with a user that had admin rights on the machine. You can try running it as an admin from the Context Menu but I don’t think that worked for me.

**Comment by atlanthony** [comment]
Please ignore this. we downloaded the latest msi file which now installs fine. We had one from a few weeks ago that had the install issue.
