### ISSUE TITLE
Allow switching between DAX locale

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#162]
Power BI Desktop and Excel users in certain countries normally use ; (semicolons) as argument separators in DAX, and , (commas) for decimal separators.

Most other folks use , (commas) as argument separators and . (periods) for decimal separators. This is also what Analysis Services uses internally.

However, Tabular Editors UI could be improved to let the former group of people keep writing DAX their way. This should be an option in the UI, but could default based on the OS locale.

Do we have any Tabular Editor users, who prefer semicolons for argument separators in DAX? Show of hands please :-)

**Comment by holmsson** [comment]
Yes please!

**Comment by tschwenger** [comment]
I like it as an option instead of default in order to keep it consistent with analysis services

**Comment by otykier** [comment]
This is now possible in [version 2.7.4](https://github.com/otykier/TabularEditor/releases/tag/2.7.4).

**Comment by otykier** [comment]
@analyzethat when using scripts (or custom actions) within Tabular Editor, you’re basically interacting directly with the TOM, which expects DAX expressions to be in their native format, that is, commas for list separators and periods for decimal separators. If you want to use the non-US format within a script/custom action, you must convert the expression using the new `ConvertDax(string, bool)` method:

```
Selected.Measure.Expression = ConvertDax("CALCULATE(1,234;ALL(MyTable))");
```
