### ISSUE TITLE
Change Compatibility Level

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#163]
Hi again 

as you know, we can upgrade SSAS  Compatibility Level in SSDT. can we do this in Tabular editor?

**Comment by otykier** [comment]
Hi Arman,
Unfortunately, this is a read-only property for now. I would like to support both a compatibility level upgrade and downgrade feature in a future version of Tabular Editor.

As a workaround, and when going from 1200 to 1400, you should be able to do it simply by editing the JSON of your Model.bim file. Keep in mind that this is unsupported though, so it's probably better to do it from inside SSDT.

**Comment by otykier** [comment]
I see - thanks. Yes, we'll have to map out which features / properties need to be changed/removed when going from 1200 to 1400 or vice versa, so we don't get the XMLA errors. But it's on the backlog, so I'll close this issue for now.

**Comment by Rasenkantenstein** [comment]
Hi Daniel, 
it's an old topic, however - did this backlog item make it to production already? ;)
Best regards,
Konstantin

**Comment by otykier** [comment]
Not yet, unfortunately. For now, editing the compat level of the .bim in a text editor is still the way to go.

**Comment by OlapOffice** [comment]
https://community.powerbi.com/t5/Desktop/Consistent-Compatability-Levels-SSAS-amp-PBI-Versions/m-p/1175243/highlight/false#M529659

**Comment by otykier** [comment]
@OlapOffice It's not possible to downgrade tabular models. You might have better luck creating a new Model.bim file from scratch using Tabular Editor (File > New) and then copy-pasting all data sources, tables and relationships (in that order) from your PBI model (CL1520) to the new blank model (CL1200, CL1400 or CL1500 depending on which version of SSAS you're migrating to).

**Comment by OlapOffice** [comment]
Yep. Was thinking of doing something along those lines. Thanks for the reply.
