### ISSUE TITLE
token recognition error at

### ISSUE THREAD

**Issue by jsnape** [otykier/TabularEditor#165]
I've inherited a rather large cube and when I use Tabular Editor to deploy it I get lots of token recognition errors like so:

Tabular Editor 2.7.6682.40635
--------------------------------
line 5:104 token recognition error at: '. '
line 5:215 token recognition error at: '. '
line 5:313 token recognition error at: '. '
line 5:104 token recognition error at: '. '
line 5:215 token recognition error at: '. '
line 5:313 token recognition error at: '. '
line 5:107 token recognition error at: '. '
line 5:218 token recognition error at: '. '
line 5:316 token recognition error at: '. '
line 28:62 token recognition error at: '",\n)'
line 5:107 token recognition error at: '. '
line 5:218 token recognition error at: '. '
line 5:316 token recognition error at: '. '
line 38:143 token recognition error at: '. '
line 38:181 token recognition error at: '.s'
line 38:260 token recognition error at: '.\n'
line 44:57 token recognition error at: '.\n'
line 38:143 token recognition error at: '. '
line 38:181 token recognition error at: '.s'
line 38:260 token recognition error at: '.\n'
line 44:57 token recognition error at: '.\n'
Dependency tree built in 193 ms

Is there any way I can find out where these issues are occurring? E.g. a measure name.

**Comment by otykier** [comment]
These are outputted by the ANTLR lexer when analyzing DAX formula dependencies. In general, please don't rely on Tabular Editor for DAX syntax validation - that's not supported at the moment. However, Tabular Editor will output any errors reported by Analysis Services after deployment (if any), so if you're not getting any errors other than the ones above, you should be good. To verify, try to open the model directly from the database from inside the Tabular Editor UI. Then, the status bar should tell you if there are any errors in the deployed model.

There are some corner cases where perfectly valid DAX cannot be properly handled by the lexer, which could explain why you see these errors.
