### ISSUE TITLE
Unhandled exception when adding CustomAction without a CustomActions.json file

### ISSUE THREAD

**Issue by dybzon** [otykier/TabularEditor#17]
The Tabular Editor throws an unhandled exception when I try to add a CustomAction (by clicking "+ Save as Custom Action..." on the Advanced Scripting tab), if I do not have a CustomActions.json file located under ...\AppData\Local\TabularEditor\.

The function is working as intended when the CustomActions.json file does exist.

**Comment by otykier** [comment]
Cannot reproduce as of 2.0.6219.
