### ISSUE TITLE
Search box for "From column" and "To column"  when creating relationship.

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#173]
Hi Daniel, 
I hope you are doing well.

I think it is a good idea to add a search box for finding columns in the relationship.
If you have a lot of tables and columns in your model, it is not easy to find columns when you want to create a relationship between columns.

Kind regards,
Arman

**Comment by otykier** [comment]
Hi Arman,
I agree, the UI for specifying the FromColumn and ToColumn properties could certainly be improved. Until I have a better solution, remember that you can always right-click on a column to create a new relationship directly from or to that column:

![image](https://user-images.githubusercontent.com/8976200/43904741-bd5befd6-9bef-11e8-80e6-aa6773807977.png)

This might be a little easier if you have many tables/columns in the model. Also, the submenus will only show columns that have a matching data type, and additionally, columns with a similar name will be shown at the top, as can be seen from the screenshot.

**Comment by ArmanFalah** [comment]
I hadn't seen that feature, I think it's great!
I am always eager to see Tabular Editor new features.
Thanks a million, Daniel.

**Comment by otykier** [comment]
Cleaning up old issues / features that are already planned for Tabular Editor V3.
