### ISSUE TITLE
Automatic change of Model Name to 'Model' when deploying the model structure via Tabular Editor

### ISSUE THREAD

**Issue by WoutMachtelinckx** [otykier/TabularEditor#174]
I'm wondering if the following is a bug or not when using Tabular Editor with SSAS 2017 on-prem.
When I deploy the model structure of an existing cube by using Tabular Editor, it automatically puts the Model Name on 'Model'. And hence overwrites the Model Name we have set initially when we deployed via Visual Studio.

The change in Model Name 'breaks' the connection in our Power BI because we need to manually reconnect to the SSAS cubes with the modified model names.

**Comment by otykier** [comment]
Can you provide some more detailed repro steps, please?

If I open a model (either from a Model.bim file, or from an already deployed database), and rename the Model node:
![image](https://user-images.githubusercontent.com/8976200/43701056-31fccc5e-9955-11e8-8f79-d0bfaa274b42.png)
This rename is persisted when deploying, as far as I can tell.

**Comment by WoutMachtelinckx** [comment]
Hello, thanks for the swifty reply!

Indeed you are correct. When you change the model name directly in tabular editor, it remains! 
I typically changed the Model Name in Visual Studio (see screenshot attached). Never thought about changing the Model Name directly in Tabular Editor. 

Anyway, thanks a lot. This solves my problem :)

![changing model name in visual studio](https://user-images.githubusercontent.com/42025197/43709349-d85f4826-996c-11e8-8cac-e23c92eae1f6.png)

**Comment by otykier** [comment]
Yes, unfortunately, when you change the Model Name in Visual Studio's deployment properties (your screenshot), the name is only changed during deployment. The name specified in the Model.bim file remains untouched ("Model"). Visual Studio stores the deployment properties in a different file, so unfortunately this information does not make it into Tabular Editor when you load the Model.bim file. Closing the issue, as changing the model name inside Tabular Editor solved the problem for you.
