### ISSUE TITLE
Wrong Detection of Datatype

### ISSUE THREAD

**Issue by DomAtGitHub** [otykier/TabularEditor#179]
Hi Folks. I'm using the Tabluar Editor 2.7 at the moment. If I'm running the BPA rule "Do not use floating point data types" against my tabular model all my measures are getting listed. This is seems not to be correct. Thus, I double checked it with a certain measure which is defined as Whole Number. in this case the Tabluar Editor lists the data type as "Floating Point / Decimal Number (double)" even though in the tabular model the data type is set to Whole Number. The SQL Server I'm using is SQL Server 2017 (Version 14.0.223.1) and compatibility Level 1200. 
Do you have any idea why this happens?

Thank you in advance.

Dominik

**Comment by otykier** [comment]
Hi Dominik,
I don't think it's possible to change the data type of a measure (it will have the data type of whatever the evaluation of the DAX expression yields). As such, this BPA rule should not consider measures - only columns (Data Columns, Calculated Columns, Calculated Table Columns), where we can actually set the data type explicitly.

Please make sure that you're not confusing measure or column **format strings** with the actual data type.

Let me know if you have any further questions.

**Comment by DomAtGitHub** [comment]
Thanks for the fast response. Just to make sure that I decribed the Situation correctly. The expression of the rule mention above is: DataType = "Double". In the metadata information of the measure which is detected by this rule the Tabluar Editor Shows "Floating Point / Decimal Number (double)". However, if I look up this measure in the Tabular Model (via Visual Studio) it is defined as Whole Number. Thus, I am bit confused what is the data type of this measure?

**Comment by otykier** [comment]
I'm not sure why this happens. My best guess is that in your Model.bim file, the DataType property of this measure has been explicitly set to "Double", which explains why Tabular Editor reports it as such. However, it could be that the DAX expression of the measure evaluates to an integer, which could explain why Visual Studio reports it as a whole number.

According to the documentation of the [Measure.DataType Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.measure.datatype?view=sqlserver-2016#Microsoft_AnalysisServices_Tabular_Measure_DataType):

> Gets or sets the Auto Inferred data type of the measure.

In reality, this property is read-only, but the main point here is that the data type of a measure is **Auto Inferred**, meaning that it depends on whatever the DAX expression of the measure evaluates to. That is why I wouldn't normally create a BPA rule that checks for floating point values (DataType = "double") on measures. For **Columns**, on the other hand, I would always avoid Double, unless I had a specific need for that.
