### ISSUE TITLE
Copying measures

### ISSUE THREAD

**Issue by karaoan** [otykier/TabularEditor#181]
This is potentially a limitation on the Power BI side. So, this is just to confirm: Tabular Editor allows copying of measures. When you do this with two Power BI sources (as opposed to SSAS) TE initially allows it but on saving the model the attached error message comes up. 
![image](https://user-images.githubusercontent.com/32475223/44766488-fa74b300-ab9c-11e8-9d7f-77d120e816be.png)

**Comment by otykier** [comment]
This behaviour seems to have changed in a recent update of Power BI, as it was certainly possible to do before (although unsupported by Microsoft...)

It looks like the issue arises when copying a measure that has an annotation - specifically the "Format" annotation used by Power BI. I tried removing the annotations from measures I had copied into the PBI model, and that allowed me to save the model. The measures appeared in PBI after I saved the .pbix file and restarted PBI Desktop.

Until I find a workaround in Tabular Editor (or until Microsoft decides to [support TOM changes on the diagnostics port](https://www.sqlbi.com/blog/marco/2018/08/21/dax-studio-and-power-bi-diagnostic-port/)), you can use the following script to remove annotations from measures:

```csharp
Selected.Measures.ForEach(m => m.RemoveAnnotation("Format"));
```

Save this script as a custom action for easy reuse.

**Comment by otykier** [comment]
Could you provide some more details on how to reproduce this? Are you copying that measure, then running the script to remove the annotations, then saving it, or am I missing something? Thanks!

**Comment by karaoan** [comment]
I ran the script. For most measures it works but for the one shown in the screen shot above I get the message. I am not quite sure what "extended properties" are and where you can manage them.

**Comment by otykier** [comment]
I just discovered that most of the objects in the TOM have an `ExtendedProperties` property, which is not documented anywhere, and apparently is only used for models of compatibility level 1400+:

![image](https://user-images.githubusercontent.com/8976200/45533328-96d2c280-b7f7-11e8-9b12-3aa8d5e28ff5.png)

My guess is that Power BI attaches some additional information for internal housekeeping as ExtendedProperties, which could explain the error you're seeing. Indeed, if you create a quick measure and copy it from Tabular Editor into a text editor, you'll see the following:

```js
{
  "InstanceID": "c2e02c1e-72f7-454d-85ef-5a5e685c97a5",
  "measures": [
    {
  "name": "SalesAmount plus Freight",
  "expression": "\nSUM('FactInternetSales'[SalesAmount]) + SUM('FactInternetSales'[Freight])",
  "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
  "dataType": "decimal",
  "modifiedTime": "2018-09-14T06:30:23.136667",
  "structureModifiedTime": "2018-09-14T06:30:22.463333",
  "extendedProperties": [
    {
      "type": "json",
      "name": "MeasureTemplate",
      "value": {
        "version": 0,
        "daxTemplateName": "MathematicalAddition"
      },
      "modifiedTime": "2018-09-14T06:30:22.463333"
    }
  ],
  "annotations": [
    {
      "name": "Format",
      "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>",
      "modifiedTime": "2018-09-14T06:30:23.136667"
    }
  ]
}
  ]
}
```

I will see if I can gain some more knowledge about how Power BI uses the `ExtendedProperties` structure, and consider whether it would make sense to expose it in Tabular Editor. As a workaround when copying measures, you could simply remove the `extendedProperties` and `annotations` sections from the JSON above, before pasting it into your target model, and then I think everything should work.

**Comment by otykier** [comment]
Instead of manually editing the JSON through a text editor, I managed to brew up the following Tabular Editor script, that will clear the extended properties and annotations of all currently selected measures. Use it instead of the script I provided above, and you should be good to go:

```csharp
var extProp = typeof(Measure).GetProperties(
    System.Reflection.BindingFlags.Instance |
    System.Reflection.BindingFlags.NonPublic 
    ).FirstOrDefault(p => p.PropertyType.Name == "Measure" && p.Name == "MetadataObject");

foreach(var m in Selected.Measures)
{
    m.RemoveAnnotation("Format");
    var tomObject = (Microsoft.AnalysisServices.Tabular.Measure)extProp.GetValue(m);
    tomObject.ExtendedProperties.Clear();
}
```

**Comment by otykier** [comment]
Sorry for the late reply on this. Seems like some stuff was changed recently (within the last 3 months), in the Power BI model metadata, that makes it difficult to add/remove/modify measures and calculated tables.

There's not much we can do about it at this point. Version 2.8 of Tabular Editor adds support for Extended Properties, which may help a little bit, but it doesn't solve all the scenarios listed above. 

Hopefully, Power BI will have better support for AMO/TOM changes in the future - especially once the XMLA endpoints of the Power BI service are opened up.
