### ISSUE TITLE
Cube deployment through Tabular Editor returning error - IsKey property set to true on multiple columns of a table

### ISSUE THREAD

**Issue by CubeWala** [otykier/TabularEditor#182]
Hi,

I have recently updated to Tabular Editor version 2.7.3 and while trying to deploy a cube I get errors saying-

IsKey property set to true for multiple columns of a table - please see the following error screen:

![image](https://user-images.githubusercontent.com/42845685/44868391-51b37a00-aca8-11e8-8b31-891fffcf01d3.png)

Please suggest a workaround to this issue.

Many thanks.
Anirban.

**Comment by otykier** [comment]
Hi Anirban,
This is a known issue, please see #40. Workaround is to save the file as a Model.bim file - load that file into Tabular Editor and deploy from there. Let me know if you still have any issues!
