### ISSUE TITLE
Opening BIM file with thousands of calculations

### ISSUE THREAD

**Issue by IanHopewell** [otykier/TabularEditor#183]
Tabular Editor 2.7.3 no longer opens our BIM file after the update to 2.7.3, it appears to be related to Show/hide display folders, if the folders are hidden the file opens, however when selecting to show folders, the application then hangs.

**Comment by otykier** [comment]
Thanks for reporting this. To help me nail this down: Does this happen to all your models, or only specific ones? If possible, could you send me the .bim file that causes the issue? do@kapacity.dk

**Comment by otykier** [comment]
@IanHopewell Any update on this? I was able to reproduce a crash in case an object has a Display Folder string that contains double backslashes: `Test\\Folder` - however, this was also an issue with previous versions of TE. Could you please check your BIM file to make sure it doesn't contain any double backslashes? (If you load the file in a text editor, they would appear as quadruple backslashes `\\\\` as backslash is itself an escape character in JSON).

**Comment by jordandakota** [comment]
I tried reproducing this as well. Dumped my measure properties and mass replicated a measure (measure1, measure2, measure3, ... etc) and ended up with about 5000 measures. BIM opened fine. I hid most of them, saved, closed, reopened, showed folders, no hang.

**Comment by otykier** [comment]
Just an FYI, the issue has been found and fixed. You'll see that the performance will be greatly improved in the upcoming 2.7.4 release :-)

**Comment by IanHopewell** [comment]
Fantastic news, thank you, looking forward to the next release, an invaluable tool for us!

**Comment by otykier** [comment]
[2.7.4 now released](https://github.com/otykier/TabularEditor/releases/tag/2.7.4) - let me know if you still have any issues.

**Comment by IanHopewell** [comment]
Thanks, we have tested the update and it works really well, now opens the file in a few seconds, also noticed a huge improvement in the filtering performance!  Thanks for your help and assistance in resolving our issues, much appreciated!

**Comment by otykier** [comment]
Thanks for reporting back. Glad to hear it worked! On a side note, I even tried duplicating all the measures of your model a couple of times... at around 20.000 measures, things still worked :)

Don't push it though, at some point you'll probably run out of memory and crash Tabular Editor, so no guarantees ;-)
