### ISSUE TITLE
Renaming a column doesn't rename it in calculated table expression

### ISSUE THREAD

**Issue by simplesi** [otykier/TabularEditor#185]
Amazing tool. One small bug:

I renamed `postcodeDistrict` to `postcode District`.

However, the calculated expression below was not automatically updated, resulting in a file that Visual Studio couldn't load, referring to a missing column ID

```
"partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "SUMMARIZE(Geography,'Geography'[postcodeDistrict],\"latitude\",average(Geography[latitude]),\"longitude\",average(Geography[longitude]))"
            }
          }
        ]
```

I believe that the rename should have also changed the column name within this expression.

**Comment by otykier** [comment]
Thanks for reporting this. Unfortunately, I was unable to reproduce the behaviour described as of version 2.7.3. Can you provide some more detailed step-by-step instructions as to how to reproduce the error? If possible, can you send me the Model.bim file in question (or just a minimal version of it, where the issue exists).

**Comment by simplesi** [comment]
Thanks for trying!

Unfortunately this was the result of a mega-refactor so although *I
thought* that was the step that caused it, it was possibly something else.
Suggest you close this bug for now and I'll reopen if I can reproduce
later.

Thanks so much - this is a brilliant tool.

Simon Phillips
