### ISSUE TITLE
Save / Cancel buttons not appearing when creating Custom Actions on Windows 7

### ISSUE THREAD

**Issue by simplesi** [otykier/TabularEditor#187]
On a Windows 7 machines, I get the following in the Custom Actions dialog. Maximising or otherwise expanding the window still doesn't show any buttons. I've tried with both the Aero and Standard windows themes, and that doesn't make a difference. A windows server 2016 machine I alternatively use doesn't show this problem.

I can work around using `enter` and `escape`, although that does feel a little odd!

![image](https://user-images.githubusercontent.com/384302/45206719-9ed1b600-b27d-11e8-94ea-e4bcff0d1bb4.png)

**Comment by otykier** [comment]
Unfortunately, I don't have access to a Windows 7 machine at the moment. Some things that could help me track down the issue:

- Have you encountered the same on any other dialogs within Tabular Editor?
- Can you try to change some of the settings in the applications compatibility settings, to see if that changes anything? Specifically, I suspect that the "Disable display settings" option might do the trick:
![image](https://user-images.githubusercontent.com/8976200/45206964-ced18700-b286-11e8-968a-139323d30118.png)

**Comment by simplesi** [comment]
Thanks for the swift response. 

I've tried all combinations of the above (well, not the colour stuff), and it didn't resolve the problem, although it did feel a little like I was going back in time! Also tried running in Windows XP compatibility mode, to no avail.

I've checked the other dialogs too - they are not showing this problem.

Certainly not a big issue, just a bit odd!
