### ISSUE TITLE
Feature: change key mapping for collapse/expand all tree items

### ISSUE THREAD

**Issue by simplesi** [otykier/TabularEditor#188]
A few of the really useful keyboard shortcuts when editing text in windows are being used by TabularEditor for other things. I suggest the shortcuts are changed to preserve expected Windows behaviour.

Specifically `Ctrl`+`Shift` + `Left` / `Ctrl`+`Shift` + `Right` (which instead expand and collapse all items in the tree)
`Ctrl` + `Left` / `Ctrl` + `Right` (which seem to do nothing)

This is a minor issue but would make editing much easier!

See a useful list of some of the bindings here - they're usable in most windows text boxes, and very useful when editing code:
https://www.jetbrains.com/help/webstorm/ctrl-shift.html

**Comment by otykier** [comment]
Good catch. These shortcuts were actually only supposed to come into play when the explorer tree has focus, but I see that, by mistake, they are changing the behaviour of text editing elsewhere. That's a bug - will make sure it's fixed (actually, in version 2.7.2, I believe these shortcuts worked as expected, it's just that the new shortcuts added to 2.7.3 unfortunately overrides them).
