### ISSUE TITLE
DAX Formatter command inserts spurious newlines

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#189]
Whenever running a DAX Expression through the Format DAX command, or when using the `FormatDax` utility function, two trailing newlines are inserted, muddying up diffs on otherwise well-formatted measures.

**Comment by SQLBent** [comment]
I agree with this. It seems that it is actually the Dax Formatter API which returns the result with both leading and trailing carriage return (\r) and newline (\n):

``` tex
\r\n
CALCULATE (\r\n
    SUM ( [Test] ),\r\n
    FILTER ( 'New Calculated Table', [Test] = \"1\" ),\r\n
    FILTER ( 'New Calculated Table', [Test] = \"2\" )\r\n
)\r\n
\r\n
```

This causes for all objects to change when i.e. using Git or other comparison tools.

**Comment by otykier** [comment]
I never noticed this before. I'm wondering if something was changed recently in the daxformatter.com service, that would cause these chars to be added. @marcosqlbi ?

In any case, I can easily solve the problem in Tabular Editor, by trimming leading and trailing newline chars from the string returned from the service. Will add that for the upcoming 2.7.4 release.

**Comment by marcosqlbi** [comment]
I don't think we changed something there - let me know what is the API you are calling (we have more  than one) and I will check.

**Comment by SQLBent** [comment]
Tabular editor is using `daxtest02.azurewebsites.net/api/daxformatter/DaxFormat`. This was as well the one i got above request from.
