### ISSUE TITLE
automatically detect the PowerBI Desktop running  

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#19]
right now, i have to use DAX studio or a custom PowerQuery to get the port number so i can connect to the local SSAS instance, it will nice if Tabular editor detect automatically the list of pbix running

**Comment by otykier** [comment]
This is a very good suggestion, and I'm currently working on a solution that will show all running instances of Analysis Services hosted by Power BI, as well as any instances hosted by Visual Studio (for Integrated Workspace Mode).

This way, you no longer need to know the port number to connect. Will update this issue when the solution has been implemented.

**Comment by otykier** [comment]
I just pushed a new build, [2.0.6220](https://github.com/otykier/TabularEditor/tree/2.0.6220), containing some bugfixes as well as this new feature. When you choose to connect to a DB, the connection window now lists all embedded instances running locally (Power BI Desktop instances and Visual Studio Integrated Workspace instances):

![connectembedded](https://cloud.githubusercontent.com/assets/8976200/21848767/d68178d0-d802-11e6-8fb5-ae4dfc5864d6.png)

Although you can "Save" changes back to these instances, note that not all changes may be supported as discussed on Issue #18. Also, when saving, changes are not automatically persisted to the .pbix file or the Model.bim file of the Integrated Workspace database. This needs to be done manually in the respective tool after saving from Tabular Editor.
