### ISSUE TITLE
Save as folder does not respect Perspective serialization annotation

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#190]
When serializing to a folder with Perspectives serialized in-object, there is some metadata captured not in the serialization. I can open a file, change its `TabularEditor_InPerspective` annotation, and then open the model in TE and the object will preserve its perspective membership without respecting my change to its serialization.

When saving to folder we get the following annotation in the database.json:

```
      {
        "name": "TabularEditor_Perspectives",
        "value": "[{\"Name\":\"<perspective>\",\"Description\":\"<description\"}]"
      }
```
And we get something like the following in each object:

```
{
   ...,
  "annotations": [
    {
      "name": "TabularEditor_InPerspective",
      "value": "[\"<perspective1>\",\"<perspective2>\"]"
    }
  ]
}
```

If I open the file in a text editor and delete one of those perspectives in the annotation, then open TE, I will see the object still in both perspectives. I tested on columns in the latest release of TE and confirmed this behavior.

I can grep the entire model codebase and find nothing about perspectives besides the database annotation naming the perspective and the per-object annotation of membership.

It seems as if there is model metadata somehow being preserved across invocations of TE that is not captured fully in the serialization format.

The specific use case was programmatic updating of perspective membership using some command-line-fu. I substituted in some advanced scripting instead - a nice chance to brush up on my C# basics.

**Comment by otykier** [comment]
Thanks for reporting this - it turned out to be a bug when columns/measures/hierarchies are deserialized, in that they always inherit the membership information from the parent table. In other words, no metadata is preserved across TE invocations (phew!).

Will be fixed in the upcoming 2.7.4 release.
