### ISSUE TITLE
Cannot safely change serialization settings for model saved as folder

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#191]
I've been working with models saved to a folder and with serialization settings saved in the database.json annotations. There is no good way I have found to change the serialization settings of the model in situ. Changing preferences in Tabular Editor does not seem to change the annotation.

Changing the serialization annotation by hand (outside of TE) can potentially lose work. E.g. if you have serialized perspectives with objects (i.e. there is no perspective metadata in a perspective.json) and you remove the portion of the annotation stating this, you will see no perspectives upon opening the model. Other settings seem to behave similarly where you will simply lose the information. This seems fairly reasonable on its own, though should have warnings. 

The workaround I have found is to save as a .bim, delete the serialization settings annotation from the .bim outside of TE, then to open TE and change preferences, then to open the .bim, then to save to folder again.

There should be an option to change serialization settings in situ in a folder-structured model safely and within TE.

**Comment by otykier** [comment]
A solution for this was provided in the latest 2.7.3 version, which added an option to override serialization preferences within the “File” > “Save to folder...” dialog. See #175

![](https://user-images.githubusercontent.com/8976200/44672591-c1421480-a9dd-11e8-8b79-d55d04749ae6.png)

**Comment by greggyb** [comment]
Ah, that completely slipped by me. I almost never use a save-as dialog once I've saved once.

Would it be possible to surface this functionality in additional places? E.g. a modal dialog when you change your preferences to something other than what is in the currently open model to let you know that the two don't align, and then offer to change your prefs or change the current model. Or also a warning dialog when first opening a model that has different serialization settings than your preferences, with a brief instruction on how to change/override?

**Comment by otykier** [comment]
I'm thinking of adding a "Current model" tab to the preferences dialog, to make it easier to make changes to how the currently loaded model is serialized. In other words, this will provide an UI for the annotations used by Tabular Editor. How does that sound?

**Comment by greggyb** [comment]
That sounds good to me.
