### ISSUE TITLE
Azure Analysis Services Credentials get lost on deployment

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#194]
Hi,

I deploy to an instance of Azure Analysis Services. With the command line of TabularEditor.

```
Start-Process $tabulareditorexe -ArgumentList "$TempDir\Model.bim -D $SSASServer $DatabaseName -VSTS -ROLES -MEMBERS -OVERWRITE -NoNewWindow -Wait
```

I have not specified any -C to deploy the connections. However, after every deployment I have to reenter the credentials with SSMS.

![image](https://user-images.githubusercontent.com/908734/46162570-fb2a6300-c288-11e8-8cbd-152d9a0a870a.png)

I am using version 2.7.6814.17990.

**Comment by otykier** [comment]
This is unfortunately a limitation of 1400 models using M/Power Query data sources:
When executing a createOrReplace TMSL script (which is what Tabular Editors deployment option does), the credentials are always dropped, even when no data sources are specified in the script. I’ve tried raising this as an issue with the AS product team, but haven’t gotten any response yet.

To workaround, consider adding an additional step to your deployment pipeline, to add the credentials back to the model.

**Comment by fmms** [comment]
Hi Daniel, thanks for the fast answer. 

How can I do this in my deployment pipeline? I added

```
(Model.DataSources["DWH"] as StructuredDataSource).Password = "$password";
```

However, this does not work...

Even scripting the dialog where I enter the password does result in a script not containing the password ...

**Comment by otykier** [comment]
I believe if you script the data source/credentials dialog in SSMS, you can manually add ‘“Password”: “your-password-here”’ to the generated TMSL script (just below the “Username” portion), then it should work.

**Comment by fmms** [comment]
Hi @otykier thanks alot. This works one can use Invoke-AScmd to execute the TMSL and readd the passwords.
