### ISSUE TITLE
Best practice analyzer window is not modal

### ISSUE THREAD

**Issue by jsnape** [otykier/TabularEditor#198]
Which I get because you can edit things side by side. I've lost count of the number of times I've been editing a new rule and, instead of clicking the best practise analyser close button, I've clicked the main window's close. This doesn't warn you and you lose everything.

Please add an auto-save or a confirmation dialog.

**Comment by otykier** [comment]
The bug has been fixed in the [latest release](https://github.com/otykier/TabularEditor/releases/latest).
