### ISSUE TITLE
Data Category tooltips misspelling

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#199]
Quantitativ1e is misspelled.

![image](https://user-images.githubusercontent.com/29556918/46713892-a1715380-cc0d-11e8-8145-28d33641fe4f.png)

**Comment by otykier** [comment]
The tooltips for object properties that are not exclusive to Tabular Editor, are copied directly from the XML comments in the [TOM library](https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/). I'll forward this to the SSAS product team.

**Comment by kalmenk** [comment]
Ah got it, thanks!
