### ISSUE TITLE
request: option to upgrade to 1400 (and downgrade to 1200)

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#200]
button option to upgrade to 1400. same for 1200 but checks for things like TREATAS, IN{}, detail row expressions etc. before executing.

**Comment by otykier** [comment]
This is now possible in [2.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0).

**Comment by m-kovalsky** [comment]
Thanks! Should this be a dropdown menu for selection? As it stands now, people can enter compatibility levels that are invalid.
