### ISSUE TITLE
macros/recording actions

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#201]
One thing that may be interesting is the ability to record actions and see the advanced script printout of what was done during the recording - similar to how VBA/macros work in Excel. This may make it easier to write more advanced scripting clauses - by seeing what is generated by the system.

**Comment by otykier** [comment]
This is a brilliant suggestion, and something I had actually been toying with a while ago. It would certainly increase the adoption of scripting, making it a lot easier to get started.

**Comment by kalmenk** [comment]
Exactly. There are many scenarios where I presume using advanced scripting will be a lot faster but just may not know the proper coding syntax. This feature would definitely help the adoption of advanced scripting. One other thought is that advanced scripting could be recorded within the 'Show History' (either supplementing or replacing the existing show history). The existing Show History is good for brevity but the advanced scripting version would be good for the other reasons described.

**Comment by otykier** [comment]
Will be available in Tabular Editor 3.

**Comment by m-kovalsky** [comment]
Yes! Can't wait! Too bad I already know the advanced scripting quite well now :)
