### ISSUE TITLE
2.7.4 copy table no columns showing

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#202]
Here's the bug. It happens when editing a model in tabular editor directly on a server.

1) Copy a table in tabular editor. 
2) Paste it to create a copy of that table appended with '1'
3) Table shows up along with the partition. However, the columns don't show within tabular editor. They do show when i script out the model on the server. Once i do a create/replace directly on the server, the columns reappear when i reopen tabular editor.

**Comment by otykier** [comment]
Confirmed as a bug. Also applies to measure and hierarchies on the pasted table. To workaround, toggle display folders off and on (hit Ctrl+4 twice).

**Comment by otykier** [comment]
The bug has been fixed in the [latest release](https://github.com/otykier/TabularEditor/releases/latest).
