### ISSUE TITLE
Rename object does not work properly.

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#204]
Hi again Daniel :)

Imagine that you have two column in you model "Datekey" and "InvoiceDatekey".
now if you change the "Datekey"  name to "DateID", the "InvoiceDatekey" column also will change to "InvoiceDateID".

**Comment by otykier** [comment]
Hi Arman,
I didn't see this issue using the regular F2 rename on a column. Could you provide some more detailed step-by-step how to reproduce the issue? Thanks!

**Comment by otykier** [comment]
@ArmanFalah any update on this, or can we close the issue?

**Comment by ArmanFalah** [comment]
Hi Daniel,
It seems that it has been solved in the new version. if this bug comes again I will inform you.
Thanks.
