### ISSUE TITLE
Unable to import data tables with M query schema

### ISSUE THREAD

**Issue by borizzz** [otykier/TabularEditor#206]
This may or may not be a bug, but I am currently not able to import a table via M schema query that's available in compatibility level 1400.
Is it possible to provide an example what the clipboard should contain, so I can try it?

**Comment by otykier** [comment]
Just to clarify, you're talking about using this button to import a schema, correct?
![image](https://user-images.githubusercontent.com/8976200/47280259-b074e000-d5d5-11e8-8fd7-5fc80fcf1ce5.png)

I just tested it using the following clipboard content, which seems to work fine:

```
IgnoredColumn	TypeName	Name
1	Int	IntColumn
2	String	StringColumn
```

The header is required to contain a field called "TypeName", and another field called "Name". The original idea was to search for any field containing "Type" in its name, but there's currently a bug requiring the type specification column to be called "TypeName" (which I believe is what the output of the M Table.Schema function does - if not, simply rename the column in the PowerQuery UI).

Also note that the columns must be separated by tabs and lines must be terminated by CR+LF characters.

**Comment by otykier** [comment]
[This line](https://github.com/otykier/TabularEditor/blob/master/TabularEditor/UI/Dialogs/ImportTablesForm.cs#L159) is missing an assignment to `typeIndex`

**Comment by otykier** [comment]
Closing this. Make sure to check out the updated article on importing tables for more information: https://github.com/otykier/TabularEditor/wiki/Importing-Tables#power-query-data-sources

Feel free to reopen if you have any further questions.
