### ISSUE TITLE
Object Dependancies

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#208]
I believe this feature is driven by TOM so potentially an issue there, object dependencies do not seem to be working for me, has anyone seen the same issue before?

There is a dependency in our model between two fields (note the space) however the dependency window does not show the relationship:

![image](https://user-images.githubusercontent.com/2540043/47425390-130adf00-d782-11e8-8a22-ca79d47f1b9d.png)

![image](https://user-images.githubusercontent.com/2540043/47425433-2fa71700-d782-11e8-9cc0-06f7649e848a.png)

This is happening on the latest version for me but I've noticed this before as well.

EDIT: I should point out, this is happening for all measures, none of the interdependences show.

**Comment by otykier** [comment]
Thanks for reporting this. It seems to be a bug that was introduced in 2.7.4. As far as I can tell, it happens when you have a column reference where the table name is unquoted. Could you confirm if the dependency detection works, when you change the expression of the measure to:

```
IF(
    ISBLANK('Dim_Accounts'[Cash%])
    , BLANK()
    ...
```

Will look into it, thanks.

**Comment by dmgdotnet** [comment]
You nailed it, if I add quotes it works.

**Comment by otykier** [comment]
The bug has been fixed in the [latest release](https://github.com/otykier/TabularEditor/releases/latest).

**Comment by AnalyzeThis** [comment]
I have two versions of Tabular: Paid and free.

In the free version I can view dependencies, in the paid version I cannot.
