### ISSUE TITLE
Deployment of Model via Powershell

### ISSUE THREAD

**Issue by dilshan-sivanesan** [otykier/TabularEditor#209]
When calling the deployment of a model.bim file via powershell 
You get an error if the path to the file is too long in the arguments list.
E.g. 
C:\A\B\_C\C\E\_F-CI\\Model.bim
Error Message: Error loading model: The connection string is not valid.

Model deploys fine if you move the file to
C:\A\Model.bim

or change directory to where the model file is and put the path as ".\model.bim"

**Comment by otykier** [comment]
@dilshan-sivanesan Did you enclose the path in quotes? E.g. `"C:\A\B_C\C\E_F-CI\Model.bim"`? Would you mind posting the entire PowerShell command that is failing?

**Comment by otykier** [comment]
@dilshan-sivanesan Any update on this, or can we close the issue?

**Comment by dilshan-sivanesan** [comment]
Hi Daniel

Using quotes didn't help we had to shorten the path my moving the location
of the file. I think if I'm the only one experiencing the issue we can
close the path for now

**Comment by dmarkle** [comment]
So there it is.  It's the Long File Paths setting in Windows as per my previous comment.  Seems safe to close this one.
