### ISSUE TITLE
Please allow installing updates over the top of existing installation

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#210]
It is quite a faff to have to uninstall the old version to install the update. Surely it isn't really necessary? I don't remember any other software that needs this.

**Comment by dmgdotnet** [comment]
Are you using the MSI? No uninstall necessary when I use that

**Comment by o-o00o-o** [comment]
Yes I am using the msi. When I try to install when tabular editor is already installed I get the message that tells me it is already installed so I have to uninstall first each time.

My normal user is not a.n admin so it needs to be elevated.. I'll make sure I've tried running the installer deliberately as an admin rather than allowing auto uplift perhaps that is a solution..but still, I haven't come across this with any other bit of software on the same environment.

**Comment by otykier** [comment]
I'm not able to reproduce this. Which OS are you running?

**Comment by o-o00o-o** [comment]
It is Windows 10 Enterprise 2016 LTSB (v.1607 build 14393.2551)
I am just getting a newer version of Windows 10 in the next couple of days so I can check this and see if it different on that.

**Comment by o-o00o-o** [comment]
Just spoke to a colleague, he is on the same version of windows but this doesn't happen to him, so i guess this is something specifically to do with my profile. Feels like this is less of a Tabular Editor issue so closing this
