### ISSUE TITLE
Importing annotations (again)

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#211]
Hi guys, I know that this was discussed both in #109 and #106 but I am not sure if I have missed any further documentation on this.

We want to import metadata from a file into annotations. #106 talked a bit about this but it didn't seem to be concluded so I'm not sure if it is possible or not. 

E.g. 

I have a model with a single measure
model.mytable.mymeasure

and I have a file

|object|business usage|
|-|-|
|model.mytable.mymeasure|this is used to measure stuff|

How can I get this to create/update a new Annotation in the mymeasure measure called "Business Usage"?

**Comment by otykier** [comment]
Unfortunately, the "ImportProperties" method does not yet support annotations. As a work around, you could use the following script:

```csharp
// -- Don't modify below --
// Hacky way to access the "ResolveObjectPath" method, which is currently private:
Func<string, TabularObject> ResolveObjectPath = (s) => {
    var method = typeof(TabularEditor.Scripting.PropertySerializer).GetMethod("ResolveObjectPath", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
    return method.Invoke(null, new object[] {s}) as TabularObject;
};
// -- Don't modify above --

// Load the file content:
var tsvFileContent = ReadFile(@"c:\Test\MyFile.tsv"); // MyFile.tsv is a tab-separated file with headers

// Split it into rows:
var rows = tsvFileContent.Split("\r\n");

// Iterate all rows. Skip the header (i = 0):
for(int i = 1; i < rows.Length; i++) {
    var cols = rows[i].Split("\t"); // Split the current row into columns

    var objectPath = cols[0]; // Object path in the first column
    var businessUsageValue = cols[1]; // Business Usage value in the second

    var obj = ResolveObjectPath(objectPath) as IAnnotationObject; // Resolve the object path
    if(obj == null) continue; // Skip, if the path could not be resolved

    obj.SetAnnotation("business usage", annotationValue); // Set the annotation
}
```

This assumes that the first two columns of your file (`cols[0]` and `cols[1]`) are exactly like you specified. If your file has additional columns with other annotations, you would need to expand the script above, accordingly.

I'll make the "ResolveObjectPath" public in the next release, as it is quite useful for situations like this. That way, we don't need the hacky reflection stuff at the top of the script.

Still not sure how this could be integrated into the ExportProperties / ImportProperties design. We'll have to think about that.

Let me know if the workaround works for you.

**Comment by o-o00o-o** [comment]
Ok great, I will give that a go. 

I guess I could imagine the columns in the source file to be called Ann_XXX, Ann_YYY for annotations on that object called XXX and YYY to be created/updated?

**Comment by o-o00o-o** [comment]
Hmm it isn't working. 

For the objectPath = "model.Associated Accounts" (where Associated Accounts is a table in our model) I am getting an exception from ResolveObjectPath = "Exception has been thrown by the target of an invocation"

**Comment by otykier** [comment]
The path resolving is case sensitive (which is a bug). Writing Model with capital M should do the trick.

**Comment by o-o00o-o** [comment]
Ok yes great that does work. However if I pass in a bad path, it doesn't get to the 

``` csharp
if(obj == null) continue; // Skip, if the path could not be resolved
```
bit, it just exceptions. I guess I have to wrap in a try/catch as ResolveObjectPath isn't returning null if not found, it throws?
