### ISSUE TITLE
Can’t save annotations for perspectives when using the option to “serialize perspectives per object”

### ISSUE THREAD

**Issue by dodiep** [otykier/TabularEditor#214]
Can’t save annotations for perspectives when using the option to “serialize perspectives per object”

After adding annotation to perspective and saving, the annotation seem to be keep.  When closing and reopen the Tabular Editor, the annotation no longer exists.

**Comment by otykier** [comment]
This is now fixed in [2.7.4](https://github.com/otykier/TabularEditor/releases/tag/2.7.4).
