### ISSUE TITLE
When an object in a table is not part of any perspective, it gets added to the same perspectives that the table is part of “serialize perspectives per object”

### ISSUE THREAD

**Issue by dodiep** [otykier/TabularEditor#215]
When an object in a table is not part of any perspective, it gets added to the same perspectives that the table is part of. (I think this was only when using “serialize perspectives per object”)

**Comment by otykier** [comment]
This is now fixed in [2.7.4](https://github.com/otykier/TabularEditor/releases/tag/2.7.4).
