### ISSUE TITLE
.bim after enabling new relationship serialisation has no relationships!

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#220]
We have enabled the new "Serialize relationships by their starting tables" and our build process askes tabulareditor to create a .bim file (after running a custom action script). 

This bim file has no relationships in it, so of course causes some problems! :)

![image](https://user-images.githubusercontent.com/13693159/48939710-0c03f780-ef0d-11e8-87ff-2893f0f1cd68.png)

Hopefully we can deploy from the json files, which we are trying now!

it would be great if we could fix this asap!

**Comment by otykier** [comment]
Are you seeing the same behaviour when saving as a .bim from within the UI, or is it only when executing Tabular Editor from the command line on your build process server?

**Comment by o-o00o-o** [comment]
Our build script always downloads the most recent version of 2.7.4 before running so I don't believe that this can be the problem

**Comment by otykier** [comment]
I'm not able to reproduce this using version 2.7.6894.20778 (please check that your build pipeline log outputs the same version no.).

- What is the command you use to execute Tabular Editor, when the relationships disappear?
- What is the content of the "TabularEditor_SerializeOptions" annotation on the model, before the relationships disappear?

**Comment by o-o00o-o** [comment]
Solved. It was an old version, our release master was building locally rather than using the artifacts from the build server and it wasn't always getting the latest version on his machine for boring reasons. Thanks Daniel.
