### ISSUE TITLE
Deployment failed with Available in MDX Column Property changed to false

### ISSUE THREAD

**Issue by js18070** [otykier/TabularEditor#224]
Hey, I was wondering if there were plans to make the Available in MDX Column Property  work. The error message I get saving changes directly to the database says something like error in function MDNaivecell::InitPrototype. 

This would be very handy for dealing with a user community that always wants to pull detail rows as part of their analysis. I want to hide the very high cardinality primary key of detail rows from excel pivot table field lists because users have severely bogged down the server, going straight for the detail, with no limitations on the amount of data pulled in Excel. The detail rows expressions for drill through are a great alternative and highly customizable. 

On the other hand, I don't see a problem with having the very high cardinality column exposed in Power BI, because it does a great job of pulling just the data that can be seen, and pulling more while scrolling. I'd like the Power BI using folks to be able to take advantage of this.

If you can get this property to work, giving us all the ability to customize available objects based on the type of client connecting, it would definitely make for a healthy ecosystem of user satisfaction and server performance. Thank you.

**Comment by otykier** [comment]
Please consider the following points:

* The IsAvailableInMdx property can only be set to false if you’re using Azure Analysis Services or SQL Server 2017 CU8 (or newer). There’s nothing I can do in Tabular Editor to let you set the property if you’re not using a version of Analysis Services that supports it.
* The property does not necessarily hide the column from MDX clients, and it might still cause you errors in DAX clients when used as a grouping column. When you set it to false, what really happens is that Analysis Services no longer builds a hierarchy for that column during processing. So it’s mostly useful for speeding up processing and reducing model size for numeric columns used only in aggregations, as well as key columns that have their IsHidden property set to true.

More details here: https://blog.crossjoin.co.uk/2018/07/02/isavailableinmdx-ssas-tabular/

**Comment by js18070** [comment]
Thank you for the response. Still a useful feature.  I'm using a 1400 compatibility level model for SQL Server Analysis Services 2017 enterprise edition, not using Azure. You're saying it's only available for Azure Analysis Services?

**Comment by otykier** [comment]
According to [this page](https://support.microsoft.com/en-us/help/4295097), you should also be able to set the property in SQL Server 2017 starting from [Cumulative Update 8](https://support.microsoft.com/en-us/help/4338363/cumulative-update-8-for-sql-server-2017).

**Comment by js18070** [comment]
That settles it. Thank you.
