### ISSUE TITLE
Errors should show when run interactively?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#225]
In my new script for creating derivative measures I would expect the error conditions to be shown to the user but it seems they are not (by design as per doc) but surely this should happen if executed interactively also? otherwise these conditions are hidden. Unless the intention is for us to check if we are in interactive mode and produce an Output() instead but it seems that this could/should be done for us?

**Comment by otykier** [comment]
Not entirely sure what you mean by this. Could you provide a code example that is not producing the expected error when run interactively? (By "running interactively", I assume you mean invoking a custom action from the UI?)

**Comment by o-o00o-o** [comment]
``` csharp
Error("Blah");
```
Just doesn't produce anything when run via the UI)

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)
