### ISSUE TITLE
Collection was modified, enumeration operation may not execute

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#226]
for my new derivatives script I am basically doing a

``` csharp
foreach(Measure measure in Model.Tables.SelectMany(t => t.Measures)) 
{ 
// ... work out which measures I want to add then 
measure.Table.AddMeasure(newMeasureName, newMeasureDaxExpression, newMeasureDisplayFolder);
}
```

On the second pass of the foreach I get the error "Collection was modified; enumeration operation may not execute."

Also even the first pass my new measures have not actually been added into the model when I look in the measure tree. 

What am I doing wrong?

**Comment by otykier** [comment]
This is a C# thing. You can't make changes to a collection that is currently being enumerated. Use the `.ToList()` method to make a copy of the collection, like so:

```csharp
foreach(Measure measure in Model.Tables.SelectMany(t => t.Measures).ToList()) 
{ 
// ... work out which measures I want to add then 
measure.Table.AddMeasure(newMeasureName, newMeasureDaxExpression, newMeasureDisplayFolder);
}
```

Also note that Tabular Editor provides the `Model.AllMeasures` enumeration which is just a more convenient way of writing `Model.Tables.SelectMany(t => t.Measures)`. A handful of these [convenient collections](https://github.com/otykier/TabularEditor/blob/a397c1f61111c36e5a460a545c7878a8ba28e90b/TOMWrapper/TOMWrapper/Model.cs#L122-L152) exist.
