### ISSUE TITLE
Cannot unsellect when selecting objects with Ctrl + mouse

### ISSUE THREAD

**Issue by Kilsgaard** [otykier/TabularEditor#228]
Hi

When selecting objects with Ctrl + Left Mouse, it is not possible to deselect the selection again.

I have tested wit a script, and it is both the physical selection and the storred selections that have the problem.

/Graves

**Comment by otykier** [comment]
Fixed in [2.11.6](https://github.com/otykier/TabularEditor/releases/tag/2.11.6)
