### ISSUE TITLE
Advanced scripting editor - message for syntax error

### ISSUE THREAD

**Issue by dybzon** [otykier/TabularEditor#23]
I just ran into a strange error message when using the Advanced Scripting editor in Tabular Editor 2.1. I missed the semicolon at the end of a statement, and I got the error message attached here.
![tabulareditor 2 1](https://cloud.githubusercontent.com/assets/5863959/21974041/a136bf12-dbc4-11e6-8600-acb642d7b2af.png)

In Tabular Editor 2.0 I used to get a more meaningful error message in this case. See the second attached screenshot here.
![tabulareditor 2 0](https://cloud.githubusercontent.com/assets/5863959/21974023/9581e818-dbc4-11e6-92d4-10f3be75d81a.png)

This is low priority - but in my opinion the error message thrown in Tabular Editor 2.0 was more meaningful.

**Comment by otykier** [comment]
This seems to be a bug in the initializer of the TOMWrapper.dll. Could you try deleting the file mentioned in the error message, and restart Tabular Editor?

**Comment by dybzon** [comment]
The issue was resolved by deleting the TOMWrapper.dll file on the path specified in the error message (first screenshot in the issue description).
Closing the issue.
