### ISSUE TITLE
Store Custom Actions per model

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#231]
See the discussion on #212 .

It should be possible to store custom actions locally within a model, similar to how BPA rules can be stored locally.

In addition, when doing this, there should be an option to store the actions in a separate script file, to make source control easier.

**Comment by o-o00o-o** [comment]
just to clarify, each model custom action should have its own separate .cs script file

**Comment by otykier** [comment]
From a security pov, having custom actions automatically compiled upon model metadata load is not advised (malicious users could sneak in assembly code that is executed automatically once the code is compiled). Closing this.
