### ISSUE TITLE
Renamin of Measures breaks DAX formulas

### ISSUE THREAD

**Issue by Kilsgaard** [otykier/TabularEditor#233]
Hi 

I have created a small script, and have renamed a lot of selected measures.
I have renamed to a shorter name.
When the rename is done, som of the DAX formulas is broken because the last bit of the name before renaming is still in the formula, after the new name.
Please se attached:
![image](https://user-images.githubusercontent.com/11911747/49735159-ba869700-fc86-11e8-9d87-9b73082154f0.png)

/Graves

**Comment by otykier** [comment]
Hi Graves,
Which version of Tabular Editor are you using? (File > Preferences > General)
I'm not able to reproduce this issue in version 2.7.4 (build number 2.7.6894.20788). If you are using the same version (or the 2.8.4-beta), please provide some more details on what you were doing step-by-step, when this bug appeared. Thanks!

**Comment by Kilsgaard** [comment]
I am using the following version:
![image](https://user-images.githubusercontent.com/11911747/50089134-3fccf700-0205-11e9-8961-556870b1eaed.png)

But I have not been able to reproduce the error my  test environment :-(
Closing it I will get back with a file if i can reproduce it in my model later..
