### ISSUE TITLE
Add MemberID and IdentityProvider property editing capability for roles

### ISSUE THREAD

**Issue by jdfancke** [otykier/TabularEditor#235]
Currently it is not possible to edit or correctly add new role members within Tabular Editor because they require a memberID property and an IdentityProvider property (if using Azure Analysis Services).

![image](https://user-images.githubusercontent.com/20044040/49908092-04f95500-fecd-11e8-9858-c6bb97e71ebc.png)

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)
