### ISSUE TITLE
RLS shows values assigned to table even if expression not present for given tables

### ISSUE THREAD

**Issue by JSujit** [otykier/TabularEditor#237]
![rls issue](https://user-images.githubusercontent.com/45988499/50202638-99bbe280-0313-11e9-9def-75f002f0322a.jpg)

As shown in attahed image, even if Row Level Security(RLS) is not implemented on any table, its shows as 'Value assigned to 9 out of 25 Tables'. Please look into this issue.

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)
