### ISSUE TITLE
Reusable Custom Actions

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#238]
So we now have a couple of interesting situations which would be useful to be able to modularise some of these custom actions so that we can run the same code on both the entire model but also on just a selected item

For example my "Create AutoDerivatives" action goes through all measures with a specific annotation and creates the autoderivatives according to what is in the annotation). E.g. if MTD is in the annotation then it will create a new MTD measure based on the base measure that it is on. 

However normally this is run for the entire model at build time (as we don't want to put all those autoderivatives in source control). However when just creating a new one we'd like to be able to just create the autoderivatives just for that one measure to allow easier troubleshooting. 

I thought perhaps I could write an action to work on selected nodes only and then in a parent custom action select all and then execute the child package, but I can't find a select() method in the TOMWrapper. Would this be the right way of doing it or might there be a different/better way to reuse?

Is this the right way of doing it or might there be a different way?

**Comment by otykier** [comment]
This is already possible, check out [this example](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#generate-time-intelligence-measures). The `CustomAction` method can be invoked in two different ways:

- `CustomAction(name);` - invoke a Custom Action by name.
- `CustomAction(objects, name);` - invoke a Custom Action on the specified collection of objects.

**Comment by o-o00o-o** [comment]
Ok, so we should always write our reusable scripts against the selected collections then call them by a parent if we want something a bit more declarative (i.e. the whole model). Thanks

**Comment by o-o00o-o** [comment]
Hmm, not sure if I am doing something wrong but this doesn't seem to work

I have a script called "Auto Derivatives\Recreate AutoDerivatives" and this works if I select a measure and run it. 

I then have a script call "Auto Derivatives\Recreate All AutoDerivatives" with the body:

``` csharp

var measuresWithAutoDerivatives = Model.AllMeasures
    .Where(m => m.GetAnnotation("AutoDerivatives") != null)
    .ToList();


    measuresWithAutoDerivatives.Output();
CustomAction(measuresWithAutoDerivatives, @"Auto Derivatives\Recreate AutoDerivatives");
```
The output shows the 4 measures I'm expecting to be executed but it doesn't appear to do anything "Script executed successfully. 0 model changes"?

Any ideas?

**Comment by otykier** [comment]
I hadn't thought of that scenario. I guess it would only be relevant for the `CustomAction(objects, name);`-version of the method?

**Comment by o-o00o-o** [comment]
hmm no I don't think so. You could happen to have a "DoAllX" and decide that you would like this only on a Measure and a DoAllY and decide that from the UI perspective it makes sense only on the Model but then want to call one from the other. 

The point is that programmatic method calling shouldn't care about the UI constraints that have been put on for purely UI reasons. It isn't security it is UI friendliness.

**Comment by otykier** [comment]
Closing this issue, as no more features will be added to this version of Tabular Editor regarding custom actions.

Tabular Editor 3 will feature a richer set of scripting features, that allow you to define reusable classes, methods, etc.
