### ISSUE TITLE
Provide better error messages for Custom Actions that can't be compiled

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#239]
I'm trying to build my own Custom Actions file (while waiting for the feature to add custom actions to the model directly) however I am having trouble with getting the file right with the "free money bar" (status bar) showing "Failed loading custom actions. See CustomActionsError.log" for more details. 

Could this be a more obvious error rather than on the status bar (very easy to miss) and also can you tell me where the CustomActionsError.log is? it isn't alongside the CustomActions.json.

**Comment by otykier** [comment]
Yeah - this area needs some more work. I'm not sure where the CustomActionsError.log has gone - will investigate. But generally, when there's a C# syntax error in a single action, then the entire compilation of actions will fail, as everything is combined into one code module which is compiled when Tabular Editor is loading.

In the mean time, the first thing to look out for is missing semicolons at the end of C# statements or unmatched parentheses or curly braces, as this is most likely to cause a syntax error that causes the entire file to fail compilation.

**Comment by o-o00o-o** [comment]
yeah right now I have to bring in the script in via the samples (they are still listed there) and go through one by one and run them. As my library grows this will become less and less enjoyable! :)

**Comment by otykier** [comment]
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).
