### ISSUE TITLE
Expose more metadata information  

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#24]
it will be nice to have more metadata information
for example the last time a table was refreshed

**Comment by otykier** [comment]
The TOM unfortunately does not contain information about when a particular table was last refreshed. See [the TOM API documentation](https://msdn.microsoft.com/en-us/library/microsoft.analysisservices.tabular.table.aspx). Perhaps this information can be obtained from a DMV, but I will have to look into that. Right now, Tabular Editor only uses the TOM to read out metadata. But if we choose to use DMVs in the future, there may be other advantages such as showing the number of records and memory footprint of a table and its child objects.

At the Model/Database level, we have a little metadata available, which is exposed in the Property Grid:
![image](https://cloud.githubusercontent.com/assets/8976200/22011667/87ce0360-dc90-11e6-8aaf-2d2677da5246.png)

Could you be more specific as to what other metadata you expect to see?

**Comment by djouallah** [comment]
Thanks for the explanation, I am not sure if feasible at all, for example the source data when using compatibility level 1400, it will nice to see the M query itself 

![image](https://cloud.githubusercontent.com/assets/12554469/22012414/70bb3436-dcdb-11e6-9dcd-b729119a4606.png)

sorry if the question does not make any sense :)

**Comment by otykier** [comment]
I've made a [new build](https://github.com/otykier/TabularEditor/releases/tag/2.1.6229-pre) where the Data Source names are inferred from the "location" attribute of the mashup connection string. Furthermore, the M query is exposed in the property grid, which is also taken from the connection string (it's encoded in base64 and zipped according to [this article](http://sbrickey.com/Tech/Blog/Post/Secrets_Revealed_PowerQuery_connection_string_format)).
![image](https://cloud.githubusercontent.com/assets/8976200/22141269/7f76345e-def1-11e6-875d-f66d09f14d52.png)
Let me know if this works for you.

**Comment by djouallah** [comment]
wow, it works perfect thanks, 

![image](https://cloud.githubusercontent.com/assets/12554469/22141617/62c05d50-df3a-11e6-84cd-106131b64ac8.png)
