### ISSUE TITLE
TabularEditor.exe when called from msbuild doesn't show output

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#241]
when run from the commandline tabulareditor.exe seems to run asyncronously in that you run it and the command prompt returns almost immediately and you get the std out appearing after that. Not only does it make a mess of the command prompt but I think it also has the side effect that when you run through msbuild you don't get any of the stdout using the normal msbuild command

``` xml
<Exec Command="start /wait $(_TabularEditor) %(TabularProject.Identity) -S &quot;$(ScriptPath)AutoDerivatives\RecreateAllAutoDerivatives.cs&quot; -B $(OutputPath)Model.bim -O -V" />
```

I wonder if you have any plans to resolve this? Alongside better error messages #240 this would make using customactions (and dealing with the issues) a lot more efficient as we could troubleshoot directly from the ADO build process where now we have to hope we can reproduce on a local machine to get the error.

**Comment by otykier** [comment]
Unfortunately, it’s simply not possible to run a WinForms application in the same thread as the command prompt. That’s why we have to use the `start /wait` approach. Working around this would require shipping TabularEditor with a separate .exe for command line use only, or spawning a WinForms application from a command line thread (which would cause a command prompt window to stay open in the background).

I think you can redirect the output using `start /B /wait TabularEditor.exe ...` for use with msbuild. So far, I’ve only used the command line in Azure DevOps build pipelines, and they seem to capture the output just fine, even without the /B switch.

**Comment by o-o00o-o** [comment]
unfortunately running 


```
start /b /wait C:\Users\xxxxx\Source\Vega\VegaDW\build\TabularEditor.exe C:\Users\xxxxi\Source\Vega\VegaDW\src\VegaDW.Cube\database.json -ANALYZE -VSTS -ERR
```
just on the command line returns the output to stdout but running via msbuild with target
```xml
<Exec Command="start /b /wait $(_TabularEditor) %(TabularProject.Identity) -ANALYZE -VSTS -ERR"/>
```
just returns 

```
CompileCube:
  start /b /wait C:\Users\bgerhardi\Source\Vega\VegaDW\build\TabularEditor.exe C:\Users\bgerhardi\Source\Vega\VegaDW\src\VegaDW.Cube\dat
  abase.json -ANALYZE -VSTS -ERR
C:\Users\bgerhardi\Source\Vega\VegaDW\build\build.proj(143,9): error MSB3073: The command "start /b /wait C:\Users\xxxx\Source\Vega
\VegaDW\build\TabularEditor.exe C:\Users\xxxx\Source\Vega\VegaDW\src\VegaDW.Cube\database.json -ANALYZE -VSTS -ERR" exited with cod
e 1.
Done Building Project "C:\Users\xxxxx\Source\Vega\VegaDW\build\build.proj" (Build target(s)) -- FAILED.


Build FAILED.
````
which means when the build fails on the AzureDevOps build agent, we don't know which of the rules have failed.

**Comment by otykier** [comment]
Did you ever find a workaround for this?

When running TabularEditor.exe through a regular Command Line task in an Azure DevOps pipeline, this does not seem to be an issue.

**Comment by o-o00o-o** [comment]
no never did find a workaround unfortunately. We just don't get any logging from the msbuild step.

**Comment by otykier** [comment]
Please see the [June 14th update of vesion 2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3). I've tested this with the Command Line task of Azure DevOps Build Pipelines, which works well (see screenshot), but I'm not sure if this matches your specific scenario:

![image](https://user-images.githubusercontent.com/8976200/59492912-483b7d00-8e8a-11e9-9816-8fb4b84ae56d.png)

Feel free to reopen the issue, if the problem persists.
