### ISSUE TITLE
Altering perspective doesn't change annotations for an object

### ISSUE THREAD

**Issue by nissim-panchpor** [otykier/TabularEditor#242]
Hi Daniel,
Recently noticed that removing an object from a perspective doesn't remove the "TabularEditor_InPerspective" annotation and corresponding value. For eg. I wanted to remove a column from a perspective. The column had an annotation with the above name and perspective name as its value. When I tried to remove the column from perspective, it was removed from the list but this annotation remained as it is. When I saved and reopened the model, the column was still in that perspective.
Please let me know if you have any questions. Thanks!
- Nissim Panchpor

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)
