### ISSUE TITLE
Undoing Delete Table doesn't return columns/measures

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#245]
If you delete a table then undo the UI doesn't show the columns/measures. Not sure what would happen if I save now but I'm guessing that it would not keep the columns/measures so not a true undo.

Not really high prioritity but noticed it so I thought I'd report

**Comment by otykier** [comment]
Thanks for reporting. This is bug since 2.7.4. The columns/measures/hierarchies are still there, the UI just doesn't render them. They will show up again I if you toggle the "Show display folders" button off and on (Ctrl+4).

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8).
