### ISSUE TITLE
Item highlighting issue

### ISSUE THREAD

**Issue by PhilippeCand** [otykier/TabularEditor#246]
Hi- When selecting an item in the tree, the color is too dark and the item title cannot be read.
![image](https://user-images.githubusercontent.com/46706849/51169300-d4318480-18ab-11e9-9fb6-6933d98f8b34.png)

**Comment by otykier** [comment]
2.8 will have the following colors, which should at least ensure that selected item titles are easier to read:

![image](https://user-images.githubusercontent.com/8976200/51171702-dc8cbe00-18b1-11e9-9555-d9666fd9f7ac.png)

The colors used are as follows:

- Unselected visible no translation: `SystemColors.ControlText` (`#000000` on my OS)
- Unselected hidden no translation: `#808080`
- Unselected visible with translation: `#0000A1`
- Unselected hidden with translation: `#6F6FBF`
- Selected visible no translation: `SystemColors.HighlightText` (`#FFFFFF` on my OS)
- Selected hidden no translation: `#C0C0C0`
- Selected visible with translation: `#D3D3FF`
- Selected hidden with translation: `#A1A1D3`

I'm very open to suggestions, as I'm actually colorblind myself, so I have no idea if this is a good choice of colors in general.

**Comment by PhilippeCand** [comment]
Thanks for the quick turnaround. I think the coloy choice you propose is good.
And I am learning to love this great tool.

**Comment by otykier** [comment]
This is now fixed in [version 2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8).
