### ISSUE TITLE
Edit all DAX expressions in DAX Editor

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#247]
There are a number of locations in a Tabular model that hold DAX expressions. Tabular Editor only supports editing a subset of DAX expressions in a Tabular model.

- [x] Calculated table
- [x] Calculated column
- [x] Measure Expression
- [x] Measure DetailRows expression
- [x] Table DetailRows expression
- [ ] RLS expression

Items in the list have DAX expressions. Checked items can be edited in Tabular Editor's DAX editor. Unchecked items can only be edited in a weird little drop-down menu.

For RLS, perhaps we could have an expandable node for each security role that would list tables under them? Or perhaps we could get a dropdown in the expression editor when selecting a table to edit that table's RLS expression for each role?

**Comment by otykier** [comment]
Good suggestion. Will add expandable nodes for reach security role in next release.

**Comment by greggyb** [comment]
@otykier I think the list I provided is comprehensive, but I just wanted to make explicit that I think any DAX-holding property/object should have availability to edit in the DAX editor widget of Tabular Editor.

If there are any other items I missed, I'm happy to help brainstorm on intuitive ways to get to those areas.

**Comment by otykier** [comment]
This is now fixed in [2.8.1](https://github.com/otykier/TabularEditor/releases/tag/2.8.1). To my knowledge, all objects containing any kind of DAX property, are now editable in the Expression Editor.
