### ISSUE TITLE
How to specify impersonationMode, account and password on the command line?

### ISSUE THREAD

**Issue by jsnape** [otykier/TabularEditor#249]
When we deploy the cube in our CI/CD pipeline we have different impersonationModes and accounts depending on the release stage - e.g. Test uses impersonateService where as UAT uses impersonateAccount with a specific account and password; Prod uses a different account and password.

How can I call TE and specify these different options from the command line?

**Comment by otykier** [comment]
Hi @jsnape 

This can be done using a set of scripts - one for each environment you're deploying to. You can use the `-S` switch of the command line to pass in a script file, that will be executed before the model is deployed (with the `-D` switch).

The script for your Test environment in this case, would look something like this:

```csharp
(Model.DataSources["YOUR DATA SOURCE"] as ProviderDataSource).ImpersonationMode = ImpersonationMode.ImpersonateServiceAccount;
```

(Just drag-and-drop the data source from the tree-view into the Advanced Scripting editor to generate the first portion of this code).

The options for the [ImpersonationMode property can be seen here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.impersonationmode?view=sqlserver-2016).

For your UAT environment, you would set the username and password on the data source as well, which would look something like this:

```csharp
(Model.DataSources["YOUR DATA SOURCE"] as ProviderDataSource).ImpersonationMode = ImpersonationMode.ImpersonateAccount;
(Model.DataSources["YOUR DATA SOURCE"] as ProviderDataSource).Account = @"kapacity\do";
(Model.DataSources["YOUR DATA SOURCE"] as ProviderDataSource).Password = @"********";
```

**Comment by jsnape** [comment]
Thanks Daniel, I hadn't considered using scripts. Good idea. One last question - is it possible to pass in the password? Ours are stored as AzureDevOps Pipeline variables - we specifically disallow passwords in source code.

**Comment by otykier** [comment]
Yeah, good point. Well, you have two options:

1. Create a version of your script where the password is replaced by a placeholder value: `.Password = @"<%PASSWORD%>";` or something like that. Then, in your build pipeline, add a PowerShell step, just before you invoke Tabular Editor, to swap the placeholder in the file with the real password from your pipeline variable.

or:

2. Instead of setting the account/password properties on the data source, specify a connection string that includes a password placeholder in your script: 
    ```csharp
    (Model.DataSources["YOUR DATA SOURCE"] as ProviderDataSource).ConnectionString = 
        "Data Source=myserver123;Initial Catalog=mydwh;Uid=username;Password=<%PASSWORD%>";
    ```

    Then, when executing the Tabular Editor CLI for deploying the model, use the -C switch to swap the connection string placeholder with your pipeline variables. Something like:

    ```
    start /wait TabularEditor.exe Model.bim /D uatserver dbname /C "<%PASSWORD%>" "$(passwordvariable)"
    ```

    where $(passwordvariable) points to the Azure DevOps pipeline variable holding the password. This way, you're never writing the password to disk. It will only be applied to the connection string during deployment of the model.

**Comment by jsnape** [comment]
Thanks for your quick replies.
