### ISSUE TITLE
Tabular editor fail to connect to SSAS if it is hosted in another domain

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#25]
if the SSAS server is in another domain, tabular fail to connect, to be fair it fail with PBID too, only Excel using the traditional data connection works

![image](https://cloud.githubusercontent.com/assets/12554469/22139868/7aa9cffa-df30-11e6-85f3-57703e022611.png)

**Comment by otykier** [comment]
Hi Mimoune. Have you tried the following:

* Enter the server as: <domain>\<servername>
* Enter the username as: <domain>\<username>
* Run Tabular Editor under the credentials of the domain user, e.g:
    `runas /netonly /user:<domain>\<username> TabularEditor.exe`

[This guy](https://community.powerbi.com/t5/Desktop/Connecting-PBID-to-SSAS-Tabular-when-not-in-domain/td-p/14241) managed to connect cross-domain from Power BI Desktop, so I imagine the same technique should work for Tabular Editor.

**Comment by djouallah** [comment]
eh sorry the SSAS was installed without domain, ( home server for testing purpose only), so I guess it won't work, i know you are "just" using AMO, so i guess it has to be fixed there :)

**Comment by otykier** [comment]
I am not sure the issue is with AMO, since AMO is really just connecting through OLEDB. Did you try the "runas" suggestion? You don't need to supply a domain name as long as you have a similarly named account on the home server and the client machine.

**Comment by djouallah** [comment]
it works :)
