### ISSUE TITLE
Toggling DetailRows expression causes TE to indicate changes to current model

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#250]
Viewing an existing DetailRows Expression causes TE to indicate a change to the model, despite no changes.

1. Select measure with a DetailRows Expression already set
2. Use the DAX Expression Editor dropdown to view the DetailRows Expression.
3. Toggle back to the measure expression in the DAX Expression Editor pane.
4. TE indicates that the model has been changed (an entry in the edit history, and a little blue icon on the measure)

There is no content change (verified by manual inspection and `git status` of a version controlled model). This is a quality of life issue when working with DetailRows expressions.

**Comment by otykier** [comment]
Fixed in [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2). Thanks for reporting!
