### ISSUE TITLE
Can't rename measure in PBI

### ISSUE THREAD

**Issue by troyel** [otykier/TabularEditor#253]
When trying to rename a measure after creating it I get the following error. Trying to update PBI model running locally.
![image](https://user-images.githubusercontent.com/22769102/52302498-afea3480-298d-11e9-93ff-aee0e20eae10.png)

**Comment by otykier** [comment]
Please see issue #181 and try to see if the workarounds provided there, solves the issue for you. In short, this issue appeared after an update to Power BI (within the last 3-4 months). Looks like the Power BI object model deviates slightly from the SSAS TOM, which means that (for now), Tabular Editor support for Power BI is even worse than it was previously.

This should hopefully change, once Microsoft aligns the object models between Power BI and SSAS, which is a requirement for opening up the Power BI XMLA endpoints, which should happen some time this year.

**Comment by troyel** [comment]
Thanks for the quick reply. That makes sense. Perhaps this is why I get
compatibility 1455 when importing pbix into AAS? Fingers crossed for March
xmla support!

**Comment by otykier** [comment]
Yeah, I'm not sure 1455 is officially supported by AAS, so please be cautious about that... :-)
