### ISSUE TITLE
Schema compare option during Deployment

### ISSUE THREAD

**Issue by mattlcook** [otykier/TabularEditor#254]
Hi,

Really enjoying the Tabular Editor.  This is a request to have more targeted deployment options, similar to the schema compare features of the popular VS add-in: BISM Normalizer.  We have a few developers working on a single .bim file, and when doing a deployment, it would be really helpful to see what has changed in terms of objects as part of the deployment (ex: tables, columns, translations, perspectives, etc..).  And then we could selectively deploy the add/change/deletes that are required for the deployment.  These change details could even be logged to a dated .xls file.  

Thanks for your work.

**Comment by otykier** [comment]
I actually considered integrating BISM Normalizer at some point, but other features took precedence.

You should look into using the "Save to Folder" option, which allows you to split your Model.bim into individual files representing tables, columns, measures, translations, etc. When you do this, combined with a source control environment such as GIT, merging parallel work is easy as a breeze and conflicts are easily handed in standard DIFF tools! In fact, I'm going to present a session on this very topic at [SQLBits in Manchester](https://sqlbits.com/Sessions/Event18/Analysis_Services_DevOps_using_Tabular_Editor). I believe there'll be a video recording of the session as well :-)

This also opens the door for automated build/deployment in the longer term, so it's really worth spending some time on getting up and running.

**Comment by mattlcook** [comment]
Thanks for the response - our firm is using TFS for source control, which integrates into Visual Studio.  Do you know if it's possible to add the .bim file from Tabular Editor into a Visual Studio project?  If it's possible, then I could create a work flow using BISM Normalizer.  I've been trying to do it, but it hasn't worked so far.

**Comment by otykier** [comment]
TFS works well with the "Save to Folder" option as well, as long as you remember to include new files that were added :-)

If you want to keep the .bim format, it should still be possible to overwrite the .bim file of a Visual Studio project, with a .bim file that has been manipulated inside Tabular Editor, provided you delete the Model.bim.Layout file, which would otherwise cause crashes and whatnot when Visual Studio tries to load the .bim.

Alternatively, you could consider using BISM Normalizer to merge **from** a database that was manipulated using Tabular Editor, and into the Model.bim file of your VS project.

**Comment by mattlcook** [comment]
Thanks again for the response - I am looking forward to the video session from SQLBits.  Regarding the .bim format in Visual Studio, I have come up with the following workflow:

1). Create new VS and import from my cube model
2). Locate the .bim file and open it in Tabular Editor
3). Make changes in Tabular Editor and save back to the .bim file
4). Return to Visual Studio and launch a BISM Normalizer comparison on the project
5). Choose the project and compare to the target database
6). Hit "OK" and receive this error: "BISM Normalizer could not read JSON in BIM file".

I compared the Model.bim file from a previous VS solution with the Model.bim file that was edited by Tabular Editor, and I found one difference.  There is a top level "id" property that is missing when Tabular Editor saves the .bim file. The "id" property seems to just contain the model name.  When I manually add this property to the .bim file, I am able to do the BISM Normalizer compare successfully.  **Should the Tabular Editor be adding this property?**  

Here is an empty Model.bim file showing the "id" property at the end:

{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}

**Comment by otykier** [comment]
Hi Matt,
Thanks for posting this. I'm using the TOM AMO libs to serialize and deserialize the Model.bim file, so I'm not really in control of which properties gets written to the file. It seems that the TOM only outputs the "id" property if its value differs from the "name" property. I'm not sure how BISM Normalizer loads the metadata, but if it was using the TOM, it shouldn't throw this error. I'd suggest raising this as a bug on the [Analysis Services issue tracker](https://github.com/Microsoft/Analysis-Services/issues) - make sure to put "BISM Normalizer" in the issue title.

**Comment by otykier** [comment]
As of [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2), you can now set the "id" property inside the Tabular Editor UI before saving to a file/folder. But please note that the TOM still only outputs the "id" property to the JSON file if its value differs from the "name" property:

![image](https://user-images.githubusercontent.com/8976200/56661037-2bac7100-66a1-11e9-9dce-c4801cd73472.png)

Feel free to reopen the issue if you have any other questions.
