### ISSUE TITLE
Export all M queries as Text files 

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#26]
as now, Tabular Editor knows how to parse M queries which is fantastic by itself,  it will be really useful to have the  capability to export those Queries as a text file.

the rational is most of the time in PowerBI desktop we reuse a lot of M queries, having them as a text file, will make it easier for development.

**Comment by otykier** [comment]
You can do this easily by going to the Advanced Scripting tab and enter the following code:

```foreach(var ds in Model.DataSources)
{
    System.IO.File.WriteAllText("c:\\Output\\" + ds.Name + ".m", ds.MQuery);
}`

This assumes you already have a folder on your C: drive called "Output".

**Comment by djouallah** [comment]
it did works but when i try to save i get this 

![image](https://cloud.githubusercontent.com/assets/12554469/22144013/c1fca0a4-df43-11e6-8f58-95359de12388.png)

**Comment by otykier** [comment]
Ah - that's another bug. Could you please try to create an empty CustomActions.json file in the specified location, before saving the action?

**Comment by otykier** [comment]
Just updated [this release](https://github.com/otykier/TabularEditor/releases/tag/2.1.6229-pre) with a fix for that bug. It appears if the TabularEditor folder does not exist below AppData\Local when saving a Custom Action.
