### ISSUE TITLE
Global Script

### ISSUE THREAD

**Issue by thracian2015** [otykier/TabularEditor#260]
Hi Daniel,

Thank you so much for this tool! It got me out of the SSDT hell. Do you have planned the option to have a script of all measures, similar to MD? And diagram with graphical representation of relationships?

**Comment by otykier** [comment]
Scripting measures (and other objects, like Calculation Groups and Items) is planned. 

Visualizing the model in a diagram is something I’d like to do, but the effort required currently outweighs the value, so it’s not something that’s going to happen in the short term (but code contributions are always welcome, so if someone wants to do it, feel free!)

**Comment by thracian2015** [comment]
Thanks Daniel. By diagramming, I meant something relatively simple as a better way to visualize relationships. I think they are third-party controls.

One more thing. Exists a way to change the compatability settings or this requires SSDT?

**Comment by otykier** [comment]
Unfortunately, Compatibility Level can not currently be modified within Tabular Editor. Normally though, when upgrading a model, you can simply open the Model.bim or Database.json file in a text editor and set the level: 1200 -> 1400 -> 1470. This may cause the model to step working in SSDT however, so only do it this way, if you don't plan on using SSDT going forward. Downgrading might not work, if you're using features that are not available in the lower compatibility level.

**Comment by otykier** [comment]
Closed, as the compatibility level thing is mentioned in #200. DAX Script is on the backlog.
