### ISSUE TITLE
Implement short/long formatting for DAX Formatter

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#262]
The DAX Formatter service has now two way to format code:
- long (the current default) tries to reduce the number of rows of the formula
- short keeps the minimum content on every row, increasing the number or rows

The short version requires the MaxLineLenght parameter to be 1 in the request.

Additional bonus: update the DAX Formatter icon.

**Comment by otykier** [comment]
Hi Marco,
Nice! Will update the icon and make both long/short formatting available in the UI. Thanks!

**Comment by marcosqlbi** [comment]
Great!
In DAX Studio we use:
F6 to format the code with the default mode
CTRL+F6 to format the code with the alternate mode
Default mode (long or short - default of default is long to keep compatibility with previous settings) is set in the preferences.
We might use a similar approach in Tabular Studio :)

**Comment by otykier** [comment]
Good idea with similar hotkeys! "Tabular Studio"? Are you suggesting a rebrand? :-)

**Comment by marcosqlbi** [comment]
OPS!! Tabular Editor!!! :)

**Comment by otykier** [comment]
[Release 2.8.1](https://github.com/otykier/TabularEditor/releases/tag/2.8.1) was just updated, and now lets you select which DAX formatting option to use:

![image](https://user-images.githubusercontent.com/8976200/54395636-a94b8d00-46b0-11e9-9bbe-eaacd5f4235d.png)

**Comment by ExcelDude** [comment]
@otykier nice one! unfortunately now deploy and format have the same shortcut F6 - maybe deploy should be assigned a new one :-)

**Comment by otykier** [comment]
Oh wow, why didn't I notice that? Thanks! I'll change the shortcut for deploy, since I think it's practical to align the shortcuts between Tabular Editor and DAX Studio as much as possible.

**Comment by ExcelDude** [comment]
Yes, it’s definitely very nice to have them aligned

**Comment by marcosqlbi** [comment]
SSDT does not have a shortcut for deploy and it uses:
F5 run
F10 step over
F11 step into

I would say F5 is the closest semantic to Deploy, but I'm concerned of pressing F5 by mistake (too close to F6). In DAX Studio F5 runs the code, but it does not have the side effects of a Deploy.
Therefore, considering a F10 or F11 seems safer from this point of view. But I'm very open to other considerations!

**Comment by otykier** [comment]
[Keyboard shortcuts](https://github.com/otykier/TabularEditor/wiki/Keyboard-Shortcuts).

F5 is already in use for running a script in Tabular Editor and F10 is used to show the Best Practice Analyzer window.

Maybe a combination such as CTRL+D for Deploy? It only brings up the deployment wizard UI, so the shortcut itself wouldn't actually have any side effects.

**Comment by marcosqlbi** [comment]
It should work - at the same time, I'd link a "quick deploy" feature that does not popup the dialog box or at least does not require all the clicks required now. It would be very useful in certain frequent edit operations (I made an intensive use of calculation groups lately!).
