### ISSUE TITLE
Not responding when selecting field after Refresh Table Metadata

### ISSUE THREAD

**Issue by andboy** [otykier/TabularEditor#264]
Hi I’m running into the following issue:

1.	Open model from Server
2.	Right Click on `<Table>` -> Refresh Table Metadata…
             a.	Tabular Editor: ‘Unable to validate source query’
3.	`<Table>` -> Partitions -> All `<Table>`
4.	Edit SQL Statement - > Click tick mark: √
5.	Right Click on `<Table>` -> Refresh Table Metadata…
6.	Apply Tabular Edit suggestions (including removing some fields)
7.	Choosing a field which is not included in the SQL statement anymore
8.	Tabular Editor crash

Unfortunately I’m not able to get the ‘Exception stack trace’ before the program is not responding and I have to shut it down.

**Comment by otykier** [comment]
Hi @andboy.
I'm not able to reproduce this issue. Can you provide the following details please:

- Build version number of Tabular Editor used (File > Preferences)
- Type of data source provider (SqlClient, OLEDB, ODBC, or...?)
- Number of partitions on the table
- Partition SQL query in step 2, before making the change
- Partition SQL query in step 5, after making the change

**Comment by andboy** [comment]
Build version: 2.8.7004.27392
Data source provider: System.Data.SqlClient
Number of partitions: 1

Step 2 SQL:
```
SELECT [Selskab]
      ,[Løbenr]
      ,[Dokumentnr]
      ,[DokumentTypeNr]
      ,[DokumentType]
      ,[Posteringsdato]
      ,[BeløbDKK]
      ,[DimSagBKey]
      ,[DimFinanskontoplanBKey]
      ,[DimFirmaBKey]
      ,[DimLukkepostBKey]
      ,[DimOrganisationBKey]
      ,[DimProduktbogføringsgruppeBKey]
      ,[DimSegmentBKey]
      ,[DimVirksomhedsbogføringsgruppeBKey]
      ,[DimPosteringsdatoDKey]
  FROM [dbo].[FactFinans]
```

Step 5 SQL:
```
SELECT 
      [BeløbDKK]
      ,[DimSagBKey]
      ,[DimFinanskontoplanBKey]
      ,[DimFirmaBKey]
      ,[DimLukkepostBKey]
      ,[DimOrganisationBKey]
      ,[DimProduktbogføringsgruppeBKey]
      ,[DimSegmentBKey]
      ,[DimVirksomhedsbogføringsgruppeBKey]
      ,[DimBogføringsdatoDKey]
      ,[DimBilagBKey]      
  FROM [dbo].[FactFinans]
```

**Comment by andboy** [comment]
Hi Daniel,

After installing the newest build version: 2.8.7012.42370 i issue above is resolved :)

**Comment by otykier** [comment]
Good to know - thanks!
