### ISSUE TITLE
Calculation Groups deletion

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#265]
Tabular Editor crashes if I try to delete a Calculation Group when I right click on a Calculation Group and click 'Delete Calculation Group'. Actually, the first time I click delete it doesn't do anything. The second time it crashes.

**Comment by kalmenk** [comment]
Same issue occurs with Calculation items. Tried pressing Delete while selecting the Calculation Group/Item and the issue also occurs.

**Comment by otykier** [comment]
[Release 2.8.1](https://github.com/otykier/TabularEditor/releases/tag/2.8.1) updated to fix this issue. Thanks!
