### ISSUE TITLE
Creating hierarchy using Advanced Ccripting

### ISSUE THREAD

**Issue by faurholdt** [otykier/TabularEditor#268]
Hi Daniel
Sorry if this is not the right place to ask this...

I'm trying to create a hierachy using a script. This is what I've got so far:

Selected.Table.AddHierarchy("Org", "", Column[1,2,3]);

I take it there's a problem with how I select the columns. The function expects an argument "levels" but that doesn't really tell me much. I'm guessing take it that it has something to do with the TOMWrapper.¨

Kind regards and thank you

**Comment by otykier** [comment]
Absolutely! All questions are welcome, and apologies for not having better documentation for this stuff.

The "levels" argument should be an array of strings, or an array of columns. So you can do it in one of two ways. If using strings, they are assumed to be names of columns that exist on the table where you're creating the hierarchy:

```csharp
// Assumes the selected table have 3 columns named "Column 1", "Column 2" and "Column 3" respectively:
Selected.Table.AddHierarchy("Org", "", new[] { "Column 1", "Column 2", "Column 3" } );
```

Or you can pass column references:
```csharp
// Assumes the selected table have at least 3 columns:
var col1 = Selected.Table.Columns[0]; // First column on the selected table in metadata order
var col2 = Selected.Table.Columns[1]; // Second column
var col3 = Selected.Table.Columns[2]; // Third column
Selected.Table.AddHierarchy("Org", "", new[] { col1, col2, col3 } );
```

If you select a range of columns, you can use the following code to create a hierarchy that contains the selected columns as levels. However, this functionality is already available in the UI by right-clicking and choosing "Create New > Hierarchy", so this code is only for demonstration purposes:

```csharp
Selected.Table.AddHierarchy("Org", "", Selected.Columns.ToArray());
```

Feel free to re-open the issue if you have any further questions. If the questions are not related to scripting and hierarchies, feel free to open a new issue.
