### ISSUE TITLE
Composite models: Cannot connect to PowerBI Desktop 2.67.5404.581 64-bit (March 2019)? 

### ISSUE THREAD

**Issue by devaccount89** [otykier/TabularEditor#269]
Hi Daniel, 

after updating my PowerBI Desktop to the latest version, i cannot connect with Tabular Editor to it. 
I also get the same error with DaxStudio. 
Are you aware of any issues or should it be raised with the PowerBI Guys? Thanks. 

Best, 

Moritz

![image](https://user-images.githubusercontent.com/25116639/54420665-e8a6c780-470a-11e9-9e95-99f4a734e9e9.png)

**Comment by otykier** [comment]
I'm not able to reproduce this issue. What kind of data source does your .pbix file use?

**Comment by devaccount89** [comment]
Great to hear. I am using most of the time import mode. But I have two tables connect via direct query. (All hitting an SQL Server 2016 ) 
Is this supported as well? Using composite of Import and direct query?

**Comment by devaccount89** [comment]
Plus: I connected to another file which is import mode only -> This works also with the March Version of PBI Desktop. 
Thanks Daniel for the super quick answer!

**Comment by devaccount89** [comment]
Hi Daniel, 
i just noticed that when you safe a pbix which is a composite model on a page which has only visuals with DirectQuery Data, neither Tabular Editor nor Dax-Studio is recognizing the server as running. ( Mentioned issue above) When you save the report on a blank page- and reopen- it works without any issues. 
Not sure if this is a bug or a issue. 
Thanks.
