### ISSUE TITLE
Virus in the package?

### ISSUE THREAD

**Issue by hohlick** [otykier/TabularEditor#270]
Windows Defender found a virus in the package when I tried to download it:
Trojan:Win32/Azden.A!cl

**Comment by otykier** [comment]
Interestingly, you're not the first one to report this. Seems to be a false positive (if you're in doubt - you can clone the repo and compile the source yourself). I'm trying to contact the Windows Defender team to find out what's going on.

**Comment by otykier** [comment]
Can you provide the [Definition Version](https://docs.microsoft.com/da-dk/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version) of your Windows Defender software? Thanks!

**Comment by hohlick** [comment]
![image](https://user-images.githubusercontent.com/15851608/54516701-bac2bc80-4970-11e9-9c5b-e39b3e5edf00.png)

**Comment by hohlick** [comment]
Do you need a more details on this treat from Defender?

**Comment by otykier** [comment]
That's fine - thanks!

**Comment by otykier** [comment]
I got an answer from the Windows Defender team:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. 3. Run “MpCmdRun.exe -SignatureUpdate” 
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
