### ISSUE TITLE
Error with forbidden character at Deserialization

### ISSUE THREAD

**Issue by djeepy1** [otykier/TabularEditor#274]
Hi, 

I got this error when connecting to my Power BI model (through XMLA Endpoint) :
_Deserialization failed: The 'name' property cannot contain any of the Following characters: …._
(see attached Screenshot)

Workspace and database names contains parenthesis and hyphen. I successfully connect to another workspace with parenthesis but where all datasets have "clean" names.
I added a dataset with parenthesis in name and I reproduce error.

![TabularEditor-Bug-ForbiddenCharacters](https://user-images.githubusercontent.com/7985875/55007220-568ea100-4fdf-11e9-8c83-56b08d072eff.png)

**Comment by otykier** [comment]
Unfortunately, this is not something that can be fixed within Tabular Editor, as the deserialization happens within the [AMO/TOM library provided by Microsoft](https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/).

I will forward this information to the product team, and see if they have any suggestions.

**Comment by otykier** [comment]
Update: The product team is aware of this issue, and will provide an updated version of the client libs soon. When that’s out, I will provide a new build of Tabular Editor that targets the new lib, and then we should be good. Stay tuned!

**Comment by otykier** [comment]
@djeepy1 Do you still have this issue with the latest version of Tabular Editor?

**Comment by djeepy1** [comment]
Daniel, 
I've just tested again with the same version of DAX Studio (2.8.3) and...it works.
Maybe a modification from the service side ? (I don't remember any update of my DAX Studio)
JP
