### ISSUE TITLE
Time formats like "hh:mm tt" show "5:12 tt" not "5:12 PM"

### ISSUE THREAD

**Issue by dgosbell** [otykier/TabularEditor#275]
Some of the built in format strings for datetime columns show "tt" as the placeholder for AM/PM.

![image](https://user-images.githubusercontent.com/8241830/55054637-af7c3900-50b4-11e9-899c-69d251145d45.png)

I believe this is a c# time format option where as I think tabular uses the following options
[https://docs.microsoft.com/en-us/dax/custom-date-and-time-formats-for-the-format-function](https://docs.microsoft.com/en-us/dax/custom-date-and-time-formats-for-the-format-function)

This is how the FORMAT function treats these different options
![image](https://user-images.githubusercontent.com/8241830/55054567-76dc5f80-50b4-11e9-99dd-d76072c14002.png)

This matches the behaviour we are seeing from columns using format strings with the "tt" suffix

**Comment by otykier** [comment]
Good catch. Indeed, I populate the dropdown from the .NET [GetAllDateTimePatterns()-method](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.getalldatetimepatterns?view=netframework-4.7.2), and just assumed that Tabular would use the same patterns.

I guess a simple way to fix it, would be to replace any occurences of "tt" -> "AMPM" - at least until we discover other tokens in the .NET patterns, that are not compatible with Tabular :-)

**Comment by dgosbell** [comment]
> I guess a simple way to fix it, would be to replace any occurences of "tt" -> "AMPM" - at least until we discover other tokens in the .NET patterns, that are not compatible with Tabular :-)

Yes, that is the only symbol I noticed that was causing an issue. Of course you'd probably need to flip this replacement back the other way when showing the preview of the format string...

**Comment by otykier** [comment]
Indeed. An update was already pushed to GitHub. Will provide a pre-release later today that includes this.

**Comment by otykier** [comment]
Fixed in [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2).
