### ISSUE TITLE
DAX Formatter not working behind Proxy

### ISSUE THREAD

**Issue by ExcelDude** [otykier/TabularEditor#277]
Hi Daniel,
I'm opening a new issue as you mentioned in https://github.com/otykier/TabularEditor/issues/41 - I'm having the same issue, TabularEditor cannot use the DaxFormatter while I'm dialed into our corporate VPN - which is strange, because DAX Studio can.
So, right now I'm copying back and forth between the two to get my measures formatted.

Thanks a lot for this phantastic tool, makes my work so much more enjoyable :-) :+1: 

also updating does not work, probably for the same reason:
![image](https://user-images.githubusercontent.com/49077745/55257820-61586880-5261-11e9-8fe8-9d07ea6fdc6c.png)

**Comment by otykier** [comment]
Should be fixed in [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2). Thanks for reporting!
