### ISSUE TITLE
Git merge conflicts

### ISSUE THREAD

**Issue by Stewwe1** [otykier/TabularEditor#279]
Hi Daniel!
we really appreciate your work! Thank you.
 I have the problem that I can't load the .json back into tabular editor, if git merged due to conflicts. When I reconstruct the HEAD in the json, the load process works again. 

How do I solve this problem?

Thank you!

Steffen

**Comment by otykier** [comment]
If I understand your question correctly, you have a file that contains Git conflict markers? Well, as long as the markets are in the file, it won’t be a valid JSON file, or more specifically, it won’t be a valid TOM document, so that’s why it won’t load. Tabular Editor does not support the Git conflict markers.

**Comment by Stewwe1** [comment]
Hello Daniel,

thank you for your quick reply. Our goal is to work parallel on our tabular model as you showed in your "Multiple developer - Modeling workflow".
I attached you a file, which caused our problem:
![Daniel](https://user-images.githubusercontent.com/49725984/56343459-2049d900-61bb-11e9-8def-d19ebc733bba.png)
As you can see Git merged our two files, but Tabular Editor can`t read the green underlined lines.
I´m relatively new to Github: are this your mentioned Git conflict markers? 

Thank you

Steffen

**Comment by otykier** [comment]
Yes - these are the git conflict markers. As long as these are in the file, the file is not a valid JSON document, and therefore it's unreadable by Tabular Editor. You have to resolve the conflict first, using a diff tool. I normally do it through the Team Explorer window in Visual Studio.

However, based on the values of the "name" property in the JSON, I suspect that these are names of workspace databases belonging to individual developers (Karina and Steffen). Before committing the database.json file to Git, you should make sure that it contains an invariant name ("Performance_Test"), to avoid these conflicts going forward. In other words, make sure to edit the file or change the database name in Tabular Editor before saving as a file.

**Comment by Stewwe1** [comment]
Hello Daniel!

I quickly solved our issue with your help.

Thank your very much!

Steffen
