### ISSUE TITLE
Search enhancement: item & dependencies

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#280]
This is an idea I think would benefit from more discussion, but I want to put it out there.

## Workflow

I will often search for a measure in a large model with intention to inspect or change it. In a complex model, it is quite likely that there will be multiple measure dependencies, and often multiple levels of dependencies. I may have to inspect or modify a dependency of the measure, rather than the measure itself. Or, if there are many measures that depend on my measure of interest, I will want to inspect those to ensure my change doesn't break anything downstream.

Currently, I try to come up with a literal substring which is in all of the measures I'm concerned with, but this depends on:

1. Me knowing the full dependency tree already
2. The related measures sharing a unique substring

The first item is not too difficult in a small enough model. The second is often impossible.

## Suggestion

When searching, add additional controls to allow:

1. Search for object and items it depends upon
2. Search for object and items which depend on it
3. Both (1) and (2).
4. Maybe something to control how many levels of dependency in each direction are displayed?

I know that you can sort of get here now with the dependency viewer, but this is a separate window and you still see all the irrelevant measures in the expanded tree view.

I would be happy to discuss further to figure out something that will be useful, or to hear feedback of other potential solutions to deal with the challenge of making edits to a tree of dependencies.

**Comment by otykier** [comment]
Great suggestion, and I'm certainly open for discussion/improvements in this area. My largest concern is adding too many new controls, buttons, etc. to the main UI, making it too cluttered. That's primarily why I initially decided to have the dependency tree in a separate window (you can still work in the main UI why the dependency tree window is open). UX is really not my strong suit, so if anyone has some experience in this area and would like to contribute - please speak up!

Today, you can navigate to dependent measures by placing the cursor over any measure reference in the DAX expression you're currently looking at, and hitting F12 ("Go to definition"). You can then use the little arrows at the top right corner to navigate back and forth (or use ALT+Left/Right arrow).

I imagine something like "Peak definition", in addition to "Go to definition" would be very useful - imagine putting the cursor over a measure reference, hitting some shortcut key, and then the DAX expression of whatever measure is under the cursor is shown in a little tooltip or popup box.

Regarding searching, Dynamic LINQ mode kind of lets us do this today, albeit it's not very intuitive to use, and you have to know the syntax:

1. The following search expression will find all measures that are being referenced (directly) by [Total Sales]:
   ```
   :ObjectType = "Measure" and ReferencedBy.Measures.Any(Name="Total Sales")
   ```
2. The following expression will find all measures that depend (directly) on [Total Sales]:
   ```
   :ObjectType = "Measure" and DependsOn.Measures.Any(Name="Total Sales")
   ```
3. The following expression will find all measures that depend (directly **and indirectly**) on [Total Sales]:
   ```
   :ObjectType = "Measure" and DependsOn.Deep().Any(Name="Total Sales")
   ```
Also, results are returned in list form, so in the last case you don't get a visual representation of the dependencies between objects.

Admittedly, this is not ideal for the workflow you describe. Maybe a better option would be a new toggle button "Measure Dependency Mode", in addition to the current 3 search result options (hierarchical by parent, hierarchical by child, flat list). Once you choose this "Measure Dependency Mode", the search engine will only search among measures. The results could then be displayed in a way that would let you expand each measure to navigate to both upwards and downward dependencies. So something like this, if I search for "Sales", with the possibility of drilling both up and down within every measure at the root of the tree:

![image](https://user-images.githubusercontent.com/8976200/56671518-180b0580-66b5-11e9-8f45-fc3027791ab0.png)

**Comment by greggyb** [comment]
There are some very good ideas in your response, and I'll follow up more later. The thing that stands out as probably easy to implement and which could help the workflow a low, although still being rather manual, would be having a popup with another measure's definition in it (preferably editable).

With such a popup, I could pull up several measures onto my screen and work on one while looking at the others. If the popup is editable, I could easily refactor by pulling code from one measure to another. For such a popup, I think the full expression editor would be great. Perhaps even the properties pane. DAX Studio and SSMS and Visual Studio all have an interface that I think would work well. I don't know how much effort it would be to implement it. This is a tabbed interface that allows tabs to be pulled out of the main window. I've included a snip below. If the current Expression Editor and properties pane could be tabbed and given an interface like this that allows me to view multiple and arrange them as windows on my desktop, I think I'd be a very happy camper, even if the search functionality I described isn't there.

As a start, a peek or even a view-only popup would be great. But multiple windows, each editable would be superb.

![image](https://user-images.githubusercontent.com/12113895/56672651-ce0a2b80-6684-11e9-9e68-82a5a471c7d8.png)

**Comment by greggyb** [comment]
There are some very good ideas in your response, and I'll follow up more later. The thing that stands out as probably easy to implement and which could help the workflow a low, although still being rather manual, would be having a popup with another measure's definition in it (preferably editable).

With such a popup, I could pull up several measures onto my screen and work on one while looking at the others. If the popup is editable, I could easily refactor by pulling code from one measure to another. For such a popup, I think the full expression editor would be great. Perhaps even the properties pane. DAX Studio and SSMS and Visual Studio all have an interface that I think would work well. I don't know how much effort it would be to implement it. This is a tabbed interface that allows tabs to be pulled out of the main window. I've included a snip below. If the current Expression Editor and properties pane could be tabbed and given an interface like this that allows me to view multiple and arrange them as windows on my desktop, I think I'd be a very happy camper, even if the search functionality I described isn't there.

As a start, a peek or even a view-only popup would be great. But multiple windows, each editable would be superb.

![image](https://user-images.githubusercontent.com/12113895/56673893-14f92080-6687-11e9-91c8-31c7c060da31.png)

**Comment by otykier** [comment]
Yeah, I had a feeling this discussion would head towards some major UI overhaul. And you're not the first to bring it up :-) In fact, I considered something like this around 2 years ago (issue #36), but I guess the tool wasn't as popular back then, so I didn't receive a lot of responses at the time.

I'd like to have full support for dragging, dropping and docking windows and DAX "documents", similar to Visual Studio and other tools. The only problem is that this is not something that's supported out of the box in a WinForms application - I'd have to include a 3rd party lib to achieve this, and all the good quality docking frameworks cost $$$... if anyone can pull some strings, or have any suggestions in this regard, I'm all ears! (I'm not going to write my own docking code... life's simply too short)

**Comment by greggyb** [comment]
[Darren Gosbell](https://github.com/dgosbell) has got a UI like I've described in the free DAX Studio.

It seems like the Output window for a measure is 1/3-1/2 of the way to workable. I'm not sure about what the level of effort would be for the changes required. If I use an Advanced Script to `Output()` a measure, I get an independent window that

1. allows me to edit the measure which was output
2. does not include the Expression Editor
3. takes exclusive focus and prevents me from interacting with the primary Tabular Editor window
4. can only have one instance

My thought is that if you could change items (2) and (3) and (4) above, it would achieve much of what we are discussing. I know that item (3) is do-able based on the dependency view and BPA window and how they do not prevent interaction with the primary window. That leaves (2) and (4) as my unknowns. Would that be a feasible approach?

Obviously it's ignoring the search entirely.

**Comment by marcosqlbi** [comment]
DAX Studio is written in WPF, not in Windows Forms - the same approach cannot be used in Tabular Editor without a big rewrite. IMHO, it is not even necessary in the short term.
A Script Window is a good idea for both Tabular Editor and DAX Studio (for different reasons), but there is a big background work to get a proper foundation. The UI is a detail at that point.

**Comment by otykier** [comment]
So I was playing around today with an open source WinForms docking framework called [DockPanelSuite](https://github.com/dockpanelsuite/dockpanelsuite) which is in active development. It turned out to be quite easy to set up, and it actually looks and feels phenomenal. I even get theming-support right out of the box (Blue, Light and Dark themes - very similar to VS2015). The thing I like most about it, is that the footprint is very low (the DockPanelSuite library is just a single 300 KB DLL).

Here's how the main UI looks with the Blue VS2015 theme of DockPanelSuite:

![image](https://user-images.githubusercontent.com/8976200/57157898-3920d400-6de2-11e9-8720-89eb9a586c75.png)

Just like in VS, you can rearrange the UI elements however you like. Is this what you had in mind @greggyb ?

**Comment by greggyb** [comment]
The primary goal is not the ability to rearrange UI elements, but to have multiple instances of the Expression Editor open simultaneously, so I can see multiple measures simultaneously. Ideally I could edit the measures in each of these instances of the expression editor, but even a view-only instance would be helpful.

A very quick and dirty mockup is shown below, using DAX Studio. I have created several instances of query panes. Each of these query panes can be edited and evaluated separately.


![image](https://user-images.githubusercontent.com/12113895/57159545-2394b580-6db4-11e9-9e6f-dd9dfffef2f5.png)

**Comment by otykier** [comment]
Yeah, that's exactly the reason why I want to have a proper UI docking framework first. Without it, the best I can do is just opening up lots of tabs in the upper right portion of the screen, which would not solve the requirement of viewing multiple measure expressions simultaneously. So far I've got this:

![image](https://user-images.githubusercontent.com/8976200/57161540-23181100-6dec-11e9-8bce-84b8e34314c5.png)

You bring up a new expression editor by double-clicking on an object. Still needs some more work (for example, the Tab should show the name of the object instead of "Expression Editor"), but I think this is the right direction to go.

**Comment by greggyb** [comment]
Yes, that is beautiful!

I have many additional thoughts as I look at this. I'll share them just to give you food for thought as well, but I don't have a good feel for the relative difficulty, and I also can't even give you a good ordered ranking of them. I want to be clear that I'm not thinking of these as immediate needs or things required for rolling out tabs like you've shown. Just sharing some thoughts.

- Properties pane should probably represent either of the below. Both make sense to me.
  - The properties of the measure (or whatever else exists) in the focused tab
  - The properties of the item selected in the TOM explorer
- If opening a tab can be a scriptable action, I could imagine opening up all dependencies or all depends-on measures based on the current selection - this could just be a custom action and wouldn't need any support beyond being able to open a tab for a measure from an advanced script
  - An obvious enhancement would probably be trying to do some sort of smart layout for the opened tabs. I expect this would be easy to start and near-impossible to perfect.
- It may make sense to make a selector in advanced scripting for "Open measures" (I'm not sure on the name) so that you could make a script that works on `Open.Measures` similar to how you can do `Selected.Measures`
- Would the script editor be positionable similarly? 
- Could I have two TOM Explorers open simultaneously? I'm thinking for a very large model, I could have two explorers open which are simply focused on different tables in the model.
  - Expanding on above, something like Visual Studio's Solution Explorer's "Scope view to this object" could be interesting, to scope to a table or a folder. This is well beyond tabs.
  - Maybe instead of scope to this, you could have independent searches on each TOM Explorer?

**Comment by otykier** [comment]
Some excellent ideas there! Here are my thoughts:

- Properties pane should reflect the object that currently has focus - this is the most intuitive way, I believe.
- It should be easy to let a script open up a new expression editor tab. But the smart layout thing is something I dread... :-)
- Instead of `Open.Measures`, I think I will provide an UI toggle option that lets you decide whether the `Selected`-object should point to the current selection in the TOM Explorer (default), or the currently open expression tabs - that way, you don't need to modify your scripts.
- The script editor can be rearranged just like any other editor window, and you will also be able to open multiple script editors.
- Having multiple TOM Explorers makes a lot of sense (especially if you can scope them to a specific perspective, filter them independently, or scope to a specific parent object). However, this is more complicated due to the UI interactions that are possible within the Explorer, so this is lower priority for now.

**Comment by greggyb** [comment]
Definite agree on the properties behavior you laid out there. I think that is most intuitive.

On the `Selected` object, perhaps instead of a toggle to change behavior of the script, a button to "Select open tabs". It gives an easy way to operate on the open tabs, and also lets you preserve the existing semantic. I say this, because some of the most frequently misunderstood UI elements I've seen are toggles, rather than actions. The first two examples that jump to mind are both in PBI - the drilldown toggle (original drilling experience), which changes the behavior of left-click; and the visual interactions toggle, which turns on additional UI elements in visual headers. These have definitely caused a lot of issues in trainings I've given, and bias me against toggles.

**Comment by otykier** [comment]
That's a much better suggestion than what I came up with. Thanks!

**Comment by greggyb** [comment]
Thank you for all your work on Tabular Editor. It's a great tool and I appreciate it!
