### ISSUE TITLE
Enhancement request: Display DAX Formatter errors

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#281]
I am fallible. Sometimes when refactoring a measure, I will make mistakes and create invalid DAX. DAX Formatter typically provides very good diagnostic error messages (including line number, and column number) about what is wrong with the DAX. When we call DAX Formatter in DAX Studio, it appears that this error information is just dropped, and we simply get "DAX formatted successfully" or "Could not format DAX." in the message window.

Is it possible to display the DAX Formatter error in full? Perhaps in a popup? If it is a popup, it should not prevent interaction with the main Tabular Editor window, as it would be useful to see the error and edit DAX at the same time.

**Comment by otykier** [comment]
The only reason I haven't implemented this, is because I have something much better planned - unfortunately, I can't reveal too much about it now, but it's pretty safe to say that it'll take the DAX editing experience of Tabular Editor to new heights :-)

**Comment by greggyb** [comment]
Okay, I'll be patient (:

**Comment by greggyb** [comment]
I was also going to open an enhancement request for line numbers in the Expression editor. Should I wait patiently for that, too?

**Comment by otykier** [comment]
You'll get line numbers in the next release. Will get back to you once I have something more specific regarding DAX formatter errors. Closing the issue for now.

**Comment by otykier** [comment]
Just FYI, [2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3) now shows line numbers on the DAX editor.
