### ISSUE TITLE
Calculated groups disappear

### ISSUE THREAD

**Issue by FranMullor** [otykier/TabularEditor#282]
When I create calculated groups when updating the model they are created but the pending update warning jumps and disappear.

First. If I create it in pbit file, when I open the pbit post this error

Solve incoherence.

Tables that are no longer associated with a valid query were removed from the model

If I create it in pbix directly, when I refresh model 
First error from culture.
<a href="https://ibb.co/hWzfdHP"><img src="https://i.ibb.co/hWzfdHP/xxxx.png" alt="xxxx" border="0"></a>

<a href="https://ibb.co/xYtV4Rx"><img src="https://i.ibb.co/xYtV4Rx/xxxx2.png" alt="xxxx2" border="0"></a>

I eliminate the translation

<a href="https://ibb.co/sWCmL0J"><img src="https://i.ibb.co/sWCmL0J/xxxx3.png" alt="xxxx3" border="0"></a>

and I can see calculate groups but jump aply changes again and calculate groups dissaparead.

<a href="https://ibb.co/PF6DXCW"><img src="https://i.ibb.co/PF6DXCW/xxxx4.png" alt="xxxx4" border="0"></a>

**Comment by otykier** [comment]
I'm not able to view the screenshots you provided (next time - simply copy/paste them directly into the GitHub text editor). But it looks like you're trying to create Calculation Groups on a Power BI model? To my knowledge, this is not supported by Microsoft. Currently, it's only available in SQL Server 2019 CTP 2.3+ (it should be available in Azure Analysis Services soon).
