### ISSUE TITLE
File does not save as .BIM

### ISSUE THREAD

**Issue by scottjt** [otykier/TabularEditor#285]
In the save dialog, "Save as type" does not seem to do anything.  For example, I started a new project, saved as "Project1" with Save as type = *.bim.  It should automatically attach .bim so that I end up with Project1.bim.  Instead I get Project1 with no extension.

**Comment by otykier** [comment]
Confirmed bug. .bim should be the default extension, when you don't explicitly specify that in the Save File dialog.

**Comment by otykier** [comment]
Fixed in [2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3).
