### ISSUE TITLE
Postgresql DB connection

### ISSUE THREAD

**Issue by Tanner-Pettit** [otykier/TabularEditor#286]
Is it possible to connect to postgressql DBs ? I have not had any luck thus far.

**Comment by otykier** [comment]
Is your question regarding the "Table Import Wizard" in Tabular Editor, or Analysis Services Tabular in general?

Unfortunately I don't have access to a PostgreSql DB from where I work, so I'm not able to assist much, but if using an ODBC or OLE DB legacy (aka. "provider") data source, I expect that it should just work. One thing to note, though, is that Tabular Editor is a 32 bit application, so depending on your environment, you might need to have both 32 and 64 bit database drivers installed, to make this work.

**Comment by Tanner-Pettit** [comment]
My question was in regards to both, at this point i have been able to connect to the data postgres data source, however when i am trying to import tables there is not preview for tables and i get an error saying "object reference not set to an instance of an object". I also get an unresponsive interface when i refresh the table metadata. i attached two screen shots below, perhaps im just missing something ?
![image](https://user-images.githubusercontent.com/50592399/57880188-20ee8300-77ec-11e9-85b9-90920229a8fc.png)
![image](https://user-images.githubusercontent.com/50592399/57880213-32378f80-77ec-11e9-999f-35c5d2a98d2c.png)

**Comment by otykier** [comment]
> when i am trying to import tables there is not preview for tables and i get an error saying "object reference not set to an instance of an object"

Does the interface still show the list of tables and views in the database, even though it cannot preview the content?

 Which Provider is your data source using?

**Comment by Tanner-Pettit** [comment]
Yes, i can view all the tables and view in the database but where the preview would normally load there is an error "42601" screenshot attached below. The provider is system.data.odbc. Thanks for your help!
![image](https://user-images.githubusercontent.com/50592399/57882034-bf7ce300-77f0-11e9-9798-9febb511dc12.png)

**Comment by otykier** [comment]
I'm not an expert in PostgreSql syntax, but I believe you need to use LIMIT as row reduction clause, and "Double Quotes" for the identifiers. Otherwise, the SQL statement generated by Tabular Editor is not valid PostgreSql:

![image](https://user-images.githubusercontent.com/8976200/57889846-32f51380-7836-11e9-95dc-a4344b581307.png)

**Comment by Tanner-Pettit** [comment]
WOW, Thank you so much, i'm feeling a bit embarrassed right now, that worked!
