### ISSUE TITLE
Feature: Generate TMSL script from command line

### ISSUE THREAD

**Issue by msdotnetclr** [otykier/TabularEditor#289]
Add new command line switch **_-X|-XMLA xlma_script_file_** to allow TMSL script generation
When -X is used, only TMSL script is generated. Deployment will not be executed

E.g. TabularEditor.exe .\Model.bim -D server database -L ($username) ($password) -O -X database_release.xmla

**Comment by msdotnetclr** [comment]
I have implemented this feature and created Pull Request #288 
@otykier Please review and let me know if you have any questions

**Comment by otykier** [comment]
This is awesome, and a great way to utilise the CLI of Tabular Editor - I can see a lot of potential use cases for this! Thanks a lot for the contribution. Will review the pull request and get back to you!

**Comment by otykier** [comment]
Now available in [2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3). Thanks again! @msdotnetclr please see my comment on #288 regarding application type.
