### ISSUE TITLE
Calculated table name cannot use "."

### ISSUE THREAD

**Issue by applezorro** [otykier/TabularEditor#292]
Calculated table name cannot use ".", but in PowerBI Desktop, can do this.

**Comment by otykier** [comment]
Good catch. This restriction does not apply to Tabular Models of Compatibility Level 1200 or newer, so there's no need for Tabular Editor to check whether a table name contains special characters. Will provide an updated build ASAP.

**Comment by otykier** [comment]
I've uploadet a new build of 2.8.3 where this is fixed: https://github.com/otykier/TabularEditor/releases/tag/2.8.3
