### ISSUE TITLE
cannot save calculated table in pbit

### ISSUE THREAD

**Issue by applezorro** [otykier/TabularEditor#293]
1. open a pbit file
2. create a calculated table T = {0}
3. can not save this.

**Comment by otykier** [comment]
I'm not able to reproduce this issue. The .pbit file seems to save just fine from within Tabular Editor, although Power BI Desktop behaves a little weird when looking at the Data tab:

![image](https://user-images.githubusercontent.com/8976200/58176179-0875e100-7ca2-11e9-9a9d-8f471f838bfa.png)

(The calculated table should only have a single column with a single value - yet Power BI Desktop seems to show data coming from one of the other tables of the model)

Are you getting an error message when trying to save the file, or what is happening more specifically?

**Comment by applezorro** [comment]
Dear,


STEP1: create a calculated table and input DAX



input DAX : {0} and then get:





STEP2: when I lose my keyboard focus on this editor and re back, it will lose:


 


this dax is lose.








------------------ 原始邮件 ------------------
发件人: "Daniel Otykier"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 晚上8:59
收件人: "otykier/TabularEditor"<TabularEditor@noreply.github.com>;
抄送: "宗萌"<406785256@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [otykier/TabularEditor] cannot save calculated table in pbit(#293)




I'm not able to reproduce this issue. The .pbit file seems to save just fine from within Tabular Editor, although Power BI Desktop behaves a little weird when looking at the Data tab:
 

 
(The calculated table should only have a single column with a single value - yet Power BI Desktop seems to show data coming from one of the other tables of the model)
 
Are you getting an error message when trying to save the file, or what is happening more specifically?

**Comment by otykier** [comment]
Sorry, I'm not sure what you mean by losing keyboard focus on the editor. This is how it behaves on my screen:

![calculatedtable](https://user-images.githubusercontent.com/8976200/58246869-83013800-7d58-11e9-8e7d-e993312e0847.gif)

**Comment by applezorro** [comment]
Yes, if you open a tabular database in SSAS server, it works.

BUT:
1. Open a new empty PowerBI Desktop
2. Save directly as a pbit file
3. Open this pbit file with this tool
4. Create a calculated table and this issue will show as below:

![bug TabularEditor-can-not-create-calculatedtable-in-empty-pbit](https://user-images.githubusercontent.com/4034918/58274109-bda0ba00-7dc4-11e9-95ee-68509282c8d3.gif)

Do you think this is by design?

**Comment by otykier** [comment]
Sorry for not responding sooner. Did you check the "Allow unsupported Power BI features" under File > Preferences > Features:

![image](https://user-images.githubusercontent.com/8976200/62110831-8f04fb00-b2af-11e9-9b22-1da57d4eee75.png)
