### ISSUE TITLE
Translation json structure

### ISSUE THREAD

**Issue by kkostantos** [otykier/TabularEditor#297]
Hello,

I am facing an issue regarding editing the exported translation json file via the tabular translator tool (https://www.sqlbi.com/tools/ssas-tabular-translator/). When a translation json file exported from tabular editor the section referenceCulture is missing (this section is generated when the translation json file exported from visual studio) and the tabular translator tool cannot process the file. 

Thank you

**Comment by otykier** [comment]
Fixed in [2.8.4](https://github.com/otykier/TabularEditor/releases/tag/2.8.4). Thanks for reporting!
