### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by DaniilMaslyuk** [otykier/TabularEditor#298]
The latest release has version number 1.3.16 somewhere in it. I found out because the organisation I work at currently has to on-board new applications, and they got this version number from somewhere, so the organisational app store shows "Tabular Editor 1.3.16". In case you recognize this version number, could you please align it with the actual version (2.8.3)? If not, feel free to close this issue.

**Comment by otykier** [comment]
Yes, this is the version number of the installer application.

I've changed it to 2.8.3001 for the June 13th update available here: https://github.com/otykier/TabularEditor/releases/tag/2.8.3

This is the best I can do, as I have to increment the installer version to allow in-place upgrades to work. Sometimes, I find minor issues after releasing a version, so I want to provide an updated build without incrementing Tabular Editors version number. So going forward, I will use A.B.C for the application, and A.B.Cxxx for the installer.
