### ISSUE TITLE
Running script from command line cannot replace existing database.json

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#299]
When running a csharp script from the command line to modify an existing model serialized to a folder, Tabular Editor crashes with a System.IO error.

I want to run the following command to edit an existing model based on a script file.

```bash
$ "/c/Program Files (x86)/Tabular Editor/TabularEditor.exe" \
    database.json \
    -S MasterModel/UAT_phase.cs \
    -F ./database.json

Tabular Editor 2.8.7075.20683
--------------------------------
Dependency tree built in 85 ms

Unhandled Exception: System.IO.IOException: Cannot create "C:\Users\username\Source\path\to\model\dir\database.json" because a file or directory with the same name already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TabularEditor.Program.HandleCommandLine(String[] args)
   at TabularEditor.Program.Main()
```

If I output to a bim with `-B`, I can overwrite an existing file, so this seems specific to the folder output. I have also tested running with a single bim as both input and output (analogous to what I'm trying above).

**Comment by otykier** [comment]
The -F switch expects a folder path - not a file path. Please modify your command as follows:

```bash
$ "/c/Program Files (x86)/Tabular Editor/TabularEditor.exe" \
    database.json \
    -S MasterModel/UAT_phase.cs \
    -F .
```

You could also change the first argument ("database.json") to a dot for brevity :-)

**Comment by greggyb** [comment]
Thanks much. I've updated the wiki page on CLI to indicate this. It previously said that -F could take a database.json file as its argument.

Change appears to be live: https://github.com/otykier/TabularEditor/wiki/Command-line-Options

**Comment by otykier** [comment]
Thank you!
