### ISSUE TITLE
ModelRoleMember Exception Error

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#300]
When clicking the 'X' to close the ModelRoleMember Collection Editor, an unhandled exception error comes up.
![image](https://user-images.githubusercontent.com/29556918/59885921-d4a9dc00-9371-11e9-960e-5b87eb6c0c83.png)

**Comment by kalmenk** [comment]
Interestingly, this only happens the first time you close out this window for each role. Second time for each role and on there is no error.

**Comment by otykier** [comment]
Fixed in [2.8.4](https://github.com/otykier/TabularEditor/releases/tag/2.8.4). Thanks for reporting!
