### ISSUE TITLE
Exporting Best Practice Analyzer Result into a file ( Csv or Txt )

### ISSUE THREAD

**Issue by ehab23** [otykier/TabularEditor#302]
it would be great if the user can exports the Result of the BPA into a file  .

**Comment by otykier** [comment]
Great suggestion - it would certainly make sense to have an "Export results" buttons within the UI. For now, you can use the CLI to run the BPA against a model, and pipe the console output into a file:

```bash
TabularEditor.exe "c:\Projects\AdventureWorks\Model.bim" -A > BPAResults.txt
```

**Comment by ehab23** [comment]
Thank you for your reply ,
I'm using the Azure SSAS instance   , what i did is i saved the The project as "BIM" file , then  i ran the CLI Command and i Got "No objects in violation of Best Practices."  message in the output File .
But there is some findings  in the Tabular Editor as below :
![image](https://user-images.githubusercontent.com/18497746/60434493-ed3ab180-9c0f-11e9-98ab-1f328d28b5e4.png)

**Comment by ehab23** [comment]
It worked after i moved the "BPA Rule" File to the "%ProgramData%\TabularEditor" Folder  , it seems that the Tabular Editor can't recognize the BBA Rules File if it was imported externally for specific bim file .

Thank you

**Comment by bobduffyie** [comment]
Hi,

Anyone actually using Tabular Editor to say add calculated measures to a PBIX ?

I see the warning on corruption, but not sure if that’s more if you try and add tables, etc

Bets Regards,
Bob
