### ISSUE TITLE
Deployment elements

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#305]
Just as when you deploy a model for the second time to the same server (in a session) TE remembers which database you are deploying to, it should also remember the settings you used in the Deployment elements window. Just so one doesn't have to keep clicking all the checkmarks every time a deployment is made. Not a bug, just a request :) Thanks!

![image](https://user-images.githubusercontent.com/29556918/62149991-c70d3d80-b2b1-11e9-87db-1aff533554a6.png)

**Comment by otykier** [comment]
Fixed in [2.9.4](https://github.com/otykier/TabularEditor/releases/tag/2.9.4)
