### ISSUE TITLE
Show what visuals measures/columns are used in a pbix/pbit file

### ISSUE THREAD

**Issue by Tanner-Pettit** [otykier/TabularEditor#306]
Is it possible to add a feature that will allow a user to see where measures/columns are being used in a pbix or pbit file?(like what visuals they are being used in)

Often times when creating a metrics there is trial and error as well as progression of the file and some metrics become obsolete and clutter the file.

If there is a way to see which metrics are being used and where they are being used it would definitely help in cleaning up the file.

Sometimes there are metrics that are not directly used in a visual but act as a middle man, would it be possible to show those as well? "has dependencies that are used in a visual"

I know this would be super helpful but not sure if it is possible!

**Comment by otykier** [comment]
I think [Power BI Helper](https://radacad.com/power-bi-helper) can do this, but to my knowledge, there’s no officially supported way to do this, and for that reason I’m hesitant to build this kind of functionality into Tabular Editor.

**Comment by marcosqlbi** [comment]
There is also another issue in this feature: you are not able to inspect other reports that are connected to the same dataset in Power BI.
