### ISSUE TITLE
Could you add a method to export the results of the ExportProperties method to an Excel file

### ISSUE THREAD

**Issue by minren118** [otykier/TabularEditor#307]
At present, if you want to export the original data, there are many tabs and Carriage returns in the measure  expression. When exporting the data, the current TSV file will have the problem of line breaking dislocation. 

If it is an export of Excel file, An expression can only be in one cell.there will be no such problem.The same  needs to support the Excel file format for the import Process to be perfect.

`var tsv = ExportProperties(list,"Name,Description,SourceColumn,Expression,FormatString,DataType,DisplayFolder,ObjectType,Parent");
tsv.Output();`
//SaveFile("E:\\test.tsv", tsv); 

![image](https://user-images.githubusercontent.com/28550438/62408604-ec75b080-b5fd-11e9-9859-841e246fbbda.png)

**Comment by minren118** [comment]
Another solution Clear the soft carriage return symbol,I used notepad++ to clear it manually, paste it into an Excel file and it will work fine.It's a small pity that \n appears in Excel instead of the actual newline character

![image](https://user-images.githubusercontent.com/28550438/62408769-6313ad80-b600-11e9-876e-919d3505d7ee.png)

![image](https://user-images.githubusercontent.com/28550438/62408903-1f21a800-b602-11e9-8b47-b5185b88ae17.png)

**Comment by otykier** [comment]
This functionality will not make it into Tabular Editor, as it seems very specific to a certain use case. You can of course create a script that exports the metadata in whatever format you want, even including external .dll's for saving the metadata in Excel format.

Closing the issue.

**Comment by minren118** [comment]
thanks，i use tom dll and make a powerbi external tool ，it contains output data to Excel fuction.Unfortunately, it is only available in Chinese at present. Thank you for your contribution.
link here https://www.yuque.com/excelcuihuajihome/helpdocument/cmqa50
