### ISSUE TITLE
Certificate missing

### ISSUE THREAD

**Issue by haakonlangballe** [otykier/TabularEditor#313]
I can't install the binaries or build the resources without the files being signed.
Any chance of adding a certificate to the files?

**Comment by otykier** [comment]
I don’t have any funding for certificates, so at the time being I’m afraid this is not possible.

**Comment by dmarkle** [comment]
What's the cost?  Chances are when this terrible meltdown of society is over my company may be able to help.

**Comment by otykier** [comment]
**Update:** I convinced my company to sponsor a certificate for Tabular Editor. It should arrive within a few days, at which point I will provide a new build of Tabular Editor with the certificate installed. Big thanks to Kapacity for this. If your company is benefitting from Tabular Editor getting a certificate, please send a happy thought to Kapacity and consider paying our website a visit: www.kapacity.com

**Comment by otykier** [comment]
Finally! As of [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8) Tabular Editor is now digitally signed. Please let me know if you have any issues!
