### ISSUE TITLE
Full Process Post Deploy

### ISSUE THREAD

**Issue by adamrobinson361** [otykier/TabularEditor#314]
Hi there,

Thanks again for your work on this - looks really great and i'm just getting round to _attempting_ to set up a deployment pipeline for one of our models.

One thing I am not clear on is if a deploy achieved by something like follows:

```
start /wait TabularEditor.exe "C:\Projects\MyModel\Model.bim" -D ssasserver databasename -O -C -P -V -W
```

Will actually do a process on the deployed model? 

With the scale of my model meaning it isn't too much resource I would like to deploy and then ensure a full process is done each time the database is deployed.

Is this possible in current command line functionality? 

Regards,

Adam

**Comment by otykier** [comment]
Currently, Tabular Editor will not do any kind of processing, but the functionality is in the works for version 3.0.

You'd have to add a subsequent step to your pipeline to perform the processing, for example using PowerShell and the [Invoke-AsCmd cmdlet](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-ascmd?view=sqlserver-ps).
