### ISSUE TITLE
Missing the Refresh Table Metadata function

### ISSUE THREAD

**Issue by JakeGH** [otykier/TabularEditor#315]
Hi all, 
I just can't find the "Refresh Table Metadata" function. I had installed the latest Version (2.8.5) but have downgraded to the Version 2.8.2. But in both, I can't refresh the metadata. When I rightclick the Tables I have only the two options: "Import tables" and "Create new…" What's the matter? A colleague has installed the 2.8.2 and all works fine.
Thank You.

**Comment by otykier** [comment]
Sorry for the late response. Are you using PowerQuery data sources in your model, or only Legacy (Provider) data sources?

**Comment by JakeGH** [comment]
Now I have to apologize for my late reply. That was the point, I added a PowerQuery Data Source. Its working fine now with the Legacy Data Source.
