### ISSUE TITLE
Support for large datasets

### ISSUE THREAD

**Issue by thracian2015** [otykier/TabularEditor#317]
Microsoft is currently working on supporting large datasets in Power BI Premium. Do you plan to extend Tabular Editor to support developing semantic models that target Power BI Premium and take advantage of Premium features, such as composite models? I'd prefer to use Tabular Editor than Power BI Desktop.

**Comment by otykier** [comment]
Once Microsoft opens up the ability to write model metadata to the XMLA endpoints of Power BI Premium, then everything you request will work - no changes needed in Tabular Editor.
