### ISSUE TITLE
When duplicating measures or undoing some batch operation the list of measures does not update

### ISSUE THREAD

**Issue by leniel** [otykier/TabularEditor#320]
The workaround is clicking the Show/hide metadata information icon or even trying Toggle alphabetical order. This refreshes the measure list.

**Comment by otykier** [comment]
Unable to reproduce as of 2.8.5. Please provide more information.

**Comment by otykier** [comment]
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).
