### ISSUE TITLE
"You're deploying it wrong!" with  Multi-Factor Authentication at Azure Tenant

### ISSUE THREAD

**Issue by Vinhaman** [otykier/TabularEditor#325]
First of all thank you for the tool it's been awesome and I was following up the "You're deploying it wrong!" blog post but I'm hitting a bit of death end because of our security policies enforces the multi factor authentication that is the security best practices at the moment..

When using the Tabular Editor during the deployment F6 (when it connects to the Azure Analysis Services server) I just click my Windows User that is recognized and it's all done.

Since only use the integrated security so the -Login with user pass don't work either.

I've tried a lot of combinations of the given examples and I get either one of the errors below:

"Error loading model: Authentication failed: User ID and Password are required when user interface is not available."

"Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials."

I'm not sure if running some kind of command line with the application open if it would open the prompt to select the user details for the integrated security.

Thank you for the attention before hand.

**Comment by otykier** [comment]
The whole point of deploying through the command line, is that you don't need any user interaction - meaning the process can be completely automated and run in a scheduled manner, for example as part of an Azure DevOps pipeline. Thus, two-factor authentication is out of the question for this type of deployment. For this reason AAS (and other Azure services) allow us to set up Service Principals, which can be used by other applications and services - including Tabular Editor.

First, create the Service Principal and assign it as an admin in AAS: https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-addservprinc-admins

Then, use the following connection string when running Tabular Editor from the command line, to impersonate the service principal:

```
Provider=MSOLAP;Data Source=asazure://<REGION>.asazure.windows.net/<INSTANCE>;User ID=app:<APPLICATION ID>@<TENANT ID>;Password=<APPLICATION KEY>;Persist Security Info=True;Impersonation Level=Impersonate
```

where

- <REGION> and <INSTANCE> are specific to your instance of Azure Analysis Services
- <APPLICATION ID> is the Application ID of your Service Principal
- <TENANT ID> is your Azure Active Directory ID
- <APPLICATION KEY> is the secret key of your Service Principal

If using Azure DevOps, you can store the entire connection string as a secure variable, so that you don't expose the secret key anywhere.

I was planning to provide these details in a follow-up blog post, but I just didn't have the time to finish it yet.

Let me know if you need any additional information to move forward.

**Comment by Vinhaman** [comment]
Thank you that did the trick.

Since we have the processing automated for the databases on a schedule the application and service principles were already created.

Currently I'm trying to get it to work on my machine before setting up the DevOps.

We're using the Folder structure as source (the source control seems cleared for the changes) and during the artifacts build I'll override the entire data source json to accommodate the correct environment (We have the same models across multiple Azure Analysis Services that have their own database).

The final command was the following:

**start /wait TabularEditor.exe "<FOLDER>" -D "Provider=MSOLAP;Data Source=asazure://<REGION>.asazure.windows.net/<INSTANCE>;User ID=app:<APPLICATION ID>@<TENANT ID>;Password=<APPLICATION KEY>;Persist Security Info=True;Impersonation Level=Impersonate" "<DB NAME>" -O -C -P -V -W**

Again thank you for the help ;) !

**Comment by otykier** [comment]
Glad to be of help, and thanks for posting the full command, so that others can see how it's done :-)

**Comment by Ashish-Jovial** [comment]
> The whole point of deploying through the command line, is that you don't need any user interaction - meaning the process can be completely automated and run in a scheduled manner, for example as part of an Azure DevOps pipeline. Thus, two-factor authentication is out of the question for this type of deployment. For this reason AAS (and other Azure services) allow us to set up Service Principals, which can be used by other applications and services - including Tabular Editor.
> 
> First, create the Service Principal and assign it as an admin in AAS: https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-addservprinc-admins
> 
> Then, use the following connection string when running Tabular Editor from the command line, to impersonate the service principal:
> 
> ```
> Provider=MSOLAP;Data Source=asazure://<REGION>.asazure.windows.net/<INSTANCE>;User ID=app:<APPLICATION ID>@<TENANT ID>;Password=<APPLICATION KEY>;Persist Security Info=True;Impersonation Level=Impersonate
> ```
> 
> where
> 
> * and  are specific to your instance of Azure Analysis Services
> * is the Application ID of your Service Principal
> * is your Azure Active Directory ID
> * is the secret key of your Service Principal
> 
> If using Azure DevOps, you can store the entire connection string as a secure variable, so that you don't expose the secret key anywhere.
> 
> I was planning to provide these details in a follow-up blog post, but I just didn't have the time to finish it yet.
> 
> Let me know if you need any additional information to move forward.

Hi @otykier, How can I execute the following command using PowerShell?
Provider=MSOLAP;Data Source=asazure://<REGION>.asazure.windows.net/<INSTANCE>;User ID=app:<APPLICATION ID>@<TENANT ID>;Password=<APPLICATION KEY>;Persist Security Info=True;Impersonation Level=Impersonate

**Comment by otykier** [comment]
Hi @Ashish-Jovial 
What is the command you wish to execute? Is this question related to Tabular Editor?

**Comment by abdelrahmanseleem** [comment]
Is there any other way for authenticating the Service Principal other than the secret key?

**Comment by otykier** [comment]
To my knowledge no. The AMO/TOM lib requires the SP secret to be specified as the password part of the connection string, but the article illustrates that you can pass the secret to Tabular Editor as an environment variable from a pipeline variable. The pipeline variable could be populated from a Key Vault through a Service Connection in DevOps. This way, the secret is not disclosed or logged anywhere.

**Comment by chrisweis** [comment]
@otykier Thanks so much for everything you do, love Tabular Editor!  Curious, does the thread above also apply to Power BI via XMLA?  Will it also work?  And do you already have documentation on that (using TabularEditor.exe with MFA or service principal)?

**Comment by otykier** [comment]
Hi @chrisweis - yes, you can use service principals to connect to Power BI through the XMLA endpoint as well: https://powerbi.microsoft.com/en-us/blog/announcing-support-for-service-principals-using-the-xmla-endpoint-in-power-bi-premium/

**Comment by Kazanskyi** [comment]
@otykier, 
I have weird behaviour with the connection.
I am iterating through workspaces and datasets and after about 20 times opening and closing the connection I start getting the error:
`Microsoft OLE DB Provider for Analysis Services.', "Errors in the OLE DB provider. Unable to obtain authentication token using the credentials provided`

The connection string is okay as it works after I try to connect manually.
