### ISSUE TITLE
Please fix CustomActionsError.log so it really exists!

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#326]
If I have a bad script I get the message See CustomActionsError.log in the status bar but I can't find it anywhere. 

I can use the command line trick as mentioned below but it would be good to clean this up?

_Originally posted by @otykier in https://github.com/otykier/TabularEditor/issues/186#issuecomment-419354392_

**Comment by otykier** [comment]
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).
