### ISSUE TITLE
Dependency view not updated when saving (needs to reopen model) on calculated tables

### ISSUE THREAD

**Issue by zenzeinet** [otykier/TabularEditor#328]
Hi, 

First of all, I love TE. Thank you so much!

When creating new measures and saving the model, I'm finding that the dependency tree does not update completely unless I re-open the connection to the Tabular Server when the table/column is a calculated one:

For example, if I create a new 
MyMeasure = Sum(CalculatedTable[CalculatedColumn]) , 

then when I look at the dependency tree of CalculatedTable[CalculatedColumn] , I do not see MyMeasure as depending on it. I need to re-open the connection to the model for it to successfully appear.

Best regards and thanks again

**Comment by otykier** [comment]
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).
