### ISSUE TITLE
Tabular Editor Function guide

### ISSUE THREAD

**Issue by tschwenger** [otykier/TabularEditor#335]
Is it possible to add something to the Wiki that contains all the functions that can be used in tabular editor for adding, formatting, and updating measures/columns/tables?

**Comment by tschwenger** [comment]
it's in the TOM

**Comment by otykier** [comment]
While many of the [TOM functions and properties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular?view=analysisservices-dotnet) are available in Tabular Editor through the TOMWrapper API, but please note that creating/deleting objects is done a little differently. For example, to add a new measure to a table 'Reseller Sales', use:

```csharp
var newMeasure = Model.Tables["Reseller Sales"].AddMeasure("My New Measure", "1+2");
newMeasure.FormatString = "0.0";
```

To delete an object, simply use:

```csharp
Model.Tables["Reseller Sales"].Measures["My New Measure"].Delete();
```

I was planning to provide a comprehensive document on the methods available, but since the TOMWrapper is not finalised, things are subject to change. In the mean time, you can also take a look here: https://github.com/otykier/TabularEditor/wiki/TabularEditor.TOMWrapper (all though keep in mind this document is a little old and does not include the newest additions)

**Comment by sherlockspreadsheets** [comment]
@otykier -- How can we View/Restore all Table Fields that have been deleted with Tabular Editor (TE)? 

For example, when I perform delete function, `Model.Tables["PBI Activity"].Columns["OrganizationId"].Delete();` and then "Save changed to connected database", I can see the Table Field is gone. But how to restore the deletion? 

If the Table Field is deleted within PBI Desktop, it looks like the query editor script is updated with a final step using the `Table.RemoveColumns()` function. 

But when deleted using TE, I do not see the deleted fields being added to the query editor script. I looked in the PowerQuery editor for the table. There are many removed columns but not the ones I did with TE. 

* PBI Manual deletes = [IsSuccess], [Workload]
* TE Script deletes = ["Id"].Delete(), ["OrganizationId"].Delete()
* TE Manual delets = [CapacityId]

```
RemovedCols = Table.RemoveColumns(#"replace_PK_(Null)(-1)",{"Activity", "AggregatedWorkspaceInformation", "AuditedArtifactInformation", "CapacityName", "CreationTime", "CustomVisualAccessTokenResourceId", "CustomVisualAccessTokenSiteUri", "DataConnectivityMode", "DataflowAccessTokenRequestParameters", "DistributionMethod", "Engagement", "ExportEventEndDateTimeParameter", "ExportEventStartDateTimeParameter", "GatewayId", "GenerateScreenshotInformation", "ImportDisplayName", "ImportId", "ImportSource", "ImportType", "LastRefreshTime", "MentionedUsersInformation", "ModelsSnapshots", "Modifications", "RefreshType", "RequestId", "TileText", "UserAgent", "UserType", "IsSuccess", "Workload"})
```

**Comment by otykier** [comment]
@sherlockspreadsheets 
It’s not clear what you’re asking. Are you connecting Tabular Editor to a model in PBI Desktop and then deleting tables through TE? That is [not supported by Microsoft](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations) and will only cause you trouble. Delete the tables through Power BI Desktop instead.

**Comment by sherlockspreadsheets** [comment]
Phooey. Not the answer I was hoping for. Well this tool created by 'TheBIAccountant' finds unused columns and includes scripts to delete the columns using Tabular Editor. 

Power BI Cleaner Gen2 now covers Analysis Services Models as well
https://www.thebiccountant.com/2021/08/23/power-bi-cleaner-gen2-now-covers-analysis-services-models-as-well/

**Comment by otykier** [comment]
Deleting columns through 3rd party tools is also not supported by Power BI Desktop.

If you’re using a c# script to delete the columns, consider storing the names of the deleted columns in a string which is then outputted at the end of the script. That way, you can get a list of deleted columns which you can then use to update the Power Query/M expression for the table.

**Comment by didierterrien** [comment]
The best way being able to undo model modification is to backup the report before.
Even though Power BI cleaner is an excellent tool, it cannot be totally perfect. Some columns marked as 'delete' can be deleted by the script but will reappear after a refresh. So it's necessary to modify manually M queries and/or DAX calculated tables.
