### ISSUE TITLE
How to access ExtendedProperty in Advanced Scripting

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#336]
Hi,

I want to access a specific ExtendedProperty, how can i get access to this in an extended script?

Idea
```
Selected.Measures.Where(m => m.ExtendedProperties.GetExtendedProperty("ExcelGenerator") = "yes").Delete();
```

regards

**Comment by otykier** [comment]
Hi Felix,

[Here are the methods supported](https://github.com/otykier/TabularEditor/blob/26d1230e6c145e0cbfbdcfe99ae9cce14d07608d/TOMWrapper/TOMWrapper/Interfaces.cs#L125-L139) by the `IExtendedPropertyObject` interface.

So simply rewrite your code as follows (note the double equal sign which is always needed in C# when comparing two values):
```csharp
Selected.Measures.Where(m => m.GetExtendedProperty("ExcelGenerator") == "yes").Delete();
```

**Comment by fmms** [comment]
Thanks alot. That works for me.
