### ISSUE TITLE
How to add references to assemblies like System.Text.RegularExpressions?

### ISSUE THREAD

**Issue by darlove** [otykier/TabularEditor#338]
Hi there. I'd like to do some processing on measures... but I need regexes for this. How can I add a reference to the assembly in the script? Thanks.

**Comment by otykier** [comment]
The assembly is already included, but you need to fully qualify all calls to the Regex class, like so:

```csharp
if(System.Text.RegularExpressions.Regex.IsMatch(Selected.Measure.Name, "hello"))
{
    ...
}
```

**Comment by otykier** [comment]
`using` keyword now supported in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).
