### ISSUE TITLE
DaxFormatter removes comments

### ISSUE THREAD

**Issue by TonyGaul** [otykier/TabularEditor#34]
When using the DaxFormatter functionality, it removes any comments in the DA code.  For example comments in this format:
/* blah blah */

However using DaxFormatter.com doesn't remove comments.

**Comment by marcosqlbi** [comment]
This is an issue in DAX Formatter. The problem is not the format of the comment, but its position. Comments after the expressions are always removed. Please, post any bug of DAX Formatter on www.daxformatter.com, thanks!

**Comment by TonyGaul** [comment]
OK, my mistake.  I tested www.daxformatter.com with already formatted code containing comments, and the comments didn't get removed so I assumed an issue with the TabularEditor.  Just tested unformatted code with comments, and www.daxformatter.com does not format the code.
