### ISSUE TITLE
Doco enhancement

### ISSUE THREAD

**Issue by ElectricLlama** [otykier/TabularEditor#340]
With regards to the doco around DevOps depoyment scripts;

https://github.com/otykier/TabularEditor/wiki/Command-line-Options#integration-with-azure-devops

I used the V2 command line task in DevOps. In order to see any console output, I had to use ECHO ON and the /B switch:

    echo on
    start /B /wait TabularEditor.exe .....

WIthout this, no console output is shown and you can't see error messages of special VSTS log lines

Can you update the doco for everyones benefit?

**Comment by ElectricLlama** [comment]
OK I note deep down in the comments that removing Start /wait altogether fixes this, but don't you need this to allow for the fact that it's a windowed app?

**Comment by otykier** [comment]
Thanks for reporting this. I've updated the docs accordingly: https://github.com/otykier/TabularEditor/wiki/Command-line-Options#integration-with-azure-devops
