### ISSUE TITLE
2.8.6 deploying new model

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#341]
when deploying a new database to a server, it gives the following error. An error should not show as the person deploying knows they're creating a new database since they entered in a database name that had not existed on the server before. The deployment does work so even though an error shows it still works. This issue doesn't happen with deploying to existing databases.

Happens in 2.8.6

![image](https://user-images.githubusercontent.com/29556918/67016079-461b5080-f100-11e9-9fdb-0071ae9ff96b.png)

**Comment by otykier** [comment]
I made an update to [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6) where this issue was fixed. Thanks for reporting.
