### ISSUE TITLE
Table editor of (column) properties

### ISSUE THREAD

**Issue by MarkGStacey** [otykier/TabularEditor#343]
What would be fantastic would be a table view of all the columns (and in a later greater version, a picker for an object type), where properties can be edited en masse.

For instance, I may want to hide many columns, or set the format of a whole ton of columns, etc etc. and this would be much faster than the current way of clicking through

A table to do one property after the next would be a good start - but then a ctrl-click / checkbox to select multiple rows in the table and set the same property to many columns at once would be ideal

**Comment by otykier** [comment]
I’m not sure what you would gain from this, that you can’t already do today, by multi-selecting (hold down SHIFT or CTRL while clicking objects in the tree), and then setting the properties.

You can even multi select columns across tables by applying a filter such as `:ObjectType="Column"` and then displaying the results as a list.

Maybe I’m missing something?

**Comment by otykier** [comment]
This functionality will not make it into Tabular Editor. However, you may use the `ExportProperties` and `ImportProperties` script methods to export object properties to a file that you can then edit in Excel. See [here](https://docs.tabulareditor.com/Useful-script-snippets.html#export-object-properties-to-a-file).
