### ISSUE TITLE
TO end cardinatlity must always be set to One

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#345]
Tabular editor allows me the freedom to create a model that does not open in VS:

![image](https://user-images.githubusercontent.com/908734/67703793-4fd06e00-f9b4-11e9-8985-d3b37d3eb6d7.png)

**Comment by otykier** [comment]
This is just one of many things that are allowed in Tabular Editor (or rather, it's allowed in the TOM), even though Analysis Services won't have it. It would be a lot of work to build in validation for everything. Instead, I'm relying on Tabular developers to know what they're doing :-)

Of course, it would be a minor thing to add validation that the TO-end cardinality should always be "One", but then [in Compatibility Level 1500, you can actually have relationships where both ends have a cardinality of Many](https://docs.microsoft.com/en-us/analysis-services/what-s-new-in-sql-server-analysis-services#many-to-many-relationships-in-tabular-models).

My design philosophy, at least for now, is to keep Tabular Editor as lightweight as possible in terms of what it lets you do to the TOM, and then rely on Analysis Services to validate the model.

**Comment by fmms** [comment]
Hi @otykier ok, I see your point. I am just trying to totally migrate away from Visual Studio as it is pretty much unusable on very large models. 
Might be a good idea to have this as a rule in the Best Practice Analyzer so people catch it before actually deploying or opening in VS...
