### ISSUE TITLE
TabularEditor Versions changing over time

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#349]
In my experience a version should never change over time. v1.1.1 would be the same no matter when you downloaded and installed it. 

However [v2.8.6](https://github.com/otykier/TabularEditor/releases) has already had 3 changes to it. Following [Semver rules](https://semver.org/), really have been 2.9, then 2.9.1 and 2.9.2 for the hotfixes? Why are we reusing the same version numbers like we will run out of them? :) 

Our CICD process gets the most recent version of tabular editor based on the version number. If it already has the folder then it won't get it again, so we are stuck with the old version on some developers machines but others who come along later will have the later code even though they all say they are the same version. It means it isn't easy for us to ensure that everyone is on the same version apart from hammering the download servers and downloading it each time (costing an extra minute every build) and doing a binary compare on the files and that is one of a version numbers jobs to save that heavy lifting.

This practice of reusing version numbers over time does seem to be a pattern with TabularEditor. Any chance this practice could be changed and start to treat the code in a version as immutable and using minor and patch according to semver standard?

**Comment by dmarkle** [comment]
Can't agree more on this one.  Correct use of SemVer is what allows CI to even work.  Some artifact repositories don't even *allow* multiple copies of software with the same version number to be uploaded in any case.  Everyone loves TE, nobody's going to look askance at anyone for posting a new point-release to fix issues.

**Comment by otykier** [comment]
Thanks for the feedback. I'm sorry if incremental updates have caused any issues on your side - I simply didn't consider the impact on CI/CD processes, etc. I wasn't familiar with the SemVer rules, but will change my practice going forward, to adhere to them.
