### ISSUE TITLE
Error: CLR20r3.

### ISSUE THREAD

**Issue by maikonabati** [otykier/TabularEditor#35]
**How to fix this problem?**

Assinatura do problema:
  Nome do Evento de Problema:	CLR20r3
  Assinatura do Problema 01:	TabularEditor.exe
  Assinatura do Problema 02:	2.2.6240.39196
  Assinatura do Problema 03:	5890f7a9
  Assinatura do Problema 04:	TabularEditor
  Assinatura do Problema 05:	2.2.6240.39196
  Assinatura do Problema 06:	5890f7a9
  Assinatura do Problema 07:	511
  Assinatura do Problema 08:	56
  Assinatura do Problema 09:	System.IO.FileNotFoundException
  Versão do sistema operacional:	6.1.7601.2.1.0.256.4
  Identificação da Localidade:	1046
  Informações Adicionais 1:	0a9e
  Informações Adicionais 2:	0a9e372d3b4ad19135b953a78882e789
  Informações Adicionais 3:	0a9e
  Informações Adicionais 4:	0a9e372d3b4ad19135b953a78882e789

Leia nossa declaração de privacidade online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0416

Se a declaração de privacidade online não estiver disponível, leia nossa declaração de privacidade offline:
  C:\Windows\system32\pt-BR\erofflps.txt

**Comment by otykier** [comment]
Hi Maikon,
When did the error occur? Did it happen immediately when running TabularEditor.exe? In that case, it could be that you are missing the [prerequisites](https://github.com/otykier/TabularEditor/wiki#prerequisites). Could you please check?

**Comment by maikonabati** [comment]
Yes, immediately when running TabularEditor.exe.

I reinstall "\X64\SQL_AS_AMO.msi" and is working now.

Tks!
