### ISSUE TITLE
Why not import table When I Create Power Query Datasource

### ISSUE THREAD

**Issue by chenzhanglin** [otykier/TabularEditor#352]
I  create a 1400(SQL Server 2017+) model，There is a DataSource named Power Query，so i create a Power Query datasource ,but when i import table ,i can't import any table. 
I try it in SSDT，there have no problem,but I open BIM file in TabluarEditor，i still does't work .

**Comment by otykier** [comment]
Tabular Editor can’t automatically obtain metadata from Power Query data sources, as there is no supported way for it to parse or execute the M query. You’d have to map the columns manually, or switch to a Provider (Legacy) Data Source.
