### ISSUE TITLE
ReferencedBy Calculations Groups

### ISSUE THREAD

**Issue by TheDataViking** [otykier/TabularEditor#354]
Working with referenced by on a given object does not output details related to calculation groups & items. This would be great to have an understanding of the complete dependency tree.

**Comment by otykier** [comment]
This works in [2.9.0](https://github.com/otykier/TabularEditor/releases/tag/2.9.0). However, note that the dependencies only work in one direction: You can see which objects a calculation item depends on, but not the other way around. I.e., if you refer to a calculation item somewhere in your DAX with something like:

```
[My Measure 1] :=
CALCULATE( [Something] , 'My Calc Group'[Calculations] = "MTD" )
```

then Tabular Editor will not show that [My Measure 1] depends on this specific calculation item ("MTD"). However, it will show a dependency on the `[Calculations]` column on the `'My Calc Group'` Calculation Group table.
