### ISSUE TITLE
Calculation Groups for Power BI

### ISSUE THREAD

**Issue by nishantjainuk** [otykier/TabularEditor#358]
Hi, 

Today in the "_Triple A Community Event with Amir Netz_", Amir mentioned that it is possible to create  calculation groups for Power BI Desktop using Tabular Editor. Is that right? I couldn't find any documentation for it anywhere.

**Comment by marcosqlbi** [comment]
It *will* be possible :) There is no such a guy as Amir providing the time machine.

**Comment by nishantjainuk** [comment]
Thanks Marco. Thought so. Can't wait for this feature though.
