### ISSUE TITLE
Format String for Text measures

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#359]
Hi,

the best practice Analyzer is complaining a lot about my model because I have 270 measures that are and should be of the type text. However, I was not able to find out, how to set a measure to type Text.

warnings:
![image](https://user-images.githubusercontent.com/908734/69339025-bf104980-0c64-11ea-84db-5f48d57ea170.png)

Format Drop Down:
![image](https://user-images.githubusercontent.com/908734/69339040-c9cade80-0c64-11ea-9374-d8a135d39e08.png)

regards

**Comment by otykier** [comment]
This is a bug in the Best Practice Rule. By adding `and DataType <> "String"` to the rule expression, you can ensure that the rule only considers measures that return a numeric result.

**Comment by fmms** [comment]
Hi @otykier . When opening my Model.bim all DataTypes are "Unknown"
![image](https://user-images.githubusercontent.com/908734/69351630-ef171700-0c7b-11ea-9083-ade429472932.png)

It works when connected to the Cube. Is there any chance to make this work offline?

**Comment by otykier** [comment]
Oh right. Unfortunately, that’s not currently possible as it requires offline parsing/static type analysis of the DAX code within the measures.

I guess for now, you would have to resort to “ignoring” these measures in the BPA, which puts an annotation on each measure, instructing the BPA to ignore the measure for this particular rule.
