### ISSUE TITLE
Allow filtering based on property values and translations

### ISSUE THREAD

**Issue by J0den** [otykier/TabularEditor#360]
Example:
I'd like to find all columns that have had their name translated to a specific string in a certain language.

**Comment by otykier** [comment]
This can actually be done today, with the proper syntax in the Filter box.

To perform an exact, case-sensitive match within all Danish translations:
```
:TranslatedNames["da-DK"] = "Beløb"
```
To perform an exact, case-insensitive match within all Danish translations:
```
:TranslatedNames["da-DK"].ToLower() = "beløb"
```
To perform case-insensitive search within all Danish translations:
```
:TranslatedNames["da-DK"].ToLower().Contains("beløb")
```
To perform case-insensitive search across all translations in the model:
```
:TranslatedNames.Any(ToLower().Contains("land"))
```
