### ISSUE TITLE
Script for disabling property Available in MDX

### ISSUE THREAD

**Issue by Rasenkantenstein** [otykier/TabularEditor#362]
Hi All
I wanted to ask for help redgarding a little script that does the following:

* Scan all hidden columns
* set "Available in MDX" to false

Thank you guys. Best regards,
Konstantin

**Comment by otykier** [comment]
Certainly!

Here you go:

```csharp
foreach(var column in Model.AllColumns.Where(c => c.IsHidden))
    column.IsAvailableInMDX = false;
```

Let me know if there's anything else you need!
