### ISSUE TITLE
No warning for dots and quotes in table names (Power BI dataset)

### ISSUE THREAD

**Issue by nolockcz** [otykier/TabularEditor#365]
Hi,
I'd like to ask you to display at least a warning if a user tries to change a name of a table and the new table name contains either a dot or a quote. It can happen that the modified pbit file won't be loaded in Power BI Desktop any more.
Power BI Desktop and Power Query Editor contains a check for long time, however the check was in the UI only. I think that something has changed in the November version of Power BI Desktop because a PBIT file containing a dot in a table name can't be loaded anymore :(

![image](https://user-images.githubusercontent.com/52107554/70029405-5485d480-15a7-11ea-8321-6bc45f243ca2.png)

**Comment by otykier** [comment]
This is not an issue with Analysis Services, which supports periods and quotation marks in table names just fine. I am very hesitant to implement a lot of rules/warnings specifically for Power BI file, as _any_ modification you make to a .pbit file or model loaded into Power BI Desktop is unsupported, and can break/corrupt the model. Also, whenever a new version of Power BI Desktop is released, it is possible that a modification which did work in a previous version, no longer works, or vice versa, so it's a nightmare to maintain.

After all - this is why I display the following warning whenever you do anything to a .pbit file or a model loaded in PBI Desktop:

![image](https://user-images.githubusercontent.com/8976200/70035960-222ea400-15b4-11ea-8f6d-0954c5dc3226.png)
