### ISSUE TITLE
Best Practice Analyser issue counts includes ignored

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#368]
We have a few BP rules that we have to ignore for now but we still get the indicator in the status bar saying we have issues. This removes the benefit of this as unless we track what the number was at the beginning we can't quickly see if we have introduced any new issues that need addressing

![image](https://user-images.githubusercontent.com/13693159/70172030-cd7c4d80-16c7-11ea-99be-0e9380ba557c.png)

Pehaps it would be better to say "X issues and Y ignored" . X Issues could be in Red, Y ignored could be in blue.

Also confusing on the BP Analyser screen as you can see it says 16 objects in violation but can only see 5 of them as the rest are ignored.
![image](https://user-images.githubusercontent.com/13693159/70171971-b2a9d900-16c7-11ea-83d7-71b1b5d42e7a.png)

**Comment by otykier** [comment]
Clearly a bug. Thanks for reporting. Will be fixed shortly.
