### ISSUE TITLE
Calculation Group Attributes and Best Practice Analyser wierdness

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#369]
Hi Daniel, we have some existing BP rules against tables and columns and are now just implementing Calculation Groups and having a couple of unexpected issues

1. BP rules that are indicated for Tables are also picking up Calculation Groups. It doesn't seem that this was your intention as you do have a specific type for Calculation Groups. I have been able to work around this by putting in a specific ObjectType filter in the code, but it might be worth reviewing the design of this

2. A similar problem with the Calculation Group Attribute (column), however I can't seem to screen this one out with logic in the BP rule. The column shows as a CalculationGroupAttribute through the UI properties pane when navigating via the object tree view, but when I interrogate using Advanced Scripting I see it is showing as a normal column?

![image](https://user-images.githubusercontent.com/13693159/70172624-fa7d3000-16c8-11ea-9402-119d368addd7.png)

Really weird. Any ideas how I can screen for these (I guess I will just manually ignore for now)? I guess it would be nice to have a specific type for these in the BP analyser also as the types are pretty distinct

3. We would like to add Annotations to Calculation Items and [this does seem to be supported](https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssas-t/7a16a837-cb88-4cb2-a766-a97c4d0e1f43) but the UI doesn't allow it. Any chance you could support this?

**Comment by otykier** [comment]
Regarding 1 and 2: This is a bug. Rules applied to "Tables" should not consider Calculation Group tables, in the same way that they don't consider Calculated Tables. Similarly for the columns on Calculation Groups (called "Attributes").

Regarding 3: Although it seems supported by XMLA, the [TOM (as of 18.2.3)](https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/) does not support annotations on calculation items:

![image](https://user-images.githubusercontent.com/8976200/70285032-685b5180-17c6-11ea-8fec-e9f6c2a647e9.png)

I will reach out to Microsoft to figure out if this is an oversight in the TOM.

**Comment by otykier** [comment]
@o-o00o-o it turns out that the AS engine does not actually support annotations on calc items. It's an error in the documentation. In my opinion they should be there, but the AS team does not agree. May I ask what you intended to use these annotations for?

**Comment by o-o00o-o** [comment]
Thanks @otykier - One of the main things that we use Annotations for is to record discrete information for our data dictionary that essentially serves as the user manual for the Cube.

We have a different selection of fields for Tables/Columns and Measures and we have Best Practice Rules to ensure that we always have sensible values for each of them

For measures we have the following required Annotation fields

- Simple Description (basic overview information)
- Friendly Formula (pseudo code to help users understand what it does)
- Worked Example (in Gherkin style GIVEN x WHEN y THEN z ) to show how the calculation works with an example for more complex formulas)
- Business Uses (examples of how the business could use this to make better business decisions)
- See Also (helps discovery of other related areas of the cube)
- Owner (who should be consulted if a change to the formula is desired)

We then take some of these and run a Custom Action during build to format these into the standard Description field so they appear in the tooltip in Power BI but also we expose these internals via a separate "Data Dictionary" Power BI report that provides all the details in the discrete fields to allow more detailed searching/understanding of our model for more advance users and architects

As these Calculation Items are essentially Measure modifiers and do provide a calculation, I think most of these fields are still relevant in the same way they are for measures.

Ultimately if the team think a Description field is relevant (which they do as it is there!), then I would argue that the justification for Annotations is there by association?

**Comment by otykier** [comment]
Thanks a lot. I will forward this to the team. Hopefully we can convince them that it is worth having the annotations there, even though they might not be able to backport to SQL Server 2019.

**Comment by otykier** [comment]
The [2.9.0 release](https://github.com/otykier/TabularEditor/releases/tag/2.9.0) fixes the first two issues, regarding the Best Practice Analyzer.

The "Calculation Group Attribute" is no longer a thing in Tabular Editor. Instead, columns on Calculation Group Tables are simply that - columns. If you want to restrict your BPA rule to consider only columns on Calculation Group Tables, add the following to your rule: `Table.ObjectType = "CalculationGroupTable"`.

Regarding annotations, I will let you know once I hear back from the team. If they are added to AS/TOM at a later time, they will automatically be included in a newer version of Tabular Editor, thanks to the way I generate code based on TOM. Closing this issue for now.

**Comment by otykier** [comment]
@o-o00o-o : Response from Akshai Mirchandani, AS engine team, regarding Calc Item annotations:

> I agree that it is useful, and it is something that we should have added. But at this time, it is not possible to add it in the SQL 2019 release. We could potentially add it to a future compat level for AAS, but this is not currently on the roadmap.
>
> There is an easy workaround:
>
> To define annotations based on the name of the calc item in the calc group object
E.g. “YoY Description”, “YoY Friendly Formula”
>
> I agree that it would be much more convenient to do so on the item itself, but its simply not likely to happen anytime soon.
