### ISSUE TITLE
[Question] Create Relationships with Drag&Drop

### ISSUE THREAD

**Issue by Rasenkantenstein** [otykier/TabularEditor#372]
Hi Daniel,
i am still new to the Tabular Editor world. So before discovering #63 I tried to build relationships in the Relationship subfolder. This was troublesome especially for huge models. I thought it would be a cool idea to use drag&drop to place the fields inside the relationship:
![githubdraganddrop](https://user-images.githubusercontent.com/6643712/70529218-4eb46400-1b50-11ea-9024-ee7898b91f38.jpg)

The beautiful red arrow indicates the desired dragging behavior.

Thank you for your beautiful work on TabularEditor!

Best regards,
Konstantin

**Comment by otykier** [comment]
That’s a good idea. Will consider it for a future update. Remember that you can create relationships also by right-clicking on a column and choosing Create New->Relationship To/From->Table->Column.

This is easier than browsing the full list of columns across all tables.

**Comment by Daandamhuis** [comment]
> That’s a good idea. Will consider it for a future update. Remember that you can create relationships also by right-clicking on a column and choosing Create New->Relationship To/From->Table->Column.
> 
> This is easier than browsing the full list of columns across all tables.

I never new this was an option! Thanks for the tip.

**Comment by IgnatiusJ** [comment]
Great tip Daniel. Would also be cool to be able to ctrl-select two columns in different tables and then right-click on one of them and be able to directly select a "Create relationship"-option from there. Minimal work! Or perhaps if you would drag one column from table A and release over another column in table B, same thing.

Daniel keep up the good work, Tabular Editor is amazing!

**Comment by otykier** [comment]
Cleaning up old issues / things that are planned for Tabular Editor V3.
