### ISSUE TITLE
Best Practice Rule for IsAvailableInMDX

### ISSUE THREAD

**Issue by caiolm** [otykier/TabularEditor#374]
Hi Daniel,
In order to reduce the size of our cube, I am setting “IsAvailableInMDX” to false for most of the columns in the cube with some exceptions. One of them is when the column is used to sort another one, but I am having some trouble to setup a best practice rule for this case.
For now, that is what I have:

`(Model.AllColumns.Where(c => c.SortByColumn != null).Any(d => d.SortByColumn == this)`

and I got the error: “No property or field ‘c’ exists in type ‘Column’.  On the "Applies to" I used "Calculated Columns" and "Data Columns".

Any ideas? 
Thank you!

**Comment by otykier** [comment]
The iterator variable should not be specified in a Dynamic LINQ expression. Instead, use `it` to reference the object and `outerIt` to reference the object outside the iteration. Also, you don’t need an explicit null check. The following should work:

```
(Model.AllColumns.Any(SortByColumn == outerIt)
```

But we can also use the `UsedInSortBy` property to write this even more concise:

```
UsedInSortBy.Any()
```

**Comment by otykier** [comment]
Cleaning up old issues from the backlog. Feel free to reopen if the issue isn't solved for you!
