### ISSUE TITLE
Azure Devops Build pipeline issue with Tabular editor .exe 

### ISSUE THREAD

**Issue by Surendra-thota1640** [otykier/TabularEditor#376]
for one of the tabular deployment we are facing this error 
Tabular Editor 2.8.7150.19986
--------------------------------
Loading model...
Deploying...
Deployment failed! The JSON DDL request failed with the following error: Cannot resolve all the paths while de-serializing Database. .
The same database we are able to deploy manually through Tabular editor , but when we are using devops pipeline we are facing this issue

**Comment by otykier** [comment]
Could you please provide the full command that you are using within your pipeline?

Have you tried to execute this command manually through a windows command prompt?

**Comment by Surendra-thota1640** [comment]
TabularEditor.exe "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/Model.bim" -D "$(ASConnectionString)" "$(ASDatabase)" -O

**Comment by otykier** [comment]
Do you get the same error message if you try to run this command locally on your machine? Also - could you try to use the newest version of Tabular Editor in your build pipeline? (2.9.1)

**Comment by Surendra-thota1640** [comment]
Through command line the deployment it is working fine

**Comment by otykier** [comment]
Are you sure that you are deploying exactly the same version of the Model.bim file?

If you're using the same version of Tabular Editor both locally in your command line, and in Azure DevOps, there should not be any difference to running the command locally or running it through Azure DevOps...

**Comment by Surendra-thota1640** [comment]
I am using the same model.bim and same tabular editor  version

**Comment by otykier** [comment]
Which command are you using locally, that works fine?

**Comment by Surendra-thota1640** [comment]
C:\FromAzure\TabularEditor.Portable>TabularEditor.exe "C:/AzureRepo/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/Model.bim" -D "Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/<>;User ID=app:<>;Password=<>:gM/TE=508;Persist Security Info=True;Impersonation Level=Impersonate;" "AsqQuantificationTabular" -O

**Comment by otykier** [comment]
Looks good. Maybe your Pipeline variables have not been assigned properly? What happens if you copy your local command with the hard-coded connection string, etc. into a command line task in DevOps?

**Comment by Surendra-thota1640** [comment]
when I given script directly which is used in cmd line its worked fine in devops pipeline , what would be the problem

**Comment by Surendra-thota1640** [comment]
now it worked with parameters are also. do you know why we got that error
