### ISSUE TITLE
Dynamically deploy Role members based on Env

### ISSUE THREAD

**Issue by Surendra-thota1640** [otykier/TabularEditor#377]
we are migrating sql server analysis tabular model to Azure analysis services model , in the process we are using azure devops for deployment process through pipeline using tabulareditor ,  how to deploy the azure AD groups as rolemembers  based on environment (dev,test ,prod ) through some configfile or variables without manual intervention.

**Comment by otykier** [comment]
Sorry for the late reply. Through the TabularEditor.exe CLI you can execute a script against the model before deploying.

There are two types of members you can add - Windows or External. For Azure Analysis Services, you would normally use the External members:

![image](https://user-images.githubusercontent.com/8976200/72336734-a56a0c00-36c1-11ea-96e2-bf5a27c88f13.png)

So an example script, that clears all members of "Finance" and adds a couple of members would look like this:

```csharp
Model.Roles["Finance"].ClearMembers();
Model.Roles["Finance"].AddExternalMember("user1@kapacity.dk");
Model.Roles["Finance"].AddExternalMember("user2@kapacity.dk");
```

You can also pass pipeline variables to the script, so if you have a variable that holds the name of the Azure AD Group that should be added to a role, $(MyAADGroup), pass that variable into the command line task as an Environment Variable (similar to what I'm doing [here](https://user-images.githubusercontent.com/8976200/67012878-73610200-f0f2-11e9-976b-d9349cdbf57c.png) with the SQLDWConnectionString variable - from [this article](https://tabulareditor.github.io/2019/10/17/DevOps4.html)).

Then, use the following code in the script, to create a role member using the content of the variable:

```csharp
Model.Roles["Finance"].ClearMembers();
var myAADGroup = Environment.GetEnvironmentVariable("MyAADGroup");
Model.Roles["Finance"].AddExternalMember(myAADGroup);
```

It is up to you how you want to provide this script to your DevOps pipeline - it could be an artifact of the build, or you could generate the script inside the pipeline before calling TabularEditor.exe, etc.

Let me know if you have any additional questions (feel free to reopen the issue).

**Comment by Surendra-thota1640** [comment]
Hi
Thanks for the reply, we achieved the same with same logic.

Thanks

Surendra
