### ISSUE TITLE
KPI Status Graphic drop-down values incompatible with Power BI

### ISSUE THREAD

**Issue by jamhos** [otykier/TabularEditor#379]
Some of the pre-populated drop-down values for Status Graphic in the KPI properties work with Excel, but not Power BI (Power BI displays integer values).

The issue appears to be the hyphen - for example using "Traffic Light - Single", Tabular Editor populates "Traffic Light – Single" (long hypen) but Power BI appears only to work with "Traffic Light - Single" (short hyphen).

Can these be changed to pre-populate with the short hyphens?

![image](https://user-images.githubusercontent.com/59585318/71856836-63791d00-3139-11ea-8295-f01c584ddd6a.png)

**Comment by otykier** [comment]
Fixed in [2.9.3](https://github.com/otykier/TabularEditor/releases/tag/2.9.3)
