### ISSUE TITLE
How to Build CI \CD with release pipeline implementation

### ISSUE THREAD

**Issue by Surendra-thota1640** [otykier/TabularEditor#382]
we have Build pipeline to deployment , but we need build pipeline for creating artificates and Release pipeline to trigger from that artifact and to have 3 stages with approval process  at each stage . How to implement this using tabular editor

**Comment by otykier** [comment]
I'm not sure how this question is related to Tabular Editor.

If you're asking how to create a generic deployment task that uses Tabular Editor to deploy a model to different instances of AS based on pipeline variables, you can get the idea by looking at step 2 and 3 in [this blog post](https://tabulareditor.github.io/2019/10/17/DevOps4.html#step-2---schema-check). Step 2 illustrates how you can change the connection inside your Tabular Model to point to a different source database during deployment. Step 3 illustrates how you can change the connection string to which instance Tabular Editor should deploy the Tabular model.

I have plans to write up a more detailed blog post as the final part of this series, but I just don't have the time for it right now.
