### ISSUE TITLE
Support for Power BI Model Editing

### ISSUE THREAD

**Issue by tobimax** [otykier/TabularEditor#385]
Hi Daniel,

I love this tool and have just realised how good it is when I now have to develop inside Power BI. It's terrible. Have you got any more plans to better support PBIX/PBIT files? 

Issues like

Folder Support
Power Query Support
Dataflow Support
Round Tripping between TE and Power BI

**Comment by otykier** [comment]
Hi,
Glad you like the tool. Unfortunately, editing a Power BI Model through the TOM is not supported by Microsoft, so it's out of my hands. Once Microsoft releases the V3 metadata format and read/write XMLA endpoints, this should change, however, so keep an eye out for announcements from Microsoft on this area.
