### ISSUE TITLE
Crash when you delete column whose dependency view is open

### ISSUE THREAD

**Issue by greggyb** [otykier/TabularEditor#387]
If I open the dependency view for a certain column and then delete that column, I reliably crash the program.

I found this because I had deleted a column from source. I opened up that column's dependency view in TE. I deleted measures from the leaves of its dependency tree (double clicking on each measure name in the dependency view), and finally selected the root column (by double clicking its name in the dependency view). Upon deleting the column, TE reliably crashes with an unhandled exception.

Running on 2.9.1

**Comment by otykier** [comment]
Fixed in [2.9.3](https://github.com/otykier/TabularEditor/releases/tag/2.9.3)
