### ISSUE TITLE
Best practice analyzer with embedded rule engine

### ISSUE THREAD

**Issue by DBojsen** [otykier/TabularEditor#39]
I would like to see Tabular Editor add a way to check for global best practices as well as local standards.
I imagine it as a rule engine, where you can define rules thru a GUI with context like:
* If column name ends with Key or ID, it should be set the "Summarize By" property to "Do not summarize"
* If column is used as foreign key for other table, it should be set as hidden and "Do not summarize"
* Measure names must start with either "Count of", "Sum of", "Average/Avg of"

You should be able to add your own rules and disable global rules.
You should be able to do full check against rules as well as have on-the-fly checking while editing.
You should be able to dismiss a warning/error and this info should be saved for subsequent checks.

**Comment by otykier** [comment]
I love this idea! Will see what is feasible within a few days, and get back to you.

**Comment by otykier** [comment]
Just an FYI - this new feature is coming along great! Screenshot below shows the new interface for browsing defined rules and identifying objects that are in violation. Double-clicking an item in the lower list switches focus back to the main form and selects the corresponding object in the tree:

![image](https://cloud.githubusercontent.com/assets/8976200/23507717/a46187c8-ff4e-11e6-9c76-ba2d05ef0849.png)

Additionally, the lower list has a context menu that provides shortcuts to "fix" any violations encountered. This is possible for standard rules, where we can define how a rule violation can be fixed - for example, by setting the "Summarize By" property to a different value.

I'm currently working on an UI for defining rules (a rule builder - I didn't find any interesting 3rd party libraries compatible with WinForms, so I decided to roll my own...). Behind the scenes, rules are defined using [Dynamic LINQ](https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions) so the expressions generated by the UI are quite easy to understand, and these will be stored directly in the model annotations (for local rules) or in a .json file on the machine (for standard rules).

If you have any other suggestions for standard rules that should ship with Tabular Editor, please let me know - everyone is welcome to suggest!

Lastly, I'm considering packaging this Best Practice Analyzer as a stand-alone Visual Studio plug-in, that could be used even without Tabular Editor. What are your thoughts on that?

**Comment by marcosqlbi** [comment]
This is a great thing and I'd like to support it. The spin-off to a VS plug-in is also very interesting. I think we should create also a repository/library of suggested rules (imagine "core rules" that you can combine with your specific ones). I will certainly provide a contribute discussing/defining/implementing the rules for these libraries!

**Comment by otykier** [comment]
Thanks a lot, Marco - really appreciated! The idea is that rules can be imported/exported in the tool, so basically a central repository is just a matter of hosting a .json file somewhere (for example here on github), so that we can update and add new rules over time. Will provide more info when I have a build ready for testing.

**Comment by otykier** [comment]
Hi all - great news, with release 2.3 of Tabular Editor, the Best Practice Analyzer is ready to use. [More info here](https://github.com/otykier/TabularEditor/wiki/Best-Practice-Analyzer).

I originally planned to include a visual rule builder (see screenshot below), but it turned out to be very difficult to support a wide range of expressions, which I found would typically be used for rules. So I parked this for now. If the community is interested in getting a visual UI for building rules, I will consider bringing it back at a later time.

In any case, I'd very much like to build on Marco's idea of creating a repository/library of rules. As written in the wiki - the rules are stored in a simple JSON format. How do we get the ball rolling?

![image](https://cloud.githubusercontent.com/assets/8976200/25298692/adf44b2e-26f7-11e7-8dce-384ca48a0b42.png)

**Comment by marcosqlbi** [comment]
This is great! I am busy in the next week or two, but as soon as I can, I will play with that a little bit. I think to:

1. Evaluate the type of rules we can implement, and whether the JSON format below should be extended/changed or not

2. Once the JSON format is considered "solid", we can implement a web service to maintain a repository that could be queried from Tabular Editor (or from other editors - I imagine we could implement this logic as a separate rule in SSDT or DAX Studio, for example). The service would be a "delivery" service, initially, whereas for the publishing part, at the beginning we could manage a store manually, and then evaluate how to implement some publishing feature (I suspect this will not be necessary unless there will be many other authors of rules)

3. Implement the client of the service in Tabular Editor and maybe other tools.

This is awesome - I really look forward to start playing with it!

**Comment by otykier** [comment]
Thanks a lot Marco - looking forward to hear more from you.

FYI, I've updated the Wiki to explain a little more how to work with the Dynamic LINQ expressions on the BPA: https://github.com/otykier/TabularEditor/wiki/Best-Practice-Analyzer (with your knowledge of the TOM, this should not be an issue at all, but just in case others find this thread).

**Comment by marcosqlbi** [comment]
I tried to use BPA, but its window is always empty and buttons (add rule, edite rule, ... ) are always disabled.
I don't see any rule loaded, I tried the window connecting to a database on a server and opening a BIM file.
What can I do to investigate more?
Thanks!

Marco

**Comment by otykier** [comment]
Hi Marco
Apparently, I still have some UI work to do, to make the BPA more intuitive and user-friendly... :-)

Anyway, the BPA is only usable while a model is loaded in Tabular Editor. You should see that the "Add rule..." button becomes enabled as soon as you load a model (either by opening a .bim file
or connecting do an existing database). Unfortunately, there are no pre-defined/standard rules built into the BPA at the moment, so all rules need to be created from scratch. However, to get you started, could you try pasting the following code into a file, name it BPARules.json and put it in your %AppData%\..\Local\TabularEditor folder?

```json
[
  {
    "ID": "APPLY_FORMAT_STRING_TO_MEASURES",
    "Name": "Apply format string to measures",
    "Description": "FormatString property should be set for all measures",
    "Severity": 10,
    "Scope": "Measure",
    "Expression": "String.IsNullOrWhitespace(FormatString)"
  },
  {
    "ID": "ORGANIZE_COLUMNS_IN_DISPLAY_FOLDERS",
    "Name": "Organize measures in display folders",
    "Description": "Tables with more than 10 visible measures should have them organized in display folders for improved usability",
    "Severity": 10,
    "Scope": "Table",
    "Expression": "Measures.Count(not IsHidden) > 10"
  },
  {
    "ID": "DO_NOT_SUMMARIZE_KEY_COLUMNS",
    "Name": "Do not summarize visible key columns",
    "Description": "Visible numerical columns whose name ends with \"Key\", \"ID\" or \"Code\" should have their \"SummarizeBy\" property set to \"None\"",
    "Severity": 10,
    "Scope": "Column",
    "Expression": "(DataType = \"Int64\" or DataType = \"Decimal\" or DataType = \"Double\")\nand IsHidden = false\nand (Name.EndsWith(\"Key\") or Name.EndsWith(\"ID\") or Name.EndsWith(\"Code\"))\nand SummarizeBy != \"None\"",
    "FixExpression": "SummarizeBy = TOM.AggregateFunction.None"
  },
  {
    "ID": "FKCOLUMNS_HIDDEN",
    "Name": "Hide foreign key columns",
    "Description": "Columns used on the Many side of a relationship should be hidden.",
    "Severity": 1,
    "Scope": "Column",
    "Expression": "Model.Relationships.Any(FromColumn = outerIt) and not IsHidden and not Table.IsHidden",
    "FixExpression": "IsHidden = true"
  }
]
```

The next time you run Tabular Editor, you should then see these 4 rules in the BPA:
![image](https://cloud.githubusercontent.com/assets/8976200/25574291/4ec262be-2e4d-11e7-962c-a07f67c274fc.png)

Let me know if you have any further questions!

**Comment by marcosqlbi** [comment]
Ok the bug is the following: when there are no rules, and until you don't select one rule in the list, the "Add Rule" button is disabled.
Fixing this would allow an user to start creating queries :) because with no rules there is no way to enable that button!
I will work on exploring rules and I'll give you more feedback, thanks!

**Comment by otykier** [comment]
Thanks Marco - I found the bug with the "Add rule"-button. I really need to step up my testing game :-)
Also, the "Analyze All" button seemed to be forever disabled.
Both these issues are fixed in the [latest build](https://github.com/otykier/TabularEditor/releases/tag/2.3.6330).

**Comment by marcosqlbi** [comment]
Ok, now it works and I'm trying to understand how to implement certain rules. For example, this one:
Hide columns in hierarchy levels

**Comment by otykier** [comment]
Hi Marco,
You hit one of the current limitations of Dynamic LINQ, which is that the "outerIt" only works for the previous "level" of iteration using LINQ methods. We need a way to access the original object (similar to how EARLIEST in DAX, works ;-)). In that case, we could write something like:

```
Table.Hierarchies.Any(Levels.Any(Column = originalIt))
```
(Here "Column" references the source column of the current hierarchy level, and "originalIt" would reference the column being iterated by the rule analyzer).

I'm looking into a way to expanding Dynamic LINQ to allow this type of syntax.

Also, I will add some additional collections to the TOM wrapper, to allow for easier iteration of certain types of objects of the model. For example:

Model.AllHierarchies (iterates all hierarchies across all tables)
Model.AllLevels (iterates all levels across all hierarchies of all tables)

This would enable the above rule to be implemented simply as:

```
Model.AllLevels.Any(Column = outerIt) and IsHidden = false
```

I expect to have a new build ready later today with this implemented.

**Comment by otykier** [comment]
Hi Marco.
I [made some improvements to DynamicLinq.cs](https://github.com/kahanu/System.Linq.Dynamic/issues/71#issuecomment-298522506), so we can now properly use multiple levels of nesting (Any(...) inside Any(...)). Furthermore, I added a new keyword "current", which always refers the outermost object.

In addition, I've added some convenient collections on various classes, to make these kinds of expressions easier to write:

```
Model.AllColumns              // Iterates all columns across all tables of the model
Model.AllMeasures             // Iterates all measures across all tables of the model
Model.AllHierarchies          // Iterates all hierarchies across all tables of the model
Model.AllLevels               // Iterates all levels across all hierarchies on all tables of the model
Table.AllLevels               // Iterates all levels across all hierarchies of the table
Column.UsedInHierarchies      // Iterates all hierarchies of the table, in which this column is used as a level
Column.UsedInRelationships    // Iterates all relationships in which the column is used (either as FromColumn or ToColumn)
```

This means that your rule can now be implemented (on Column scope), by either one of these expressions. Which one to use, I guess is a matter of preference: 

- `UsedInHierarchies.Count() > 0 and not IsHidden`
- `UsedInHierarchies.Any() and not IsHidden`
- `Table.AllLevels.Any(Column = current) and not IsHidden`
- `Table.AllLevels.Any(Column = outerIt) and not IsHidden`
- `Table.Hierarchies.Any(Levels.Any(Column = current)) and not IsHidden`

You can try this out by downloading [this preview build](https://github.com/otykier/TabularEditor/files/969751/TabularEditor.zip).

Let me know if you feel you need other types of collections, etc. to make it easier to write certain rules.

**Comment by marcosqlbi** [comment]
I will try it in 1-2 days and I will update you – thanks!

Marco

**Comment by marcosqlbi** [comment]
I made some rule, and now I have another question! :)
I would like to implement this rule:

- TITLE: Pascal casing on visible names
- DESCRIPTION: The visible names of measures, columns, tables, and hierarchies should not have pascal casing, but separated words instead

I see two problems:

1. How can I create a function "IsPascalCasing" with a regular expression on a string, or with a C# function if the former is not possible? In other words... how can I reference other classes?
2. If I create the same rule for measures, columns, tables, hierarchies... it works, but I would not have a way to "group" these rules in a single "super-rule". If we had a single collection of all the "names", it would be easier. But I would prefer to implement individual name type - for example, I would consider the IsHidden property, too - if a name is hidden, it can be in PascalCasing.

Let me know your thoughts - thanks!

**Comment by otykier** [comment]
Hi Marco.
Thanks for the feedback.

1. Dynamic Linq only exposes a predefined set of .NET types, to keep things simple. System.Text.RegularExpressions is one of them, so writing an expression like the following, should return visible objects whose name is in PascalCase:

   `Regex.IsMatch(Name, "[A-Z]([A-Z0-9]*[a-z][a-z0-9]*[A-Z]|[a-z0-9]*[A-Z][A-Z0-9]*[a-z])[A-Za-z0-9]*") and not IsHidden`

   I found the regex code above on [this stackoverflow question](http://stackoverflow.com/questions/1128305/regular-expression-to-identify-camelcased-words-with-leading-uppercase-letter). Let me know if you can think of any other .NET types that should be exposed by default.

2. I see your point here. Currently, you would have to create a separate rule for every type of object. I guess a "Clone rule" button would be the easiest way to fix this, as well as having an option to logically group several rules as one. Writing a single generic rule for several different types of objects would probably be too confusing, as the TOM does not have, for example, a base type that supports both the Name and the IsHidden property, etc. In fact, in my TOMWrapper.dll, I have some interfaces (IHideableObject, IExpressionObject, IDescriptionObject, etc.) that could potentially be used, but I don't have interfaces for all kinds of properties, and as I said - it would probably be too confusing.

   For now, I guess we can "group" rules, by providing similar rule ID's: `NO_PASCALCASE_VISIBLE_TABLES`, `NO_PASCALCASE_VISIBLE_COLUMNS`, etc.

**Comment by otykier** [comment]
Hi Marco,
Hope you are well.
Just to give you an update on this, I am working on a change to the BPA rule editor, which allows you to create a rule that applies to several different object types:
![image](https://user-images.githubusercontent.com/8976200/27125362-53cb7434-50f4-11e7-855e-82c8fea704b8.png)
Naturally, the expression specified must be applicable to every type of objected selected. But this should make it a lot easier to create naming rules such as a rule for avoiding PascalCase on visible objects.

Please expect a new release in a weeks time, with this feature in place.

**Comment by marcosqlbi** [comment]
Very interesting! I'm busy these days, I hope I'll have more time towards the end of June to do more tests with that.

**Comment by otykier** [comment]
You will find the improved Best Practice Analyzer in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4).

In addition to being able to create one rule that scans several different object types, we can now also execute the analyzer from the Command Line. This may be useful in automated deployment scenarios, where you want to check if a model conforms to all defined practices, prior to deployment. The command-line syntax is: 

```
start /wait TabularEditor.exe Model.bim -A
```

Tabular Editor will list all objects that match the conditions of one or more rules. By using the `-V` switch, the output format will be changed into VSTS Logging Commands, so the VSTS build definition can react accordingly. It is possible to supply a custom rules .json file after the -A switch, to test the model against a specific set of rules.

Hereby encouraging all users of the BPA to share their ideas, and post any useful rules you may have created :-)

**Comment by otykier** [comment]
A new repository has been created for hosting and discussing Best Practice Rules. Please take a look here: https://github.com/TabularEditor/BestPracticeRules

An [initial release](https://github.com/TabularEditor/BestPracticeRules/releases/tag/0.1) containing 10 rules of various kind has also been created.

Closing this issue, but encouraging everyone who'd like to contribute to continue discussion/open new issues [here](https://github.com/TabularEditor/BestPracticeRules/issues).
