### ISSUE TITLE
Tadbular editor deployment is failing suddenly with the fallowing error

### ISSUE THREAD

**Issue by Surendra-thota1640** [otykier/TabularEditor#391]
Until today the Azure Devops deployment (Release pipeline worked fine ) suddenly we are getting the fallowing error . we are using tabular editor for deployment into azure analysis services

Deployment failed! Deserialization failed: The 'CompatibilityMode' element in the 'http://schemas.microsoft.com/analysisservices/2019/engine/900' namespace is unexpected.

**Comment by otykier** [comment]
Duplicate of #389 .
