### ISSUE TITLE
Cannot save a custom action if no model is open

### ISSUE THREAD

**Issue by warthurton** [otykier/TabularEditor#394]
FormMain.cs line 522

`
var toRemove = UI.Actions.OfType<CustomAction>().FirstOrDefault(a => a.BaseName.Equals(act.Name, StringComparison.InvariantCultureIgnoreCase));
`

This occurs as due to `TabularEditor.UI.Actions.Action.get_Name()` failing due to its reliance on ModelActions.cs and 

`
        public virtual string Name
        {
            get
            {
                return _name(ui.Selection, ui.Handler.Model);
            }
`
Not having a either a selection or model.

I will update with a cleaner set of details but to re-create.

1) Open Tabular Editor
2) Do not open a model
3) Go to Advanced Scripting
4) Put in some code
5) Click Save + buttion
6) Enter name and choose any type
7) Click OK
8) Exception occurs

**Comment by otykier** [comment]
Thanks for reporting. I never considered that users would create and save custom actions while not having a model loaded. Should be an easy fix by checking `ui.Handler` for `null`.

**Comment by warthurton** [comment]
I was cleaning up after a problem with my configuration file and never loaded the model.  It wasn't obvious to me either.

**Comment by otykier** [comment]
Fixed in [2.9.3](https://github.com/otykier/TabularEditor/releases/tag/2.9.3)
