### ISSUE TITLE
New Columns don't Show for Calculated Tables

### ISSUE THREAD

**Issue by jburns7744** [otykier/TabularEditor#399]
Hi There,

I've noticed when adding a calculated table to Tabular Editor (and then subsequently modifying it (i.e. adding additional columns), that those new columns are not recognized in the object explorer area.  Is this a known issue?  Redeploying, restarting Tabular Editor, and pulling in from copies from GIT repo does not seem to fix the issue.

P.S. I am not using any "Add Columns" functionality at all.  The entire table structure is contained in the initial DAX.

**Comment by otykier** [comment]
This is by design. Tabular Editor can not parse the DAX code to determine the resulting columns. If instead you load the model from am already deployed database, then Tabular Editor will update the column metadata from Analysis Services after you hit save.

**Comment by jburns7744** [comment]
Thank you sir, will do.
