### ISSUE TITLE
Deployment Wizard should remember recent settings

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#4]
Sometimes you need to deploy several times in a row. It would be useful if the Deployment Wizard stored all settings when you deploy, so that next time you open the wizard, it opens up on the "Summary" page, ready to deploy again.

The deployment wizard should only reset the server/database/deployment options, when a new tabular model is loaded into Tabular Editor.

**Comment by match-gabeflores** [comment]
I'm not sure if it's just me, but Tabular Editor isn't remembering deployment settings for me. 
deploying to ssas 2019 and azure analysis services. 

![Image](https://github.com/user-attachments/assets/4f28b32b-248b-404c-9c64-e4f39845e02e)
