### ISSUE TITLE
Time Format

### ISSUE THREAD

**Issue by j0hnnyw1nter** [otykier/TabularEditor#402]
Kind of an issue, but I also seem to have the solution. I have a time stored in my source database, and the users would like this to be displayed in time format h:mm AMPM

This option is available in the drop down in Tabular editor, and seems to work all ok.

If I connect to my tabular model in Excel, this displays as I would expect, but Power BI doesn't seem to like this time format.

HH:mm seems to be fine or H:mm, but any option with an AMPM suffix deosn't seem to agree with Power BI.

I fixed this myself by using a custom format of h:mmAM/PM  

Both Excel and PBI now display this as expected. I wondered if it would be useful to replace the current drop down options in Tabular Editor with this version instead to save people the same pain I had trying to figure out what the issue was.

Thanks

**Comment by otykier** [comment]
Sure - I'll replace the drop down option with your suggestion! Thanks for reporting.

**Comment by otykier** [comment]
Fixed in [2.9.3](https://github.com/otykier/TabularEditor/releases/tag/2.9.3)
