### ISSUE TITLE
cmd Deployment fails on AAD group 

### ISSUE THREAD

**Issue by ArthurSteijn** [otykier/TabularEditor#403]
I added an AD group to the model via SSMS/VS. after this the deployment in my Azure DevOps Pipeline and cmdline locally fails with the following error. 

`##[error]Deployment failed! The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'ID cannot be specified for Azure Analysis Services role member: 'obj:a5dd211d-7b32-4235-9c66-30192c0b4777@***'.`

My work around skips the Members and after the deployment I execute a TMSL script in my pipeline to Create or Replace my roles with members

**Comment by MatsMolina** [comment]
Having the same problem here. In my case im adding a service principle to a role member

**Comment by MatsMolina** [comment]
Also get the same error when i have Integrated Workspace Mode = false

**Comment by otykier** [comment]
Hi all
When adding Azure AD members to roles in Tabular Editor, please make sure you only specify the "MemberName" property, as follows:
1. Select the role you want to add/edit members for in the tree
2. Locate the "Members" property in the property grid and click the ellipsis button
3. Add a new member using the little dropdown arrow. Choose "Azure AD Member"
4. Fill out the MemberName property. For an Azure AD group, the syntax should be: `obj:<objectID>@<tenantID>`

![image](https://user-images.githubusercontent.com/8976200/77520962-458e9f00-6e82-11ea-8b59-2f3ee8ed9c17.png)

If done correctly, Tabular Editor should generate the following TMSL upon deployment, which should not cause the error shown above:

```json
"roles": [
  {
	"name": "Admins",
	"description": "All administrators",
	"modelPermission": "administrator",
	"members": [
	  {
		"memberName": "obj:c6ad2168-xxxx-xxxx-xxxx-5c5cbb13b01e@1fff85b8-xxxx-xxxx-xxxx-a2e175280850",
		"identityProvider": "AzureAD"
	  }
	]
  },
  ...
]

Let me know if you have any further questions.
```

**Comment by MatsMolina** [comment]
My script looked almost the same as yours. 
 `   "roles": [
      {
        "name": "Test",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "app:xx-xx@xx-xx",
            "memberId": " app:xxxx@xxxx",
            "identityProvider": "AzureAD"
          }
        ]
      },
]`

Removed the memberId and it worked.

**Comment by ArthurSteijn** [comment]
So to specify a bit more what I experienced.

If you want to deploy a *.bim file via the cmd the members that are in the .bim must be in the deployed model, if not the deployment fails.
This means adding new role members must be done in two places or done afterwards with a TMSL script.
________________________________
Van: MatsMolina <notifications@github.com>
Verzonden: woensdag 25 maart 2020 10:43
Aan: otykier/TabularEditor <TabularEditor@noreply.github.com>
CC: Arthur Steijn <Arthur.Steijn@motion10.com>; Author <author@noreply.github.com>
Onderwerp: Re: [otykier/TabularEditor] cmd Deployment fails on AAD group (#403)


My script looked almost the same as yours.
"roles": [ { "name": "Test", "modelPermission": "read", "members": [ { "memberName": "app:xx-xx@xx-xx", "memberId": " app:xxxx@xxxx", "identityProvider": "AzureAD" } ] }, ]

Removed the memberId and it worked.

**Comment by otykier** [comment]
@ArthurSteijn what is the exact command that you use for deploying the .bim file?

By default, Tabular Editor should not deploy any existing roles/role members (instead, it should generate a TMSL script that would keep the original members which are already in the deployed database). You can use the -X switch to confirm how the generated TMSL script looks.

**Comment by ArthurSteijn** [comment]
I'm using:
`start /wait TabularEditor.exe " C:\Users\-xxx-\Model.bim" –D “Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/-xxx-aas;Initial Catalog=NL_ECP_Model;User ID= app:d62d5a96-xxx-xxx-xxx-xxxxxxx@xxxxxxx;Password= xxx;Persist Security Info=True;Impersonation Level=Impersonate” “Model" -O -C -P -R -M -W -E -V  `

I get an Error when I want to generate the XMLA file (in dutch, sorry for that):
`Onverwerkte uitzondering: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij TabularEditor.Program.HandleCommandLine(String[] args)
   bij TabularEditor.Program.Main()`

I was expecting the deployment to overwrite existing/add new roles and members when I use the -R and -M commands. Since regular AD members do get added, but AD Groups and Service Principals causes it to fail. If this is wrong, my bad.

**Comment by otykier** [comment]
Using the `-R -M` switches to deploy roles and role members from the .bim file is indeed correct, when you want to overwrite those members already in the deployed database.

Could you please load your Model.bim file in Tabular Editor and see how the role members look like in the UI, as per my screenshot above? Specifically, you want to make sure that the role members have the Identity Provider set to "Azure AD", and that only the "Member Name" property is specified. "Member ID" should be blank.

![image](https://user-images.githubusercontent.com/8976200/77539602-f5bfd000-6ea1-11ea-8547-a9a71cd9a013.png)

**Comment by ArthurSteijn** [comment]
So I added a new member through visual studio, this fills the MemberID aswell. Identity Provides is AzureAD. 

Many thanks for your help!

**Comment by otykier** [comment]
I see. I have no idea why Visual Studio fills in the Member ID property, since it is obviously not supported for Azure Analysis Services as per the error message you received.

If needed, here's a script you can use as part of your DevOps pipeline to clear all Member ID strings:

```csharp
foreach(ModelRoleMember member in Model.Roles.SelectMany(r => r.Members))
    member.MemberID = "";
```

...or, if you need to copy the value of MemberID into MemberName (not sure what exactly Visual Studio does):

```csharp
foreach(ModelRoleMember member in Model.Roles.SelectMany(r => r.Members))
{
    if(!string.IsNullOrEmpty(member.MemberID))
        member.MemberID = member.MemberName;
}
```

Put this script into a file and use the `-S <filename>` command to execute the script before deploying.

Also, in regards to the `-X` switch causing a crash, you have to specify `-X <outputfilename>`, where `<outputfilename>` is the name of a file that will be created, containing the TMSL/XMLA script.

**Comment by ArthurSteijn** [comment]
Just wanted to let you know that the first script generates the following error:

"Script execution error: Property 'MemberID' of object 'ModelRoleMember' is immutable and can't be changed once set."

________________________________
Van: Daniel Otykier <notifications@github.com>
Verzonden: woensdag 25 maart 2020 16:07
Aan: otykier/TabularEditor <TabularEditor@noreply.github.com>
CC: Arthur Steijn <Arthur.Steijn@motion10.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [otykier/TabularEditor] cmd Deployment fails on AAD group (#403)


I see. I have no idea why Visual Studio fills in the Member ID property, since it is obviously not supported for Azure Analysis Services as per the error message you received.

If needed, here's a script you can use as part of your DevOps pipeline to clear all Member ID strings:

foreach(ModelRoleMember member in Model.Roles.SelectMany(r => r.Members))
    member.MemberID = "";

...or, if you need to copy the value of MemberID into MemberName (not sure what exactly Visual Studio does):

foreach(ModelRoleMember member in Model.Roles.SelectMany(r => r.Members))
{
    if(!string.IsNullOrEmpty(member.MemberID))
        member.MemberID = member.MemberName;
}

Put this script into a file and use the -S <filename> command to execute the script before deploying.

Also, in regards to the -X switch causing a crash, you have to specify -X <outputfilename>, where <outputfilename> is the name of a file that will be created, containing the TMSL/XMLA script.

**Comment by otykier** [comment]
I see. For some reason, TOM has this limitation that we can't change the MemberID of a member after it's been persisted in the model. Use the following script, which will delete and recreate the role members without the Member ID:

```csharp
foreach(var role in Model.Roles)
{
    // Find all Azure AD role members where MemberID is assigned:
    var orgMembers = role.Members.OfType<ExternalModelRoleMember>()
        .Where(m => m.IdentityProvider == "AzureAD" && !string.IsNullOrEmpty(m.MemberID)).ToList();
        
    // Delete the member and recreate it without assigning MemberID:
    foreach(var orgMember in orgMembers)
    {
        orgMember.Delete();
        role.AddExternalMember(orgMember.MemberName);
    }
}
```
