### ISSUE TITLE
feature request - copy out of BPA

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#407]
Currently can select result items within BPA but can't copy them (say to Excel). I know you can do it using advanced scripting but would be a nice feature to have directly within the BPA.

Thanks!

**Comment by kalmenk** [comment]
as an example, say the rule is showing unnecessary columns. would be great to join it to Vertipaq Analyzer data to show how much memory could be saved by removing said columns.

**Comment by otykier** [comment]
Fixed in [2.11.5](https://github.com/otykier/TabularEditor/releases/tag/2.11.5)

**Comment by m-kovalsky** [comment]
Niiice! Thanks!
