### ISSUE TITLE
How to get input from users when running a CustomAction

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#408]
I am thinking about writing an import tool as I've written about before. One of the things I'd like to do is, after the developer has picked the excel file (using the standard Open File Dialog) , prompt them with a list of all the Part Id's in a Combo box so they can choose which part of the document they want to import. 

Is there any way to do this? It could be just a textbox rather than a combo if that was simpler.

**Comment by otykier** [comment]
It can be done, but it takes some trial and error to layout and configure the form and controls to appear the way you want. Here's a sample, where I'm using the [TableLayoutPanel](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutpanel?view=netframework-4.8) to place the label, combobox and buttons in a 2 x 3 grid:

```csharp
using System.Windows.Forms;

// Configure form. See: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form?view=netframework-4.8#properties 
var form = new Form() { 
    Width = 400, 
    Height = 300, 
    Text = "Hello World", 
    MinimizeBox = false, 
    MaximizeBox = false, 
    FormBorderStyle = FormBorderStyle.FixedSingle,
    StartPosition = FormStartPosition.CenterParent,
};

// Use a TableLayoutPanel to layout the controls:
var layoutPanel = new TableLayoutPanel(){
    Dock = DockStyle.Fill,
    RowCount = 3,
    ColumnCount = 2 
};
form.Controls.Add(layoutPanel);

var label1 = new Label() { Text = "Select something", Dock = DockStyle.Fill };

// Configure the combobox:
var comboBox1 = new ComboBox() { Dock = DockStyle.Fill, DropDownStyle = ComboBoxStyle.DropDownList };
// Populate the list of items:
comboBox1.Items.Add("Item 1");
comboBox1.Items.Add("Item 2");
comboBox1.Items.Add("Item 3");

layoutPanel.Controls.Add(label1, 0, 0);
layoutPanel.Controls.Add(comboBox1, 1, 0);

// Add OK and Cancel button:
var okButton = new Button() { Text = "OK", DialogResult = DialogResult.OK };
var cancelButton = new Button() { Text = "Cancel", DialogResult = DialogResult.Cancel };

layoutPanel.Controls.Add(okButton, 0, 2);
layoutPanel.Controls.Add(cancelButton, 1, 2);

// Show the dialog:
if(form.ShowDialog() == DialogResult.Cancel) return; // User clicked "Cancel"

// Display the selected item:
comboBox1.SelectedItem.Output();
```

Result:
![image](https://user-images.githubusercontent.com/8976200/77154396-e6a0e280-6a9b-11ea-8c72-a89e129573d0.png)

**Comment by otykier** [comment]
If you have Visual Studio, I recommend creating a new WinForms project and then using the WinForms designer to build and layout your form. Once done, you can copy the code generated by the designer into your script. Might be easier than trial-and-error.

**Comment by o-o00o-o** [comment]
Thanks Daniel. Really helpful, I'll have a play in Visual Studio
