### ISSUE TITLE
Msg possible Ransomware Detected

### ISSUE THREAD

**Issue by pcand1001** [otykier/TabularEditor#409]
Message Possible Ransomware Detected thrown by Acronis Active Protection
![image](https://user-images.githubusercontent.com/62514847/77255352-f3504280-6c23-11ea-85bb-9ec3af05f6dd.png)

**Comment by pcand1001** [comment]
The I tried to download a new copy and the download gets blocked
![image](https://user-images.githubusercontent.com/62514847/77255435-94d79400-6c24-11ea-84f2-c9dc5a64ec4e.png)

**Comment by otykier** [comment]
Closed as duplicate of #313 

I'm working on securing funds for a code signing certificate. In the mean time, if you have Visual Studio installed, you can get around the limitations by compiling Tabular Editor from source code.

**Comment by otykier** [comment]
As of [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8) Tabular Editor is now digitally signed. Please let me know if it is still being reported as malware/ransomware.
