### ISSUE TITLE
Tabular Editor and Oracle

### ISSUE THREAD

**Issue by Drudgaard** [otykier/TabularEditor#410]
Hi Daniel,

I am a big fan of Tabular Editor and have used it with great success in my previous workplace, which was a clean SQL Server setup.

Now I have moved to a place where it is Oracle databases and here I have some challenges to make everything work properly. Among other things. I can't use "Import Tables" and "Refresh Table Metadata".

Do you know what it is due to?

And do you have other good tips for making Tabular Editor and Oracle databases work well together?

Best regards, 
Steffen Drudgaard

**Comment by otykier** [comment]
Hi Steffen,

Unfortunately, I don't have any experience working with AS Tabular directly on top of Oracle, and for that reason, I never got around to finish the implementation of adding Oracle sources through the Import Table wizard.

My best advice would be to create the initial model using Visual Studio, connecting to your Oracle data source and importing a couple of tables in VS using either Power Query or Legacy data sources (try both to see what works best, also considering refresh performance, etc.). Then, once you've done that, close Visual Studio and load the model in Tabular Editor.

At this point, even though the regular Import Table wizard and Refresh Table Metadata options do not work, you may still be able to import additional tables by choosing the ["Manually import metadata from another application" option](https://github.com/otykier/TabularEditor/wiki/Importing-Tables#manually-importing-schemametadata) in the wizard.

With this approach, you only need to copy-paste a PL/SQL CREATE TABLE or CREATE VIEW statement, representing the table you want to import, and Tabular Editor should infer the column names and data types from that code. Once the table is imported, make sure the Partition properties have been set up in a similar way as the tables you imported using Visual Studio.

Please let me know if there are any issues.

**Comment by Drudgaard** [comment]
Hello Daniel,

Thanks for your reply.

I will try your advice and let you know if I experience any issues.

All the best,
Steffen Drudgaard
