### ISSUE TITLE
Overwriting folder structure changes false positives?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#412]
I haven't done any dev in TE for a while, but this weekend when building that repro for #411 I found that I was getting the 

---------------------------
Overwriting folder structure changes
---------------------------
Changes were made to the currently loaded folder structure after the model was loaded in Tabular Editor. Overwrite these changes?
---------------------------
OK   Cancel   
---------------------------

dialog when I wasn't expecting it.

Trying it again today shows that if I open the model, save - if I then save again I then get this warning.

This message box I thought should only happen if the files have changed from something other than Tabular Editor (to warn perhaps that you have done a GIT checkout or something since opening the model - so I think this is a bug?

**Comment by otykier** [comment]
Could you confirm that this issue only appears after you use File > Save As... ?

**Comment by o-o00o-o** [comment]
- Open from database.json (from my recent items)
- Save (ctrl-s)
- Save (ctrl-s)
- get the overwrite message

**Comment by otykier** [comment]
I found the bug. Will be fixed in 2.9.6 which is released later today. Thanks!

**Comment by otykier** [comment]
Fixed in [2.9.6](https://github.com/otykier/TabularEditor/releases/tag/2.9.6).
