### ISSUE TITLE
Find as you type for drop down

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#415]
Hi,

when defining a relationship in Tabular Editor one has to scroll through a list that potentially contains thousands of columns.

![image](https://user-images.githubusercontent.com/908734/77852685-42781380-71e0-11ea-813d-34c80e3fc15b.png)

Please add a filter functionality there so that I can just enter a few letters and only see matching columns.
Another idea would be to use a hierarchical drop down. Because then one could select first a table and then the column.

Thanks alot.

**Comment by otykier** [comment]
This is already in the backlog. In the mean time, remember you can right-click on a column to create a relationship to another column: Right-click > Create new > Relationship To/From > (choose table) > (choose column).
