### ISSUE TITLE
Expose DiscourageImplicitMeasures Model Property for PowerBI Template

### ISSUE THREAD

**Issue by WillAyd** [otykier/TabularEditor#418]
Going through the steps described here to try and set up a calculation group

https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions#benefits

One of the things that's rather difficult though is that I can't seem to find the DiscourageImplicitMeasures property anywhere in the editor, even when using the enhanced metadata model in PowerBI with "compatibilityLevel": 1520

For what it's worth, when unzipping the template locally I don't see a key for "discourageImplicitMeasures" which is perhaps the root cause, but some way to edit in any case may be useful

**Comment by otykier** [comment]
Yep - this is a bug in 2.9.6. Please enable experimental Power BI features under File > Preferences as a workaround.

**Comment by WillAyd** [comment]
Confirmed this option is available with that option checked - thanks! Feel free to close unless you want this open for further tracking

**Comment by otykier** [comment]
Fixed in [2.9.7](https://github.com/otykier/TabularEditor/releases/tag/2.9.7)
