### ISSUE TITLE
Cannot Change Name of Calculation Item in Calculation Group

### ISSUE THREAD

**Issue by WillAyd** [otykier/TabularEditor#419]
First and foremost - kudos on a great tool!

I am trying to add a calculation group which seems OK, but the ability to change the name of items added to the group is always grayed out:

![image](https://user-images.githubusercontent.com/609873/78086234-2efcb200-7372-11ea-8db3-fad11191a498.png)

**Comment by otykier** [comment]
Yep - this is a bug in 2.9.6. Please enable experimental Power BI features under File > Preferences as a workaround.

**Comment by otykier** [comment]
Fixed in [2.9.7](https://github.com/otykier/TabularEditor/releases/tag/2.9.7)
