### ISSUE TITLE
PowerBI Calculation Group Yields "not a Valid M Expression"

### ISSUE THREAD

**Issue by WillAyd** [otykier/TabularEditor#420]
This might not be an issue with the tool but worth trying anyway...With 2.9.6 and "Allow unsupported Power BI features (experimental)" checked, I can create a Calculation Group and save back appropriately (at least using a .pbit file).

However, when opening the template in PowerBI I receive "The query, New Calculation Group 1, does not have a valid M Expression"

![image](https://user-images.githubusercontent.com/609873/78167048-a417c800-7402-11ea-9431-a571b0545153.png)

I noticed that the following gets written in the `DataModelSchema`

```js
        "partitions": [
          {
            "name": "Partition",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
```

Which when compared to other queries I've seen doesn't have an "expression" key in the "source" object (may or may not be an issue)

**Comment by WillAyd** [comment]
By the way would be happy to help debug on this; out of curiosity how are you figuring out the requirements for the `DataModelSchema` file? Is this published by MSFT?

**Comment by WillAyd** [comment]
Found the PartitionSource docs which I assume this may be derived from, though didn't see anything documented for calculationGroup

https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.partitionsourcetype?view=analysisservices-dotnet

**Comment by otykier** [comment]
Calculation Groups are not yet supported on models hosted by Power BI Desktop, which is why you're getting this error. If you have access to a Read/Write enabled Power BI Premium workspace, you should be able to add calculation groups to a dataset that was published to this workspace without issue.
