### ISSUE TITLE
Set Format String Expression hides metadata in DAX Studio

### ISSUE THREAD

**Issue by jorgemlesteves** [otykier/TabularEditor#422]
Setting an expression ("0.00%", as an example) in the Format String Expression property of a Calculation Item  **hides**, in **DAX Studio** ,any metadata information from tables that have measures defined. 
![image](https://user-images.githubusercontent.com/31868867/78176671-ccc8ad80-7454-11ea-80e4-708331ebf75b.png)

![image](https://user-images.githubusercontent.com/31868867/78176688-d5b97f00-7454-11ea-9d1f-4f28462b3d94.png)

**Comment by otykier** [comment]
I see you raised this as an issue on the [DaxStudio](https://github.com/DaxStudio/DaxStudio/issues/303) GitHub which is where this belongs, so closing this issue here.

**Comment by jorgemlesteves** [comment]
You're right!
Thanks Daniel for your great, great job!
