### ISSUE TITLE
Please auto-expand Calculation Items when opening a Calculation Group

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#423]
I know there are still some outstanding requests for tree control improvements, but something that I thought would be useful and possibly easy to implement is when expanding a Calculation Group 99% of the time you want to edit a calculation item but you have to click expand twice to get there. Any chance you can give my RSI a break? :)

**Comment by otykier** [comment]
Fixed in [2.9.7](https://github.com/otykier/TabularEditor/releases/tag/2.9.7)
