### ISSUE TITLE
A way to be able to easily compare measures/properties etc

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#427]
Increasingly I'm finding that I am slowed down by the UI when wanting to compare two measures/calculation groups etc. 

I often end up running two instances of TE to allow side by side comparisons, but this is clumsy and requires quite careful discipline to ensure that you are only editing in one of them, which is easily broken which leads to missing/overwritten code.

There are a few ways to solve this but some ideas to help these
1. Back/Forward ability like a web browser. Linked to my mouse buttons
2. Ability to open multiple windows for the same open model

Any other ideas?

**Comment by marcosqlbi** [comment]
The Back/Forward is a very good idea.
I'd like also the multiple windows, even though there could be issues in getting a good synchronization (but maybe it's already implemented - Daniel certainly know that!).

**Comment by o-o00o-o** [comment]
I'm constantly hitting ctrl-tab to switch between the last measure I was on as this is the way that all other code editors work.  Right now that switches to the Scripting pane which (I think Daniel would agree) is a bit of a strange implementation. I would suggest that Scripting pane would be more of a "View" item that you can toggle on or off in the menu rather than it being a tab on the scripting window which is where the multi documents would be. This would make it a more consistent design language with other code tools.

**Comment by otykier** [comment]
I definitely agree the UI needs an overhaul in this regard (see the discussion in #280 - it's not forgotten, and there will be some exciting announcements later this year). In the mean time, note that Tabular Editor already has a "back/forward" shortcut, that let's you use the keyboard to navigate back and forward between objects that have DAX expressions, that you visited (measures, calc tables, etc.) - you use the two arrow buttons in the top right of the Expression Editor to navigate (or shortcut Alt+Left/Right arrow). In the short term, I could let these buttons navigate the history of any objects that were visited - not just measures, calc tables. Would that work?

**Comment by o-o00o-o** [comment]
Wow, I never noticed these back/forward buttons before! They are not where a back/forward button would normally be, I'd suggest should be on the left side like browsers have them, to help discovery.

Yes I think that would be a good enhanced functionality so can quickly switch between objects to compare properties etc and move the buttons so they are in the main toolbar on the left hand side like a browser would be a really useful enhancement

**Comment by otykier** [comment]
Closing this as Tabular Editor 3 addresses the enhancements suggested here. Opening multiple windows will not make it into the open-source version of Tabular Editor, as this would require a major overhaul of the UI stack.
