### ISSUE TITLE
Provide a better way to update/delete existing custom actions

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#429]
Hello Daniel,
In "advanced scripting" tab, I can load a custom action clicking on "Samples" listbox.
When I modify the script then I need to update the custom action clicking on "+" button but then I need to type again name, tooltip an actions. Is there an other way to update the script or do I need to update it in the Json file ?
Is there an other way to delete a script than modifying the Json file ?

**Comment by asocorro** [comment]
Hi Daniel, I have the same question about updating custom actions.  Thanks!

**Comment by otykier** [comment]
Hi both.
Unfortunately, this is the correct way of modifying an existing custom action as of right now. If you need more control, or if you need to delete existing custom actions, you'd have to edit the json file here: `%localappdata%\TabularEditor\CustomActions.json`

**Comment by otykier** [comment]
Fixed in [4.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0)
