### ISSUE TITLE
ExportProperties does not work with TranslatedNames!

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#434]
Hi,
I want to extract Name and TranslatedNames of columns but when I want to extract the TranslatedNames with ExportProperties in advance scripting, the value of TranslatedNames is same for all records (TabularEditor.TOMWrapper.TranslationIndexer ).
This also happens if I use TranslatedDescriptions,TranslatedDisplayFolders.

best regards,
Arman

**Comment by didierterrien** [comment]
Hello,
I wrote a script to export translatable objects. In case it will be usefull for you, you can download it here  : https://thebipower.fr/index.php/2020/04/12/automatic-translation-of-tabular-model/
Regards

**Comment by ArmanFalah** [comment]
Thanks, but I afraid it doesn't work with SSAS Tabular.

**Comment by ArmanFalah** [comment]
Didier,
I couldn't download the files on your website!

**Comment by didierterrien** [comment]
Hello,
You can retry now and let me know

**Comment by ArmanFalah** [comment]
Thanks Didier.
the "Save Translate" file works, the other file does not work.
maybe because I am using SSAS Tabular.

**Comment by didierterrien** [comment]
That's normal. 
The "Load translations" loads a file created by the Excel application. For the moment, the Excel application is not available. I plan to make a walkthrough before publishing the Excel file.

**Comment by otykier** [comment]
Hi all. @albertospelta created a fantastic PR for this, so you can now use the `ExportProperties` and `ImportProperties` methods with indexed properties such as TranslatedNames. Get the latest version [2.11.0 here](https://github.com/otykier/TabularEditor/releases/tag/2.11.0). More details on [how ExportProperties works with indexed properties here](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#exporting-indexed-properties).
