### ISSUE TITLE
Automatic translation of tabular model

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#436]
Hello Daniel,
I finally succeeded to implement automatic translations of translatable objects writing 2 scripts. Do you know if visuals metadata will be available in Tabular Editor in the future so we can translate visuals titles, tooltips, ... ?

The presentation video and scripts are here :    https://thebipower.fr/index.php/2020/04/12/automatic-translation-of-tabular-model/

The hierarchies levels are not translated for the moment but might be in the future.
Best regards

**Comment by otykier** [comment]
Great scripts, thanks for sharing!

I'm not aware of any roadmap that would allow us to translate visuals metadata from within Tabular Editor, as these metadata are not stored as part of the Tabular model inside a .pbix / .pbit file.
As a workaround, consider using [DAX expressions to provide different titles based on user culture](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-format-visual-titles#create-a-field-for-your-title).
