### ISSUE TITLE
Tabular Editor and Oracle 

### ISSUE THREAD

**Issue by Time637** [otykier/TabularEditor#438]
Hi Daniel,

I am a big fan of Tabular Editor and have used it with great success in my previous workplace, which was a clean SQL Server setup.
I  want to know how to connect oracle dababase？
can connect oracle 11g？
Best regards,
TIme637

**Comment by otykier** [comment]
Tabular Editor does unfortunately not support Oracle 11g (or newer). For importing table metadata to your tabular model, consider using an ODBC driver, or import the metadata "manually" as [described here](https://github.com/otykier/TabularEditor/wiki/Importing-Tables#manually-importing-schemametadata).
