### ISSUE TITLE
ADO Builds Running Tabular Editor 2.9.7 (build 2.9.7397.23259) Taking Very Long

### ISSUE THREAD

**Issue by cztaylor** [otykier/TabularEditor#439]
Below is the Tabular Editor CLI command being used in one example. The command does the following:

- Opens database.json from the source control folder
- Runs a BPARules file
- Saves the model as a .bim file

This step used to take 1 to 2 minutes when running on Tabular Editor 2.8.6964.26585. After updating the Job Agent to build 2.9.7397.23259, this step is taking 8+ minutes

`C:\VSOJobAgent\_work\_tool\TabularEditor.exe "C:\VSOJobAgent\_work\6\s\Main\KPI_Lake\database.json" -A "C:\VSOJobAgent\_work\6\s\BestPracticeAnalyzer\BPARules.json" -B "C:\VSOJobAgent\_work\6\a\KPI_LakeUAT.bim" -V
`

**Comment by cztaylor** [comment]
After removing the step for running Best Practice Analyzer the build is running fast. So this must have something to do with BPA

` -A "C:\VSOJobAgent\_work\6\s\BestPracticeAnalyzer\BPARules.json"`

**Comment by otykier** [comment]
Thanks for reporting. At first glance, I don't see any differences between the two versions of Tabular Editor that could cause this slowdown. However, I found that the BPA may bog down the overall execution time if a rule causes an exception while being evaluated - for example, when doing something like `Description.StartsWith("abc")` on an object where `Description` is null. There is also a bug in the UI where such exceptions are not handled correctly and this may cause crashes that look like this:

![image](https://user-images.githubusercontent.com/8976200/79334268-3f8b5b80-7f20-11ea-85ae-5b88b3b2d352.png)

Until I provide a fix for the above, please check to see if you have any rules that could cause runtime exceptions like this.

**Comment by cztaylor** [comment]
We've narrowed it down to these two rules, which are taking a very long time to run on 1400 and 1500 models.

These two rules are taking a very long time to run, but after a long time they are running successfully.

**No two measures should have the same definition**
Model.AllMeasures.Any(Expression.Replace(" ","").Replace("\n","").Replace("\r","").Replace("\t","") = outerIt.Expression.Replace(" ","").Replace("\n","").Replace("\r","").Replace("\t","") and it <> outerIt)


**No direct measure references**
Model.AllMeasures.Any("[" + Name + "]" = outerIt.Expression.Replace("\n","").Replace("\r","").Replace("\t","").Replace("CALCULATE","").Trim())

**Comment by otykier** [comment]
These rules are going to be particularly slow on a model with a large number of measures, as they are comparing every single measure against every other measure on the model - that means 1.000.000 comparisons if you have 1.000 measures in your model. The BPA is not well suited for this type of analysis.

As a workaround, consider using the following script as part of your build pipeline, to perform the same checks. It's even slightly better, as it uses DAX tokenization to compare the expressions, instead of string manipulations (this means it has better dealing with comments, whitespaces, etc.):

```csharp
// ------------------------------------------------------------------------------------------------
// Rule 1: No two measures should have identical DAX expressions (ignoring whitespace and comments)
// ------------------------------------------------------------------------------------------------

// Define a function that can calculate a unique hash code for a list of DAX tokens:
Func<IEnumerable<DaxToken>, int> GetSequenceHashCode = (tokens) => {
    const int seed = 487;
    const int modifier = 31;
    unchecked {
        return tokens.Aggregate(seed, (current, token) => (current * modifier) + token.Text.GetHashCode());
    }
};
var hashCache = new Dictionary<int, Measure>();
Measure other;

foreach(var measure in Model.AllMeasures)
{
    // Calculate a hash value for the tokenized expression of each measure (ignore comments and whitespace):
    var hash = GetSequenceHashCode(measure.Tokenize().Where(t => !t.CommentOrWhitespace));
    
    // If another measure has the same hash value, report it as a duplicate expression:
    if(hashCache.TryGetValue(hash, out other)) {
        Error(measure.DaxObjectName + " has the same DAX expression as " + other.DaxObjectName);
    }
    else
        hashCache.Add(hash, measure);
}

// ------------------------------------------------------------------------------------------------
// Rule 2: No measure should have an expression that directly references a single other measure
// without any additional logic, or in a call to CALCULATE without other parameters.
// ------------------------------------------------------------------------------------------------
foreach(var measure in Model.AllMeasures)
{
    // Get a list of tokens for the current measure (ignore comments and whitespace):
    var tokens = measure.Tokenize().Where(t => !t.CommentOrWhitespace).ToList();
    
    if(tokens.Count == 1 && tokens[0].Type == DaxToken.COLUMN_OR_MEASURE)
        Error(measure.DaxObjectName + " does nothing but reference a single measure.");
    if(tokens.Count == 4 && tokens[0].Type == DaxToken.CALCULATE && tokens[2].Type == DaxToken.COLUMN_OR_MEASURE)
        Error(measure.DaxObjectName + " does nothing but reference a single measure in a call to CALCULATE(...).");
}
```

To execute from the command line, save the script into a file and use the -S switch.

**Comment by otykier** [comment]
@cztaylor were you able to workaround this issue using the provided script?

Also, you mentioned that the issue appeared when upgrading Tabular Editor. Can you confirm that going back to the old version causes the Best Practice Analyzer to run faster on the problematic rules?

**Comment by otykier** [comment]
[2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8) contains the fix I mentioned above. Please feel free to open a new issue if the information provided in this thread did not help you.
