### ISSUE TITLE
Query, New Calculation Group , does not have a valid M Expression | Power BI | Calculation Groups | 

### ISSUE THREAD

**Issue by jainn4** [otykier/TabularEditor#441]
Hi, 

I am trying to create calculation groups in Power BI (.pbit) file. I am able to create the group and save the .pbit file. However, when I open the .pbit file and refresh it, I get the following error message

![Capture](https://user-images.githubusercontent.com/42496773/79547715-37e8c580-808c-11ea-8459-f5d79f2b3cd2.PNG)

The enhanced metadata feature is enabled 
Power BI Desktop Version: 2.79.5768.721 64-bit (March 2020)

Thanks
Nishant

**Comment by otykier** [comment]
Desktop doesn't yet support calculation groups (only through live connections to AS). The support should come later this year.
