### ISSUE TITLE
LinguisticMetadataID missing in cultures ?

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#443]
Hello Daniel,
After adding several translations I managed to translate the model in a pbix file. But when I connect Dax studio to this file, there is only one LinguisticMetadataID in the $SYSTEM.TMSCHEMA_CULTURES DMV. Is it normal ? Sorry to disturb you if it is normal.

![image](https://user-images.githubusercontent.com/37301981/79722726-df603500-82e4-11ea-9a67-8b33f66c03a9.png)

**Comment by otykier** [comment]
Tabular Editor does not currently have support for adding/removing/editing Linguistic Metadata (metadata used by Power BI Q&A). Do you need this functionality or is it sufficient to be able to add metadata translations?

**Comment by didierterrien** [comment]
Daniel, for the moment, I focus  on translating the visuals. I don't care about the Q&A. May be in the future. You can close the issue or keep it open as a reminder. Thank you!

**Comment by otykier** [comment]
I will close the issue, as I don't have any plans of adding support for linguistic metadata in the short term. Q&A in Power BI only supports English (and Spanish in preview), so I don't think there's much need for support in Tabular Editor at the moment.
