### ISSUE TITLE
Error when trying to deploy items added to perspectives

### ISSUE THREAD

**Issue by helgews** [otykier/TabularEditor#444]
Either **adding** a measure or a column to one of our perspectives causes deployment to existing model to fail. Seems like adding things to perspectives does not work anymore on existing models.

Deploying it as a new model works fine.
Removing a column from perspectives also works fine on existing models (but I get the same error when trying to put the column back into the perspectives).

Error message in norwegian (sorry):
![image](https://user-images.githubusercontent.com/56156227/79900178-1f6f0700-840e-11ea-8645-41e469b01cf7.png)

In english it would be something like:
 "The table referenced by the PerspectiveTable object  in perspective cannot be altered. Altering the referenced object is not permitted after the object has been created."

**Comment by otykier** [comment]
Thanks for reporting. This is an issue in TOM which was reported to the product group some time ago. There is a new release of TOM available as of a couple of days ago - I will try to recompile Tabular Editor against this version to see if the issue is resolved, and get back to you.

**Comment by mtvessel** [comment]
Hi Daniel.  Just letting you know I'm seeing the same issue deploying an XMLA script created with TE 2.9.7.  TIA!

**Comment by otykier** [comment]
[2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8) is out now, which uses an updated version of TOM/AMO. Could you please try this version and let me konw if the issue persists?

**Comment by helgews** [comment]
Thank you! Issue was fixed in 2.9.8 👍
