### ISSUE TITLE
Tabular Editor connection to Power Pivot Model

### ISSUE THREAD

**Issue by BojVO** [otykier/TabularEditor#445]
Good day,
Would it be technically feasible to connect directly to an open instance of a Power Pivot model as opposed to connecting to an open instance of a Power BI file. This would be similar to the manner in which DAX Studio gives you the ability to connect to Power Pivot or Power BI. Furthermore, would it be technically feasible to save the changes in Tabular Editor and have them updated in the Power Pivot model. Given there is still a significant number of people using Power Pivot, your feedback on the same would be highly appreciated.

**Comment by otykier** [comment]
I could be mistaken, but I believe Power Pivot uses tabular models in [Compatibility Level lower than 1200](https://www.sqlbi.com/blog/marco/2013/01/14/powerpivot-compatibility-across-versions/) - even in newer versions of Excel. These are not supported by [AMO/TOM](https://docs.microsoft.com/en-us/analysis-services/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo?view=asallproducts-allversions) which is required for Tabular Editor to load and edit the model metadata.

**Comment by BojVO** [comment]
Thank you for the feedback. Therefore, the likely recourse would be for Excel to support AMO/TOM.

**Comment by marcosqlbi** [comment]
Daniel is right - we need a new version of Power Pivot that supports the new compatibility level to enable this feature. The bad news is that a new compatibility level would break XLSX compatibility so it is not likely to happen soon.

**Comment by BojVO** [comment]
Dear Marco,
Thank you for your input. Please elaborate on how the new compatibility level would break XLSX compatibility (in the event you have a moment).

**Comment by marcosqlbi** [comment]
The XLSX file includes a backup of the data in Power Pivot. If Excel 2019 would support the new compatibility level, you would not be able to open the same XLSX file in Excel 2017. Best case, you open the Excel file but you cannot open Power Pivot and you cannot navigate data.
