### ISSUE TITLE
Schema Check - Some data types appear to be compared as if it is a string datatype

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#448]
Hello,

When I run the schema check via the command prompt i get the following warning when my underlying datatype is a datetime2(7).

##[warning]Column 'Date'[Last Date Of Year] is imported as DateTime but the source type should normally map to String.

I also get the following warning when the underlying data type is smallint.

##[warning]Column 'Date'[Week Number] is imported as Int64 but the source type should normally map to String.

![image](https://user-images.githubusercontent.com/64218283/80603233-c139b980-89f5-11ea-96a4-f5e712e31d7d.png)

This seems like a bug. If not, can you explain the reasoning.

Cory

**Comment by otykier** [comment]
Closing this. Will use #454 to track.
