### ISSUE TITLE
Suppress Data Type Warnings on Schema Check

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#449]
The ability to suppress data type warnings in the schema check would be great. Sometimes we need to explicitly go against the guidance. 

For example, when bringing in latitude and longitude or when absolutely needing float data types due to needing more precision than 4 decimal places.

I know I can ignore them in the BPA, but I don't see a way to suppress these from the schema check. 

Cory Cundy

**Comment by otykier** [comment]
Is this regarding the -SC command line option, or the "Refresh Metadata" UI (or both)?

**Comment by corycundy** [comment]
My post was regarding the -SC command line option. I like this option, however, there is not an ability to ignore, like there is in the BPA. Without this ability, my builds will always contain warnings in DevOps. The data type warning seems to be the one area that I have run across so far that seems reasonable to ignore. Potentially it could be useful to suppress other types of -SC Schema Check warnings as well.


As far as I can tell, everything in the UI BPA can be ignored. I'm not sure how my comments would apply to the Refresh Metadata. My assumption is that when Refreshing Metadata, the BPA results would automatically update.

**Comment by otykier** [comment]
Fixed in [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8).
