### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by sqlenders** [otykier/TabularEditor#451]
Today my boss asked me if she could have documentation of the datamarts.
She can't use Visual Studio or SSMS or the Tabular Editor. 
Can you make an option like Generate Documentation ? 

It would be nice if the output format could be a HTLM, Markdown,  PDF or perhaps Word.

What should be in it :

- List of Tables. It should also state if the table has multiple partitions. 
- List of Columns per Table. Fields should be Column name, Source Column name, data type, calculated column formula, visibility.
- List of calculated fields (measures). Fields should be measure name, visibility and formula. 
- Table of relations (just like in Visual Studio) From table, from field, to table to field, direction/filtering/active 

Other things like connections, perspectives and security. 
Or perhaps measure group calculations.

What do you think ?

**Comment by TheDataViking** [comment]
You can join my session Saturday about automating your documentation on you semantic model. 

“ Everyone know how difficult it is to keep your documentation up to date and available for the business and super users. There is a solution for that and it utilises automated build, Tabular Editor, Jekyll and a website.

As part of this session you will learn how to use Power Shell and information in a SQL Database to automate documentation and insights for your Analysis Services and Power BI Models. This will ensure that business can access business context, security setup and details information on how the solution is build.”

The session will be recorded and you can see more details here in the schedule around 12.45.

[data weekender] (https://www.dataweekender.com/) The conference
[Automate documentation](https://www-dataweekender-com.filesusr.com/html/78f878_e5764ccb94bc435d2d6a97c32f991f13.html) the Session

/Bent

**Comment by otykier** [comment]
This is one of those things where it's incredibly difficult to come up with a "one-size-fits-all" solution. Tabular Editor has a very capable scripting interface, which is perfect for these kinds of scenarios. If someone already has a good script for generating documentation, I encourage you to share it in the new [Tabular Editor Scripts](https://github.com/TabularEditor/Scripts) repository.

From the abstract of Bent's presentation, it sounds like this is exactly what you need.

A simpler solution might be to simple use the [ExportProperties](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#export-object-properties-to-a-file) method, which will output a TSV string of various properties. You can combine multiple types of objects in a call to ExportProperties and it will just output whatever properties are available.

[Example](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#generating-documentation).

Closing this issue, but feel free to open new issues if you have specific questions on how to use any of the existing functionality.

**Comment by zenzeinet** [comment]
Hi Bent,
Any luck you could share the recorded session? I'm very much looking
forward to watching your session, but I find myself unable to find the
recordings at the dataweekender website.
Thanks a lot!
Martin
