### ISSUE TITLE
Refresh MetaData Issue

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#452]
Hello,

Unless I'm not understanding something, I think I found an issue with the Refresh MetaData. I had a column name Semester Number that was originally a varchar in the underlying database. I changed it to an int an clicked Refresh Table Metadata.

The screenshot shows what I would have expected, however, the result from applying the change was a change in the model data type, but not the Source Provider Type. That still said VarChar. I was expecting this to update. Should it have updated?

Because of this, I still receive a warning in the Schema Check.

![image](https://user-images.githubusercontent.com/64218283/80540121-542f1100-896e-11ea-94bd-b7409edbc8e0.png)

Cory Cundy

**Comment by otykier** [comment]
Thanks for reporting. It is indeed a bug that Source Provider Type does not get updated - however, I think you should still be able to refresh the table/partitions, even if Source Provider Type is not alligned with the type on the underlying source.

**Comment by corycundy** [comment]
Daniel, 

Thanks for your quick reply. I agree, despite this bug, the refresh is still functioning fine and I can update the Source Provider Type manually. If you don't catch this, it shows up in the Schema Check. It's good that it shows in the Schema Check, however when this is fixed, it will be one less thing to go back and fix up.

Cory

**Comment by otykier** [comment]
Fixed in [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8).
