### ISSUE TITLE
Cannot list tables from Vertica after making connections

### ISSUE THREAD

**Issue by jayaswalraj** [otykier/TabularEditor#453]
Hi,
I am not able to retrieve list of tables from Vertica. I had entered the server details and tested for connection (which I successfully got through) but in the next step, it does not lists down the tables and views. There is an error popup with message 
"Unable to read list of tables/views from the source: [Vertica][DSI][20032] Required setting 'Database' is not present in the connection settings." 

Please can you advice further.

**Comment by otykier** [comment]
Sorry, I have no experience working with Vertica. Are you using an OLE DB provider to connect? Have you tried specifying the Database in the connection string as suggested by the error message? You can do that by editing the Connection String directly on the data source, or by clicking the "Advanced" button in the Connection dialog:

![image](https://user-images.githubusercontent.com/8976200/80691479-9d977180-8ad0-11ea-9c9e-b4d280d38826.png)

![image](https://user-images.githubusercontent.com/8976200/80691634-d0416a00-8ad0-11ea-9602-920b4092bb3a.png)

After you edit the connection string, try to bring up the Import Table Wizard again, to see if that solves the problem.

**Comment by otykier** [comment]
@jayaswalraj do you have an update on this, or can we close the issue?

**Comment by jayaswalraj** [comment]
Hi,
I am not sourcing any more from Vertca now. Please close the issue.

Regards,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
