### ISSUE TITLE
Importing Table - Mapping Source Data Types to Tabular Data Types

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#454]
Hello,

When importing a table, can Tabular Editor try to imply as best as it can the data type from the source system and map it to the most appropriate tabular data type as Visual Studio does. It appears that an Int32 for Source Provider Type automatically sets the column data type to Integer, but not Int16. I haven't checked the other data types. I'm not sure how complicated this gets when factoring in other data sources aside from SQL Server. Addressing SQL Server data type mapping would be a great start though!

This screenshot is after a new table import.

![image](https://user-images.githubusercontent.com/64218283/80610628-32ca3580-89ff-11ea-80de-c125c73307ae.png)

Cory

**Comment by otykier** [comment]
Good catch, thanks for reporting.

**Comment by otykier** [comment]
Data types are mapped according to [this table](https://github.com/otykier/TabularEditor/blob/d8d26f8619662f1d12eaa6fda3e1bc8c1e06e321/TabularEditor/UIServices/TableMetadata.cs#L196-L274).

Currently known datatypes that do not map correctly:

- datetime2(7) --> String (should be DateTime)
- int16 --> String (should be Int64)

Others?

**Comment by otykier** [comment]
Fixed in [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8).

**Comment by evaverbeke** [comment]
Hi Daniel,

I am currently working in TE 2.16.5, and it seems that datetime2(7) is mapped to String again. 

![image](https://user-images.githubusercontent.com/11046174/151770696-0b91b3b9-026b-4cae-b155-c51116c88cf3.png)

When I try to deploy without changing the datatype to String, I get an error when I try to deploy the model:

![image](https://user-images.githubusercontent.com/11046174/151770835-590d9ba8-4cce-4dfd-a813-3c5d073d7a4c.png)

Would it be possible to look into this?

Thanks!
Eva

**Comment by otykier** [comment]
Hi Eva,

I just tested with 2.16.5, and on my machine, a SQL table with a datetime2(7) column correctly maps to DateTime. Are you sure you are querying the correct table in your tabular model partition? Maybe you are querying the table through a view that alters the data type?

Regarding the issue you face while trying to deploy, you must clear the table before deploying, as values which were already loaded into the table as strings, cannot be automatically converted to datetime values. I.e. run a Clear Refresh on the table before deploying.
