### ISSUE TITLE
PowerBI visual "lost" renamed measures??

### ISSUE THREAD

**Issue by LQ0202** [otykier/TabularEditor#455]
Hi, all:

I have used Tabular Editor to rename a measure from a * .pbit file.
When I open again the file in PowerBI, the visuals "don´t find" the measure and show error.
To solve this, I need to add again the measure.

I think this behavior could be normal. Am I right or is there something I'm not doing well?

Thank you!

**Comment by otykier** [comment]
Tabular Editor can only manipulate the data model - not the report pages/visuals. So if you rename a measure, a column, a table or a hierarchy which is being used in any visual, you will have to manually update the visuals in Power BI Desktop afterwards. No way around that, unfortunately.
