### ISSUE TITLE
Add .csx as an option in the file types for opening Advanced Scripts

### ISSUE THREAD

**Issue by dgosbell** [otykier/TabularEditor#456]
When you click on the open button in the Advanced Script editor the file type defaults to *.cs but in the new script repository (https://github.com/TabularEditor/Scripts) the suggested extension is *.csx

![image](https://user-images.githubusercontent.com/8241830/80785428-91401100-8bc3-11ea-8856-10df78d36d5b.png)

You can work around this by switching to *.* but it would be nice to maybe even default to .cs and csx files.  I'm happy to have a go at this and submit a pull request if you'd like, it should not be too hard to configure.

**Comment by otykier** [comment]
Good catch - I've got a new release coming up shortly and this is a very minor fix, so don't worry about submitting a PR (unless you really want to 😄)

**Comment by dgosbell** [comment]
Nah, that's OK. You can probably fix the issue before I could get my fork updated and find where to make the edit :)

**Comment by otykier** [comment]
Fixed in [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8).
