### ISSUE TITLE
Deployment issue with role member

### ISSUE THREAD

**Issue by datacatsuk** [otykier/TabularEditor#457]
I searched for a similar issue in open tickets but could not find any.

I'm having issues when adding and deploying a new user into the role membership in the model. When deploying I'm getting the error attached. Strange part is, it does not happen all the time. Sometime it happens sometime it doesn't. For example, if I get this error, I use VS to deploy the model. VS deploys successfully. After that, if I use Tabular Editor to deploy, it doesn't fail. 

![image](https://user-images.githubusercontent.com/20473345/80794060-caab5900-8b90-11ea-9319-849ae50be7a0.png)

**Comment by otykier** [comment]
Please see issue #403 . For some reason Visual Studio sometimes fills out the MemberID property, but this is not compatible with AzureAD role members, causing errors when deploying with Tabular Editor. I might be able to provide a fix that causes Tabular Editor to strip the MemberID values in the generated deployment script, for any AzureAD role members, but in the mean time, please remove these values manually/through advanced scripting as shown in the other thread.

**Comment by datacatsuk** [comment]
Thanks a lot for the explanation. Much appreciated. I think the script that removes the MemberID properties will do it for me. I will try that option and close this ticket afterwards.

**Comment by datacatsuk** [comment]
Script is definitely very useful. Keep up the great work.
Thanks again!

**Comment by gflores1023** [comment]
@otykier  I encountered the same issue. As you mentioned VS creates these MemberID properties (example below)
```
{
            "memberName": "first.last@xyz",
            "memberId": "first.last@xyz",
            "identityProvider": "AzureAD"
}
```
But VS is able to successfully deploy. When I script the model on the server, it doesn't have memberId. 

Is there a workaround you can do?

**Comment by datacatsuk** [comment]
You need to run this script below before deploying. Works like a charm, thanks to @otykier.

foreach(var role in Model.Roles)
{
    // Find all Azure AD role members where MemberID is assigned:
    var orgMembers = role.Members.OfType<ExternalModelRoleMember>()
        .Where(m => m.IdentityProvider == "AzureAD" && !string.IsNullOrEmpty(m.MemberID)).ToList();
        
    // Delete the member and recreate it without assigning MemberID:
    foreach(var orgMember in orgMembers)
    {
        orgMember.Delete();
        role.AddExternalMember(orgMember.MemberName);
    }
}

**Comment by gflores1023** [comment]
@datacatsuk I'm aware of that (I linked to it in my comment). I understand that the VS output is maybe incorrect, but my thought process is that if Visual Studio is able to deploy the project successfully, then Tabular Editor should too without workarounds.

**Comment by datacatsuk** [comment]
Sorry, I haven't noticed the link. I suppose that was a request from the developer to add this workaround in the deployment code directly.
