### ISSUE TITLE
Unable to download pbix file after deploying a dataset from Tabular Editor

### ISSUE THREAD

**Issue by Georgy2017** [otykier/TabularEditor#458]
I am unable to download the Power BI Dataset as a .pbix file from Power BI service after deploying the Dataset from Tabular Editor. Any assistance to resolve this is much appreciated.

**Comment by otykier** [comment]
This is a limitation of the PBI Service, so it’s not a Tabular Editor issue: https://docs.microsoft.com/da-dk/power-bi/service-premium-connect-tools#power-bi-desktop-authored-datasets
