### ISSUE TITLE
TabularEditor Commandline cannot connect if password contains quotation mark

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#459]
Hi,

I am using TabularEditor as part of a DevOps pipeline. For a new environment I was given a service account with a strong password. It contains 
- "
- '
- $
-  ;
- =
- `
- \

I have been failing to use TabularEditor with a ". I have been able to reproduce the issue on plain command line.

Let's assume my password is `abcd"abcd`
```
C:\Program Files (x86)\Tabular Editor>start /wait TabularEditor.exe "Model.bim" 
-DEPLOY "asazure://westeurope.asazure.windows.net/xxx:rw" "Finance1_INTf" 
-LOGIN "yyy@zzz.com" "abcd""abcd" -OVERWRITE -CONNECTIONS -ROLES -PARTITIONS

Tabular Editor 2.9.7 (build 2.9.7397.23259)
--------------------------------
Dependency tree built in 401 ms
Loading model...
Deploying...
Deployment failed! The property value containing the '"' character (at index 137 in the connection string) must be enclosed in quotation marks.
```

```
C:\Program Files (x86)\Tabular Editor>start /wait TabularEditor.exe "Model.bim"
 -DEPLOY "asazure://westeurope.asazure.windows.net/xxx:rw" "Finance1_INTf" 
-LOGIN "yyy@zzz.com" """abcd""abcd""" -OVERWRITE -CONNECTIONS -ROLES -PARTITIONS

Tabular Editor 2.9.7 (build 2.9.7397.23259)
--------------------------------
Dependency tree built in 397 ms
Loading model...
Deploying...
Deployment failed! A semicolon was expected at index 139 in the connection string.
```

I have tried many other variants. None had success so far @otykier do you have any idea? Should the code put the sourrouding quotes there, or do I have the chance to pass the correct thing from the commandline?

Thanks a whole lot.

**Comment by fmms** [comment]
I have tried the connection string syntax as well:
```
start /wait TabularEditor.exe "C:\Users\FelixMoeller\source\repos\alfred-beye\Alfred-beye\as-alfredbeye\Model.bim" -DEPLOY "Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/xxx:rw;User ID=yyy@zzz.com;PWD="abcd""abcd";Persist Security Info=True" "Finance1_INTf" 
```

I found the following ideas:
- in ODBC one has to put the password in {} in case it contains any special characters. 
- in OLEDB one has to put the password in quotes if it contains anything special and double all quotes in the connection string
- other sources state that the parsing happens arround the = signs and that they have to be doubled (e.g https://renenyffenegger.ch/notes/development/databases/OLE-DB/connection-string/index )
- wrapping the password in single quotes

I have tried all that and all combinations of it, but no success so far.

The following error messages have been shown so far:
- Deployment failed! An equal sign was expected after index 191 in the connection string.
- Deployment failed! The property value containing the '"' character (at index 165 in the connection string) must be enclosed in quotation marks.
- Deployment failed! A semicolon was expected at index 167 in the connection string.
- Deployment failed! Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.

**Comment by otykier** [comment]
I think you have to escape the double quote [as shown in this post](https://stackoverflow.com/a/7760618/1594867):

```shell
start /wait TabularEditor.exe "Model.bim" 
-DEPLOY "Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/xxx:rw;User ID=yyy@zzz.com;PWD=abcd^"abcd;Persist Security Info=True" "Finance1_INTf"
```

**Comment by fmms** [comment]
I have set the password of an account to `CDEabc"321`

Now my tries:
- whole argument enclosed in double quotes
  - PWD=CDEabc^"321 -> Deployment failed! An equal sign was expected after index 165 in the connection string.
  - PWD='CDEabc"321' -> Deployment failed! An equal sign was expected after index 166 in the connection string.
  - PWD=CDEabc""321 -> Deployment failed! The property value containing the '"' character (at index 160 in the connection string) must be enclosed in quotation marks.
  - PWD=^"CDEabc^"321^" -> Deployment failed! An equal sign was expected after index 165 in the connection string.
  - PWD="CDEabc\"321" -> Deployment failed! The property value containing the '"' character (at index 160 in the connection string) must be enclosed in quotation marks.
  - PWD='CDEabc""321' --> crash of tabular Editor
```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
   at System.Console.WriteLine(String format, Object[] arg)
   at TabularEditor.Program.Error(String errorMessage, Object[] args)
   at TabularEditor.Program.HandleCommandLine(String[] args)
   at TabularEditor.Program.Main()
```
- whole argument enclosed in single quotes
  - PWD=CDEabc^"321 -> Deployment failed! The opening quotation mark (at index 27 in the connection string) requires a closing quotation mark.
  - PWD=CDEabc"321 -> Deployment failed! The opening quotation mark (at index 27 in the connection string) requires a closing quotation mark.
  - PWD="CDEabc""321"  -> Deployment failed! The opening quotation mark (at index 27 in the connection string) requires a closing quotation mark.

Any further idea? Is the exception above expected?

**Comment by otykier** [comment]
How about: `Password='CDEabc^"123'`

**Comment by fmms** [comment]
That results in `Deployment failed! An equal sign was expected after index 172 in the connection string.`

**Comment by otykier** [comment]
Are you able to deploy within Tabular Editor’s UI, by entering the full connection string as the server name?

Try to experiment with the string in the UI until you find the one that works, by quoting the password in various ways (single quotes, double quotes, curly braces, etc)

Then, to convert that string into one you can use from the command line, you should only have to precede any double quotes with `^`.

**Comment by fmms** [comment]
Thanks for your help.

From the GUI is is not working when entering the full connection string. However, it works fine when entering the password in the interactive "experience". It works fine with the same account if I remove the " from the password.

I have by now checked out the source code. It is erroring out on https://github.com/otykier/TabularEditor/blob/e437b8e482864c493bfe399893f31d9bc9341322/TOMWrapper/TOMWrapper/TabularDeployer.cs#L97 even if i hardcode the connection string there... 
So it seems not related to commandline argument escaping but to the parsing that goes on in Microsoft.AnalysisServices.Core ...

**Comment by otykier** [comment]
Ok, thanks for looking into it. Maybe it should be raised as a bug to the Analysis Services team then. I don’t understand why it shouldn’t be possible to have a double quote as part of the password in the connection string.

**Comment by fmms** [comment]
The above pull request fixes this issue for me. The last thing which I could only debug with a self compiled version was that cmd does needs % signs to be doubled. Otherwise they are expaneded. I will now research how to safely do this from Azure DevOps.

If you merge #461 others can benefit from many hours of research. The link that should be the official documentation is at https://docs.microsoft.com/en-us/dotnet/api/system.data.oledb.oledbconnection.connectionstring?view=dotnet-plat-ext-3.1#remarks .

**Comment by otykier** [comment]
Great job! So just to be clear, this lets you deploy using the syntax

```shell
-DEPLOY ServerName Database -LOGIN Username Password
```

but the issue still remains when using

```shell
-DEPLOY ConnectionString Database
```

?

**Comment by fmms** [comment]
Hi Daniel,

this now works in all situations, one only has to know how the escaping works. ;)

Lets take `ab%cd"xy%z` as an example password.

Execunting this from cmd one can either do
```
-DEPLOY "Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/xxx:rw;User ID=yyy@zzz.com;PWD=""ab%%cd""""xy%%z"";Persist Security Info=True"
```
or
```
-DEPLOY ServerName Database -LOGIN yyy@zzz.com "ab%%cd""xy%%z"
```

Thanks
