### ISSUE TITLE
Tabular Editor crashes if Error message contains special characters

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#460]
Hi,

while trying to investigate #459 I found a bug -- I think.

Looking at https://github.com/otykier/TabularEditor/blob/2da0fd2e26938c8efdf36d0ccac66dcff676fb00/TabularEditor/Program.cs#L154

This did not work with my error message that you see below.

Here how to reproduce:
```
                string msg = @"Deployment failed! The JSON DDL request failed with the following error: The 'Name' property cannot contain any of the following characters: . , ; ' ` : / \ * | ? "" & % $ !+ = ( )[ ] { } < >.

Technical Details:
RootActivityId: 08de469b - 3d73 - 4313 - 89ac - f014f1bd84be
Date(UTC): 5 / 2 / 2020 8:21:06 PM";
                Console.WriteLine(msg);
                Console.WriteLine(msg, new object[] { });
```

This was the reason for the crashes I received in #459 which means that the quotation mark should actually be working. Will report back there as soon as I am certain.

Actually this is caused by a bug https://github.com/microsoft/Analysis-Services/issues/51 .

Thanks
Felix

**Comment by otykier** [comment]
Fixed in [2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8).
