### ISSUE TITLE
TOMWRAPPER : additional documentation

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#462]
Hello Daniel,
I checked TOMWRAPPER wiki page but I cannot figure out how to start with it. Is there an additional documentation that I could use as a starter guide ?

By the way, Visual studio complains about a missing file which has been ignored in Github :  daxlexer.cs
Is it on purpose ? 
Thanks in advance for your reply

**Comment by otykier** [comment]
daxlexer.cs is automatically generated when the AntlrGrammars project is built.

You can find some information about TOMWrapper [here](https://github.com/otykier/TabularEditor/wiki/TabularEditor.TOMWrapper). Unfortunately, it's a bit outdated, and there's no other documentation available. I'm sorry, but I just don't have the time to invest in updating and improving the documentation at this time - there's a huge backlog of features and bugfixes that are more important.

**Comment by didierterrien** [comment]
Thank you, it makes sense and sorry for disturbing.
I think I'd better wait for "public API for developers" as it is in the roadmap. Do you have any clue about the date it will begin to be available ?

**Comment by otykier** [comment]
I'm afraid it's not something that will ship this year.

But please - if you have specific questions on the TOMWrapper, feel free to open issues here.
 
The ultra-short introduction to what the TOMWrapper is that it is a library that wraps most of the stuff in [AMO/TOM](https://docs.microsoft.com/en-us/analysis-services/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo?view=asallproducts-allversions), and provides some more convenient methods for doing various things, as well as providing DAX dependency detection, etc. Before you start to work with TOMWrapper, make sure you understand and preferably have some experience with working with AMO/TOM (which have some pretty good documentation - see link above).

Then, when you're ready to use TOMWrapper, you can try the following to get started. I recommend you compile TOMWrapper using Tabular Editor's source code, as you then also get the .xml file which will enable IntelliSense in VisualStudio to show the XMLDOC comments in the TOMWrapper source code:

![image](https://user-images.githubusercontent.com/8976200/80915304-bd899800-8d51-11ea-88d7-bfee1f1b2ff3.png)

The code below illustrates how to create a model.bim file from scratch with TOMWrapper. Hopefully it's enough to get you started:

```csharp
// Create a blank model:
var handler = new TabularModelHandler(1500); // Compatibility Level 1500
var model = handler.Model;

// Add a table with some columns:
var newTable = model.AddTable("New table");
newTable.AddDataColumn("Column1", "SourceColumn1");
newTable.AddDataColumn("Column2", "SourceColumn2");

// Save as a .bim:
handler.Save("c:\Temp\Model.bim", SaveFormat.ModelSchemaOnly, SerializeOptions.Default);
```

**Comment by didierterrien** [comment]
Thank you, very clear ! I could start with it
Is it possible to discover the available connections like you do feeding the connections lists in the "Connect to tabular server" screen ?

**Comment by didierterrien** [comment]
I've found out this is not a function of TOMWRAPPER. The class used is in PowerBIhelper.cs which seems to be a part of DAX studio.
I close the issue
