### ISSUE TITLE
Release path

### ISSUE THREAD

**Issue by anvtitte** [otykier/TabularEditor#465]
This is a request, not an actual issue. Is it possible to create a path/folder named "latest" or "current" to always get the latest release of tabular editor?

Currently, we use this to get the latest version. As there are new releases, we have to remember to go change this manually.

https://github.com/otykier/TabularEditor/releases/download/2.9.8/TabularEditor.Portable.zip

Instead, something like this where the latest release is always available in a folder. Thereby eliminating the need to hard code the version.

https://github.com/otykier/TabularEditor/releases/download/current/TabularEditor.Portable.zip

Thank you.

**Comment by otykier** [comment]
I believe this is already possible:


https://github.com/otykier/TabularEditor/releases/download/latest/TabularEditor.Portable.zip

**Comment by fmms** [comment]
Just for anyone else the link above contains a bug for me only the following is working https://github.com/otykier/TabularEditor/releases/latest/download/TabularEditor.Installer.msi e.g. latest and download have to change the order.
