### ISSUE TITLE
Add instructions how to load translations from command line 

### ISSUE THREAD

**Issue by TePeBoxer** [otykier/TabularEditor#466]
Hi,

would like to see how to build a script (with the appropriate command line) that loads a translation file (the JSON) and deploys it to the model... I guess that's something a lot of people might use for deploying translations until there's a functionality for that in the Power BI UI :-)

Thanks...

**Comment by otykier** [comment]
This is an interesting scenario that I hadn't thought about. Unfortunately it's not documented and there's no intellisense in the script editor to help you, but it can be done using a C# script:

```csharp
// Save all translations to JSON file:
SaveFile(@"c:\Test\translations-all.json", Scripter.ScriptTranslations(Model, Model.Cultures));

// Save specific translation to JSON file:
SaveFile(@"c:\Test\translations-DK.json", Scripter.ScriptTranslations(Model, Model.Cultures.Where(c => c.Name == "da-DK")));

// Import translations:
var json = ReadFile(@"c:\Test\translations-DK.json");
TabularCultureHelper.ImportTranslations(json, Model, overwriteExisting: true, haltOnError: false);
```

To execute this from the command line you have to save this script to a file, which you can then execute from the command line with the -S switch. Now unfortunately, the script hard codes the names of the JSON files, so one option is to generate the script on the fly on the command line:

```shell
echo TabularCultureHelper.ImportTranslations(ReadFile(@"c:\Test\Translations-DK.json"), Model, true, false); >> ImportTranslations.cs
start /wait TabularEditor "localhost" "AdventureWorks" -S ImportTranslations.cs -D "localhost" "AdventureWorks" -O
```

The first line generates the script that imports a translation from the specified file. The second line calls Tabular Editor, loads an existing model from a server/database name, applies the scripts and performs a deployment.

If you're executing this from a DevOps pipeline you can substitute the name of the json file as well as the "localhost" and "AdventureWorks" strings with variables.

Hope this helps!

**Comment by TePeBoxer** [comment]
Sounds great! I'll give it a try, soon!. One further question might be how to create an initial translation file... As far as I understand in your tool you can only export an existing translation, modify it and upload it again. I didn't find any way how to create a new one besides modifying the JSON manually... Did I miss something? This is a special situation for Power BI users, in Visual Studio it's just easy...

**Comment by otykier** [comment]
Sure - that's easy to script as well:

```c#
// Add a danish translation:
Model.AddTranslation("da-DK");

// Save to file:
SaveFile(@"c:\Test\translations-DK.json", Scripter.ScriptTranslations(Model, Model.Cultures.Where(c => c.Name == "da-DK")));
```

Again, if you need to run this from the command line and would like to avoid hard-coding the language (da-DK), you have to generate the script on the command line. See [here](https://stackoverflow.com/a/23530712/1594867) for instructions on how to output multiple lines of text to a file from the command line.

**Comment by TePeBoxer** [comment]
You're great! Very much appreciated! Will try it later!

**Comment by TePeBoxer** [comment]
I already asked Christian Wade about his point of view about that but probably you have your own opinion about that... 
Using Tabular Editor I can now easily add a translation to a Power BI model. If I would like to deploy this model to different workspaces I can now use the typical methods to do so and add translations after that via Tabular Editor. So far so good. 
What would make things even easier would be if the model itself can save the translations. So I thought about is loading the model into PBI desktop, then adding the translation via Tabular Editor and save the file to deploy it later. I saw the warnings about TOM and so I was hesitant to proceed. What do you think?

**Comment by otykier** [comment]
For now, I wouldn't do that. You may encounter weird errors and crashes when you add translations to a model loaded in Desktop, which is the reason we're showing this warning. Later this year, however, Desktop will fully support translations that were added externally, at which point you can safely use the approach you described.

**Comment by didierterrien** [comment]
Hello TePeBoxer,
We probably have the same issues than you.
I would like to know how you will manage the translations. Will you modify the JSON file directly ? Will you do it by yourself or will you send it to different translators ? Do you have any plans for the translations maintenance after creation of new tables/columns/measures/display folders/ ... and after their modifications ?
Didier

**Comment by TePeBoxer** [comment]
Didier,
very relevant questions and we're just starting to think about that... 
I guess we're just early in the process, tools are not fully aligned here (i.e. PBI Desktop not supporting translations, PBI Service not offering Object Level Security, VS not supporting PBI roles, ...), as soon as that happens (I hope in the timeframe of XML/A R/W GA) at least some of your questions would be solved. I think a good practice is to have just a single language per JSON so you can send it to different developers. 
As soon as PBI Desktop will support translations that will be easier (no import/export of JSONs anymore) but also more complicated (only a single user can work with it). So still Visual Studio might play a role (or out much beloved Tabular Editor). 
Translation management needs to be an integrated part of the model development, as it was before. Well, an organizational challenge... I'm not aware of a tool which makes you aware of not-fitting or missing translations...

Thomas

**Comment by didierterrien** [comment]
Thomas,
Yes we are early but we waited for such a long time for translations. If we want to increase the adoption of our reports, we reach a population who doesn't understand correctly english. Some confusions may happen so for me it's an important topic and I don't want to wait more. I didn't hear about any possibility to translate models or visuals within the desktop in the near future. I think Power BI team relies on external tools to progress on this topic. 

To be precise, Power BI desktop already uses translations we input in tabular model through Tabular editor. It even works without the new preview option about XMLA endpoint. But, for the moment, it is not recommended at all to deploy it in production. We just need to wait a few months so I try to get prepared making a lot of tests.

Translations management is an important process. I have a quite a precise view how I will manage it. It will involve IT teams and business teams who will not accept to use a JSON file. I suggest you have a look at this short video. Your comments/critics/ideas will be very welcome.
      https://thebipower.fr/index.php/2020/04/12/automatic-translation-of-tabular-model/

I'm available for further discussions around translations management but I don't know if it is the right place for that.

Daniel's opinion would be precious also. 
Didier

**Comment by TePeBoxer** [comment]
Didier,

cool stuff... Question would be if it's possible to integrate this into a DevOps pipeline as well, so can we use command lines to apply custom scripts? But nice stuff you presented! Anyway modifying the internal .pbix file wouldn't be something I would do right now due to what Christian Wade gave me as feedback... However it might be a great option in the future...

Thomas

**Comment by otykier** [comment]
@didierterrien and @TePeBoxer - feel free to use this thread for discussion.

> I'm not aware of a tool which makes you aware of not-fitting or missing translations...

You can use Tabular Editor's Best Practice Analyzer to detect if any objects are missing translations! These rules are already part of the standard rules collection [found here](https://github.com/TabularEditor/BestPracticeRules).

To load these rules into your model, go to Tools > Manage BPA Rules. Here is the direct URL to the standard rules JSON file on GitHub:

```
https://raw.githubusercontent.com/TabularEditor/BestPracticeRules/master/BPARules-standard.json
```

To link this file directly in your model, click "Add..." and then "Include Rule File from URL". Then paste the URL above into the textbox and click OK. Alternatively, you can download the file and merge it into your `%localappdata%\TabularEditor\BPARules.json%`-file, to ensure that the rules are always applied to any model you load on your machine. More information [here](https://github.com/otykier/TabularEditor/wiki/Best-Practice-Analyzer-Improvements).

Once the rules are imported, you should see them appear in the UI:

![image](https://user-images.githubusercontent.com/8976200/82155663-d8dac400-9876-11ea-8e72-d21e6c0e54ed.png)

When you click OK, Tabular Editor will show the count of objects that are in violation of best practice rules at the bottom of the screen. Clicking the link will bring up the Best Practice Analyzer that shows you the list of objects in violation. You can double-click an object to navigate directly to it.

![image](https://user-images.githubusercontent.com/8976200/82155721-42f36900-9877-11ea-8059-a4459042e1b9.png)

Note, there are many other rules in the JSON file provided above. If you don't need the Best Practice Analyzer for anything other than ensuring translations are applied, feel free to disable these other rules as you see fit.

> if it's possible to integrate this into a DevOps pipeline as well, so can we use command lines to apply custom scripts?

Well, absolutely! Use the -S option for executing a script through the command line (provide the path of a text file containing the script after the -S switch).

**Comment by tepebox** [comment]
Sorry, being far from a DevOps expert... Is my understanding correct that when I would use something like Azure DevOps we would run into an issue because there's no way to install Tabular Editor on a build server, so I can't deploy my languages? The only solution I would see then is to import the languages, then create some XMLA out of that using Tabular Editor and then deploy it from Azure DevOps?

**Comment by otykier** [comment]
It's easy to use Tabular Editor in an Azure DevOps pipeline. Simply include a PowerShell step that downloads it before the step where you actually want to use Tabular Editor. This technique is described [here](https://tabulareditor.com/2019/10/08/DevOps3.html#tabular-editor-on-microsoft-hosted-agents) (if you're using a self-hosted build agent, you can just pre-install Tabular Editor on that agent). Not sure how this would work with CI/CD offerings other than Azure DevOps, but I guess most of them have similar options for executing a script that would download and install software.

**Comment by otykier** [comment]
Closing this thread to clean up the backlog of issues, but feel free to open new issues if you have any further questions!
