### ISSUE TITLE
Question: Can script copy a measure and change the measurename referenced in the expression

### ISSUE THREAD

**Issue by ravip27** [otykier/TabularEditor#467]
This is more a question. I know we can copy a measure using scripting to create another measure. The question I have if the measure being copied has reference to other measurename is it possible to replace the referenced measurename with another measurename? I have a need where I need to create a new measure based on another measure and keep the expression same except for the called measure within the measure. This is a good candidate for Calculation Group but unfortunately we are still on 2017 Analysis service and cannot leverage this feature.

**Comment by otykier** [comment]
Great question!

Provided you don't have any columns that have the same name as any measures in the model, you can simply use string `.Replace()`, as measure references are all in square brackets. So something like this:

```csharp
var oldMeasure = Selected.Measure; // ...or Model.Tables["MyTable"].Measures["OrgMeasure"];
var newMeasureName = "Copied measure";
var otherMeasureName = "Other measure";
var otherMeasureNameReplace = "Other measure replaced";

var newMeasure = oldMeasure.Table.AddMeasure(
    newMeasureName,
    oldMeasure.Expression.Replace("[" + otherMeasureName + "]", "[" + otherMeasureNameReplace + "]"),
    oldMeasure.DisplayFolder
);
newMeasure.FormatString = oldMeasure.FormatString;
```

If you feel using string replace is too much of a hack, there's also a more advanced version of this, where you call the `.Tokenize()` method on the measure. This will return a list of [DaxToken objects](https://github.com/otykier/TabularEditor/blob/master/TOMWrapper/Utils/DaxToken.cs) each one having a specific [type](https://github.com/otykier/TabularEditor/blob/master/TOMWrapper/Utils/DaxToken.Generated.cs). The `DaxToken.COLUMN_OR_MEASURE` indicates a column or measure reference in the DAX expression. You can then use the `.Text` property of the token to determine the name of the object being referenced, and see if it is one of those names that needs replace. Each token also holds the start- and end character index that indicates where the token occurred in the original DAX expression. Putting all this information together, it is possible to write code that loops through the DAX expression and replaces only the relevant tokens with the updated references. At the end of the day, all of the above is what Tabular Editor's automatic formula fix-up does every time you change the name of an object. So why not simply utilize formula fix-up to perform the DAX code changes for us?

```csharp
var oldMeasure = Selected.Measure; // ...or Model.Tables["MyTable"].Measures["OrgMeasure"];
var newMeasureName = "Copied measure";
var otherMeasureName = "Other measure";
var otherMeasureNameReplace = "Other measure replaced";

var otherMeasure = Model.Tables["MyTable"].Measures[otherMeasureName];
var otherMeasureReplace = Model.Tables["MyTable"].Measures[otherMeasureNameReplace];

// Temporarily rename [Other measure] and [Other measure replaced]:
otherMeasureReplace.Name = "__" + otherMeasureNameReplace;
otherMeasure.Name = otherMeasureNameReplace;

// Now, the expression of [OrgMeasure] holds the modified DAX that we need for our new measure:
var dax = oldMeasure.Expression;

// Revert the name changes:
otherMeasure.Name = otherMeasureName;
otherMeasureReplace.Name = otherMeasureNameReplace;

// Create the new measure using the DAX we extracted above:
Model.Tables["MyTable"].AddMeasure(newMeasureName, dax);
```

Let me know if you have any further questions.
