### ISSUE TITLE
Best practices to create the simplest table in Tabular Editor

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#468]
Hello Daniel,
I wrote a script to generates measures to be used in visuals conditional formating in order to translate 
visuals labels (title, ...). It reads a tsv file which contains the measures list.
I added it in the scripts repository in the intermediate folder (Create visuals translations measures.csx).
In this script I create a table to host the measures. I created a calculated table because I got some issues when I created a table. What are the best practices to create the simplest table in Tabular Editor scripts ? I couldn't find an example.
Regards

**Comment by otykier** [comment]
Great job with the script!

I would use a calculated table for this purpose, with a DAX expression such as `{0}`, which would result in a 1x1 table with a column named "Value". This is easy to set up in a script, however if you want to hide the column, you need to manually add that in the script, as Tabular Editor doesn't parse the DAX expression to figure out which columns are inferred:

```csharp
// Create a calculated table with a single column which is hidden:
var table = Model.AddCalculatedTable("Model Measures", "{0}");
var column = table.AddCalculatedTableColumn("Value", "[Value]", "", DataType.Int64);
column.IsHidden = true;
```

Feel free to reopen this if you have any further questions.
