### ISSUE TITLE
Find and Replace Dialog Hangs When Moving Between Columns

### ISSUE THREAD

**Issue by saviourofdp** [otykier/TabularEditor#469]
Using version 2.9.8

1. Select a calculated column
2. Click to focus the expression pane 
3. Press <kbd>Ctrl</kbd>+<kbd>H</kbd> to bring up Find & Replace dialog
4. Enter find / replace strings and Replace All
5. Select another column in the same table _without closing the dialog_
6. Click Replace All again
7. Select another column in the same table _without closing the dialog_

The Find & Replace dialog hangs as described in #103. I _think_ the problem is that the 

> _N_ occurance(s) replaced

report appears behind the Find & Replace dialog, rendering the OK button unclickable.

**Comment by otykier** [comment]
@saviourofdp thanks for reporting - indeed you are correct. When I follow your steps to reproduce, I found that I can hover over the Tabular Editor application icon in the Windows task bar, and this causes the "n occurances(s) replaced" dialog to show up, after which I can close it and continue working. But this is indeed a bug that I'll look into.

**Comment by otykier** [comment]
Fixed in [2.10.0](https://github.com/otykier/TabularEditor/releases/tag/2.10.0)
