### ISSUE TITLE
Unable to download pbix dataset after deploying with TabularEditor

### ISSUE THREAD

**Issue by Yacetin** [otykier/TabularEditor#470]
Hi,

My first need is to deploy a .bim SSAS (on premise) model file on PowerBI Online if possible, if impossible, I need to create a new dataset with TabularEditor stored on PBI Online.

After creating or modifiying and deploying a dataset stored in PowerBI Online using TabularEditor, an error message pops up while trying to download the modified dataset:
![export issue](https://user-images.githubusercontent.com/65174264/81570331-bf320c00-93a0-11ea-8d2a-3d45b8518016.png)

After discussing with MicroSoft, they told that there is a flag which is defining if the dataset is exportable, maybe it can help

Regards.

**Comment by otykier** [comment]
Please see the warning in the [documentation](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#power-bi-desktop-authored-datasets).
