### ISSUE TITLE
Azure DevOps Pipeline - loop data sources to set connection string

### ISSUE THREAD

**Issue by anvtitte** [otykier/TabularEditor#471]
In your blog post, https://tabulareditor.com/2019/10/17/DevOps4.html, you have a tabular editor script to loop through the data sources. Two questions:

1. In the script there is a call to _Environment.GetEnvironmentVariable()_ function. Is there a way to access the package variables instead? In a scenario, we are using the Azure Key Vault package to retrieve the secrets instead of embedding it in the pipeline and environment variables. In other words, the environment variable has to be created on the fly.

2. The script sets the ConnectionString property of the dataSource. But this doesnt work for M query based connections. Any guidance on how to handle this? Trying to set the connection string results in this error in DevOps.

**##[error]Deployment failed! The JSON DDL request failed with the following error: The 'Name' property cannot contain any of the following characters: . , ; ' ` : / \ * | ? " & % $ ! + = ( ) [ ] { } < >.**

Thank you.

**Comment by otykier** [comment]
1. When you write "package variables" did you mean the pipeline variables? To my knowledge, there is no way Tabular Editor can retrieve these values other than transferring them into the command line task as environment variables, as shown in the blog. When you transfer the variables using the command-line task UI as shown in the bottom of the figure below, the environment variables are only available for the duration of the command-line task. Also, they are not logged anywhere, so there is no risk of leaking sensitive data:
![image](https://user-images.githubusercontent.com/8976200/81776925-0e3a8700-94f0-11ea-8710-1c31f5eb4cbc.png)
2. I don't have much experience working with Power Query data sources. I'm afraid you'd have to do some testing with VS/SSDT and then inspect how the various data source properties look like when pointing the source to various environments, for example by scripting the data source using SSMS after deployment. Then, adapt your script to set the properties to identical values with Tabular Editor. I'm afraid there's some trial and error involved.

**Comment by fmms** [comment]
Hi, the error message in the original issue is most probably related to an AS bug https://github.com/microsoft/Analysis-Services/issues/51

**Comment by otykier** [comment]
Thanks for pointing that out @fmms. However, in OP's case it sounds like the error only occurs when modifying Power Query data source properties through a script during deployment. @anvtitte - can you confirm that none of the database names on the server you're deploying to contain any of the mentioned characters, as Christian Wade suggests in the other thread?
