### ISSUE TITLE
Translated Names property problem Power BI Desktop

### ISSUE THREAD

**Issue by varayalagos** [otykier/TabularEditor#472]
Hi!

I know this is not supported by Power BI Desktop, but I am using it anyway to create measures in a much faster way. By doing this I found that the "Translated Names" property for each measure need to be blank in order to work fine in Power BI Desktop. I found these issues so far:
1) Different measures names in modeling view and in report view
2) Can not rename a measure
3) Not allowing me to delete a table

Based on this, is there a way to do something like:  AllMeasures.TranslatedNames  = "" ;  ?

**Comment by otykier** [comment]
You almost nailed the script. Use this code:

```csharp
Model.AllMeasures.ForEach(m => m.TranslatedNames.Reset());
```

**Comment by varayalagos** [comment]
![Duda Tabular Editor](https://user-images.githubusercontent.com/64966969/82600161-7554dd00-9b7b-11ea-9263-b80d5ae0d267.png)

Daniel,

I have tried your code several times: Model.AllMeasures.ForEach(m => m.TranslatedNames.Reset());
But it is giving me the error you see in the photo. I am using windows 10, regional settings from Chile (español).
 
Hope you give us some guide about how to make it run. It would be so useful to solve this issue for our work.

**Comment by BM4291** [comment]
@varayalagos - I get the same error when trying to follow this step and have made a separate issue #474 perhaps we're trying to do the same thing?

**Comment by otykier** [comment]
Sorry - there was an error in the script I provided. Here's a version that works:

```csharp
Model.AllMeasures.ToList().ForEach(m => m.TranslatedNames.Reset());
```
