### ISSUE TITLE
Not sure how to use Schema Check

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#473]
Hi guys, Schema Check sounds like a good idea to run as part of our CICD pipeline, but I can't get it to work

I run 

```
TabularEditor.exe 'asazure://westeurope.asazure.windows.net/ourserver' 'ourdatabase' -schemacheck -login 'user@domain.com' 'password' 
```

and many other permutations with/without quotes etc and I always get 

> Error loading model: Authentication failed: User ID and Password are required when user interface is not available.

In the Command Line docs it seems like -L is only part of the -Deploy function, not the SC is that the problem? Is there another way to provide the login/pass

It seems only sensible for us to use this once we have deployed the cube & database as it is only then that schemacompare has a real connection with authentication details. 

What am I missng?

**Comment by otykier** [comment]
`-schemacheck` uses the credentials stored in the data sources inside the model metadata (if available). It only works for OLE DB/ODBC data sources. Please note that AS masks any sensitive information in the data sources when the model metadata is loaded from AS. There is no way for Tabular Editor to obtain the authentication details stored in the deployed database (that would be a major security breach in AS...), so you'd need to run a script as part of the command line using the `-s` or `-script` switch, to specify the proper data source credentials to be used for the schema check. For this reason, you might as well consider running the schema check on your Model.bim or Database.json files before actually deploying the model, as you would need to set the credentials either way.

If you're using Azure DevOps, I have a [blog post here](https://tabulareditor.com/2019/10/17/DevOps4.html#step-2---schema-check) that shows how to run a script that does just that, by passing the credentials to the script using environment variables.

However, the error message you're seeing seems to be related to Tabular Editor not being able to load the model metadata from the specified server. You're right that the `-L` option is only valid for deployment. There is no corresponding switch for connecting to AS when loading the model metadata. Instead, specify the full connection string in the first argument, as described [here](https://github.com/otykier/TabularEditor/wiki/Command-line-Options#connecting-to-azure-analysis-services). But again - you may not need this, as the data source will not contain any authentication details when the model metadata is loaded from Azure AS.

Let me know if you have any further questions.
