### ISSUE TITLE
Copy tables between pbix?

### ISSUE THREAD

**Issue by LQ0202** [otykier/TabularEditor#475]
Hello:

I have a pbix with a single table. It is a calendar table.
I get this table by executing an M script in Power Query (inside this pbix file).

Once the script's calendar table has been obtained, with Tabular Editor, I format and organize the columns in folders, I create hierarchies, I hide columns ...

My question is how to reuse this table in other pbix files.
An option could be to start the new pbix from this file. If I dont´t need this table (in this case a Calendar Table) I always can delete it. 

Can I copy and paste the Calendar Table between pbix files? Everything will remain  (Power Query queries, M script, hierarchies...)?

It is this way, a way designed to be done with Tabular Editor to be able to copy tables between pbix and increase productivity in the creation of new models.

ALLWAYS thank you!!

**Comment by marcosqlbi** [comment]
I'm not sure whether the M script is correctly copied - I am sure that it works if you use a calculated table in DAX; because it is what I usually do with the DAX Date Template: https://www.sqlbi.com/tools/dax-date-template/
If I have a model with a different date table, I do this:
- Save the PBIX file as a PBIT file
- Open the PBIT file in Tabular Editor
- Open the Date Template in another instance of Tabular Editor
- Copy the Date table from Date Template to the PBIT model
- Save the PBIT file from Tabular Editor
- Open the PBIT file in Power BI Desktop

Maybe it already works with M script, maybe not. You can also get this behavior by moving your code to a calculated table in DAX, of course.

**Comment by LQ0202** [comment]
Hi Marco:

Thank you very much for your always prompt answer.

Before doing the calendar table in Power Query with M, I read https://www.sqlbi.com/tools/dax-date-template/. It has been a very useful source for me and I have taken it as a reference. However, the DAX expression is getting too big/complex for me and my DAX knowledge still doesn't allow me to confidently edit and customize it as I would like. I would like to know much more DAX and I am in it, but it is a slow and long path... (https://www.sqlbi.com/articles/a-proposal-for-visual-calculations-in-dax/).

I want to have a calendar table that I can edit and modify if necessary. In M it has been very easy for me to make the table and I have full control of what it does.

Let's see if anyone confirms that my solution with M script works.

With tabular editor is it a necessary step to save the file as pbit or can I work with the pbix file?

ALLWAYS thank you!!

**Comment by marcosqlbi** [comment]
Working with the PBIT is safer at the moment. You can corrupt the PBIX because it is not supported, yet.

**Comment by otykier** [comment]
Closing this. We expect that Power BI will support adding calculated tables from external tools like Tabular Editor in the future, at which point we will have full support for copy-pasting calculated tables between PBIX files loaded in Desktop.

**Comment by bogomda** [comment]
Daniel, will Tabular Editor 3 support copy/paste of tables (not calculated tables) from one PBIX to another PBIX?

**Comment by otykier** [comment]
This is not a limitation of Tabular Editor but of Power BI Desktop, which does not support external tools adding/modifying tables. You can try to experiment with exporting your pbix as a pbit file, then open that file in Tabular Editor and paste a table into it. Then, save the file and open it back in Power BI Desktop. Sometimes it works, but there are no guarantees.
