### ISSUE TITLE
PBI Premium XLMA deployments

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#476]
Add the **defaultPowerBIDataSourceVersion** property within the Model properties so that one can deploy and overwrite existing pbi premium datasets via tabular editor. currently have to add this property in the .bim file in a text editor and then it can be deployed via tabular editor.

Here's an example of the property with a valid setting:

"compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,

**Comment by otykier** [comment]
Thanks for reporting. Just to make sure I understand the use case here: Is this when creating a model from scratch using Tabular Editor? My understanding is that this property would already have been set if you enable the "enhanced metadata preview" feature on your model (if you don't enable it, XMLA read/write should not be possible).

**Comment by kalmenk** [comment]
Exactly. I created a model in tabular editor (from scratch), deployed it to power bi premium and received an error on deployment (that the model ID didn't exist) although it worked. when i went to redeploy the same model to overwrite the dataset in power bi premium it gave me an error regarding the defaultPowerBIDataSourceVersion. I put this into the .bim file and then it deployed successfully, overwriting the existing dataset in the premium workspace.

**Comment by otykier** [comment]
Thanks! I'll make sure to expose the property so it can be edited. In fact, when creating a new model through File > New Model..., you get a list of Compatibility Level options. I'll throw "Compatibility Level 1520 (PBI Premium Dataset)" in there as well, and make sure the property is already set to `powerBI_V3` when Tabular Editor creates this kind of model.

Question: Are you adding legacy or power query data sources to this model? Are you facing any issues with these data sources when refreshing them in the service?

**Comment by kalmenk** [comment]
Ah, that is perfect. Goal is to be able to do the full development of premium models in tabular editor - from start to prod. once this is enabled, it is possible and I recommend it.

i've only been using legacy data sources. haven't had any issues refreshing (just refreshed it in the service with a small model).

**Comment by kalmenk** [comment]
and to confirm, this property will also be able to be added programatically via advanced scripting, correct?

**Comment by otykier** [comment]
Yes, once it's available in the UI, you can set it through scripting as well.

**Comment by otykier** [comment]
Fixed in [2.10.0](https://github.com/otykier/TabularEditor/releases/tag/2.10.0).

**Comment by kalmenk** [comment]
Thanks so much! Just one thing - haven't been able to change this property in advanced scripting - below is what I tried but it doesn't work. what is the correct syntax?

Model.DefaultPowerBIDataSourceVersion.PowerBI_V3;

**Comment by otykier** [comment]
```csharp
Model.DefaultPowerBIDataSourceVersion = PowerBIDataSourceVersion.PowerBI_V3;
```

**Comment by kalmenk** [comment]
fantastic, thanks!

**Comment by Dayanjun-data** [comment]
> Exactly. I created a model in tabular editor (from scratch), deployed it to power bi premium and received an error on deployment (that the model ID didn't exist) although it worked. when i went to redeploy the same model to overwrite the dataset in power bi premium it gave me an error regarding the defaultPowerBIDataSourceVersion. I put this into the .bim file and then it deployed successfully, overwriting the existing dataset in the premium workspace.

Hello, how to "put this into the .bim file", can you post a picture? Thanks~

**Comment by m-kovalsky** [comment]
@Dayanjun-data you have 2 options.

1. Run the following script in the Advanced Scripting window : Model.DefaultPowerBIDataSourceVersion = PowerBIDataSourceVersion.PowerBI_V3;
2. Click on the Model in the Object Explorer (left pane), navigate to the properties window, and set the property as highlighted in the screenshot below.

![image](https://user-images.githubusercontent.com/29556918/116793727-1a3ca180-aad1-11eb-9df3-6b973c2a508b.png)

**Comment by BrundaLanka** [comment]
> ```cs
> Model.DefaultPowerBIDataSourceVersion = PowerBIDataSourceVersion.PowerBI_V3;
> ```

Hi, I have used the above command in C# script and executed it through command line and tabular editor, its getting succeeded but the changes are not getting reflected when I tried to deploy the bim file. Any insights here please?

**Comment by otykier** [comment]
@BrundaLanka what is the CLI command you used to run the script? Did you include the `-B` switch (which will save the .bim file), or the `-D` switch (to perform a deployment)?

**Comment by BrundaLanka** [comment]
Hi

Thank you for the prompt response.

I have used the below command to run script , I wanted to just update the bim file and use the same file to deploy

  *
      TabularEditor.exe "my bim file"  -S "script file"  -V -W -E -O -C -P


And used the below for deployment.


  *
TabularEditor.exe "my bim file" -D "powerbi workspace" "DBname" -O -C -P -V -E -W

Thanks
Brunda
________________________________

**Comment by otykier** [comment]
@BrundaLanka right - so the first command you used,

`TabularEditor.exe "my bim file"  -S "script file"  -V -W -E -O -C -P`

...will not actually update the .bim file, since you didn't specify the `-B` switch, which explains why you don't see the change after deploying. Change this command to:

`TabularEditor.exe "my bim file"  -S "script file"  -V -B`

(note, the `-W`, `-E`, `-O`, `-C` and `-P` switches are only used when deploying, i.e. following the `-D` switch).

https://docs.tabulareditor.com/te2/Command-line-Options.html

**Comment by BrundaLanka** [comment]
Hi

Thank you for the prompt response .

I changed the command  as given below, and it says as deployment succeeded.


  *
TabularEditor.exe "my bim file" -S "script file"  - D "Provider=MSOLAP; Data Source=MyWorkSpace;Password=####" "DBName"  -O -C -P -V -E -W -P -R

but if my bim file name and DB name are same its not actually deploying and if I change the DB name to some thing else its working. Request you to please let me know if I am missing anything or doing anything wrong. Your help is greatly appreciated.

Thanks,
Brunda
________________________________

**Comment by otykier** [comment]
You have the `-P` switch specified twice, and you have a space between `-` and `D`. Also, the order of the switches matter. `-V` is not related to deployment, and should come *after* `-E` and `-W`, or before the `-D`. Recommend changing your command to:

```cmd
TabularEditor.exe "my bim file" -S "script file" -V -D "Provider=MSOLAP;Data Source=MyWorkSpace;Password=####" "DBName" -O -C -P -R -E -W
```

**Comment by BrundaLanka** [comment]
Hi , thank you for a very quick response, as suggested I made the changes to my command as given below, but Overwrite functionality is not working, its only working whenever I give a new DB name. Any suggestions please

TabularEditor.exe "my bim file" -S "script file" -V -D "Provider=MSOLAP;Data Source=MyWorkSpace;Password=####" "DBName" -O -C -P -R -E -W

Thanks
Brunda

**Comment by otykier** [comment]
What is the output you’re seeing when running this command?

**Comment by BrundaLanka** [comment]
Hi

When I give same DB name to overwrite it is giving output like below but DB is not getting refreshed.

Tabular Editor 2.25.0 (build 2.25.8952.22276)
--------------------------------
Loading model...
Loaded script: D:\a\_work\1\updateVersion.cs
Executing script 0...
Deploying...
Deployment succeeded.


When I give a new DB name , output is like below and DB with new name is getting deployed. I even checked service connection permissions, it has read & write access to all power bi services

Loading model...
Loaded script: D:\a\_work\1\updateVersion.cs
Executing script 0...
Deploying...
Deployment succeeded.
##[warning]Information: Unprocessed object: partition 'Partition' on table 'XXXXXXXXX' (NoData)
##[warning]Information: Unprocessed object: partition 'Partition' on table 'XXXXXXXXXX' (NoData)
##[warning]Information: Unprocessed object: partition 'Partition' on table 'XXXXXXXXXx' (NoData)

Thanks,
Brunda


________________________________

**Comment by otykier** [comment]
I’m sorry, but I think there is some kind of misunderstanding. In both these cases, the metadata is successfully deployed. The reason you’re not getting a warning about unprocessed objects in the first case, is that you did not deploy any changes to the model which caused data to be dropped, requiring a data refresh. Why don’t you do a simple test: Add a new measure to your model.bim file, then run the command again. You should see that new measure in the existing DB, after the command has finished running. 

In general, you don’t need to perform any data refresh when making simple changes such as adding or modifying measures, descriptions, or various model-level settings. However, if you add tables or columns, or if you modify relationships or calculated tables/calculated columns, then you’ll see the warning about unprocessed objects after deploying, and then you’ll need to perform a refresh before users can query the model.

**Comment by BrundaLanka** [comment]
Got it, thank you for the quick responses. As suggested, I did some small change in measures, and it reflected in semantic model though it doesn’t seem to be refreshed (Refreshed date and timestamp are not changing). Thank you so much for your help.

Thanks
Brunda
