### ISSUE TITLE
cmd line for deploying models to power bi premium

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#477]
is there a cmd line code to deploy a .bim file to pbi premium. tried variations on the cmd line code for deploying a model to azure AS but didn't get it to work. would be great to put this variation here

https://github.com/otykier/TabularEditor/wiki/Command-line-Options

Thanks!

**Comment by otykier** [comment]
I'm afraid this won't be possible until PBI Premium allows service principals to connect. Currently, only interactive authentication is allowed, which prevents us from using the CLI.

If your tenant does **not** have MFA enabled, I think interactive authentication is not strictly required, so in that case, you may be able to deploy through CLI by providing your user name and password in the connection string, like:

```
Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/[tenant name]/[workspace name];User ID=[user name];Password=[password];Persist Security Info=True;Impersonation Level=Impersonate
```

**Comment by kalmenk** [comment]
Hmm, yeah I tried this and got the following error. It's odd that pbi premium doesn't allow but Azure AS does.

Deployment failed! Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.

**Comment by otykier** [comment]
Actually, support for service principals was announced a couple of weeks ago: https://powerbi.microsoft.com/en-us/blog/announcing-support-for-service-principals-using-the-xmla-endpoint-in-power-bi-premium/

Have you tried this approach?

**Comment by kalmenk** [comment]
haven't been able to get it to work but thought of another idea:

It would be great to have an option within the deployment wizard to output the equivalent cmd prompt code (with switches) that would do the deployment.

**Comment by otykier** [comment]
Please see [this blog-post](https://tabulareditor.com/2020/06/02/PBI-SP-Access.html) for more details on deployment to PBI Premium using Service Principals.

**Comment by kalmenk** [comment]
works great now after connecting the service principal as you suggested. Thanks!
