### ISSUE TITLE
importproperties via cmd line not working

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#478]
Running the importproperties method works when the script is executed in tabular editor. however, the same script with importproperties fails when run via the cmd line. it gives this error:

Object reference not set to an instance of an object.

**Comment by otykier** [comment]
Do you mind posting the exact script you're using and the command line syntax?

**Comment by otykier** [comment]
Try this build
[TabularEditor.Portable.zip](https://github.com/otykier/TabularEditor/files/4695608/TabularEditor.Portable.zip)

**Comment by kalmenk** [comment]
Hi Daniel,

It didn’t fail but it didn’t apply the changes from the .cs script. Attached is the resulting .bim file. It should have added a data source.

Thanks,
Michael

**Comment by otykier** [comment]
Issue with ImportProperties is fixed in [2.10.0](https://github.com/otykier/TabularEditor/releases/tag/2.10.0). Feel free to reach out if you still need assistance in getting the script to work.

**Comment by kalmenk** [comment]
tested 2.10.0 and it works. Thanks so much Daniel!
