### ISSUE TITLE
Shift+Delete does not trigger "Activate changes" button in Expression Editor

### ISSUE THREAD

**Issue by sweql** [otykier/TabularEditor#479]
_Using Tabular Editor 2.9.8_

When editing a measure's DAX code in the expression editor, it seems that if you **only** do changes via one or more Shift+Delete-presses (which deletes a whole row), this is not detected as a change and the Accept Changes button is not activated/enabled.

**Comment by otykier** [comment]
Thanks for reporting. Fixed in [2.10.0](https://github.com/otykier/TabularEditor/releases/tag/2.10.0).
