### ISSUE TITLE
Add line breaks to expressions in json files

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#48]
Hi,

when exporting the tabular model to a folder all expressions are formatted as a single line:
![grafik](https://cloud.githubusercontent.com/assets/908734/25315818/a822b964-285b-11e7-9f05-a7b78e730b30.png)

For version control purposses i would favour very much to have a new line after every \n. Thus, when changing ca complex DAX statement you can understand the diff.

regards

**Comment by otykier** [comment]
I'm not completely sure this is possible. JSON strings cannot contain real line breaks. It might be possible to store the expression as an array of strings, where each entry in the array corresponds to a separate line. In this case, the measure above would end up looking something like this in the outputtet JSON:

```json
{
  "name": "Costs",
  "expression": [
    "SWITCH(TRUE(),",
    "\t",
    "\t[BASE00 Costs (SUM)] = BLANK(),",
    "\tBLANK(),",
    ... // etc...
  ],
  "formatString": "#,0.00",
  "displayFolder": "00 Costs"
}
```

But I will have to test to see if the TOM can handle deserializing this format.

**Comment by fmms** [comment]
Hi,

looking at the original Model.bim file created with VS 14.0.61021 it has the line breaks:
![grafik](https://cloud.githubusercontent.com/assets/908734/25326620/47eb975c-28d1-11e7-994c-144ebf5ee8db.png)

Thanks

**Comment by otykier** [comment]
Thanks Felix - I see now that there is actually an option on the TOM's SerializeDatabase method that allows us to specify whether multiline strings should be split in the outputted JSON.

I'll expose this field in the File > Preferences dialog, so users can choose whatever suits them best. In addition, I've also exposed some other options from SerializeDatabase, and a new feature which may prove to be very useful for Version Control scenarios: Letting the user choose which object types should be serialized individually:

![image](https://cloud.githubusercontent.com/assets/8976200/25333606/30578a78-28eb-11e7-9885-0fc66f5e4046.png)

I've uploaded a new pre-release with this feature, so give it a spin and let me know what you think. Get it here: https://github.com/otykier/TabularEditor/releases/tag/2.3.6323

**Comment by fmms** [comment]
Thank you very much for fixing this that quickly. The files look very good.

I cannot save the preferences. However, I think this is a different problem (see #49)

**Comment by otykier** [comment]
Yup - different problem indeed. Will close this and keep #49 open until I hear back from you.

**Comment by Markoff79** [comment]
Hi Daniel,

in the current version (2.3.6327.18125) the line breaks are lost whenever we save the bim-file.

When we "save to folder" the line breaks are retained perfectly, but when saving the bim they are compressed to one line...

Can you take a look at this?

Best regards,
Marco

**Comment by otykier** [comment]
Hi Marco,
I just published a [new build](https://github.com/otykier/TabularEditor/releases/tag/2.3.6330) of Tabular Editor, where you can set Serialization Options when saving to a Model.bim file. You will find these options under File > Preferences... on the "Save to File" tab. By default, multiline strings will be split (as this is also what Visual Studio does).

![image](https://cloud.githubusercontent.com/assets/8976200/25580573/6ff4cb36-2e82-11e7-8d7c-dedbc24b8f32.png)
