### ISSUE TITLE
Connect to Power BI w/ ServicePrincipal using Username and Password textbox

### ISSUE THREAD

**Issue by RuiRomano** [otykier/TabularEditor#480]
Instead of having to build the connectionstring "Provider=MSOLAP;Data Source=<xmla endpoint>;User ID=app:<application id>@<tenant id>;Password=<application secret>" it would be easier to just input the XMLA Endpoint on Server and Client Id on Username and CLient Secret on Password.

Thanks for all the work you all put on this AMAZING tool.

**Comment by otykier** [comment]
Turns out you can already do this today, but you have to type the username as `app:<client id>@<tenant id>`:

![image](https://user-images.githubusercontent.com/8976200/83844947-3ccf0a80-a708-11ea-8bde-f9dd7a90b969.png)
