### ISSUE TITLE
Tabular Editor crashing with too much on clipboard

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#483]
Tabular Editor crashes under these circumstances:

Step 1: Copy 336 lines of C# code from text editor and paste into advanced scripting window.
Step 2: Run the advanced script
Step 3: Press Undo

After Step 3, tabular editor crashes.

The workaround is to copy a small portion of text to reduce the clipboard size (before step 3)

**Comment by otykier** [comment]
I can't reproduce this issue. Does it happen consistently on your end? Could you send me the Model.bim file and C# script you were using when it crashed?

**Comment by otykier** [comment]
@m-kovalsky do you still face this issue with newer versions of Tabular Editor?

**Comment by m-kovalsky** [comment]
Haven't faced this issue in quite a while. And, trust me, I've had lots of text in the clipboard. Seems to be resolved :)
