### ISSUE TITLE
Ability to update connection string for non legacy data source

### ISSUE THREAD

**Issue by DSwain1996** [otykier/TabularEditor#487]
currently it is not possible to update connection string,username and password for any non legacy datasource used in AAS tabular model using the script functionality, is there any solution for it ?

**Comment by otykier** [comment]
You should be able to set all data source properties if you make sure to cast it as a `StructuredDataSource`:

```csharp
var ds = Model.DataSources["StructuredDS"] as StructuredDataSource;

ds.Username = "test";
ds.Password = "12345";
ds.ConnectionString = "xyz";
```

**Comment by DSwain1996** [comment]
Thanks @otykier  , i will quickly test it in my CICD Pipeline and confirm .

**Comment by DSwain1996** [comment]
![image](https://user-images.githubusercontent.com/55327056/84665921-0a11e700-af3e-11ea-96e7-0a6c18816a9e.png)


@otykier : can you help me on how can i update credentials for multiple datasources in single script  .For example: in the attached image i have two datasource i.e DEV ADE and UAT ADW .

**Comment by otykier** [comment]
You need to provide the right name for each data source in the Model.DataSources array:

```csharp
var devadw = Model.DataSources["DEV ADW"] as StructuredDataSource;
devadw.Username = "test";
devadw.Password = "12345";
devadw.ConnectionString = "xyz";

var uatadw = Model.DataSources["UAT ADW"] as StructuredDataSource;
uatadw.Username = "test";
uatadw.Password = "12345";
uatadw.ConnectionString = "xyz";
```

**Comment by DSwain1996** [comment]
Thanks @otykier  this works perfectly. One last piece I would like to check . We have the below scenario for which CI/CD is required -
Scenario 
We have around 30 different teams having a repo linked to each project and going forward we are going to use Tabular editor for CI/CD  of Tabular models, we will have this c# script for data source updation  in git repository . We want the password for the data source in Tabular Model to be retrieved from the Azure Key vault linked to each stage in my CD Release pipeline. Will this be possible to do , if so can you point me to correct way I should create the script .

**Comment by otykier** [comment]
The best way to do it, is to pass the secrets from your CI/CD pipeline as environment variables.

Let's say you have a variable, `$(SQLDWConnectionString)`, in your your CI/CD pipeline that was read from a key vault (this is possible with Variable Groups in Azure DevOps). You want to pick up the value of this variable inside your script. First, make sure the pipeline variable is passed to the command line task as an environment variable (see bottom of this screenshot):

![image](https://user-images.githubusercontent.com/8976200/84688799-3af31b80-af40-11ea-8aeb-7fb2d7491c48.png)

Then, to pick up the value inside the script, use:

```csharp
// ...
devadw.ConnectionString = Environment.GetEnvironmentVariabel("SQLDWConnectionString");
// ...
```

**Comment by DSwain1996** [comment]
@otykier : Thank you for the detailed explanation .
It works perfectly .
