### ISSUE TITLE
Preferences must be saved in user folder

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#49]
The tabular editor saves the preferences in a global file.
However in a multi user environment this creates a problem with permissions.

![grafik](https://cloud.githubusercontent.com/assets/908734/25435906/f9100f10-2a91-11e7-99aa-ee124227aed3.png)

The file should be saved in a user writable location.

Thanks

**Comment by otykier** [comment]
Hi Felix - thanks for raising this.
Indeed, Preferences should be user-based. Going forward, the file will be stored in the %AppData%\Local folder. If no file exists in this folder, Tabular Editor will attempt to load preferences from the %ProgramData% folder, for backwards compatibility.

You may have noticed that the %ProgramData%\TabularEditor folder also contains a file called TOMWrapper.dll file. Indeed, this suffers from the same issue in multi-user environments, and it can cause crashes when executing custom scripts inside Tabular Editor. For this reason, the .dll will also be stored in the %AppData%\Local\TabularEditor folder, going forward.

This has been implemented in the [latest pre-release](https://github.com/otykier/TabularEditor/releases/tag/2.3.6325).

Could you please let me know if this solution works for you?

**Comment by fmms** [comment]
works indeed. thank you.
