### ISSUE TITLE
Copying columns for dependent measures

### ISSUE THREAD

**Issue by tekdata** [otykier/TabularEditor#492]
I'm transferring measures from one pbix file to another using tabular editor. This saves an great deal of time.

But this doesn't account for measures which are dependent on calculated conditional columns. Is it possible to copy calculated columns in bulk like it is with measures?

**Comment by otykier** [comment]
While you can certainly copy calc columns between instances of Tabular Editor, Power BI does not currently support making changes to your model with an external tool. You may have more luck by exporting your pbix as a .pbit (Power BI Template), then load and make changes to the template in Tabular Editor, but it is still not guaranteed to work. Make sure to keep a backup of your original .pbix in any case.

**Comment by tekdata** [comment]
How do you copy columns between instances of tabular editors? I can only work out how to copy measures.
