### ISSUE TITLE
Can't export to Power BI Desktop format

### ISSUE THREAD

**Issue by seryild** [otykier/TabularEditor#493]
Hi Otykier,

Thank you for an amazing tool! I use it a lot, but since I started to connect directly to a dataset in Power BI Service, I experienced some problems. I get the following error when I try to download the dataset after I worked with it in Tabular Editor.

Hope you can help me!

![image](https://user-images.githubusercontent.com/66314652/84764427-0168f180-afce-11ea-9a79-4bdea6a8a704.png)

**Comment by gustavoleo** [comment]
Hi seryild, 

Any messages on the technical details or just codes?

**Comment by seryild** [comment]
Hi Gustavoleo,

No messages, only codes and IDs

**Comment by otykier** [comment]
This is by design. Please read the official [documentation on XMLA read/write access](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#power-bi-desktop-authored-datasets) and direct any concerns to Microsoft.

> **Caution**
>
> At this time, a write operation on a dataset authored in Power BI Desktop will prevent it from being downloaded back as a PBIX file. Be sure to retain your original PBIX file.
