### ISSUE TITLE
Copy relationships from one model to another

### ISSUE THREAD

**Issue by maka89** [otykier/TabularEditor#494]
Relationships doesnt show up before saving, closing and reopening tabularEditor.

I am copying from 1400 -> 1520 comp. level

**Comment by otykier** [comment]
I'm not able to reproduce this. Could you please provide step-by-step details? Thanks!

**Comment by maka89** [comment]
- opened model.bim (1400)
 - opened another instance of tabular editor. File -> new model -> 1520 comp. level.
- Copied shared expression, data sources, tables first.
- Copied relationships, but it doesnt show... 

Should I send you my model.bim?

**Comment by otykier** [comment]
Even better if you could record a short video (for example using https://www.screentogif.com/ ) to show what you're doing.

**Comment by maka89** [comment]
it worked now...  pls delete ^^ Will post if it happens again and am able to document
