### ISSUE TITLE
Define Measures

### ISSUE THREAD

**Issue by Besiki21** [otykier/TabularEditor#495]
Can't define all measures in Power BI. Can you tell me the way to do it? I just want list of the measures with all details about them in a readable format. Thanks.

**Comment by marcosqlbi** [comment]
You can get that list using DAX Studio + VertiPaq Analyzer.
https://www.sqlbi.com/blog/marco/2019/09/15/vertipaq-analyzer-2-0-preview-1/

**Comment by Besiki21** [comment]
> You can get that list using DAX Studio + VertiPaq Analyzer.
> https://www.sqlbi.com/blog/marco/2019/09/15/vertipaq-analyzer-2-0-preview-1/

Thank you Marco, but I want it in a txt format. I  tried it using DAX Studio with "Define All Measures (All tables), however, it skips comments in the measures. I have no Idea why :/

**Comment by marcosqlbi** [comment]
Are skipped comments at the beginning or at the end of the measures?

**Comment by Besiki21** [comment]
> Are skipped comments at the beginning or at the end of the measures?

At the beginning. Comments in the middle are shown.

**Comment by otykier** [comment]
Try this script in Tabular Editor (run it under the “Advanced Scripting”-tab):

```csharp
ExportProperties(Model.AllMeasures).Output();
```

This will give you a list of all measures and their basic properties (expression, description, etc.) in a tab-separated format that you can copy into Excel. For more info, see here: https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#export-object-properties-to-a-file

**Comment by marcosqlbi** [comment]
I created an issue in DAX Studio for this behavior:
https://github.com/DaxStudio/DaxStudio/issues/357

**Comment by Besiki21** [comment]
Thank you guys. You are amazing <3

**Comment by dgosbell** [comment]
You can also run `SELECT * FROM $SYSTEM.TMSCHEMA_MEASURES` in DAX Studio to get a list of all measures and their expressions
