### ISSUE TITLE
Script roles

### ISSUE THREAD

**Issue by gaudrick** [otykier/TabularEditor#496]
Hi, 

Scripting is fantastic!

That would be nice to be able to script roles, table permissions... and allow to create multiple roles from a csv file for example. Clone role is great if you already have a template of role for example but apparently not yet supported in Power BI service. If you have already some scripts working on roles please share!

Again, fantastic work. thx ! :-)

Best regards

**Comment by otykier** [comment]
As a rule of thumb, everything that can be done through the UI, can be done through scripting as well. Here are some snippets to get you started:

```csharp
// Store name of role in a variable for easy reference:
var roleName = "My New Role";

// Add the new role to the model:
Model.AddRole(roleName);

// Add a row level filter (DAX expression) on table 'Employee' for the new role:
Model.Tables["Employee"].RowLevelSecurity[roleName] = "Employee[Department] = \"xyz\"";

// Add Object Level Security, hiding the [Salary] column on table 'Employee' for the new role:
Model.Tables["Employee"].Columns["Salary"].ObjectLevelSecurity[roleName] = MetadataPermission.None;

// Add a member to the role:
Model.Roles[roleName].AddExternalMember("user@account.mail");
```

**Comment by gaudrick** [comment]
Thx @otykier  that's make sense. Your script is useful, exactly what needed. Unfortunately not yet supported by Power Bi Service. It shows a "Publishing failed for an unknown reason" even if everything seems ok on the Power Bi Desktop manage role window. Same when I clone a role.

**Comment by otykier** [comment]
Please read the [official documentation](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#model-roles):

> During the public preview, you cannot specify role membership for a dataset by using the XMLA endpoint. Instead, specify role members on the Row-Level Security page for a dataset in the Power BI service.
