### ISSUE TITLE
Copying columns between tabular editor instances

### ISSUE THREAD

**Issue by tekdata** [otykier/TabularEditor#497]
Can it be possible to copy custom columns between instances of Tabular Editor using ctrl +c and ctrl +v, like you can with measures?

This would be a great time saving enhancement.

**Comment by otykier** [comment]
What is Custom Columns? Did you mean Calculated Columns?

There is no issue in copying calculated columns between instances of Tabular Editor, but if you're working on a Power BI model (.pbit file or connected directly to a model in PBI Desktop) **this is not supported**. If you feel brave, you can try to enable experimental features under File > Preferences, but you may end up breaking your .pbix file, so make 100% sure that you keep a backup.

**Comment by tekdata** [comment]
Ok that makes sense. Thanks
