### ISSUE TITLE
PBI Desktop will not refresh after Tabular Editor change.

### ISSUE THREAD

**Issue by bobc-jmann** [otykier/TabularEditor#499]
I'm running a fairly large PBI Desktop model (June Release). It contains five measure tables. After duplicating a measure with Tabular Editor (2.10.0) and then trying to refresh the model, I get the following error: 

"The model doesn't have a named expression named Measures - GL. 

Measures - GL is one of my measure tables. Here is the definition in m:

let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
in
    #"Removed Columns"

**Comment by otykier** [comment]
Making changes to a PBI Desktop model with Tabular Editor is not yet supported in Desktop. You might have more luck by saving your model as a .pbit file and then making the changes to that in Tabular Editor, but that's still not supported. You'll have to be a little more patient before editing measures with Tabular Editor will be fully supported.

**Comment by bobc-jmann** [comment]
No problem and thanks for the prompt response.

I thought you would like to know about the problem though…

Thanks for the very cool tool!!

Bob

**Comment by otykier** [comment]
Thanks a lot, but until the feature is fully supported, it's no surprise that things don't always work :-)
