### ISSUE TITLE
Adding the ability to update Tabular Editor through command line

### ISSUE THREAD

**Issue by SQLBent** [otykier/TabularEditor#50]
It would be a great improvement if the file could be called with a command like "TabularEditor.exe update" which would enable it to download the latest version.

In addition it should be possible to specify either"-path" or "-self"
"-path" where it should be downloaded to
"-self" replace the file itself
label:enhancement

**Comment by otykier** [comment]
I'll have to look into this. Unfortunately, it's not easy to do an in-place update of an .exe file which is currently running. An easier solution would be to include a new file, TabularEditorUpdater.exe that can be used to download and overwrite the existing TabularEditor.exe file, in case a new version is available. However, I would very much like to keep Tabular Editor as a single, stand-alone .exe file like it is today...

Why don't you create a simple PowerShell script that can do the trick? (Feel free to post the script here, for the benefit of everyone else) :-)
