### ISSUE TITLE
export properties - parent property

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#500]
There is an issue when using the Parent property within the ExportProperties function in the latest version of tabular editor: 2.11.0. When 'Parent' is requested as shown below, it gives an error saying 'Cannot export property Parent on Column...since it is a complex object'.

ExportProperties(Model.AllColumns, "Name,Parent").Output();

![image](https://user-images.githubusercontent.com/29556918/85382561-c1fb5180-b547-11ea-8953-b10ac2988e1e.png)

**Comment by peloscvcd** [comment]
Me too :(

**Comment by otykier** [comment]
Fixed in [2.11.1](https://github.com/otykier/TabularEditor/releases/tag/2.11.1). Thanks for reporting!

**Comment by m-kovalsky** [comment]
Thanks, however I tried downloading both the MSI and the zip file and neither seems to work. The MSI offers to repair or remove tabular editor. The zip file opens 2.11.0, not 2.11.1 tabular editor

**Comment by otykier** [comment]
I accidentally uploaded the previous version binaries to the release... /doh

Please try again now :)

**Comment by m-kovalsky** [comment]
no worries :) 2.11.1 downloads fine now and the issue is fixed 👍
