### ISSUE TITLE
Export Error Messages

### ISSUE THREAD

**Issue by anbudhanush** [otykier/TabularEditor#501]
Hi , In the current version one can click on the Errors link at the bottom left side of the screen which opens a new window with error and measure details. Is it possible to export all the measures errored along with the error message?  I tried copy/paste as well as right click on the gird, did not work. Finally I ended up with a screen grab and OCR it ?
Thanks 
Anbu

**Comment by otykier** [comment]
I will consider a "Copy to clipboard" button in the error dialog. In the mean time, you can use the following script under the "Advanced Scripting" tab to output all error messages in a way where you can copy them to Excel:

```csharp
var tsv = "Table\tMeasure\tErrorMessage";
foreach(var measure in Model.AllMeasures.Where(m => m.ErrorMessage != ""))
{
    tsv += "\r\n" + measure.Table.Name + "\t" + measure.Name + "\t" + measure.ErrorMessage.Replace("\n"," ");
}
tsv.Output();
```

**Comment by anbudhanush** [comment]
Super. Thanks Daniel.
