### ISSUE TITLE
Refresh Loaded Model When pbix file is modified

### ISSUE THREAD

**Issue by anbudhanush** [otykier/TabularEditor#502]
Hi Daniel , 

Currently when I load the model into TE from Power BI Desktop, I can make changes in TE and click on save changes to the pbix file.  But when i make changes in the Pbix file while connected to TE, it does not reflect changes in the loaded TE model. Is there are way we can refresh both ways between TE and Pbix file?

thanks
Anbu

**Comment by otykier** [comment]
Did you try this with the latest version [2.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0)?

Make sure File > Preferences > "Detect changes on local AS instance" is enabled.

**Comment by anbudhanush** [comment]
My current version is 2.10.0 . I will try that feature now. Thanks

**Comment by anbudhanush** [comment]
Awesome. It worked.  Thanks.
A barrel of beer for you.
