### ISSUE TITLE
Visibilty Property of database without effect

### ISSUE THREAD

**Issue by SalCag** [otykier/TabularEditor#503]
Hello

I search for a possibility to make a Tabular database invisible like it's possible for tables and columns.

In Tabular Editor, I stumbled over the visibility property of the database:
![image](https://user-images.githubusercontent.com/26252452/85436544-85504a00-b589-11ea-8765-916bb9b5bb06.png)

But it seems that this property has no effect.

I can deploy the database, but it's still visible.
When I reload the model.bim file, the property is reset to true, even when I set it to false and save the file.

Is this for a future feature of SSAS?

Regards
Salvatore

**Comment by otykier** [comment]
Hi Salvatore. I must be honest with you: I have no idea what this property does! Tabular Editor basically just exposes all public properties from the API in the UI... maybe it's something used only by the PBI Service - maybe it's a future feature. I have no clue. But remember, if you want to hide a database from certain users for security/privacy purposes, it's best to use Roles for that.

**Comment by SalCag** [comment]
> Hi Salvatore. I must be honest with you: I have no idea what this property does! Tabular Editor basically just exposes all public properties from the API in the UI... maybe it's something used only by the PBI Service - maybe it's a future feature. I have no clue. But remember, if you want to hide a database from certain users for security/privacy purposes, it's best to use Roles for that.

Hi Daniel
Thank you for your answer.

We don't want to restrict access to the data model, but only set it to invisible.
We have Test models, which shouldn't be visible to end-users.
Then we have a model, which is used for a welcome page. It makes no sense to navigate this model with a reporting tool.
We don't want to change the permissions in either case.

Anyway, at the moment there is no solution for our requirement.

**Comment by otykier** [comment]
I'm afraid not. Closing this issue as this is more a question of Analysis Services functionality than Tabular Editor.
