### ISSUE TITLE
Dax-formatter - don't erase commented out (//,--)

### ISSUE THREAD

**Issue by caniel** [otykier/TabularEditor#506]
Hi,

When using the DAX-formatter button, this will delete/erase my code that was commented out. 

for example :

// Calculate()
or 
-- Calculate()

is it possible that this will stay ? because the formatter is great!

Camille

**Comment by otykier** [comment]
I am not able to reproduce this. Could you provide the exact DAX formula (including comments) where you experience that comments disappear? Does www.daxformatter.com produce the same issue? (Tabular Editor simply calls daxformatter.com under the hood)

**Comment by caniel** [comment]
oke thanks , also see now that it works again, i think they fixed it !

thanks for the fast reply and keep up the good work!
