### ISSUE TITLE
Error occured during deployment

### ISSUE THREAD

**Issue by caniel** [otykier/TabularEditor#507]
Hi,

just now after your last update 2.11.3 i get the following error:

![Capture](https://user-images.githubusercontent.com/4134862/85855033-d6448600-b7b5-11ea-9c90-f33820b4df94.PNG)

so i can't deploy a current model with a new name as a new model.
or can't override my _dev cube to non _dev cube.

Camille

**Comment by otykier** [comment]
Thanks for reporting. As a workaround, until I get this fixed, save your model as a .bim file, then open that file and deploy it.

**Comment by otykier** [comment]
Fixed in [2.11.4](https://github.com/otykier/TabularEditor/releases/tag/2.11.4).
