### ISSUE TITLE
Proposition for more readable error communicate when the partition has duplicate columns

### ISSUE THREAD

**Issue by modliszka** [otykier/TabularEditor#509]
When I mistakenly add to Partition two columns with the same name and then I refresh table metadata, I'm getting such error:
> An item with the same key has already been added.

It's not clear at first sight what and where is wrong and I spent some time searching the root cause of this.
Is it possible to make this sentence more understandable? Because 'key' can mean a lot. I would like to see at least some additional information in brackets like "... the same key (ex. columns) ...".

**Comment by otykier** [comment]
Fixed in [2.11.5](https://github.com/otykier/TabularEditor/releases/tag/2.11.5)
