### ISSUE TITLE
Version 2.3.6325.39049 crashes on startup

### ISSUE THREAD

**Issue by Markoff79** [otykier/TabularEditor#51]
Hello otykier,

unfortunately it crashes on startup. We assume that it opens correctly when opening the exe as an administrator but I do not have the admin role on the server where I want to execute it.

![image](https://cloud.githubusercontent.com/assets/28108965/25517358/5a265f6c-2bef-11e7-9dbe-ea430d8d37ac.png)

Best regards,
Marco

Here is the error message:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TabularEditor.exe
  Problem Signature 02:	2.3.6325.39049
  Problem Signature 03:	5900f7f3
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1087.0
  Problem Signature 06:	583e5abb
  Problem Signature 07:	157f
  Problem Signature 08:	12e
  Problem Signature 09:	System.UnauthorizedAccess
  OS Version:	6.1.7601.2.1.0.16.7
  Locale ID:	1031
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by otykier** [comment]
Hi Marco
Thanks for reporting this. Unfortunately, I'm not able to reproduce the issue. In theory, Tabular Editor does not need admin rights to run, but perhaps it's inadvertently accessing some resource that does need admin rights.

A couple of questions to help me narrow down the cause:
- Did any of the previous versions work without crashing? If so, what version #?
- Do you need admin rights to access the folder %AppData%\..\Local on your machine?
- If you execute TabularEditor.exe from a command-line, does it output anything in the console before crashing?

**Comment by Markoff79** [comment]
Hi Daniel,

version 2.2.6260.26261 is working fine.

I can access and write in %AppData..\Local without admin rights in the machine.

In cmd it crahses too (see below)

Best regards and thank you very much for the editor (it saves precious time!!!),
Marco



C:\Users\MNIELINGER\Desktop>TabularEditor.exe

C:\Users\MNIELINGER\Desktop>
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'c:\
Projects\test.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean che
ckHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encodin
g, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding
 encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at TabularEditor.BestPracticeAnalyzer.BestPracticeCollection.SaveToFile(Strin
g filePath)
   at TabularEditor.BestPracticeAnalyzer.Analyzer..ctor()
   at TabularEditor.UI.Dialogs.BPAForm..ctor()
   at TabularEditor.FormMain..ctor()
   at TabularEditor.Program.Main()

**Comment by otykier** [comment]
Thanks Marco - I found the culprit.

[New release available](https://github.com/otykier/TabularEditor/releases/tag/2.3.6327) with this bug fixed.

**Comment by Markoff79** [comment]
Thanks!
