### ISSUE TITLE
Error on saving or deploying when mode is Direct Query

### ISSUE THREAD

**Issue by benito2313** [otykier/TabularEditor#510]
Hello,

When i set a partition on directquery i get the following error:

For Partitions that have a full dataset ( no sample data), the DirectQuery and Full DataViews must be configured or the query mode must be Import to get the data.
This model probably contains non-compatible partitions.
Check the partitions configuration

I'm on a azure analysis server, and in tabular editor i get the partition data in legacy mode.

What am i doing wrong?

Goal is to get the aggregation setup working.

Kind regards,

Benito2313

**Comment by otykier** [comment]
Azure Analysis Services [does not support aggregations / composite models](https://randombi.com/2020/04/27/migrating-from-azure-analysis-services-to-power-bi-premium/).

**Comment by benito2313** [comment]
Does it support Direct Query?

**Comment by otykier** [comment]
Yes, but then all tables in your model must use DirectQuery.

**Comment by benito2313** [comment]
i cant set them as dual?

**Comment by otykier** [comment]
Nope. Dual is the composite model feature.

**Comment by benito2313** [comment]
thnx for your help :)
