### ISSUE TITLE
TOM - Renaming objects

### ISSUE THREAD

**Issue by TePeBoxer** [otykier/TabularEditor#513]
Is it correct that renaming objects (i.e. a table) is not supported when you're connected through TOM? Tried to add a translation directly to my PowerBI model but it didn't work...

**Comment by otykier** [comment]
Are you asking whether objects (tables, columns, measures, etc.) can be renamed, or whether translations can be applied, when model metadata is loaded from an instance of AS? In general, the answer is yes to both. However, Power BI Desktop doesn't support translations, so if you're trying to add them to a .pbix file loaded in Desktop it won't work. However, translations should work fine in the PBI Service, so if you're editing your dataset through the XMLA R/W endpoint, there should not be any issues.

**Comment by otykier** [comment]
Feel free to reopen or create a new issue if you still need assistance.
