### ISSUE TITLE
Update Description for set of Measures

### ISSUE THREAD

**Issue by anbudhanush** [otykier/TabularEditor#517]
Hi, 

I would like to update description of measures from tsv files. I was planning to tweak the _Import Measure From File_ script you have provided. I wonder just like AddMeasure(name) is there property called UpdateMeasure(Name) ? 

The Steps I had in mind for the scripts are 

1. Load tsv data to table with ObjectName, MeasureName, Description 
2. Iterate each row and match with measure name already in the model 
3. Update each measure with new description - Add/Update Description

My struggle is , how to map to the measure in the model and just add the description. 

thanks

**Comment by otykier** [comment]
Why not simply use the `ImportProperties` method? See the example at the bottom of this description: https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#export-object-properties-to-a-file

**Comment by anbudhanush** [comment]
Perfect. Good to know about the import properties. it worked. Thanks
