### ISSUE TITLE
hierarchy ordinal note

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#518]
when the Ordinal property is selected for a hierarchy level, the notes at the bottom state: 'The levels in the hierarchy must be properly ordered, starting with 1 and increasing monotonically'. The ordinal starts from 0, not 1.

![image](https://user-images.githubusercontent.com/29556918/86261061-c0c0c900-bbc6-11ea-896e-e193ab2549e8.png)

**Comment by otykier** [comment]
Tabular Editor simply displays the XMLDoc comments in the TOM AMO libs. And [as you can see](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.level.ordinal?view=analysisservices-dotnet), there's a bug in the docs. If the docs are updated and a new AMO release is made, we should get the updated note in Tabular Editor as well.

**Comment by m-kovalsky** [comment]
ah i see, thanks!
