### ISSUE TITLE
FormatString - Column - String DataType

### ISSUE THREAD

**Issue by mst42a** [otykier/TabularEditor#519]
Hello,
I have faced some problems with FormatString on columns with DataType = String. 
A long time ago, I have run a script in Advanced Scripting window, to set FormatString on every columns without FormatString containing some pattern in Name. (And forgot about that).
I was surprised when my data show incorrectly. I needed some time to figure out what is going on because TabularEditor didn't show up Properties FormatString for Column with Data Type = String (properties.png), but when I run script Selected.Column.FormatString.Output(); Format showed Up.

Can You change "basic" section? I mean, show FormatString properties but blocked and greyed out
![Properties](https://user-images.githubusercontent.com/63145285/86327903-459df800-bc44-11ea-84d4-99d4d39bd1d9.PNG)
![FormatString](https://user-images.githubusercontent.com/63145285/86328039-7aaa4a80-bc44-11ea-9ace-a0b5bd2e08be.PNG)

**Comment by otykier** [comment]
What client tool are you using to browse the data model (Excel, Power BI, or ...?) To my knowledge, AS is not supposed to apply format strings to columns of DataType = String (or at least it's not documented anywhere). But if this is standard behaviour, I don't mind keeping the FormatString property visible in Tabular Editor's UI when DataType=String.

**Comment by mst42a** [comment]
End user use Excel only or SSRS (report services)

**Comment by otykier** [comment]
Fixed in [2.11.6](https://github.com/otykier/TabularEditor/releases/tag/2.11.6), so that the FormatString property is always visible regardless of the data type.
