### ISSUE TITLE
expression color formatting - ASC, DESC

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#520]
Would be great for ASC & DESC to show in blue color in the expression editor.

**Comment by otykier** [comment]
Thanks for reporting. Adding these + the new financial DAX functions (and a few other missing functions and keywords)

**Comment by m-kovalsky** [comment]
Ah perfect, thanks!

**Comment by otykier** [comment]
Fixed in [2.11.6](https://github.com/otykier/TabularEditor/releases/tag/2.11.6).
