### ISSUE TITLE
How would you like to edit object translations ?

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#521]
Hello Daniel,

In the last release (2.11.5), you asked where we would like to translate objects :
_"How would you like to edit object translations, perspective membership, etc. in an Excel sheet?"_

I don't know if you had already some replies but I described my point of view about translations in this blog post :
[https://thebipower.fr/index.php/2020/07/05/translations-life-cycle-management/](url)

It could be great to share opinions on this topic

Regards
Didier

**Comment by otykier** [comment]
Hi Didier,
Did you already try exporting/importing translations to the TSV format using the `ExportProperties` / `ImportProperties` methods as described [here](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#exporting-indexed-properties )? Please let me know if you have any issues or have any feedback on this approach.

**Comment by didierterrien** [comment]
Hello Daniel,
Yes I checked the export properties approach but I think the file format will be more complex once I export several languages. There will be groups of 3 columns (name, description, display folder) for each language ? I would prefer to have name, description & display folder in different rows and one column by language. The script I wrote works in this way.

**Comment by otykier** [comment]
Have you tried the [Tabular Translator](https://www.sqlbi.com/tools/ssas-tabular-translator/) tool, with a .json file exported from Tabular Editor? (Translations > Export translations...). In my opinion, this is probably the best option, if all you need is to edit object translations and no other properties.

<img width="394" alt="Screenshot 2020-07-13 at 13 28 13" src="https://user-images.githubusercontent.com/8976200/87299660-bf6b9680-c50c-11ea-9a1f-9ca6ed41e5fb.png">

I know there is an [issue right now](https://github.com/otykier/TabularEditor/issues/463) that the file does not include "empty" translations, making it difficult to work with the .json file by hand, but I think the Translator-tool should work just fine.

**Comment by didierterrien** [comment]
Yes, I tried Tabular translator. It works but it doesn't meet  some of the requirements I explained in this blog post :   [https://thebipower.fr/index.php/2020/07/05/translations-life-cycle-management/](url) :

- copy and paste
- automatic translation
- easy identification of new labels
- easy identification of the labels needing a review after modification
- splitting translations between translators with an appropriate level of security

and most of all, it doesn't help translating visuals labels like titles.

**Comment by otykier** [comment]
Closing this issue as no further additions to this version of Tabular Editor are planned in this regard.
