### ISSUE TITLE
Measure Formatting Issue

### ISSUE THREAD

**Issue by lstee014** [otykier/TabularEditor#523]
Hi Daniel - 

I am running into a strange issue that I thought I resolved yesterday, but it continues to surface and not sure what to do about it.  The issue in short is that formatting changes made in Tabular Editor are not reflected in the PBIX file that I am connected to via the DB local source option.  I have saved my changes to the model in Tabular Editor and refreshed the PBIX file.  Here is the really strange part, while the formatting does not show up in the measure tools formatting ribbon, when I use the measure in a table the measure is formatting per the change I made in Tabular Editor:  Details below:

Tabular Editor Screen Shot:
![image](https://user-images.githubusercontent.com/67977985/86946966-bf385900-c110-11ea-95df-20a7a673708a.png)
![image](https://user-images.githubusercontent.com/67977985/86947035-dd05be00-c110-11ea-802c-ff086287049f.png)

PBIX File Screen Shots:
![image](https://user-images.githubusercontent.com/67977985/86947107-f60e6f00-c110-11ea-8555-590acefb3044.png)
![image](https://user-images.githubusercontent.com/67977985/86947173-0cb4c600-c111-11ea-8649-0173b7894f8b.png)
(Note: in the table above the field is not formatted at all)

When I publish to the PowerBI service and connect a file to the data set then I can see the formatting:
![image](https://user-images.githubusercontent.com/67977985/86947781-dd528900-c111-11ea-843d-8664d2529bad.png)

If I download the PBIX file from the service, the formatting in the ribbon reverts back to "general" as it is in the PBIX screen shots in my first section of PBIX screenshots.

The another oddity that I will introduce is that if someone else on my teams uses the PBIX file with Tabular Editor then the formatting changes are not visible in Tabular Editor and is they make a change to the PBIX model, all the formatting is erased and is not visible when using the measure in PBIX or the service.  

Finally, I am able to add measures just fine and the formatting for those measures comes across as entered in to Tabular editor, so this appears to be specific to just previously existing measures that I need to format.

I am using the June release of Power BI desktop and v2.11.5 of Tabular Editor.

I love this tool and it would be amazing to get the formatting to work as I need to format over 1600 measures.

Thank you so much for this incredible tool!

Luke

**Comment by lstee014** [comment]
I tried converting the file to a PBIT to see if connecting to tabular editor would allow the formatting to get "pushed through" to the Power BI desktop and although that was unsuccessful I was able to unzip the PBIT file to view the data model schema and the formatting as a % is there....it just doesnt show up in the formatting section for Power BI... 
![image](https://user-images.githubusercontent.com/67977985/86964064-1ba87200-c12b-11ea-9e0c-b1d767d7e9a5.png)

**Comment by lstee014** [comment]
Is the possible issue that the data model schema still is showing the format as "General" when Tabular Editor is "Custom":
![image](https://user-images.githubusercontent.com/67977985/86965141-b5245380-c12c-11ea-86b4-5b7bb5430eb5.png)
![image](https://user-images.githubusercontent.com/67977985/86965214-cc634100-c12c-11ea-8884-104cf779b675.png)

**Comment by otykier** [comment]
The issue is that making changes to a Power BI model using Tabular Editor is unsupported, and could result in weird behavior like this. Please wait for the official support for external tools with Desktop and let me know if the issue still persists at that time.

**Comment by lstee014** [comment]
Thank you Daniel!  Great tool by the way!  Love it.
