### ISSUE TITLE
 Replace blob storage key property using Tabular Editor command line

### ISSUE THREAD

**Issue by subashsivaji** [otykier/TabularEditor#524]
Hi I have a Structured Data source Azure Blob Storage and the TMSL script is as follows - this TMSL script works when executed in SSMS.
```
{
    "createOrReplace": {
        "object": {
            "database": "AAS Database Name",
            "dataSource": "MyDataSource"
        },
        "dataSource": {
            "type": "structured",
            "name": "MyDataSource",
            "connectionDetails": {
                "protocol": "azure-blobs",
                "address": {
                    "account": "mystorageaccountdev",
                    "domain": "blob.core.windows.net"
                },
                "authentication": null,
                "query": null
            },
            "credential": {
                "AuthenticationKind": "Key",
                "kind": "AzureBlobs",
                "key": "gHQxxxxxxxxxxxxxxxxxxxxxxxxxxxd2Jwc0huw=="
            }
        }
    }
}
```

Using Tabular Editor - I am trying to replace the key property (also tried Key - K caps) using following C# script and call this in Tabular Editor command line.

```
var dataSource = (Model.DataSources["MyDataSource"] as StructuredDataSource);
dataSource.Account = "mystorageaccount" + Environment.GetEnvironmentVariable("environmentcode");
dataSource.key = "gHQxxxxxxxxxxxxxxxxxxxxxxxxxxxd2Jwc0huw==";
```

**But is throws following error - what am I missing? How can I replace blob storage key in data source when deploying across environments (dev -> test -> prod) using Tabular Editor command line?**

_'TabularEditor.TOMWrapper.StructuredDataSource' does not contain a definition for 'key' and no extension method 'key' accepting a first argument of type 'TabularEditor.TOMWrapper.StructuredDataSource' could be found (are you missing a using directive or an assembly reference?)
##vso[task.complete result=Failed;]Done._

Any help appreciated. Thanks.

**Comment by otykier** [comment]
[2.11.6](https://github.com/otykier/TabularEditor/releases/tag/2.11.6) now exposes a Credential object on StructuredDataSources. If you click this, you can add/remove property-value pairs to the TOM Credential object:

![image](https://user-images.githubusercontent.com/8976200/87294462-22a4fb00-c504-11ea-9287-55a4538f8310.png)

You can also access this object through scripting. So for example, to set the key value in your example, use the following script:

```csharp
var dataSource = (Model.DataSources["MyDataSource"] as StructuredDataSource);
dataSource.Account = "mystorageaccount" + Environment.GetEnvironmentVariable("environmentcode");
dataSource.Credential["key"] = "gHQxxxxxxxxxxxxxxxxxxxxxxxxxxxd2Jwc0huw==";
```
