### ISSUE TITLE
Error when trying to deploy to Azure AS

### ISSUE THREAD

**Issue by gflores1023** [otykier/TabularEditor#525]
I receive the following error on the login screen when deploying to AAS. The password field should be null since it usually pops up the modal dialog for authenticating.

_"Value cannot be null. Parameter Name: value"_

Using Tabular Editor 2.11.5. This used to work in the past in prior version. I was able to deploy using an older version (2.9.7) we have on a different server. I'm also able to deploy to an on-prem server using Windows Auth. And I can connect to it using DAX Studio and SSMS for querying.

![image](https://user-images.githubusercontent.com/286903/86958223-70df8600-c121-11ea-9938-52cc468e0211.png)

**Comment by otykier** [comment]
For Azure AS, leave the “Integrated Security” option checked. You will provide both username and password when the AAD login screen appears after you click OK.

**Comment by gflores1023** [comment]
Ah ok, I can't believe I didn't try that.
