### ISSUE TITLE
Power BI Desktop -> External Tools -> Tabular Editor -> 2nd Calculation Group Error

### ISSUE THREAD

**Issue by MicahDail** [otykier/TabularEditor#528]
Looks like there is a bug in that you can't create a second calculation group when you are connected to PBI Desktop through external tools. I'm unable to modify the precedence of the groups when connected through External tool, rather all groups have precendence = 0, and therefore error returned when trying to save to PBI Desktop:

"Failed to save modification to the server. Error returned:...contains Calculation Group...with invalid precedence = '0'. Calculation Group precedence must be greater or equal zero and unique within Model.
![image](https://user-images.githubusercontent.com/16250667/87505969-d8b93380-c62f-11ea-87df-83c588d107c6.png)

**Comment by marcosqlbi** [comment]
Can you provide the detailed steps? I'm using the 2.11.6 version and I'm not able to reproduce the problem described.

**Comment by MicahDail** [comment]
Hey Marco!! :-)

I'll update to 2.11.6 in the morning and check.

**Comment by MicahDail** [comment]
So i updated to 2.11.6 and got the following error. I have uninstalled Tabular Editor and PBI desktop, rebooted, installed Tabular Editor 2.11.6 and PBI Desktop July, rebooted, and have tried multiple different .pbix files that were working fine before, but still this error. This is probably a me problem and the issues I have with my work-provided machine or some sort of policies.

"This object does not have any child collections."
![image](https://user-images.githubusercontent.com/16250667/87568218-eb148b00-c68a-11ea-8ee7-15206905386f.png)

**Comment by marcosqlbi** [comment]
Can you provide a sample PBIX file you created and give me instructions to reproduce the issue?
Did you enable the preview feature “Store datasets using enhanced metadata format” in the Power BI options? This is required in order to create calculation groups, even though it does not seem related to the issue you describe.

**Comment by MicahDail** [comment]
Looks like the issue is related to my .pbix file. I have confirmed with other models that I neither get the "child collections" error nor do I get the precedence error that started this ticket. I can't share with you the .pbix due to data sensitivity, but I am attaching a .pbit file for you. You should find that you get the "child collections" error when opening this model in Tabular Editor.

Feel free to consider this issue resolved, though.
[tabular_editor_issue_528.zip](https://github.com/otykier/TabularEditor/files/4928344/tabular_editor_issue_528.zip)

**Comment by marcosqlbi** [comment]
I see that the PBIT file cannot be open at all from Tabular Editor producing the same message. Maybe @otykier want to take a look at this.

**Comment by MicahDail** [comment]
I'm going to go ahead and close this issue because the original 2nd calc group error is no longer present, and clearly not a real problem. I will open a separate issue for the 'child collections' issue.
