### ISSUE TITLE
Data source Updation from Oracle to SQL DB

### ISSUE THREAD

**Issue by DSwain1996** [otykier/TabularEditor#529]
Hi ,

We have around 50 Tabular Models which have Oracle as the main Data source .
Now we have completely moved to Azure and now we want the Cube to use  Azure SQL Data Warehouse Connection. 
In the image attached i can update all the highlighted items using the Scripting option in one go.
Some things i am struggling to update is the **kind** option inside tabular editor as that option is not present in data source credentials . Another thing i am not able to do is bulk update of all table partitions schema name from DWSSAS (Oracle)  to dbo (SQL ADW)  as can be seen in schema screenshot. Can you help me with any workarounds or scripts .
![Data Source'](https://user-images.githubusercontent.com/55327056/87518798-5d429b00-c69e-11ea-97a8-063ab48996f1.png)
![kind](https://user-images.githubusercontent.com/55327056/87518807-5e73c800-c69e-11ea-9064-afb621e328f9.png)
![Schema](https://user-images.githubusercontent.com/55327056/87519004-a1ce3680-c69e-11ea-977c-c9b6cf9b63cf.png)

**Comment by otykier** [comment]
Regarding the data source credentials, please make sure to update to the latest version 2.11.6. This lets you access all properties of the Credential dictionary like so:

```csharp
var ds = Model.DataSources.First as StructuredDataSource;
ds.Credential["Kind"] = "SQL";
```

The partition schema name is more tricky. If “DWSSAS” does not occur anywhere else in the M expression, you can use a simple string replace:

```csharp
foreach(var p in Model.AllPartitions.OfType<MPartition>())
{
    p.Expression = p.Expression.Replace("DWSSAS", "dbo");
}
```

**Comment by DSwain1996** [comment]
@otykier : This works perfectly.
Thanks a lot again almost saved a week's work for us .
