### ISSUE TITLE
Getting missing DLL dependencies error

### ISSUE THREAD

**Issue by snama2020** [otykier/TabularEditor#535]
I am getting the above error where it says SQL AS AMO library is required. I have downloaded and installed AMO library(latest) but I am still getting this error. Tabular editor used to work for me without any issues but I am getting this error since the last few versions. I am not sure how to resolve this issue. Appreciate any help in fixing this issue. Please let me know if you need additional information from me.

Thanks in advance.

![image](https://user-images.githubusercontent.com/38735775/87745195-e814ba00-c7b2-11ea-98c3-f4b6f878075d.png)

**Comment by otykier** [comment]
Please try to delete everything in your `%programdata%\TabularEditor` folder.

**Comment by snama2020** [comment]
Thanks for the quick reply. I tried that and unfortunately it didn't work. I also uninstalled Tabular Editor and re-installed the latest version but no luck. 

I will be miserable with this tool. Please help.

**Comment by otykier** [comment]
What happens if you download the portable version from the release page, unzip it somewhere on your machine, and run the executable from there?

**Comment by snama2020** [comment]
WOW! That worked.

Though this option makes me functional, enquiry minds may want to know what/where is the issue 😊 It could be my issue(configurations, pre-requisites etc.)

I also wanted to let you know that, when I choose Tabular Editor from External Tools, I still get the same error.

Thanks,
SN

**Comment by otykier** [comment]
Yeah, I’m not sure why this happens. Maybe you have some incompatible version of the AMO installed in your machines GAC. In any case, to make it work with External Tools, try to copy the contents of the portable .zip into the folder where Tabular Editor was installed when you used the .msi file.

**Comment by snama2020** [comment]
I wanted to try your suggestion but the weird thing I noticed is I am not able to find the location of the Tabular Editor installation folder. I turned on view hidden as well. And tried to install it again in a location where I can easily get to but the folder doesn’t show.

**Comment by otykier** [comment]
This is weird indeed. Sounds like maybe some security policies are enabled on your machine, that prevents you from accessing the installation folder - this may also explain why Tabular Editor couldn't find the DLLs in that folder.

If you can access the `%commonprogramfiles(x86)%\microsoft shared\Power BI Desktop\External Tools` folder on your machine, you should be able to manually edit the tabulareditor.pbitool.json file in that location, to point the "path" property to the location of TabularEditor.exe that you obtained from the portable (zip) file. This should let you launch Tabular Editor from inside PBI Desktop without the DLL issue occuring.

**Comment by snama2020** [comment]
Thank you so much for your prompt response and help. I will try to check with our security team and will also try the option you provided.


Thanks,
Sri

**Comment by otykier** [comment]
Sure - no problem. Feel free to reopen the issue or post a new one if you have any further questions.
