### ISSUE TITLE
Tabular Editor-> PowerBI->External Tools->icons greyed out

### ISSUE THREAD

**Issue by TedFranklin54** [otykier/TabularEditor#536]
Hi, 
I've experienced 'greyed out' icons in PBI Desktop for both DAX Studio and TE? i've checked the json file and all looks ok but i can't access any of those add-ins. Any ideas?

**Comment by otykier** [comment]
You must enable the Enhanced Metadata preview feature for the external tools to be enabled. Make sure you understand the [implications](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata#considerations-and-limitations) and keep a backup of your .pbix just in case.
