### ISSUE TITLE
Change CamelCase to Proper Case Script

### ISSUE THREAD

**Issue by markendicott** [otykier/TabularEditor#537]
Hi Daniel, 
I haven't done any previous C# coding, and I was wondering if you would have the time to provide an edit to your script that will change all objects written in the following format: **all_lower_case_with_underscore_separation** to proper case?

I guess this could be an easy fix, but I've been reading some of your links for a couple of hours and I'm really not sure where to start, seeing the finished change to compare with the 1st script would really help my learning. 

Many thanks,

**Comment by otykier** [comment]
This is a modification of the [CamelCase to Proper Case script](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#camelcase-to-proper-case), which changes the first letter of a name and every letter following and underscore to uppercase. In addition, underscores are replaced with spaces.

```csharp
foreach(var obj in Selected.OfType<ITabularNamedObject>()) {
    var oldName = obj.Name;
    var newName = new System.Text.StringBuilder();
    for(int i = 0; i < oldName.Length; i++) {
        // First letter should always be capitalized:
        if(i == 0) newName.Append(Char.ToUpper(oldName[i]));

        // When an underscore is encountered, replace it with a space and insert the next letter as uppercase:
        else if(i + 1 < oldName.Length && oldName[i] == '_')
        {
            newName.Append(" ");
            newName.Append(Char.ToUpper(oldName[i + 1]));
            i++;
        }
        else
        {
            newName.Append(oldName[i]);
        }
    }
    obj.Name = newName.ToString();
}
```

**Comment by markendicott** [comment]
@otykier - Thank you so much for this, I see it was a simple change, so has helped with my understanding.
