### ISSUE TITLE
Question about documentation (not an issue!)

### ISSUE THREAD

**Issue by JBJ2110** [otykier/TabularEditor#539]
I am curious if there is more detailed documentation on the Tabular Editor. I am exploring the tool (it is AMAZING), and find I have a lot of questions. Most of my questions are pretty basic, and I really don't want to post them here in the **Issues** section because they are not Issues. Do you have suggestions as to a) where there is more detailed documentation that I can read or b) where I should post questions so that they don't gum up the **Issues** area?

**Comment by otykier** [comment]
Here is a compilation of the learning material available online (there's possibly many other blogs/articles with more specific content out there, but these are the most comprehensive as far as I know):

My content:
- [Tabular Editor Wiki](https://github.com/otykier/TabularEditor/wiki) (overview of articles in side-bar)
- [4-part webinar series](https://www.youtube.com/playlist?list=PLn1m_aBmgsbGvz4SsmO_fkeThjDUSWFkf)
- [Tabular Editor blog](https://tabulareditor.com/blog.html)

Community content:
- [An introduction to Tabular Editor](https://github.com/itsnotaboutthecell/Power-BI-Sessions/tree/master/An%20Introduction%20to%20Tabular%20Editor) - excellent guide and tutorial (with videos) created by Alex Powers.
- [Introduction to Tabular Editor for Business Users](https://exceleratorbi.com.au/introduction-to-tabular-editor-for-business-users/) - Power BI focused introduction to Tabular Editor scripting by Matt Allington.

Even though it's called "issues", questions of any kind are more than welcome as well, so please don't hesitate to post them here! I'm not able to change the title of the tab, as it's standard for all GitHub projects to have "issues".

**Comment by JBJ2110** [comment]
Thank you so much Daniel! I will take you up on your offer, but will preface my entry with "Q:" so you know that it isn't an issue. I am trying to compile a set of documentation for folks like me, who are **not** coming from an Analysis Services background. Because I don't have that background, so I have to learn all of these things from scratch! :) I am sure there are lots of people like me out there.
