### ISSUE TITLE
Aggregate Table Configured in .pbix -> 'This object does not have any child collections.'

### ISSUE THREAD

**Issue by MicahDail** [otykier/TabularEditor#541]
I think I have isolated a 'This object does not have any child collections.' error to the existence of a configured aggregate table in .pbix.

I've attached a .zip with two .pbit's containing exactly the same (simple) model, both of them having the same tables and storage modes, and only one of them having an agg table **configuration**. The one without the agg configuration is able to be opened by Tabular Editor, while the one with the aggregate config is not, producing a "This object does not have any child collections' error.

**Comment by MicahDail** [comment]
[issue_541_childcollection.zip](https://github.com/otykier/TabularEditor/files/4956317/issue_541_childcollection.zip)

**Comment by herbalt** [comment]
The model I have is a composite model that also contains aggregations that has hit this same issue.

**Comment by otykier** [comment]
I've identified the issue and will provide a new version with a fix shortly.

**Comment by jesiong** [comment]
Im having this error "This object does not have any child collections." when launching Tabular Editor from a PBIX file with a composite model.  I dont have the error if the PBIX file is fully an import model or fully a direct query model.

**Comment by otykier** [comment]
Fixed in [2.11.7](https://github.com/otykier/TabularEditor/releases/latest).
