### ISSUE TITLE
 'TabularEditor.exe' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by DSwain1996** [otykier/TabularEditor#543]
I am passing the bollowing command line command : TabularEditor.exe "$(ModelFilePath)"  -S "$(SetConnectionStringFromEnv)" -Deploy "Provider=MSOLAP;Data Source=$(AASServerUrl);User ID=$(AASAdminUser);Password=$(AASAdminPassword)" "$(ModelName)" -O -C -V -E

This was working fine till yesterday but suddenly today it says : **'TabularEditor.exe' is not recognized as an internal or external command,**
I ran the same command in the self hosted VM and it is running fine but from devops it throws this error .
Any idea why i am getting this error @otykier 

![image](https://user-images.githubusercontent.com/55327056/88257988-ad43e200-ccdc-11ea-98f6-f8ce37935598.png)

**Comment by DSwain1996** [comment]
Just figured out a workaround 

Added the tabulareditor.exe path ‘C:\Program Files (x86)\Tabular Editor\” in the task working directory and verified. The release pipeline was able to pick the exe and perform the command.
But still not sure why without specifying in the working directory it fails as i have define it in the system variables .

**Comment by otykier** [comment]
Not sure why you suddenly faced this issue. Perhaps a configuration change to the self-hosted build agent? In any case, this is not an issue related to Tabular Editor so I'm closing the issue.
