### ISSUE TITLE
Conditional Formatting for calculation group individual items.

### ISSUE THREAD

**Issue by shahin3723** [otykier/TabularEditor#545]
Hi ,

Apparently, there is no way to do conditional formatting based on individual items in calculation group which is greatly required.

**Comment by otykier** [comment]
Have you tried to set the FormatStringExpression on each calculation item?

You can set this through the property grid, or by using the dropdown at the top of the Expression Editor:

![image](https://user-images.githubusercontent.com/8976200/88314743-a84f5480-cd15-11ea-9d33-edda6857ba3a.png)

Remember that this is a DAX expression that must return a string, so if you provide a hardcoded format string you must enclose it in double quotes.

**Comment by shahin3723** [comment]
Thanks for your response. Yes format string expression works fine for formatting however, what I need is changing font colour and add icon based on values of calculation items. 
Regards,
Shahin

**Comment by otykier** [comment]
Font colors is not something you can add to a tabular data model. For icons, you can add a KPI to a measure. But in any case, it sounds like your question should be asked to the Power BI forums, since it’s not really related to Tabular Editor.
