### ISSUE TITLE
Refresh error in PBI Premium/Embedded when deploying from DevOps Pipeline

### ISSUE THREAD

**Issue by julmoser** [otykier/TabularEditor#548]
I've followed along the blog series to integrate [Tabular Editor into a DevOps Workflow](https://tabulareditor.com/2019/10/17/DevOps4.html) and adapted it to deploy to a Power BI Workspace with Embedded Capacity added and XMLA read/write enabled.
Deployment of the model to the workspace works with the info/warning for all tables in the model, e.g.: 
"Unprocessed object: partition 'DimCustomer' on table 'DimCustomer' (NoData)" 
When I then try to refresh the dataset in the Power BI service, it throws me the error:
"Data source error: Keyword not supported: 'driver'.. The exception was raised by the IDbConnection interface. Table: DimProduct"

When I deploy exactly the same model from the Tabular Editor GUI however, refreshing the dataset in the Power BI Service works like a charm.

I am using the same connection string from the GUI and in the Azure DevOps pipeline in the format (username and password integrated in the connection string, user Admin to PBI workspace and without MFA):
- Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/tabularmodel;User ID=<...>;Password=<...>

Any idea what could cause that?

**Comment by otykier** [comment]
Could you try to connect to the Power BI workspace using SSMS, and script out the data source in both datasets (the dataset that was deployed through Tabular Editor GUI and the one that was deployed through your DevOps pipeline). Then, compare the two TMSL scripts, to see if there are any differences in the data source properties or connection string, and adjust the script / pipeline accordingly.

**Comment by otykier** [comment]
Hi @julmoser - are you still facing issues refreshing your PBI model? If not, can we close this issue?

**Comment by julmoser** [comment]
Hi @otykier the issue has been resolved by comparing the two connection strings as you suggested, the one in DevOps has indeed been formatted in a different way. You can close the issue.
