### ISSUE TITLE
Perspectives not saved correctly to folder

### ISSUE THREAD

**Issue by dybzon** [otykier/TabularEditor#55]
When saving a tabular model to folder, the perspectives are saved to the database.json file in the root folder, instead of being saved to separate json files for each perspective in a perspectives folder.

Tabular Editor version: 2.3.6334.18527

To reproduce:
Open a tabular model, and go to Preferences-->Save to Folder and check the checkbox for perspectives under Serialization levels. Then save the tabular model to folder.

**Comment by otykier** [comment]
This was fixed in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
