### ISSUE TITLE
Create new partition from existing partition

### ISSUE THREAD

**Issue by huyza** [otykier/TabularEditor#551]
Hi. Just stumbled upon Tabular Editor. So far such a great app!
I have a question. Is it possible to create new partitions from an existing partition within a table and disable it's refresh except for one? I want to split my data into yearly historical partitions where it won't ever need to be refreshed except for the current year's data.

**Comment by marcosqlbi** [comment]
You can manage partitions in Analysis Services, they are not supported by Power BI Desktop.

**Comment by otykier** [comment]
In case this question is regarding SSAS or AzureAS the answer is the following:

It's not possible to mark a partition such that it will be automatically excluded from refreshes (for tables, however, you can do it using the `ExcludeFromModelRefresh` property).

Instead, you should create a refresh TMSL that includes only the partitions that you actually want to refresh. Tabular Editor can help you create that TMSL script:

![image](https://user-images.githubusercontent.com/8976200/89015566-878b8e00-d317-11ea-922e-b47f2c67bc51.png)
