### ISSUE TITLE
Tabular Editor Auto Creates a DateTableTemplate and Several Other DateTables

### ISSUE THREAD

**Issue by chaiwa-berian** [otykier/TabularEditor#552]
I opened my tabular model in **Tabular Editor** via **Power BI External Tools**, and I see **one DateTableTemplate** table and several other **DateTables** equivalent to the **number of date columns from all the tables** in the model. The tables are named like this _`DateTableTemplate_53700851-b248-423c-b697-d6fce94d6922`_ or _`LocalDateTable_7fa006a0-7443-42e5-b82f-7c680d244d2b`_, and a lot of **relationships have been auto-detected**. The tables are **hidden** but they **fail Best Practices Analysis**, I am hesitant on deleting them as I am not too sure as to why **Tabular Editor** is adding them to the model. Would you kindly help me understand their purpose and **what triggers their addition**? They are **not visible in Power BI,** which is okay,but I am curious about **where they come from** and **for what reason**.

Thanks.

**Comment by marcosqlbi** [comment]
It is not Tabular Editor, it is your Power BI doing that.
Read this article and disable auto date-time: https://www.sqlbi.com/articles/automatic-time-intelligence-in-power-bi

**Comment by zenzeinet** [comment]
They are powerbi desktop auto generated date tables for each date column.
Power BI desktop generates them, not tabular editor. They are hidden but
there, Te just shows them
If you don't want them, disable its generation within pbid (there's an
option)

**Comment by JBJ2110** [comment]
@chaiwa-berian --You just highlighted one of the cool things about Tabular Editor--it shows these tables. You can't see them in the Power BI Desktop, but you can in the Tabular Editor.

**Comment by chaiwa-berian** [comment]
Thank you everyone. Learning both at the go, and thank you for pointing me to the resources. I now do understand they auto-generated by Power BI and checking off auto date/time option in Power BI did the magic!

**Comment by JeridInsight** [comment]
@marcosqlbi I already knew all the stuff from the discussion above ^^^^, but what I wonder is why you can't change this setting from Tabular Editor?  Is it because this is not a property in the T.O.M. that can be tweaked?  Is it something that only lives in the MS. .pbix file format, and when a model is opened in Desktop, it generates these calculated tables and sets them to hidden.
