### ISSUE TITLE
What Is The Expression Syntax/Language Used In The Rule Expression Editor

### ISSUE THREAD

**Issue by chaiwa-berian** [otykier/TabularEditor#553]
Are the **operators** used in generating the **Rule Expression** for **Best Practice Analyser(BPA)**,  **C#-like** or are they based-off some other expression syntax/language? I see **rules** being written with expressions like **Model.Cultures.Count = 0** which I expect to be an **assignment** but it is being used as a **predicate/condition**! I expected it to be like **Model.Cultures.Count == 0**, but the former is being used consistently in all the rules I have seen from the **BPA Repo**, so far. 

My assumption was since **Tabular Editor** is built using **C#,** the _operators_, _syntax_ and _semantics_ were **C# complaint**? Or is the Rule Expression Editor **overriding** the **C# operators**, and how can I get to know the **valid operators** for **predicates/conditions** used when creating a **BPA Rule**?

**Comment by otykier** [comment]
They are [Dynamic LINQ](https://github.com/zzzprojects/System.Linq.Dynamic/wiki/Dynamic-Expressions).

More information [here](https://github.com/otykier/TabularEditor/wiki/Best-Practice-Analyzer#rule-expression-samples).

**Comment by chaiwa-berian** [comment]
Thank you @otykier , this is appreciated.
