### ISSUE TITLE
Feature Request: Edit connection options

### ISSUE THREAD

**Issue by toddmcdermid** [otykier/TabularEditor#554]
Power Query connections have an "options" section that can contain properties such as a command time out. Even if this option has been specified in other tooling, it's not visible in Tabular Editor.

{
  "createOrReplace": {
    "object": {
      "database": "SampleDatabase",
      "dataSource": "DataSourceName"
    },
    "dataSource": {
      "type": "structured",
      "name": "DataSourceName",
      "connectionDetails": {
        "protocol": "tds",
        "address": {
          "server": "server.database.windows.net",
          "database": "DatabaseName"
        },
        "authentication": null,
        "query": null
      },
      "options": {
        **"commandTimeout": "P1H"**
      },
      "credential": {
        "AuthenticationKind": "UsernamePassword",
        "kind": "SQL",
        "path": "server.database.windows.net;DatabaseName",
        "Username": "username",
        "EncryptConnection": true
      }
    }
  }
}

**Comment by otykier** [comment]
Fixed in [2.11.7](https://github.com/otykier/TabularEditor/releases/latest).

I exposed a new property, `Options` on Structured (Power Query) Data Sources, which let you add name-value properties.
