### ISSUE TITLE
Structured source "EncryptedConnection" property saving as string instead of boolean

### ISSUE THREAD

**Issue by toddmcdermid** [otykier/TabularEditor#557]
Good day,

TYVM for the options addition for structured sources. The latest code seems to have also altered behaviour of the editor saving other connection properties. The connection credentials now save the "EncryptConnection" property with a value of "True" instead of true (no quotations). The editor complains of a cast error, and so does the server when attempting to deploy.

Specifically:
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "username",
          "EncryptConnection": "True",
          "PrivacySetting": "Private"
        }
Should be:
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "username",
          "EncryptConnection": true,
          "PrivacySetting": "Private"
        }

TIA

**Comment by otykier** [comment]
Thanks for the feedback. Fixed in [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0).
