### ISSUE TITLE
Question: Creating a calculated column

### ISSUE THREAD

**Issue by JBJ2110** [otykier/TabularEditor#558]
OK, I am feeling mighty foolish, but for the life of me, I can't see how to create a calculated column in the TE. I have tried right clicking on an existing column, on a table name, looking at the available commands on the ribbon. What am I missing? Thanks so much!

**Comment by otykier** [comment]
Am I correct in assuming you're editing a Power BI model with Tabular Editor? Adding calc columns to a Power BI model is disabled by default, as [this scenario is not currently supported](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).

If you want to experiment, you can put a checkmark in "Allow unsupported Power BI features" under File > Preferences, but keep in mind that doing so will allow you to make unsupported changes that could potentially break or corrupt your .pbix file - and Microsoft Support will not help you in that case!

If you're working with an Analysis Services tabular model, please re-open the question, as that would be a bug in Tabular Editor.

**Comment by JBJ2110** [comment]
Thank you! I am relieved that it wasn't blindingly obvious and I was overlooking it! Thanks for all you do for the community!
