### ISSUE TITLE
Questions: CLI - Schema Validation

### ISSUE THREAD

**Issue by Daandamhuis** [otykier/TabularEditor#562]
Is it possible to keep the errors with the -SC switch, without reporting the Warnings to Azure DevOps? Somethings, like remove columns from model but not the view, we do on purpose and it's giving a lot of warning when performing the schema validation.

**Comment by otykier** [comment]
Please see [this post](https://github.com/otykier/TabularEditor/issues/449#issuecomment-623149073). Let me know if this does not solve your issue.
