### ISSUE TITLE
Missing culture nb-NO, Norwegian Bokmål (main norwegian culture)

### ISSUE THREAD

**Issue by aslakjonhaugentalentech** [otykier/TabularEditor#563]
When you try to make a new translation to the main culture in Norwegain, nb-NO is missing. I can find nn-NO, but that is the second culture in Norway. nb-NO is the main culture.
![image](https://user-images.githubusercontent.com/69350343/89643391-ee7bea80-d8b5-11ea-98b8-fbb547054613.png)

**Comment by otykier** [comment]
The list is sorted alphabetically. Use incremental search (type "n" and "b" in quick succession) to locate bokmål:

![image](https://user-images.githubusercontent.com/8976200/89643949-29325280-d8b7-11ea-9acb-2da87b92a0e5.png)

**Comment by aslakjonhaugentalentech** [comment]
OMG … Sorry! And Thanks!


Regards
Aslak
