### ISSUE TITLE
Excel datasource doesn't appear in Tabular editor using enhanced metadata format

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#564]
Hello Daniel,
When I add data from an Excel file in a new empty report I just created in the desktop :

1. If I dont check "Store datasets using enhanced metadata format", 
A datasource appears in Tabular editor

2. If I check "Store datasets using enhanced metadata format"
A datasource doesn't appear in Tabular editor

Is it a normal behaviour ?

Thanks in advance
Didier Terrien

**Comment by otykier** [comment]
I am not an expert in how PBI stores the data source metadata, but specifically for Excel files, it looks like the table partition contains the full M query which also holds a reference to the Excel file itself:

![image](https://user-images.githubusercontent.com/8976200/89774666-9851b600-db06-11ea-9590-bbab87e08ed7.png)

It is very likely that this has changed with the enhanced metadata format, which would explain why things were stored differently before.

If you have Power Query queries that are not loaded in PBI Desktop (i.e. "Enable load" has been disabled), then you can usually find the corresponding M expressions under "Shared Expressions" in Tabular Editor:

![image](https://user-images.githubusercontent.com/8976200/89774868-f4b4d580-db06-11ea-8a97-e65f9f0a96de.png)

**Comment by didierterrien** [comment]
Thanks a lot ! Perfectly clear
