### ISSUE TITLE
Model is missing "Other" group of properties

### ISSUE THREAD

**Issue by Will849** [otykier/TabularEditor#569]
Version 2.7.4 contains "Other" group of Model properties and that group contains Culture of Model as seen in the picture.
![image](https://user-images.githubusercontent.com/55695327/90270210-1e992f80-de5a-11ea-9636-4118589ff6d5.png)
However the latest version (2.11.7) does not contain "Other" section and therefore it is impossible to change culture of model (I suppose you could do it in advanced scripting but haven't been able to find out how).
This is tremendously useful for organizations using Power BI because once the model is created it is impossible to change the culture within Power BI and sometimes report creators start with Power BI in their local language and not English and afterwards the report is inconvenient to use.
Could the "Other" section of Model properties be brought back?

**Comment by otykier** [comment]
The Model Culture and other properties are only shown when “Enable unsupported Power BI features” is checked under File > Preferences.

**Comment by Will849** [comment]
Thank you very much for lightning fast answer, I could have looked in the preferences. Once again many thanks, this is a huge help.
