### ISSUE TITLE
Edit Table Properties

### ISSUE THREAD

**Issue by moonsjine** [otykier/TabularEditor#57]
This is already a very nice tool. Are you also planning to add a feature that will allow the table query properties to be edited (or at least displayed) ? Especially when the query that returns the table content is not a view but SQL code it would be nice to be able to edit that.

 "partitions": [
          {
            "name": "xxxxx",
            "source": {
              "**query": [
                "SELECT",
                "    column1 AS [A]",
                "   ,column2 AS [B]",
                "   ,column3 AS [C]",
                "FROM",
                "    [schema].[table]",**
              ],

**Comment by otykier** [comment]
Hi @moonsjine 

Glad you like the tool :-)

Viewing/editing partition properties is already possible. If you select a table in the Explorer Tree, you should see that there is a "Partitions" property. Clicking the ellipsis button (see picture below), will open a new window where you can view each partition, as well as edit the source query.

![image](https://cloud.githubusercontent.com/assets/8976200/26024593/b19d688a-37d4-11e7-83dd-c3b201e418de.png)

Closing this issue, but feel free to reopen or create a new issue if you have any further questions.
