### ISSUE TITLE
Tabular Editor CLI async output problem

### ISSUE THREAD

**Issue by IvanovOleg** [otykier/TabularEditor#571]
Hello,
I am trying to create a CI/CD pipeline in Azure DevOps for PowerBi models. I faced an issue that any kind of tabular editor cli command returns exit code 0 right after execution and doesn't wait until that command is finished. As a result, Azure DevOps pipeline shows success and terminates a deployment job, but at that point in time deployments is not finished. To avoid this problem I have to add StartSleep to wait for a minute which is annoying. If you execute a deployment command from the powershell core terminal it behaves the same (doesn't block terminal and you can input the other commands).

**Comment by otykier** [comment]
Could you let me know exactly how you're executing TabularEditor.exe from your DevOps pipeline? I'm using a regular Command Line task, where the call to TabularEditor.exe is the only command being executed, and this way, it seems that there are no issues in having the DevOps pipeline wait for the process to complete before moving on to the next task.

I suspect you may have one or more commands following the call to TabularEditor.exe, or maybe you're using YAML or some other technique to launch the tool. In this case, try to use the `start /wait` technique as shown [here](https://github.com/otykier/TabularEditor/wiki/Command-line-Options).

**Comment by IvanovOleg** [comment]
@otykier I am using the Powershell@2 task. I will try to use the start /wait prefix. thanks!

**Comment by IvanovOleg** [comment]
@otykier start /wait doesn't work in Powershell Core 7. I will try cmdline.

**Comment by IvanovOleg** [comment]
@otykier Azure DevOps Cmdline task doesn't output any log from the tabular editor

**Comment by otykier** [comment]
Using a command line task configured as follows:

<img width="793" alt="Screenshot 2020-08-15 at 13 43 07" src="https://user-images.githubusercontent.com/8976200/90311636-45f50880-defd-11ea-9d74-bd7e7ab4af81.png">

I get the following log output:

<img width="955" alt="Screenshot 2020-08-15 at 13 41 33" src="https://user-images.githubusercontent.com/8976200/90311625-1f36d200-defd-11ea-93fd-4a8b3b37e933.png">

Please note the following:

- I'm using command line Task Version 2.*
- I do not specify start /wait
- There is only a single command in the script
- I use the `-V` switch to instruct Tabular Editor to format the output in a way that makes sense to DevOps

**Comment by IvanovOleg** [comment]
@otykier Yes, it works! Thanks!
