### ISSUE TITLE
Creating Calculation Items with script

### ISSUE THREAD

**Issue by CharlieMather** [otykier/TabularEditor#572]
Daniel,  I see scripting support for creating a new Calculation Group, But I do not see support for creating Calculation Items. Am I missing something, or will that be a future enhancement?

**Comment by otykier** [comment]
This should do the trick:

```csharp
var cg = Model.AddCalculationGroup("Time Intel");
var ci1 = cg.AddCalculationItem("YTD", "TOTALYTD(...)");
var ci2 = cg.AddCalculationItem("MTD", "TOTALMTD(...)");
// etc...
```

**Comment by CharlieMather** [comment]
Daniel, Thanks!.  I see that AddCalculationItem() does the trick,  It is not exposed in the IntelliSense.
