### ISSUE TITLE
Exception error when attempting to duplicate a calculation group

### ISSUE THREAD

**Issue by ImkeF** [otykier/TabularEditor#574]
HI Daniel,
the UI offers me to duplicate a calculation group.
But this triggers an unhandled exception error.
When clicking "Continue" the program doesn't crash, but it ignores further activities (at least, I cannot add a new calculation group).
So have to close  the program and reopen.
No big thing, though.

![image](https://user-images.githubusercontent.com/18321412/90732191-06e30080-e2cb-11ea-9381-9c4b0e98543c.png)

**Comment by otykier** [comment]
Fixed in [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0).
