### ISSUE TITLE
Deployment failing when deploying over existing dataset with Incremental Refresh

### ISSUE THREAD

**Issue by RuiRomano** [otykier/TabularEditor#575]
When deploying over an existent  dataset with Incremental Refresh active fails with "Object Reference not set to an instance of an object".

Tested without Incremental Refresh and works fine.

Version: 2.11.7

**Comment by otykier** [comment]
Fixed in [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0).
