### ISSUE TITLE
Help In creation of Dynamic Measure using Scripting

### ISSUE THREAD

**Issue by Vishy0501** [otykier/TabularEditor#578]
Hi @otykier ,

How can we create a single measure using three different measure for example for creating Dynamic measures(switch)
i.e. i selected three measures from the editor and need a single measure like Total Value = [Sales] + [Revenue] + [Margin]

**Comment by otykier** [comment]
I'm sorry, I didn't notice that the question was regarding scripting.

If I understand your question correctly, you want to create the dynamic measure using a script, based on a current selection of measures?

This is certainly possible, but you likely need to change your approach a little bit. First of all, you only need 1 dynamic measure, where as the script you created is going to add one dynamic measure foreach of the selected measures. Next, it seems that you already have a hardcoded measure called `[MetricSelection]` which returns a number based on the current selection on the disconnected table. However, when Tabular Editor's script is looping through a selection of measures, the order is not guaranteed. So it's better to use the measure names, assuming these exist in the `'Metric Selection'` disconnected table.

So I recommend you use a script that does two things:

1. Update the expression of the `'Metric Selection'` table to hardcode the names of the currently selected measures.
2. Create a single dynamic SWITCH measure.

```csharp
// Assumes the model already holds a 1-column calculated table called 'Metric Selection':
var disconnectedTable = Model.Tables["Metric Selection"] as CalculatedTable;

// Name of the single column on 'Metric Selection':
var disconnectedTableColumnName = "Value";

// Name of the dynamic switch measure, to be created (if it doesn't already exist) on the disconnected table:
var dynamicMeasureName = "Dynamic Metric";

// Make sure that the dynamic measure exists on the disconnected table:
if(!disconnectedTable.Measures.Contains(dynamicMeasureName))
    disconnectedTable.AddMeasure(dynamicMeasureName);

// Generate DAX for disconnected table:
// {"Measure 1", "Measure 2", ...}
var disconnectedTableDax = "{\n    " +
    string.Join(",\n    ", Selected.Measures.Select(m => "\"" + m.Name + "\"").ToArray()) +
    "\n}";

// Generate DAX for dynamic metric:
// VAR _s = SELECTEDVALUE('Metric Selection'[Value]) RETURN SWITCH(_s, ...)
var dynamicMetricDax = 
    "VAR _s = SELECTEDVALUE('" + disconnectedTable.Name + "'[" + disconnectedTableColumnName + "])\n" +
    "RETURN SWITCH(_s\n    " +
    string.Join(",\n    ", Selected.Measures.Select(m => "\"" + m.Name + "\", " + m.DaxObjectFullName).ToArray()) +
    "\n    , [Total SALES]\n)";

// Assign DAX expressions:
disconnectedTable.Expression = disconnectedTableDax;
disconnectedTable.Measures[dynamicMeasureName].Expression = dynamicMetricDax;
```

If you're on Azure Analysis Services, SSAS 2019 or Power BI, remember that Calculation Groups can be used to achieve very much the same thing.

**Comment by otykier** [comment]
Inspired by this question, I posted [this article today](https://tabulareditor.com/2020/08/24/Generating-a-dynamic-measure-selector.html).

**Comment by otykier** [comment]
Closing this issue, but feel free to reopen or post a new one if this didn't solve your problem.
