### ISSUE TITLE
Invalid column references in perspective after deleting data column

### ISSUE THREAD

**Issue by dybzon** [otykier/TabularEditor#58]
I tried removing a data column from a table via Tabular Editor. The data column was included in one of the perspectives in my tabular model. The reference from the perspective to the data column was not deleted automatically when I deleted the data column.

To reproduce:
1) Create a table with multiple data columns, and include these data columns in a perspective
2) Delete one of the data columns through Tabular Editor
Result: The data column is removed, but the reference from the perspective to that data column still exists.
Desired result: The reference from the perspective to the data column should be deleted automatically when the data column is deleted.

**Comment by otykier** [comment]
This was fixed in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
