### ISSUE TITLE
BPA Rule on Column Level security applied on multiple Roles

### ISSUE THREAD

**Issue by DSwain1996** [otykier/TabularEditor#580]
Hi @otykier ,

I have 3 roles in my model named read ,confidential and confidential plus .
Confidential plus being the role which allows complete access to all columns in the model to users and some restrictions applied on other 2 role . We have complete CICD implemented using Tabular editor using your useful articles .
Now  I am trying to create a BPA rule which will be used in the Build pipeline to ensure that all the necessary columns in respective roles under column level security are selected and none of them are missed while deployment.
I have these columns stored in a excel file , now I want to have rule which checks if column level security for all the columns present in excel are selected in model before deployment. Is this check possible through BPA  or c# script?

**Comment by otykier** [comment]
It's not possible through BPA, as you cannot run custom code which is needed for loading data from the Excel file.

However, with a C# script, you have complete authority to execute any arbitrary code, so if you can find a .NET library that loads data from an Excel file, this should certainly be possible. Alternatively, if you can save your Excel file as a TSV or other text-based format, you can load the data in the file into Tabular Editor without requiring any external .NET libraries. [This example shows how to load data from a TSV file](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#generating-measures-from-a-file) (in this case, it's used to generate measures that are defined in a file).

In your script, use the `Error("message");` or `Warning("message");` [helper methods](https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting#helper-methods), when you encounter a column with missing security. These methods will output "message" to the console, such that your DevOps pipeline can react accordingly.

**Comment by DSwain1996** [comment]
@otykier : Thanks for pointing me to the right direction. I will try it out .
