### ISSUE TITLE
Unable to apply Conditional Formatting

### ISSUE THREAD

**Issue by ZakChotani** [otykier/TabularEditor#581]
I am unable to apply any conditional formatting when using Tabular Editor calculation group within a Matrix.
Is this feature currently unavailable or am I not looking in the right place?

**Comment by otykier** [comment]
When you say Conditional Formatting, are you talking about [Dynamic Format Strings](https://www.sqlbi.com/articles/controlling-format-strings-in-calculation-groups/)? If you're encountering an issue with the [Power BI feature](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting) please [report this is an issue](https://community.powerbi.com/t5/Issues/ct-p/PBI_Comm_Issues) to the Power BI team.

**Comment by ZakChotani** [comment]
Hello Daniel,
I mean conditional formatting. See the link below from Microsoft on it:


Conditional table formatting in Power BI Desktop - Power BI | Microsoft
Docs
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting?WT.mc_id=email

Attached is also a screen shot of gradient conditional formatting applied
on total units highlighting values based on their amounts highest to
lowest.

Is this possible to do with calculation groups,  I found no luck with it.
May be I am overlooking something?

Zak

**Comment by otykier** [comment]
I can't see your screenshot (not sure it gets added to the GitHub post when you reply by email).

I just tried adding a calc group to a Power BI model, and afterwards I was still able to add conditional formatting to a matrix visual without any issues.

Could you please provide some more details on what exactly isn't working for you? Maybe create a minimal .pbix file that reproduces the issue and upload it here? Thanks!

**Comment by ZakChotani** [comment]
Please find the attached and let me know if you have any questions.

**Comment by ZakChotani** [comment]
Hello Daniel,
I was wondering, if you had a chance to look at PBIX. Can you please let me
know if this is one of the limitations of using calculation groups? Or is
there a work around?

**Comment by PremGBS** [comment]
Hi Daniel, 

It is possible to do a conditional formatting to a calculated item in Power BI . I tried it works for normal columns , but for calculated columns - the selected value function doesn't work ..  example in the below screen shot , I have a table with calc group on columns and KPI's on rows  - Measure used is just to sum a column in a table. additionally I have created a measure as follows and used in conditional formatting 

 **if ( SELECTEDVALUE(KPI'[KPI] ,0)="Production Value",1,0),** 

it works fine for first two columns but not for the calculated columns like Delta % .. Any workaround / help would be highly appreciated. 

![image](https://user-images.githubusercontent.com/67706524/91486304-b0c51d00-e8c9-11ea-9ae7-4a482856862b.png)

**Comment by otykier** [comment]
@ZakChotani sorry, but I'm not able to see any attachments. I think you have to reply through GitHub if you want to add a file to the thread (replying by mail seems to get rid of any attachments).

@PremGBS may I ask you to share the .pbix as well (or just the .pbit if you don't want to share the data)?

**Comment by ZakChotani** [comment]
Hello Daniel,
Please find the PBIX below. Please note I had to zip the file because Githubs do not let you upload .pbix
Let me know if I am overlooking something here or is it a limitation of calculation groups?

[Conditional Format - Tabular Editor.zip](https://github.com/otykier/TabularEditor/files/5143667/Conditional.Format.-.Tabular.Editor.zip)

**Comment by PremGBS** [comment]
@ZakChotani , 

Check if this works .   
[Conditional Format - Tabular Editor.zip](https://github.com/otykier/TabularEditor/files/5144901/Conditional.Format.-.Tabular.Editor.zip)

**Comment by PremGBS** [comment]
[PH PnL_out (2).zip](https://github.com/otykier/TabularEditor/files/5144906/PH.PnL_out.2.zip)
@otykier , 

here is the PBIX file, i tried the same in @ZakChotani 's file , It works there  but when I try to use it in this at secondary header it doesnt work for calculated fields.

**Comment by ZakChotani** [comment]
> @ZakChotani ,
> 
> Check if this works .
> [Conditional Format - Tabular Editor.zip](https://github.com/otykier/TabularEditor/files/5144901/Conditional.Format.-.Tabular.Editor.zip)

I need to apply gradient formatting. For examples, highest amount being red, 0 being white and lowest being red. The ones in between would be lighter shades of red and green. The first one you sent to me makes everything green if positive and red if negative.

**Comment by ZakChotani** [comment]
Any updates on whether we can apply gradient formatting?

**Comment by otykier** [comment]
The technique using the hidden [color] measure is the correct approach. Just make sure it returns BLANK() for the calc items you don't want colored. Also, make sure to specify "Don't format" as the Default formatting (which is what the color will be set to, when the value of [color] is blank).

Please ask these kinds of questions on the Power BI forum going forward, as this is not related to Tabular Editor :-)

![image](https://user-images.githubusercontent.com/8976200/91961177-20446d80-ed0b-11ea-8838-a76a9a0202ba.png)
