### ISSUE TITLE
Pop Up after changes made to model via TB Editor doesnt show up

### ISSUE THREAD

**Issue by PremGBS** [otykier/TabularEditor#583]
Hi,

Usually after making changes to the model in tabular Editor , hitting the save button would push a pop up notification in Power BI desktop to implement the changes.. It is not showing up recently ( i.e from this morning ) . However refreshing one of the calc groups in Power BI desktop brings in all changes which are made in TBE

**Comment by otykier** [comment]
Are you talking about the yellow bar at the top of the screen in PBI? This generally shows up only when you add/rename/remove calc items from a calc table. Changing the DAX expression of the calc item does not require you to refresh the calc group table.

However, I've seen some cases where PBI in general doesn't "react" to changes made from Tabular Editor. For example, when updating a DAX expression on a measure, the visuals are not automatically updated. Unfortunately, I haven't been able to consistently reproduce this so far.

**Comment by PremGBS** [comment]
Yes, Thats what I am referring to .. Even while adding or removing calc Groups it doesn;t save .. but refreshing one of the calc groups in PBI Desktop fixes it immediately.
