### ISSUE TITLE
Copying calculated column with dependency results in unhandled exception crash

### ISSUE THREAD

**Issue by jamhos** [otykier/TabularEditor#584]
We have two calculated columns in a table - one "display" column and one "sort by" column.

I tried to copy the "display" column to another table using Ctrl+C / Ctrl+V. As soon as I did the paste, received an "Unhandled exception" error referencing the missing "sort by" column. Even if I copy them both at the same time, I receive the same error. 

The workaround is to copy the dependency ("sort by") column first, then the "display" column.

It's easy enough to figure out what went wrong and how to fix it, however it crashes Tabular Editor and you have to quit and reopen - would be nicer if it just popped up a message explaining what I'd missed.

![image](https://user-images.githubusercontent.com/59585318/91811511-f8a1c680-ec72-11ea-9c0d-a1aaf7102168.png)

Tabular Editor version: 2.11.5

P.S. Yes I know, the calculated columns shouldn't even be there in the first place.... ;)

**Comment by otykier** [comment]
Fixed in [2.12.2](https://github.com/otykier/TabularEditor/releases/tag/2.12.2). Thanks for reporting!
