### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#585]
**Describe the bug**
Even thought 2.12.1 is out, version 2.12.0 didn't suggest it upon opening (as it usually does) - and yes, this is selected within File->Preferences->General.
Also, when clicking 'check for updates within File->Preferences->General, it spins for a while and gives a timeout error (shown below).

Thanks!
![Timeout](https://user-images.githubusercontent.com/29556918/91840341-3a257800-ec59-11ea-8958-375d4314e9a1.png)

**Comment by otykier** [comment]
Thanks for reporting. 2.12.0 (and earlier versions), should now correctly indicate that a new version is available.

The timeout issue may be web proxy related. Looking into it.

**Comment by m-kovalsky** [comment]
Confirmed! Thanks!

**Comment by otykier** [comment]
Fixed in [2.12.4](https://github.com/otykier/TabularEditor/releases/latest). Thanks!

**Comment by m-kovalsky** [comment]
Thanks!
