### ISSUE TITLE
How do I address a Calculation Group Column?

### ISSUE THREAD

**Issue by FrankFromGermany** [otykier/TabularEditor#588]
var dateColumn = "DimDate[FullDate]";
var cg = Model.AddCalculationGroup("Time Intelligence");
cg.AddCalculationItem("Current", "SELECTEDMEASURE()").Ordinal=0;
...

Now I want to change the name of the Calculation Group's first column from "Name" to eg "Formula"

**Comment by otykier** [comment]
```csharp
cg.Columns["Name"].Name = "Formula";
```

...or, if the column was previously renamed...

```csharp
cg.Columns.First(c => c.SourceColumn == "Name").Name = "Formula";
```

**Comment by otykier** [comment]
Feel free to reopen or create a new issue if you still need assistance.
