### ISSUE TITLE
Creating Custom Actions: URL

### ISSUE THREAD

**Issue by DanShrader** [otykier/TabularEditor#59]
Hi, 

I'm hoping that someone may have run into this before and can help me out.

In [BIDS Helper](https://bidshelper.codeplex.com/wikipage?title=Tabular%20Actions%20Editor) you can have custom actions, particularly URL action.

I saw the custom actions editor in TabularEditor and did't know if it was the intent to allow it to do the same thing?

If so could someone post an example of a custom action which open a URL with the item data passed in?

Thanks

**Comment by marcosqlbi** [comment]
Custom action are not implemented in compatibility level 1200 (it was an "unsupported" feature in 1103 that BIDS Helper made available). We need MS to implement such a feature in the Tabular model.

**Comment by SQLBent** [comment]
Hi Dan,

Custom actions are not available for Tabular models (compatibility level 1200 nor 1400). The custom actions you might be referring are those mentioned in [this section](https://github.com/otykier/TabularEditor/wiki/Advanced-features#custom-actions). Custom actions for Tabular Editor is ways of saving advanced scripts for later use.

For all the new features of SQL 2017 you should go read [the updated documentation](https://docs.microsoft.com/en-us/sql/analysis-services/what-s-new-in-sql-server-analysis-services-2017).

I have updated the section with details about this and will close the issue. Feel free to open it again in case you have any further requests in regards to this.

**Comment by DanShrader** [comment]
Thanks all - I was thinking that, but saw the option and didn't know if the feature had been somehow add in with TabularEditor.
