### ISSUE TITLE
Does it support Azure blob storage as data source ?

### ISSUE THREAD

**Issue by akj2784** [otykier/TabularEditor#591]
I was checking the list of supported data sources in the tabular editor, but could not find Azure blob storage. However, the documentation does mention about its support. Would you be able to provide more details?

https://github.com/otykier/TabularEditor/wiki/Importing-Tables

Note: SSDT supports Azure blob storage and we are leveraging it in one of our tabular models.

**Comment by otykier** [comment]
As I mentioned in #590, Tabular Editor does not have good support for Power Query. You won't find the PQ UI that you may be familiar with. The only thing it lets you do, is edit the M expressions, but there is no intellisense, no color coding or validation or anything like that.

Most users of Tabular Editor either use Provider Data Sources (aka. Legacy) against relational databases, or they use Power BI or SSDT to create the basic model structure (data sources, tables, relationships), and then use Tabular Editor for fine-tuning the model.
