### ISSUE TITLE
run dmvs against new ExecuteCommand feature

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#592]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**
Is it possible to run DMVs using the ExecuteCommand and provide the output? The script below runs but when I add .Output(); to the end it gives an error. It seems its currently only possible to run such scripts (for processing tables etc) but not to return output in the case of a DMV.

var dmv = "SELECT * FROM $SYSTEM.MDSCHEMA_MEASURES";

ExecuteCommand(dmv);

**Describe alternatives you've considered**
I've tried all the options in the 'querying analysis services' section of the useful script snippets but none seem to do the trick.

**Additional context**
By the way, this EvaluateDax & ExecuteCommand is very cool - well done! Bit tricky without intellisense for DAX or for the EvaluateDax/ExecuteCommand functions but still great to see this sort of functionality coming to Tabular Editor :)

**Comment by otykier** [comment]
`ExecuteCommand` does not return anything by design. Use `ExecuteDax` instead:

```csharp
ExecuteDax("SELECT * FROM $SYSTEM.MDSCHEMA_MEASURES").Tables[0].Output();
```

**Comment by m-kovalsky** [comment]
Ah, very nice. Thanks!

**Comment by m-kovalsky** [comment]
Is it possible to store the value of the output as a string in the variable? The code below returns 'Table' instead of the [ID] value. Thanks!

var tableName = Selected.Table;

var tableID = ExecuteDax("SELECT [ID] FROM $SYSTEM.TMSCHEMA_TABLES WHERE [Name] = '"+tableName+"'").Tables[0];

tableID.ToString().Output();

**Comment by otykier** [comment]
Use the [Rows indexer on the DataTable](https://stackoverflow.com/a/13816531/1594867):

```csharp
var tableName = Selected.Table;

var tableID = ExecuteDax("SELECT [ID] FROM $SYSTEM.TMSCHEMA_TABLES WHERE [Name] = '"+tableName+"'")
    .Tables[0].Rows[0][0];

tableID.ToString().Output();
```

**Comment by m-kovalsky** [comment]
Thanks!
