### ISSUE TITLE
show query duration for ExcecuteDax & ExcecuteCommand functions after the execution completes

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#593]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would be curious to have the ExecuteDax & ExecuteCommand functions return the query duration time somewhere on the screen (possibly the output window). Not sure how easy it is but just an idea :)

**Comment by otykier** [comment]
How about this:

```csharp
var sw = new System.Diagnostics.Stopwatch();
sw.Start();
var result = EvaluateDax("1 + 1");
sw.Stop();
Info("DAX execution finished in: " + sw.ElapsedMilliseconds + " ms");
result.Output();
```

**Comment by m-kovalsky** [comment]
That works, thanks!
