### ISSUE TITLE
save to folder not working properly in 2.12.1

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#594]
**Describe the bug**
Save to folder only saves the database.json file, not the folder structure. This issue happens with version 2.12.1

**To Reproduce**
1. File -> Save to Folder (from a .bim file)

**Application specifics**
 - Tabular Editor version: 2.12.1

**Comment by otykier** [comment]
Please review the serialization settings under File > Preferences > Current Model

![image](https://user-images.githubusercontent.com/8976200/92205810-b5b83c80-ee86-11ea-9448-5505327e8355.png)

When you use the File > Save to Folder... option, these are the settings that will dictate the resulting folder structure, while "Use serialization settings from annotations" is checked:

ges.githubusercontent.com/8976200/92205935-f2843380-ee86-11ea-91b3-a42c555bdb22.png)

If you uncheck this checkbox, Tabular Editor uses the settings under File > Preferences > Serialization.

**Comment by m-kovalsky** [comment]
Hmm, that's really strange. I've never had to update the 'current model' tab until now. I always keep the serialization tab with the same settings as you have in your screenshot - and this always seemed to translate over to the current model. Not sure why the current model section got cleared out when I used 2.12.1. Thanks!

**Comment by otykier** [comment]
The settings on the "Current Model" tab are stored in an annotation on the Model object. Perhaps this annotation got cleared somehow on your Model.bim file?

![image](https://user-images.githubusercontent.com/8976200/92215706-79400d00-ee95-11ea-8546-89de15b3faae.png)

If the annotation doesn't exist (for example, if the Model.bim file was produced by SSDT), then Tabular Editor uses the default settings when serializing. Anyway - let me know if you find some inconsistent behavior. Closing this issue for now.

**Comment by m-kovalsky** [comment]
Yep, not sure exactly what happened. But, as you said it's good to check the current model tab. Thanks!
