### ISSUE TITLE
Calculation Group Issue

### ISSUE THREAD

**Issue by jtgooding2** [otykier/TabularEditor#597]
Maybe a BPA issue too, so BPA tells you that your hidden Ordinal column should have IsMDXAvailable set to false for your calculation group, if you modify it in tabular editor then Visual Studio will not open it as it is not a valid property on a calculation group column,  the actual error message is about the sortbycolumn for Ordinal, but the real issue is the IsMDXAvailable property being serialized into the object.  Remove the property from the BIM file and VS will load again, worth noting that VS does not show visibility to the property either.
Thanks.

**Comment by otykier** [comment]
Thanks for reporting. Indeed, this is an issue with the BPA rule. We certainly shouldn't set IsAvailableInMDX to false for visible columns or columns that are used as Sort By on other columns. Moreover, it doesn't even make any sense to use this flag on a calc group, as setting it to false only really impacts columns with a large cardinality (>> 10000 unique values) during refresh operations. I'll reference this issue over in the Best Practice Rules repo.
