### ISSUE TITLE
add text color for functions in advanced scripting window

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#598]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add text color to functions like Count(), Any(), Replace(), AddTable() - for any object type, Delete(), SetAnnotation(), GetAnnotation(), FormatDax(), EvaluateDax(), ExcecuteCommand(), ToString(), Where(), Append() etc.

**Additional context**
Think this would be helpful when reading & writing advanced scripts. Thanks!

**Comment by otykier** [comment]
I've tried to stick to the same syntax highlighting scheme as Visual Studio for C# code, where functions aren't color coded. Tabular Editor V3 will let you customise color schemes for both DAX and C# :-)
