### ISSUE TITLE
Import new table from existing Data source(PowerQuery)

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#599]
**What are you trying to achieve?**
I am trying to import tables from existing Azure SQL Datawarehouse Datasource , when i try to right click and select import tables 
the import tables wizard does not allow to import from existing datasource from the model .
Option is greyed out, is there something i am missing ?

![image](https://user-images.githubusercontent.com/55327056/92469109-e59e7180-f1f1-11ea-867d-05e4cc4d09ed.png)

![image](https://user-images.githubusercontent.com/55327056/92469159-fcdd5f00-f1f1-11ea-8cd9-441ef6b0b5f8.png)

**Comment by otykier** [comment]
Please see [this article](https://github.com/otykier/TabularEditor/wiki/Importing-Tables). The Import Table Wizard does not support Power Query data sources.

**Comment by debashish10** [comment]
Thank you @otykier
