### ISSUE TITLE
Add Microsoft.Office.Interop.Excel reference

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#600]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the following reference to Tabular Editor so that T.E. can communicate with Excel.

Microsoft.Office.Interop.Excel

This would be helpful for exporting data/metadata to Excel (instead of a text file) as well as reading metadata from an Excel file.

**Comment by otykier** [comment]
Add the following at the top of your script:

```csharp
#r "Microsoft.Office.Interop.Excel"

// ... your script here ...
```

More information: https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting#net-references

**Comment by m-kovalsky** [comment]
ah amazing, thanks!
