### ISSUE TITLE
Cannot enter other languages except English in the edit box

### ISSUE THREAD

**Issue by jasonlaw997** [otykier/TabularEditor#601]
Cannot enter other languages except English in the edit box

**Comment by otykier** [comment]
What edit box are you refererring to?

**Comment by jasonlaw997** [comment]
I wan to input chiness,but
![Snipaste_2020-09-09_20-06-17](https://user-images.githubusercontent.com/37357651/92596147-f6291780-f2d7-11ea-934d-0ffeb46c8112.png)

**Comment by otykier** [comment]
I just published version [2.12.4](https://github.com/otykier/TabularEditor/releases/latest) in which I have set IME mode to ON on both the DAX expression editor and the advanced scripting textbox. Could you let me know if this solves the issue? Thanks!

**Comment by jasonlaw997** [comment]
The version 2.12.4 had sloved my problem.Thanks!
