### ISSUE TITLE
List of functions 

### ISSUE THREAD

**Issue by Ajinkya369** [otykier/TabularEditor#602]
Firstly thanks for your contribution to the Power BI community by giving us the magical tool Tabular editor.
I'm working on it and trying to find out different business applications.
Below are some of the problem statement which Im trying to solve.

1.I want to change the name of all the columns conditionally if the column is of Integer Data type. Like I want to add the text "Numeric-column" before every columns name.

2.I want to change all the columns Property SummarizeBy:None  those are of Data type: Integer.

It would be great if you help me in this and provide a list of functions.

Thank you
Ajinkya Kadam

**Comment by otykier** [comment]
The following script should do the trick. In case you want to consider columns with other data types, please refer to the official [TOM documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.datatype?view=analysisservices-dotnet).

```csharp
var allColumns = Model.AllColumns.ToList(); // Get a list of all columns in the model
foreach(var column in allColumns) 
{
    if (column.DataType == DataType.Int64)
    {
        column.Name = "Numeric-column " + column.Name;
        column.SummarizeBy = AggregationFunction.None;
    }
}
```
