### ISSUE TITLE
Support to provide an URL as an option for the -A flag

### ISSUE THREAD

**Issue by DaveRuijter** [otykier/TabularEditor#603]
Hi Daniel,

Please consider to provide an URL as an option for the -A flag.

Cheers,
Dave

**Comment by otykier** [comment]
This is now fixed in [2.12.4](https://github.com/otykier/TabularEditor/releases/latest).

**Comment by DaveRuijter** [comment]
Thanks Daniel! I only see this now! Guess who is going to update his [BPAA](https://github.com/DaveRuijter/BestPracticeAnalyzerAutomation) solution 👍
