### ISSUE TITLE
Referencing a columns SourceColumn

### ISSUE THREAD

**Issue by IgnatiusJ** [otykier/TabularEditor#605]
Hi

I have a table with Object Type="Table (Import)" and Source Type = "M".
The table contains many columns. Each column has a property called "Source Column".
How do I reference the Source Column property in a script?

I'm looping over the columns like so:
`foreach(var c in currTable.Columns)`

But I can't figure out how to get the value of c.SourceColumn.

I have looked at the documentation here:
https://github.com/otykier/TabularEditor/wiki/TabularEditor.TOMWrapper

And from that it seems SourceColumn property is only available for a CalculatedTableColumn, which surprises me. Is this correct?

Thanks!

**Comment by IgnatiusJ** [comment]
Now I see SourceColumn is also available as a property on a DataColumn object, sorry I did not notice that before. But I still would need help accessing it from a Column object as described above :).

**Comment by otykier** [comment]
You can use the LINQ `OfType` method to only consider DataColumns in the collection:

```csharp
foreach(var c in currTable.Columns.OfType<DataColumn>())
{
    c.SourceColumn = "...";
}
```

**Comment by IgnatiusJ** [comment]
Thank you Daniel, worked like a charm!

I just wished OfType would take more than one argument, since I want to loop over both DataColumns and CalculatedTableColumns. But no big deal, now I first loop over columns of the first type and then a new loop over columns of the other type.

By the way, what different types can a Column be?

**Comment by otykier** [comment]
Yes, unfortunately there is no common ancestor class for columns that contains the SourceColumn property. But you could do the following (at the very least, it avoids looping twice):

```csharp
foreach(var c in currTable.Columns)
{
    if(c is DataColumn)
        (c as DataColumn).SourceColumn = "...";
    if(c is CalculatedTableColumn)
        (c as CalculatedTableColumn).SourceColumn = "...";
}
```

Check out the TOM documentation for information about the classes in general:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.column?view=analysisservices-dotnet

> CalculatedColumn
CalculatedTableColumn
DataColumn
RowNumberColumn

The latter (RowNumberColumn) is not used within Tabular Editor.

Closing this issue but feel free to reopen or open a new issue if you have any additional questions.
