### ISSUE TITLE
Datasource Name updation in Partition query

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#610]
Hi Daniel ,

I am trying to deploy model through CICD , in my CD pipeline i am passing -S switch to run a script before deploying to update Data source name , credentials etc .

**Command line passed from Devops :**
 
 TabularEditor.exe "$(ModelFilePath)"  -S "$(SetConnectionStringFromEnv)" -Deploy "Provider=MSOLAP;Data Source=$(AASServerUrl);User ID=$(AASAdminUser);Password=$(AASAdminPassword)" "$(ModelName)" -O -C -V -E

**Script content** : (updating name,credential and then looping through partition expression and replacing old data source name with new name)

var Con = Model.DataSources[0] as StructuredDataSource;                // Variable to store the first Connection
var Con1 = Model.DataSources[0] as StructuredDataSource;

Con.Name =  Environment.GetEnvironmentVariable("Name"); // Update DataSource Display Name
Con.AuthenticationKind="UsernamePassword";
Con.Username = Environment.GetEnvironmentVariable("SQLUserName");     // Update the SQL Username
Con.Password = Environment.GetEnvironmentVariable("LOADER-EDW-PWD");     // Update the SQL Password from KeyVault
Con.Database=Environment.GetEnvironmentVariable("SQLDatabaseName");   // Update the SQL Database Name
Con.Server=Environment.GetEnvironmentVariable("SQLServerName");      // Update the SQL Username
Con.Credential["path"]=Environment.GetEnvironmentVariable("ServerPath");   // Updates connection 

foreach(var p in Model.AllPartitions.OfType<MPartition>())   
   {
       p.Expression = p.Expression.Replace(Con1.Name,Con.Name);
   }

The issue I am facing is that the connection name changes but in partition query data source name is still pointing to the old name due to which refresh fails with below error :

![image](https://user-images.githubusercontent.com/55327056/93339361-1bbe9f80-f849-11ea-846d-79ecc5c57834.png)

![image](https://user-images.githubusercontent.com/55327056/93339847-b0290200-f849-11ea-90ed-4db3649ad37b.png)

When I just run this c# script in Tabular editor's advanced scripting window  it works fine , even it automatically replaces connection in partition without specifying the partition loop to replace name at the end .

Not sure where I am going wrong here , could you help me on this .

**Comment by otykier** [comment]
Hi @debashish10 
This code:

```csharp
var Con = Model.DataSources[0] as StructuredDataSource; // Variable to store the first Connection
var Con1 = Model.DataSources[0] as StructuredDataSource;

Con.Name = Environment.GetEnvironmentVariable("Name"); // Update DataSource Display Name
//...
p.Expression = p.Expression.Replace(Con1.Name,Con.Name);
```

does nothing. `Con1` and `Con` are references to the same object. So when you change `Con.Name` you will also have changed `Con1.Name`. Instead, store the original name in a variable:

```csharp
var Con = Model.DataSources[0] as StructuredDataSource; // Variable to store the first Connection
var ConName = Con.Name; // Store the original name of the first connection

Con.Name = Environment.GetEnvironmentVariable("Name"); // Update DataSource Display Name
Con.AuthenticationKind="UsernamePassword";
Con.Username = Environment.GetEnvironmentVariable("SQLUserName"); // Update the SQL Username
Con.Password = Environment.GetEnvironmentVariable("LOADER-EDW-PWD"); // Update the SQL Password from KeyVault
Con.Database=Environment.GetEnvironmentVariable("SQLDatabaseName"); // Update the SQL Database Name
Con.Server=Environment.GetEnvironmentVariable("SQLServerName"); // Update the SQL Username
Con.Credential["path"]=Environment.GetEnvironmentVariable("ServerPath"); // Updates connection

foreach(var p in Model.AllPartitions.OfType())
{
p.Expression = p.Expression.Replace(ConName,Con.Name);
}
```

**Comment by debashish10** [comment]
@otykier : Thanks a lot again , will try this right away .
Just one more question: can we avoid the loop to update in partition expression, as I can see in tabular editor once we change the name it automatically updates in partition query .

**Comment by debashish10** [comment]
@otykier : for some reason the new script as suggested above also did not update the source name in partition , although the script perfectly works within tabular editor when I run in advanced scripting tab .

**Comment by debashish10** [comment]
Hi @otykier : For some reason it still does not work , the script only changes the connection name but not data source name in partitions . I have tried with 3 different model now and it does not work . Not sure what am I missing here .

**Comment by otykier** [comment]
Maybe your problem is related to #662 and #559 ?

**Comment by debashish10** [comment]
Hi Daniel,

Yes as the updation of source name is required one time in partitions i have  been doing this by using the -P flag. That solves the problem for me. Thanks a lot !!!
