### ISSUE TITLE
Creating calculation group removes the ability to summarize existing fields in Power BI model

### ISSUE THREAD

**Issue by cygnex** [otykier/TabularEditor#614]
As soon as I create my first calculation group in Tabular Editor 2.12.40, it removes the summarization feature on fields in the data model. 

Here is my Power BI screen before the creation of the calculation group:

![image](https://user-images.githubusercontent.com/62795859/93665144-3871f780-fa42-11ea-8e0c-d4dd2324e019.png)

After I create a Calculation Group called "Metrics", notice that the SUM symbol is removed.  This occurs even before I create any calculation items. 

![image](https://user-images.githubusercontent.com/62795859/93665203-a9b1aa80-fa42-11ea-9094-f95e89e06766.png)

I am not sure if this by design or if it is a bug but any new table or matrix I create no longer allows me to summarize and I get separate values for each category. 

![image](https://user-images.githubusercontent.com/62795859/93665484-d8308500-fa44-11ea-9541-bf45870f4cda.png)

When viewing the data model, the default summarization still shows SUM 

![image](https://user-images.githubusercontent.com/62795859/93665462-a5868c80-fa44-11ea-8999-4383ba41e4a4.png)

**Application specifics**
 - Tabular Editor version: [e.g. 2.12.40]
 - Semantic Engine used: Power BI Desktop

**Comment by otykier** [comment]
This is by design. The Analysis Services engine requires the DiscourageImplicitMeasures model property to be set to “true” before calculation groups can be added to the model.

**Comment by cygnex** [comment]
Thank you, I missed this originally in the documentation but see it now.
