### ISSUE TITLE
Wrong data source is used when there are multiple data sources

### ISSUE THREAD

**Issue by skiwii** [otykier/TabularEditor#617]
I import a view from one data source, but when I look at the properties of the partition, it is using another data source.

Love this tool by the way! Keep up the great work!

**Comment by jamhos** [comment]
I've been meaning to log this one too! But trying to find the time to properly replicate. It appears that if there are multiple data sources, and you use the "Import Tables" functionality to select a view, the source is set to the first data source in the list, regardless of which you imported from.

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)
