### ISSUE TITLE
Import of Stored Procedure

### ISSUE THREAD

**Issue by a2Insight** [otykier/TabularEditor#619]
Is it possible to import a table to SSAS from a stored procedure using Tabular Editor ( similar to Visual Studio) ?

**Comment by otykier** [comment]
While the import/export wizard only lets you choose tables/views from the database, you can easily have Tabular Editor refresh table metadata from a stored proc.

Assuming you already set up a data source that can connect to your SQL data source using the Import/Export wizard, the steps are as follows:

1. Create a new table (Model > New Table)
2. Assign the query that executes the stored proc to the expression on the newly created table partition, e.g. `EXEC dbo.SP_FactSales`
3. Right-click on the partition and choose "Refresh Table Metadata". Hit "OK"

![image](https://user-images.githubusercontent.com/8976200/94145254-8cca0c80-fe72-11ea-9f4a-425caf2e2750.png)

**Comment by a2Insight** [comment]
Thank you so much for your reply. I have tried the path described below but the message I get is:

[cid:image002.jpg@01D69281.2E0A9410]

Regards,
Frode

Fra: Daniel Otykier <notifications@github.com>
Sendt: torsdag 24. september 2020 14:32
Til: otykier/TabularEditor <TabularEditor@noreply.github.com>
Kopi: Frode Wathne <frode@a2insight.no>; Author <author@noreply.github.com>
Emne: Re: [otykier/TabularEditor] Import of Stored Procedure (#619)


While the import/export wizard only lets you choose tables/views from the database, you can easily have Tabular Editor refresh table metadata from a stored proc.

Assuming you already set up a data source that can connect to your SQL data source using the Import/Export wizard, the steps are as follows:

  1.  Create a new table (Model > New Table)
  2.  Assign the query that executes the stored proc to the expression on the newly created table partition, e.g. EXEC dbo.SP_FactSales
  3.  Right-click on the partition and choose "Refresh Table Metadata". Hit "OK"

[image]<https://user-images.githubusercontent.com/8976200/94145254-8cca0c80-fe72-11ea-9f4a-425caf2e2750.png>

-

**Comment by otykier** [comment]
Sorry, I can't see the image you replied with. Could you try to upload the image through the GitHub issue tracker, instead of replying by mail? Thanks

**Comment by a2Insight** [comment]
![2020-09-24_14-41-14](https://user-images.githubusercontent.com/50266788/94147256-59d54800-fe75-11ea-9219-da64cab41993.png)

**Comment by otykier** [comment]
This is a generic error when Tabular Editor can't validate the query. Either, the query text itself is wrong, or Tabular Editor is not able to connect to the database. Check the connection string on the data source. If you're connecting to a source that cannot use Windows Authentication, make sure to specify credentials (username/password) in the connection string.

**Comment by a2Insight** [comment]
OK, thank you so much !



Fra: Daniel Otykier <notifications@github.com>
Sendt: torsdag 24. september 2020 14:54
Til: otykier/TabularEditor <TabularEditor@noreply.github.com>
Kopi: Frode Wathne <frode@a2insight.no>; State change <state_change@noreply.github.com>
Emne: Re: [otykier/TabularEditor] Import of Stored Procedure (#619)


This is a generic error when Tabular Editor can't validate the query. Either, the query text itself is wrong, or Tabular Editor is not able to connect to the database. Check the connection string on the data source. If you're connecting to a source that cannot use Windows Authentication, make sure to specify credentials (username/password) in the connection string.

-
