### ISSUE TITLE
Updating dependent DAX formulas when renaming

### ISSUE THREAD

**Issue by liveandletbri** [otykier/TabularEditor#62]
I'm not sure if this is by design or not, but I have noticed that if I rename a DAX measure or column, none of the dependent DAX formulas are updated. In SSDT it updates dependencies and I've found that to be convenient. However there are times when I don't want the dependent measures to be updated, and in those cases I had to use workarounds. 

I guess ideally a pop-up window would ask you, when you rename a measure with dependencies, if you want the dependencies to also be updated. Maybe you even could add a checkbox that says "always use this preference".

**Comment by otykier** [comment]
There is an option for automatic formula fix-up under File > Preferences, on the DAX tab:

![image](https://user-images.githubusercontent.com/8976200/27331213-d83b0dc0-55bc-11e7-8964-03b993c70c26.png)

Did you make sure this was checked before changing the name of an object?

**Comment by liveandletbri** [comment]
Ah yes, that's exactly what I needed. Thank you!
