### ISSUE TITLE
DAX Query Tab - Enhancement

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#621]
Inspired from the "Data Preview in Tabular Editor" post by Michael Kovalsky, I think a great enhancement to Tabular Editor would be to have a third tab in the top right area that acted as a DAX query window where you wouldn't have to wrap DAX in a script. This could be similar to the query windows in DAX Studio. There is a lot of functionality in DAX Studio. This could start light and over time have more of that functionality added.

An additional idea would be to have a link or button somewhere to open DAX Studio from Tabular Editor with the connection already made. This could work similar to the External Tools functionality in Power BI.

Cory

**Comment by otykier** [comment]
This is part of Tabular Editor 3. Stay tuned :-)
