### ISSUE TITLE
Cannot modify fact table name in tabular editor

### ISSUE THREAD

**Issue by pingzistrong** [otykier/TabularEditor#623]
**Describe the bug**
I want to modify the fact table name in tabular editor, which can be modified in power Bi, but not in tabular editor

**Comment by otykier** [comment]
Tabular Editor (or Power BI External Tools) in general, do not support making changes to table names.

Currently, only the following changes are supported:

- Measures
- Calculation Groups
- Perspectives
- Metadata Translations

More information here: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations
