### ISSUE TITLE
可以对中文支持再友好一些吗，非常感谢

### ISSUE THREAD

**Issue by pingzistrong** [otykier/TabularEditor#624]
The latest version is more friendly to Chinese support. We can edit Chinese in the tabular editor. Can the next version be more friendly, for example, the Chinese font should be larger. Thank you very much.

**Comment by otykier** [comment]
Increasing the font size in the Expression Editor text box can be done by holding down the CTRL key and using the scroll mouse wheel. I will consider adding a dropdown where you can specify the zoom level, similar to on the Advanced Scripting tab:

![image](https://user-images.githubusercontent.com/8976200/94428932-d62b9c00-0191-11eb-8bf6-d3f633b7b61d.png)

Could you please let me know what other improvements you have in mind, that would make the tool more friendly for Chinese usage? Thanks!

**Comment by otykier** [comment]
@pingzistrong do you have any additional comments on this, or can we close the issue?

**Comment by Stivenke** [comment]
Recommendation: Allow users to select different editor fonts and font sizes.
![vs](https://github.com/Stivenke/image/blob/main/I4PuFdwmnV.png)
