### ISSUE TITLE
Trouble downloading tabular editor

### ISSUE THREAD

**Issue by callumurfet** [otykier/TabularEditor#629]
Hello,

I have been unsuccessful in downloading tabular editor. When I try to download the package it comes up with an error message saying 'it is either not a supported file type or because the file has been damaged'. Can someone help me solve this problem?

**Comment by otykier** [comment]
Please provide some more information: What Windows version and platform (x86 / x64) are you using? Did you download the .zip or .msi version of the tool? Are you able to install the tool on other machines without issue?

**Comment by callumurfet** [comment]
Hello,

I have Windows version 1803. I am working on a 64 bit operating system. I have downloaded the package as a NuGet package file? And this is the only computer I am trying to install the tool on.

Thanks,

Callum Murfet
Consultant

[Metro_Dynamics_Logo_Blk - Small]

T 020 3865 3082
E callum.murfet@metrodynamics.co.uk<mailto:callum.murfet@metrodynamics.co.uk>
A 3 Waterhouse Square, 138 Holborn, London, EC1N 2SW
W metrodynamics.co.uk
Twitter @metrodynamics

[cid:image002.png@01D69707.F1E94450]

**Comment by otykier** [comment]
Tabular Editor is not available as a NuGet package as far as I know.

You should use the .msi or .zip file from the Release page: https://github.com/otykier/TabularEditor/releases/latest

**Comment by otykier** [comment]
@callumurfet do you have an update on this? Can we close the issue?
