### ISSUE TITLE
Power BI CI/CD using Tabular Editor

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#631]
Hi @otykier 

I have been following all the blogs thus far on CICD using azure devops for tabular models using Tabular editor and we have implemented  it in our BI team.
This has helped us greatly , all  thanks to you .

I would like to know if we could do the same for PowerBI reports connected to AAS models,  mainly deploy report to different workspaces, update analysis services datasource server.
If there are any blog or sessions planned in future that can help .

**Comment by otykier** [comment]
Automating the deployment and maintenance of Power BI content should be done through the Power BI REST APIs. Here are some links to the official documentation:

- [Import API](https://docs.microsoft.com/en-us/rest/api/power-bi/imports/postimport) (for publishing content to a workspace)
- [Dataset API](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasources) (link shows how to update a data source on an existing dataset)

I don't have anything planned in this regard, as the focus of Tabular Editor is the tabular data model - not Power BI specific features. But you should be able to find plenty of material online regarding this:

- https://powerbi.microsoft.com/en-us/developers/automation/
- https://data-marc.com/2019/11/12/versioning-and-ci-cd-for-power-bi-with-azure-devops/

**Comment by debashish10** [comment]
Thank you daniel
