### ISSUE TITLE
Support deploy to a model with RefreshPolicy enabled (Incremental Refresh) 

### ISSUE THREAD

**Issue by RuiRomano** [otykier/TabularEditor#632]
I have a dataset with 2 tables: Product and Sales (with Incremental Refresh enabled)

I want to add a new column into the Product table and deploy that new column into an existent dataset.

If I run the TabularEditor cmdline to deploy with the -P parameter:

TabularEditor.exe "Model.bim" -D "<PremiumWorkspace>" "DataSet" -L "username" "password" -O -V -E -W -P

Tabular Editor on"Product" table overwrites the M code and after the refresh the column is available. But for "Sales" table it deletes all the partitions...

A nice feature could be a parameter to deploy partitions but skip the partition deploy on tables with RefreshPolicy enabled because the M code is embedded in the refresh policy and not into the partition itself

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)

**Comment by otykier** [comment]
Tabular Editor 2.13.0 now features an -Y switch which is used right after -P to indicate that you want to overwrite partitions, EXCEPT those that have Incremental Policies defined.
