### ISSUE TITLE
SchemaCheck timeout ?

### ISSUE THREAD

**Issue by mst42a** [otykier/TabularEditor#633]
We use azure pipline to deployed our model, sometimes we got error 

Unable to retrieve column metadata for table 'HERE TABLE NAME'. Check partition query. Checking by hand in Tabular Model everything is fine. In Pipeline we have step (cmd)

echo on

"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" "$(System.DefaultWorkingDirectory)\Tabular\TabularArtifact\s\TABULAR\database.json" -SCHEMACHECK -Vsts

its take almost 25 minutes to done; Can we somehow speed it up? Changing some parameters in connectionstring?

![image](https://user-images.githubusercontent.com/63145285/94672934-4531fd80-0316-11eb-82ab-fb4b05ca0d6b.png)

**Comment by otykier** [comment]
You should be able to provide timeout settings in the connection string of your data source. For example, when using OLE DB provider, you can simply specify `;Timeout=30` as part of the connection string, to have a 30 second timeout.

**Comment by mst42a** [comment]
At now we have (in tabularEditor connection view):

![image](https://user-images.githubusercontent.com/63145285/94676387-909ada80-031b-11eb-840f-c09866447d9d.png)


A value of 0 means to wait indefinitely and never time out. 

After error When I try to redeploy my pipelines sometime its goes correct sometimes no. 
But always is that on SCHEMACHECK 

Maybe there is some other hint that I can provide to avoid this odd error message?
Or maybe change something in my model?

**Comment by otykier** [comment]
You have to add `;Timeout=30` to the connection string, as the Timeout property shown on your screenshot is not used by the Schema Check functionality of Tabular Editor (the timeout property is used by Analysis Services when refreshing data).

However, even with a timeout of 30 seconds, I'm afraid the schema check could take up to 25 minutes of you have say 50 tables on your model (as the timeout applies to checking the schema of each separate table). So this indicates that Tabular Editor may not be able to connect to the data source at all, when validating the schema.

If you're using Azure Pipelines, please be aware that the MSOLEDBSQL driver is not installed on those. So if you're using this driver for your data source, the schema check will not work. The solution is to execute a script as part of your command line, that will change the provider on the data source to use something else, for example SQLNCLI.

[Here](https://tabulareditor.com/2019/10/17/DevOps4.html#step-2---schema-check) I illustrate how you can execute a script to change the connection string before running the schema check.

**Comment by mst42a** [comment]
Thanks a lot!
