### ISSUE TITLE
Unhandled exception when filtered on a perspective and importing tables

### ISSUE THREAD

**Issue by scottjt** [otykier/TabularEditor#634]
Hi,

I noticed that if I'm filtered to a specific perspective and import tables, I get an unhandled exception.  This seems to be because the table is not yet shown in this perspective so would not show in the tree.

I'd like to recommend that in this case, the table should automatically be added to the perspective selected.

Thanks,
Scott

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)
