### ISSUE TITLE
Data Column Summarization Issue After Adding Calculation Groups

### ISSUE THREAD

**Issue by lstee014** [otykier/TabularEditor#636]
Hi Daniel - 
When I create a calculation group numerically formatted columns in my model that were previously were set to aggregate, e.g. summarize no longer can be summarized.  More specially, these columns have the sigma sign next to them in PBI desktop and if I were to put the values from that column into a chart the amount would sum up.  

![With Sigma](https://user-images.githubusercontent.com/67977985/94963437-c37cd400-04bd-11eb-9b50-de6fd0534cc4.PNG)

![Values After pre CG](https://user-images.githubusercontent.com/67977985/94963929-74836e80-04be-11eb-8fe2-1e1fb09a051d.PNG)

That is the behavior prior to adding a calculation group.  

After I add the calculation group, the sigma disappears, formatting remains as a decimal, Summarization is still set to Sum and if I add the values to visual that don't sum up.  Is that the expected outcome? 

![Without Sigma](https://user-images.githubusercontent.com/67977985/94963975-87963e80-04be-11eb-88de-9cbaec994eed.PNG)

![Values After CG](https://user-images.githubusercontent.com/67977985/94963998-90871000-04be-11eb-8e2d-4bd196b6c196.PNG)

**Application specifics**
 - Tabular Editor version: [2.12.4]
 - Semantic Engine used: [Power BI Desktop Version: 2.85.681.0 64-bit (September 2020)]

Thank you in advance for any insight on this!

**Comment by marcosqlbi** [comment]
This is by design: calculation groups automatically disable implicit measures.
However, using explicit measures is a best practice when you create a model you share with other users.
Documentation: https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions

**Comment by lstee014** [comment]
Thank you!  The Power BI Community is awesome!  Thank you for being so generous with your time!

**Comment by kadirkkkk** [comment]
Some visuals like Drilldown radial barchart and Impact bubble chart stop working after creating calculation groups even if i use measures.

**Comment by otykier** [comment]
@kadirkkkk see #380. Long story short, this is an issue in Power BI Desktop.
