### ISSUE TITLE
DAX Editor

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#64]
The DAX Editor should not accept formulas with errors. Additionally, besides color-coding, there should be intellisense integration.

**Comment by otykier** [comment]
This is definitely on the backlog for Tabular Editor.

Unfortunately, parsing DAX for errors and intellisense functionality is a bit more complicated than simple color coding. To keep the footprint and dependencies of Tabular Editor down, so far I have not relied on any 3rd party libs aside from the SSAS AMO. At this point, I need to consider whether a small footprint is important enough to govern creating more advanced stuff, such as DAX error parsing and intellisense from scratch, or whether I should throw the towel in the corner and build upon some more standard libs. For example, the .NET Roslyn libraries.

Furthermore, I'm not completely happy with the textbox component used for DAX and C# script editing, but again, it gets the job done while keeping the footprint low.

Having something more proven and robust in Tabular Editor would certainly be nice, but including a better code editor (such as [RoslynPad](https://roslynpad.net/)) would mean that the .exe size would go up considerably, or alternatively, the tool would have to be shipped with a number of .dll dependencies.

I have some plans for a "poor mans" DAX intellisense, which would basically just be a shorthand for all known DAX functions, as well as table-, measure- and column names in the model. I will notify you when this is available for testing. In the meantime, any opinions and suggestions on the discussion above would be highly appreciated.

**Comment by MarkGStacey** [comment]
What would be wrong with tabular editor as a visual studio plug in? That would be great IMHO

**Comment by MarkGStacey** [comment]
And I personally would not be at all averse to dependencies to enhance the editor.
Error checking, color coding, intellisense, dax formatter. Etc

**Comment by marcosqlbi** [comment]
DAX Formatter is already integrated in Tabular Editor.
The Visual Studio plugin is a very expensive task, and there are issues related to the different libraries (Windows Forms vs WPF) used for Tabular Editor and Visual Studio. Moreover, all the features you list are not free just because you integrate with Visual Studio.

**Comment by teasot** [comment]
If you are willing to delve into embedding WPF editors into windows forms, you could probably use the Avalon Editor used in DAX Studio, and possibly even see if you can use the xshd file used in DAX Editor to copy the syntax highlighting, to get the same look and feel.

I have done so for an internal tabular editor back in ye olde 1103 era, in a native WPF app.

However, this may cause compatibility issues - I can only imagine the issues in combining WPF and Windows Forms, and I have not managed to get autocomplete working with Avalon Edit.

Also I imagine that for anything non-internal, you will need to ask the author of DAX Studio.

**Comment by otykier** [comment]
This is still on the list of things I would like to do - but other issues/features have priority currently.

For a more native Windows Forms editor, I am currently considering [ScintillaNET](https://github.com/jacobslusser/ScintillaNET), which is quite popular, has a small footprint (DLL is 1.4 MB) and is under active development. Here's a [demo](https://github.com/robinrodricks/ScintillaNET.Demo) of what it can do, and at first glance, it looks like it solves all my needs - except that a DAX parser is still needed for proper IntelliSense, syntax error handling, etc. But everything in due time :-)

**Comment by rpiboy** [comment]
I would vote for slightly footprint and/or additional if it gets IntelliSense and/or Autocomplete. I'd put priority on IntelliSense. Since I'm not using DAX every day, all day, I find that I revert to initially writing DAX in PowerBI (since I get those features there) then using Tabular Editor to edit, update, make changes, review, clean-up formatting etc.

**Comment by otykier** [comment]
Cleaning up old issues / things that are planned for Tabular Editor V3.
