### ISSUE TITLE
CLI: from folder to model.bim loses "Save to Folder" settings

### ISSUE THREAD

**Issue by NickOnbekend** [otykier/TabularEditor#640]
**Describe the bug**
With the cli i have created a script to export the model.bim to folder and from folder to bim file. With the creation of the bim file he loses the Levels settings in the annotation of TabularEditor_SerializeOptions. With this you would always end up with one big 'database.json' file instead of all the separated files.

**To Reproduce**
1. Create from a model.bim file with all the 'Save to Folder' settings active.
2. Save to Folder with or without cli. `TabularEditor.exe {sourceFile} -W -E -FOLDER {destinationFolder}`
3. Create a model.bim file with cli `TabularEditor.exe {destinationFolder} -W -E -BUILD {sourceFile}`
4. Open the model.bim file in a texteditor and look at the `TabularEditor_SerializeOptions` annotation. Here you see no values in the array of Levels.
![image](https://user-images.githubusercontent.com/7486531/95324217-ae2dee00-089f-11eb-93d1-eca8d20401ce.png)

**Expected behavior**
I was expecting that the current setting what is defined in the 'database.json' file is copied over to the model.bim so you can always use the cli from folder to the bim file and from the bim file to folder. 

**Observed behavior**
The settings of "Save to Folder" are not copied over to the model.bim file if you use the CLI with the command `TabularEditor.exe {Folder} -W -E -BUILD {BimFile}`. 
![image](https://user-images.githubusercontent.com/7486531/95324217-ae2dee00-089f-11eb-93d1-eca8d20401ce.png)

**Application specifics**
 - Tabular Editor version: 2.12.4
 - Semantic Engine used: SSAS 2016
 - Model Compatibility Level: 1200

**Comment by otykier** [comment]
This is a bug. Saving a model as a .bim, either through the UI or through the CLI, should retain all settings in the annotation (it should simply ignore settings that are not relevant when saving as a .bim, such as the contents of the `Levels` array).

As a workaround, until I have a new release where this is fixed, check my answer to #652 where I inject the annotation prior to saving to folder by adding a -S / -SCRIPT switch in the CLI call.

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)
