### ISSUE TITLE
Advanced scripting to set up KPI for multiple measures

### ISSUE THREAD

**Issue by Pjtruji** [otykier/TabularEditor#641]
Hi!
First of all, congratulations! Tabular Editor is amazing!!
I am new here in GitHub. 
I have just downloaded Tabular Editor and I have been using your "Useful scrip snippets" to create measures from columns in just one click.
I wonder wether it could be possible to have something similar to create multiple KPIs from multiple selected measures in just one click.
The reason is that, in my case, I have two tables: Actual Values and Target Values, both with the same name columns (for example: Quantity, Sales, Margin, etc..)
I have created measures for all of them and I named the measures from table Actual Values as "Actual Name.Column" and measures from table Target Values as "Target Name.Column", for example, for column named "Sales" in both tables, I have created two measures "Actual Sales" and "Target Sales".  At the same time, I created the measure "YoY Actual Sales".
Now, "Target Name.Column" meant to be the Target.Expression for KPI "Sales". And at the same time, "YoY Name.Column" meant to be the Trend.Expression.
Well, could you please help me to create that script. Any tip?
Thank you so much in advance, your work is so great!!
Javier

**Comment by otykier** [comment]
It's not completely clear to me how you want this to work. Do you want to dynamically select a few measures and then run a script to create a KPI based on the selection, or do you want to rely on some naming convention of the tables and columns?

Anyway, here's how to create a KPI on the currently selected measure and assign expressions to the KPI, based on the name of the selected measure:

```csharp
var m = Selected.Measure;
var kpi = m.AddKPI();
kpi.StatusExpression = m.DaxObjectFullName;
kpi.TargetExpression = m.DaxObjectFullName.Replace("Actual", "Target");
kpi.TrendExpression = "[YoY " + Selected.Measure.Name + "]";
```

**Comment by Pjtruji** [comment]
Thank you so much! I am going to try it and I will come back to you.
