### ISSUE TITLE
On Connection to Powerbi.com dataset behind corporate proxy: Error 407 Proxy Authentication required

### ISSUE THREAD

**Issue by datadu-de** [otykier/TabularEditor#642]
**Describe the bug**
When I try to connect to a PowerBI.com from within the corporate network I get an error "... 407: Proxy Authentication Required..."

**Expected behavior**
Connection to dataset should be possible

**Observed behavior**
error message popped up, connection is not possible
![image](https://user-images.githubusercontent.com/49077745/95354108-581f7180-08c4-11eb-8076-16e18ac7f583.png)

**Application specifics**
 - Tabular Editor version: 2.12.4
 - Semantic Engine used: Power BI Premium dataset
 - Model Compatibility Level: 1520

**Additional context**
This can be fixed by including 
```xml
<system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
```
to app.config

Please let me know if I should just create a pull request for the suggested solution.

Best Regards,
Frank

**Comment by otykier** [comment]
Thanks for reporting. I don't have a lot of experience with proxy connectivity. Are there situations where it makes sense that the user can provide a custom proxy address/username/password, when connecting to Power BI / Analysis Services? Tabular Editor supports this for web requests when checking for updates or calling the DAX formatter API, but I wonder if we can somehow reuse these proxy settings for the connection to PBI/AS?

![image](https://user-images.githubusercontent.com/8976200/95911352-abe8f980-0da1-11eb-9873-00064979cab2.png)

**Comment by datadu-de** [comment]
Hi Daniel,

Thanks for your response!

I'm by no means an expert on networking/proxies either - however I´m trapped behind/confronted with several of them in the corp environment.

For my particular situation I'm sure that reusing the web-proxy settings you mentioned would solve the problem - as from my computers´ point of view the dataset connection to app.powerbi.com is using the same network-route (i.e. has to go through the same proxy) as a web-request to daxformatter or any other site - would be great if we could give this a try.

I would assume that most corporate environments use this kind of setup - but that's just a educated guess.

What do yo think?

**Comment by otykier** [comment]
[2.13.0](https://github.com/otykier/TabularEditor/releases/latest) now uses default credentials. No need to set this up in the .appconfig file.
