### ISSUE TITLE
When deploying, connections are updated even though -C command line parameter not used

### ISSUE THREAD

**Issue by jasonhendrix** [otykier/TabularEditor#645]
I am trying to deploy an AS model to an existing Azure AS Server and overwrite most metadata there, but not alter any connection details.

@TabularEditor.exe "$(Build.SourcesDirectory)\test\test\Database.json" -D "$(ASConnectionString)" "$(ASDatabaseName)" -O -P -R -E -V

After running with the above command line options, the AS Model will not refresh and gives this error:
Failed to save modifications to the server. Error returned: 'The given credential is missing a required property. Data source kind: SQL. Authentication kind: UsernamePassword. Property name: Password. The exception was raised by the IDbConnection interface.

I then have to update the credentials manually in SSMS to get the model to refresh.

Is there a way for the deployment process to not make modifications to any existing connections?

**Comment by jasonhendrix** [comment]
For now, I'm working around this issue by running an XMLA script to update the credentials as part of an Azure DevOps Pipeline using this extension: https://github.com/liprec/vsts-release-aas

**Comment by otykier** [comment]
Does your model hold a legacy or a power query data source? Tabular Editor uses a TMSL createOrUpdate script when deploying, and as far as I know, it's not possible to retain existing credentials when deploying in this manner. I am not sure what other options we would have to avoid this. If anybody has any insight, please let me know!

See also #596 and #194
