### ISSUE TITLE
Should I convert measure result to Fixed Decimal and avoid Double?

### ISSUE THREAD

**Issue by BVMather** [otykier/TabularEditor#646]
When using the BPA analyser it is recommending not to use floating point (Double). 

I have gone through all of the sources and fixed all the columns to fixed decimal which has solved most issues, however, some measures are being automatically assigned as Double due to arithmetic operations.

An example might be a % of all sales which is the division of two fixed decimal numbers

e.g. % of Total = DIVIDE ( [partial], [whole] )

In terms of best practice, should I be wrapping the result in a convert (as below) to put it to fixed decimal, or is that overkill?
  
e.g. % of Total = CONVERT ( DIVIDE ( [partial], [whole] ), CURRENCY )

**Comment by otykier** [comment]
For measures, I don't think there's much benefit in explicitly converting back to fixed decimal after performing a division. At least not in my experience. But you can always capture some timings with [DAX Studio](https://daxstudio.org/) to be sure.

**Comment by marcosqlbi** [comment]
I agree with Daniel - Microsoft changed the engine over the years and some assumptions we made a few years ago might be no longer valid today. However, I am pretty sure there are still cases where the conversion of expressions cannot be performed by the storage engine and requires a CallbackDataID, which can be dangerous for the performance.
In theory, this is not something you should be concerned about high-level measures like the ones you included in your comment, it is more important for expressions executed in a row context when the iterator is pushed in the storage engine request.
Another reason why the floating-point can be dangerous is when you sum/subtract currencies and you don't want rounding errors, but once you start using multiplications and divisions you should be good with the rounding to the decimal numbers you would like to have in your calculation.
For more details I suggest you read these articles:
https://www.sqlbi.com/articles/choosing-numeric-data-types-in-dax/
https://www.sqlbi.com/articles/understanding-numeric-data-type-conversions-in-dax/

**Comment by BVMather** [comment]
Thanks so much guys, I didn't realise there was some potential performance implications. I'll store that in the back of my mind for the future. Thanks for the article Marco
