### ISSUE TITLE
Best Practice Analyzer across multiple models

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#65]
Expanding off of the Best Practice Analyzer, one should be able to save a set of rules which can then be applied and checked across a set of tabular models - connecting to both bim files and/or databases. That way, one can verify that best practices are being followed across a set of models and set up an automated process for checking that these practices are followed. Thanks!

**Comment by otykier** [comment]
Great suggestion. In the next release, later this week, there will be a command-line option for validating a model against Best Practices defined either in the model annotations, or in global rules on the machine. A command script could then be easily created to validate a set of models against best practice rules. Hopefully, this will be useful for now.

**Comment by otykier** [comment]
Running Best Practice Analyzer from the command line was implemented in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
