### ISSUE TITLE
Control Summarize By property in Import Table Wizard

### ISSUE THREAD

**Issue by IgnatiusJ** [otykier/TabularEditor#650]
**Is your feature request related to a problem? Please describe.**
I find it annoying when certain columns that happen to have a numeric datatype of some sort unintentionally gets the "Summarize By" attribute set to "Default" which puts that little annoying sigma sign in front of the column when browsing the model from a client tool. 
Customer_No is a good example:
![image](https://user-images.githubusercontent.com/46527404/96147739-dce33e80-0f07-11eb-8eb2-d8793c730b6e.png)

More often than not, I'd prefer to after table import manually go in and update the Summarize By property for the columns I do indeed want to be aggregated.

**Describe the solution you'd like**
Perhaps it could be an option in the in the table import GUI to be able to control this behavior. For example a checkbox for each table object "Automatically set Summarize By to Default for numeric columns". It could be enabled by default for all tables to be in line with the standard functionality, but if unchecked Tabular Editor would set Summarize By to "None" for all columns in the selected tables not checked with this option.

**Comment by otykier** [comment]
While I agree that it may be better to set the SummarizeBy property to "None" for all columns on newly imported tables, the design philosophy of Tabular Editor is that it should leave as many settings to their defaults as possible, when invoking actions through the UI. This is to ensure that developers who are used to working with the TOM API get a consistent experience.

Instead, I recommend you use the following script. Save it as a custom action to quickly reuse it whenever you import new tables:

```csharp
// Loop through all selected tables, setting the SummarizeBy-property to None on all columns:
foreach(var c in Selected.Tables.SelectMany(t => t.Columns))
{
    c.SummarizeBy = AggregateFunction.None;
}
```

**Comment by IgnatiusJ** [comment]
> While I agree that it may be better to set the SummarizeBy property to "None" for all columns on newly imported tables, the design philosophy of Tabular Editor is that it should leave as many settings to their defaults as possible, when invoking actions through the UI. This is to ensure that developers who are used to working with the TOM API get a consistent experience.
> 
> Instead, I recommend you use the following script. Save it as a custom action to quickly reuse it whenever you import new tables:
> 
> ```cs
> // Loop through all selected tables, setting the SummarizeBy-property to None on all columns:
> foreach(var c in Selected.Tables.SelectMany(t => t.Columns))
> {
>     c.SummarizeBy = AggregateFunction.None;
> }
> ```

I fully understand this reasoning Daniel. Thanks for the script-tip! 👍
