### ISSUE TITLE
Perspective Copy

### ISSUE THREAD

**Issue by jtgooding2** [otykier/TabularEditor#651]
When copying a perspective from one instance of Tabular Editor to another, it needs to check if all the tables, columns, measures exist in the target.  I am fine with it removing if the object doesn't exist, but today it leaves them in the perspective, and when you open the model in VS it throws missing table, column etc. error and won't open.
A different option of a script or right click to validate a perspective would work as well, but i don't see the issue occurring except this use case.

Thanks
John

**Comment by otykier** [comment]
Thanks for reporting. I think we have the same issue for culture (translation) objects. Will investigate if we can remove invalid references when the perspective/culture is pasted into the destination model.

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)
