### ISSUE TITLE
Azure Devops CI: PowerShell tasks with Tabular Editor not working

### ISSUE THREAD

**Issue by spythan** [otykier/TabularEditor#655]
Hello Daniel, thanks for your amazing work!

I have setup CI with Azure DevOps for a Tabular Model following your great guide, and I want to ask if there is a reason you are using Command Line tasks instead of PowerShell and if we should too, since I ran into some strange behaviour.
I have replaced your recommended Command Line tasks with PowerShell tasks, and I am experiencing some issues.
The PowerShell tasks for Schema Check and Deployment don't catch Tabular Editor generated warnings/errors, while their Command Line counterparts do.
Locally, PowerShell's output looks just fine (generates warnings/errors).

On an unrelated note, I would also like the PowerShell tasks to output the commands they run and can't find how, any ideas?

Thanks!

## Schema Check
| PowerShell | Command Line |
|-|-|
| ```.\TabularEditor.exe "$(Build.SourcesDirectory)\SemanticModel\Model" -S SetConnectionStringFromEnv.cs -SC -V``` | ```TabularEditor.exe "$(Build.SourcesDirectory)\SemanticModel\Model" -S SetConnectionStringFromEnv.cs -SC -V``` |
| ![image](https://user-images.githubusercontent.com/19828566/96592087-adaa4400-12f0-11eb-9dac-d310effcc2ed.png) | ![image](https://user-images.githubusercontent.com/19828566/96592118-b7cc4280-12f0-11eb-96f4-9f3085136b6c.png) |
| On some odd occassions, the PowerShell Schema Check step worked (same code):
![image](https://user-images.githubusercontent.com/19828566/96592814-77b98f80-12f1-11eb-9cb8-668f1661b17a.png)| |

## Deployment
| PowerShell | Command Line |
|-|-|
| ```.\TabularEditor.exe "$(Build.SourcesDirectory)\SemanticModel\Model" -S SetConnectionStringFromEnv.cs -D "Provider=MSOLAP;Data Source=$($env:AASServer);User ID=app:$($env:AppID)@$($env:TenantID);Password=$($env:AppSecret);Persist Security Info=True;Impersonation Level=Impersonate" $(AASDatabaseName) -O -C -R -V -E -W``` | ```TabularEditor.exe "$(Build.SourcesDirectory)\SemanticModel\Model" -S SetConnectionStringFromEnv.cs -D "Provider=MSOLAP;Data Source=%AASServer%;User ID=app:%AppID%@%TenantID%;Password=%AppSecret%;Persist Security Info=True;Impersonation Level=Impersonate" $(AASDatabaseName) -O -C -R -V -E``` |
| ![image](https://user-images.githubusercontent.com/19828566/96592087-adaa4400-12f0-11eb-9dac-d310effcc2ed.png) | ![image](https://user-images.githubusercontent.com/19828566/96592118-b7cc4280-12f0-11eb-96f4-9f3085136b6c.png) |

**Comment by otykier** [comment]
The reason I prefer using command line tasks is exactly because PowerShell tasks have problems catching the async output from Tabular Editor. See also #571.

If you must use PowerShell, see [this answer](https://github.com/otykier/TabularEditor/issues/154#issuecomment-389536276) from a user who managed to get it working using the `Start-Process` cmdlet.

**Comment by spythan** [comment]
Thanks a lot, that clears it up, command line it is!
