### ISSUE TITLE
Failed to save modifications to the server

### ISSUE THREAD

**Issue by POMelisa** [otykier/TabularEditor#658]
Hi,
I was trying to change some things in my model and when I tried to save the changes I get this error message:
"Failed to save modifications to the server. Error returned: Egenskaberne Culture og Collation for objektet kan kun ændres, før alle andre objekter oprettes."

What am I missing?

/Melisa

**Comment by otykier** [comment]
Sounds like you may have tried to change the Culture property on the Model:

![image](https://user-images.githubusercontent.com/8976200/97539342-13b65b80-19c2-11eb-8b14-484a6e11aed5.png)

Unfortunately, Analysis Services does not allow changing this property on an existing data model. If you're connecting to an Analysis Services instance, you can redeploy the model as a new database. If you're working on a PBIX file, then you can try to export/save the file as a PBIT (Power BI Template), then, open the PBIT file in Tabular Editor, change the model culture, save it, and open the PBIT back in Power BI.

More details here: https://www.sqlbi.com/articles/changing-the-culture-of-a-power-bi-desktop-file/
