### ISSUE TITLE
1400 compatibility level

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#66]
Integration and support of 1400 level features (i.e. ragged hierarchies, OLS, drill through etc.).

**Comment by otykier** [comment]
This is already available, but you need a separate build of Tabular Editor for this (as Tabular Editor cannot dynamically load the AMO libs, based on which version of SQL Server you're using).

You'll find the 1400 compatible version [here](https://github.com/otykier/TabularEditor/releases/tag/2.3.6331-CL1400).

**Comment by kalmenk** [comment]
Fantastic! Thanks Daniel! And just to know, future releases of tabular editor will be available for 1400 as well, correct?

**Comment by otykier** [comment]
Yes, whenever a new release is ready I always build one version targeting the SQL Server 2017 AMO client libs (compatible with both CL 1400 and 1200), and one build targeting the 2016 libs.

It's exactly the same code base, it's just a compile-time flag I use to differentiate.

**Comment by kalmenk** [comment]
Great, thanks Daniel.
