### ISSUE TITLE
How can I update my table if a column is added in the source?

### ISSUE THREAD

**Issue by waltheed** [otykier/TabularEditor#661]
I have added a column in the source view for my table. I want to update the table in my Tabular Model. (How) can I do that with Tabular Editor?

What I do now is open Visual Studio and go to the table properties and design view of the M query and then import. Then the table in VS is refreshed. 

But it would be so much easier if this could be done inside Tabular Editor: Refresh - Save - Deploy. That would be awesome.

Many thanks, Edgar

**Comment by otykier** [comment]
What kind of data source are you using? For OLEDB/ODBC based data sources such as SQL Server, Tabular Editor has a rich Table Import Wizard, as well as a "Refresh Metadata" feature that automatically connects to the data source and retrieves the metadata (columns and data types) from there.

See this article: https://github.com/otykier/TabularEditor/wiki/Importing-Tables

If your model was created using a Power Query data source instead of a provider (aka. "legacy") data source, then you will need to convert your data source and partitions to the legacy type, for the above technique to work: https://tabulareditor.com/2019/07/03/TabularEditorTricks2.html

Also, there's a new script here that may be useful: https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#replace-power-query-data-sources-and-partitions-with-legacy

**Comment by waltheed** [comment]
Thanks Daniel,

Sorry that I could not find it in the manual… You described it actually very well.

I indeed use a SQL Server database as the data source.

It’s a pity that this refresh table is not available for the M query partitions.
I use the technique from Chris Webb to limit the number of rows for fact tables by using a parameter like yyyymmdd in my M script.  I do not think it’s possible to do that in a legacy partition. Do you see any other downsides to converting the M partition to a legacy patition?


Best regards,

Edgar Walther
ITsmart
www.itsmart.nl<http://www.itsmart.nl/>


[cid:image001.jpg@01D6B780.FF5EFB40]<https://nl.linkedin.com/in/edgarwalther>   [cid:image003.png@01D6B780.FF5EFB40] <https://twitter.com/edgarwalther>    [cid:image005.png@01D6B780.FF5EFB40] <http://paper.li/edgarwalther/1421271985>

**Comment by otykier** [comment]
With legacy partitions and a SQL Server data source, you can simply add a T-SQL WHERE clause to your partition queries:

```sql
SELECT * FROM fact.Sales WHERE CalendarKey BETWEEN 20201101 AND 20201130
```

I don't believe there are any downsides to using legacy partitions vs. using M partitions, when the data source is a SQL database. Quite the contrary, actually :-)

**Comment by waltheed** [comment]
Many thanks Daniel. It worked like a charm!

Happy 😊


Best regards,

Edgar Walther
ITsmart
www.itsmart.nl<http://www.itsmart.nl/>

[cid:image005.png@01D6B9D6.008DEF10]

   [cid:image006.jpg@01D6B9D6.008DEF10] <https://nl.linkedin.com/in/edgarwalther>    [cid:image007.png@01D6B9D6.008DEF10] <https://twitter.com/edgarwalther>    [cid:image008.png@01D6B9D6.008DEF10] <http://paper.li/edgarwalther/1421271985>

**Comment by dmarkle-sandscap** [comment]
@otykier I would say the downside to using a Legacy Partition would seem to be that it's not supported in the Power BI Premium Gen2 capacity.  We're looking at switching from AAS to PBI Premium, and our legacy partitions are a bump in the road on this path.  But yes, I sure did prefer them.

**Comment by otykier** [comment]
@BasVan-datapeer you can have legacy partitions and data sources in a model deployed to Power BI, but then you can only trigger refreshes through the XMLA endpoint (ie. not through the Power BI Service UI)

**Comment by otykier** [comment]
Hi @itsmohgh 
Are you using Tabular Editor 2.x? If so, you have two options:

1. Manually add the column to the table in Tabular Editor. Make sure to specify the `SourceColumn` property of the new column to match the name of the column in your source view.
2. Right-click on the table and choose "Refresh table metadata...". In this case, Tabular Editor will automatically try to connect to the source, run the SQL query specified in the partition, and show a list of columns that have been added/removed.
 
**Note: Option 2 only works when the table uses a SQL-based partition with a Provider (aka. Legacy) Data Source.**

**Comment by AfeezR** [comment]
@otykier Awesome stuff you are doing here. Please I have just installed TE 2, but it does not have BPA and Vertipaq Analyzer there in. Could you advise on the steps to get that done, please? Thank you

**Comment by otykier** [comment]
TE2 does have BPA, but you need to download or define your own rules. A good starting place is [Michael Kovalsky's best practice rules](https://powerbi.microsoft.com/en-us/blog/best-practice-rules-to-improve-your-models-performance/).

TE2 does **not** have VertiPaq Analyzer built-in. For that, you would to use a different tool, for example [DAX Studio](https://daxstudio.org/). Or you can try out [TE3](https://tabulareditor.com/downloads) (commercial) which includes that.
