### ISSUE TITLE
Change Azure Synapse Datasource on multiple tables

### ISSUE THREAD

**Issue by anbudhanush** [otykier/TabularEditor#662]
Hi Daniel and other contributors,

I wonder if you have any thoughts on addressing this petty issue related to changing data source strings in M. 

**What are you trying to achieve?**
I have a pbix file with 30 odd tables all pointed towards an environments. We have used parameters  to change to different environments which is fine. 
For one of testing purpose,  I would like to remove those connection string parameters and hardcode the datasource Server and DB in M. 

I understand we have a snippet to find and replace text in all [Measures](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets)(. Is there one similar to find and replace "text" in the Partition / M Query? 

**What have you tried so far?**
The only way i could think of is to replace those 30 lines of codes in Pbix file by going through table by table. Any advanced scripting will be very handy for future testing. 

thanks 
Anbu

**Comment by otykier** [comment]
So changing M query expressions is not one of the [supported write operations for external tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations) at the moment. But with that disclaimer out of the way, you can certainly experiment (go to File > Preferences and check the "Allow unsupported Power BI features"). Make sure to keep a backup of your PBIX file!

This script will loop through all partitions, and let you replace terms in the M expression:

```csharp
foreach(var p in Model.AllPartitions.OfType<MPartition>())
{
    // Your replace code here...
    p.Expression = p.Expression.Replace("OldServerName", "NewServerName");
}
```

**Comment by anbudhanush** [comment]
Hi Daniel , Thanks for this,  I have tried this snippet. It find and replace the M Expression on the partition but when i commit the changes to the model , the pbix file shows up "apply changes" once that process done, in the transformation page the tables M expressions is not replaced.  It still contains parameterized server and database values in the M expression. Is there any other settings I need to enable to apply the changes? thanks

**Comment by otykier** [comment]
I'm afraid this is because Power BI Desktop also stores M expressions outside the tabular object model. See also #610 and #559 - you'd have to look into some other mechanism for changing the data sources, as Tabular Editor only has access to the metadata in the tabular object model.

**Comment by otykier** [comment]
Closed, since this issue can't be fixed within Tabular Editor.

**Comment by anbudhanush** [comment]
Thanks , That makes sense why it did not work.
