### ISSUE TITLE
Azure DevOps: Successfully deployed model update to Power BI Premium Workspace, but returns errors on refresh

### ISSUE THREAD

**Issue by gabrielsmelchor** [otykier/TabularEditor#664]
Before I begin, I realize that the XMLA read/write functionality is not in general release and this may be a quick they're working out in preview mode.

With that said, I'm following the _You're Deploying it Wrong_ guide with success. I was able to successfully deploy the .bim artifact to a dataset hosted in a Power BI Premium capacity. I have confirmed that the added columns and measures are visible in the dataset by using the 'Create Report' feature off of the dataset in Power BI service. However, when I attempt to refresh the dataset, it says the new columns are not found in the rowset.

Here's a snipper of the error I received when attempting to refresh. 
![image](https://user-images.githubusercontent.com/38728420/97608177-9ac1fe80-19d7-11eb-80f8-865773658017.png)

However, when using 'Create Report' on that same dataset, I can clearly see 'AdmissionsRequirementKey' present in the dataset. This is one of the new columns added through Azure DevOps/Tabular Editor. 

![image](https://user-images.githubusercontent.com/38728420/97608323-cf35ba80-19d7-11eb-88f2-f34542fe0fdd.png)

My question is whether this is related to the fact XMLA read/write is still in preview (my suspicion), or whether I made a mistake in the tabular editor command line.

For reference, here is the command line task that deploys the artifact to that dataset.

`TabularEditor.exe "_$(Build.DefinitionName)\drop\Model.bim" -Deploy "$(ConnectionString)" "$(Database)" -O -C -R -V -E -W`

Note: I omitted the update connection string because the dataset was already configured with the appropriate connection string.

Would appreciate any advise!

**Comment by otykier** [comment]
I'm not sure, but I think the error message refers to the column not being available in the data *source*, not the *model* itself. Are you able to refresh the model in Desktop without issues? Can you verify that the M partition queries on the model deployed to Premium through XMLA are correct and still work, if you copy them over to a blank model in Desktop?

**Comment by gabrielsmelchor** [comment]
Thanks for responding @otykier !

I'm still orienting myself with the objects within the serialized model, so this is still a learning process for me.

I have confirmed the following:
1. The column is present in the data source (same spelling, etc.)
2. The _M_ partition (retrieved from the _partitions_ folder under the table corresponds exactly to the _M_ partition in a successful dataset refresh in desktop after I've added the new column.
3. I've connected to the database.json file in the Azure repo (mapped locally, that I use in the build pipeline) with Tabular Editor and can see the column on the table.
![image](https://user-images.githubusercontent.com/38728420/97627287-c69dae00-19f0-11eb-80ac-505092bb0551.png)

Although I'm not able to perform a dataset refresh after the successful model deployment via XMLA, the dataset is reflecting the new column on the correct table. 

![image](https://user-images.githubusercontent.com/38728420/97627886-9e627f00-19f1-11eb-836a-ac0b1987f7a4.png)


It seems like this is a Power BI service issue, as the XMLA appears to be updating the model.

I'm going to open a ticket with Microsoft unless there's anything obvious to you.

**Comment by gabrielsmelchor** [comment]
Just a follow up:

I replicated this process manually using Tabular Editor (no Azure DevOps).

Published identical initial dataset and deployed changes manually using Tabular Editor. Was able to see new columns after deployment, but it had an identical error message on refresh.

Then deployed the same model directly from Tabular Editor as a new dataset and the refresh was successful. 

Confirmed that the database.json from Tabular Editor is NOT the issue - definitely a Power BI Service issue. I'll let you know what I find out from Microsoft, but will close this issue.

**Comment by gabrielsmelchor** [comment]
Closing the loop on this for anyone who might be in the same position. In short, the new column did exist in the datasource. However, I had a Power Query applied step that selected specific columns, thus overriding the new column addition. I modified the code to include the partition update and it worked perfectly. Very exciting!
