### ISSUE TITLE
##[error]Deployment failed! The 'Database' with 'ID' = <dataset_name> doesn't exist in the collection.

### ISSUE THREAD

**Issue by gabrielsmelchor** [otykier/TabularEditor#667]
Hi there again,

I'm continuing to follow the _You're deploying it wrong_ guide, using Azure DevOps to make model updates to a dataset hosted in a Power BI Premium workspace.

I'm working on the validation deployment in the build pipeline, using the following task to deploy a dataset that has previously not existed in that workspace:

`TabularEditor.exe "$(Build.SourcesDirectory)\database\database.json" -Deploy  "$(ConnectionString)" "$(Database)" -O -C -P -R -M -W -E -V
`
My build pipeline fails, with the following error message:

_##[error]Deployment failed! The 'Database' with 'ID' = <dataset_name> doesn't exist in the collection._

However, when I look in the Power BI workspace defined in the connection string, I can see the database has been deployed and configured by the Service Principal. Am I misunderstanding the intention of this step, or am I using the wrong switches?

Note: if I run this task on the dataset that previously "failed" to deploy (above), I get a success:

`TabularEditor.exe "$(Build.SourcesDirectory)\database\database.json" -O  "$(ConnectionString)" "$(Database)" -O -C -P -R -M -W -E -V
`

**Comment by otykier** [comment]
This is an issue with an earlier version of Tabular Editor. Please make sure you're using the latest version (2.12.4) in your DevOps pieline.

**Comment by gabrielsmelchor** [comment]
You are correct - using the most recent version has resolved this issue.

**Comment by andymayPlunket** [comment]
I just installed version 2.14.2, which is the latest version according to Git Hub, and I get the same issue
