### ISSUE TITLE
Unable to open pbit with datamodel, works fine with datamodelschema

### ISSUE THREAD

**Issue by RonniePitts** [otykier/TabularEditor#668]
It seems there is an issue when opening PBIX files which only contaim the DataModel file, I receive the following error: 

Error Loading model from disk 
This file is not a valid PBIX/PBIT file 

However Power BI Desktop opens the file without any issue. 

If the PBIX contains a DataModelSchema then no issues with that template file, it seems to only affect templates that contain DataModel. 

Tabular Editor 2.12.4 

Example attached.
[Sales & Returns Sample v201912.zip](https://github.com/otykier/TabularEditor/files/5479877/Sales.Returns.Sample.v201912.zip)

**Comment by otykier** [comment]
It looks like this file uses a live connection to another PBI Dataset or instance of Analysis Services. If so, the file itself doesn't hold any data model metadata, which is why it can't be opened in Tabular Editor. Only files with an imported/DirectQuery model are supported.

**Comment by RonniePitts** [comment]
Hi Dan,

Agree but Power BI Desktop still loads the PBIX, be it with a warning that the Excel file cant be found.

It still displays the various tables of which would be interested to see that metadata?

**Comment by otykier** [comment]
Sorry, I don't follow.

Are you talking about a PBIT or a PBIX file?

- PBIX files **can** not be loaded in Tabular Editor.
- PBIT files **can** be loaded, but **only** if they contain an imported/DirectQuery model

**Comment by otykier** [comment]
@RonniePitts do you have an update on this?

**Comment by RonniePitts** [comment]
Dan, not at the moment.

I'm using PowerBI Desktop to open the PBIT files and connect directly to the backend SSAS instance.

Not sure why Tabular Editor doesn't like those PBIT files.

Does TabularEditor uncompress the DataModel and mount the SSAS model internally?

________________________________

**Comment by otykier** [comment]
> open the PBIT files and connect directly to the backend SSAS instance.

This is what's known as a **live connection**. Tabular Editor does not support Power BI Desktop files in live connect mode, because the file itself does not contain any model metadata. If you want to open the data model in Tabular Editor, you would have to connect Tabular Editor to the SSAS instance itself (provided you have admin rights to the instance).
