### ISSUE TITLE
Ssms table/column description to tabular table/column description

### ISSUE THREAD

**Issue by benito2313** [otykier/TabularEditor#669]
Hi,

I have a database in ssms and I have added descriptions to the tables and columns.
When I import these tables and columns the description in tabular editor isn’t set/copied from ssms

Is there a way to do this?

Kind regards

Benito2313

**Comment by otykier** [comment]
Unfortunately, this is outside the scope of Tabular Editor's import tables wizard, as there can easily be scenarios where you want to bring in values from other extended properties (I believe SSMS uses "MS_Description"), or if you're using some other RDBMS that doesn't support extended properties.

To do what you want, I suggest you invest in writing a script for Tabular Editor that will connect to the SQL source, and fetch the extended property values for the tables and columns imported to your model. If any of your tables or data columns have been renamed in the tabular model, you would need to inspect the partition query and the "SourceColumn" property of your data columns, to be able to look up the correct extended property value from the database.

Something like below should do the trick (disclaimer: I haven't tested this, and you probably have to adjust it to suit your needs, for example, I'm assuming you're using SqlClient in your tabular model data source, but you may have to use OleDb instead, depending on what your connection string looks like)

```csharp
#r "System.Data.SqlClient"
using System.Data.SqlClient;

// TODO: Change this to point to the correct data source in your model:
var ds = Model.DataSources["MyDS"] as ProviderDataSource;

var getTableExtPropertySql = "SELECT value FROM fn_listextendedproperty('MS_Description', 'schema', '{0}', 'table', '{1}', NULL, NULL);"
var getColumnExtPropertySql = "SELECT value FROM fn_listextendedproperty('MS_Description', 'schema', '{0}', 'table', '{1}', 'column', {2});"

using(var conn = new SqlConnection(ds.ConnectionString))
{
    conn.Open();
    // Loop through all imported tables:
    foreach(var table in Model.Tables.Where(t => !t.IsCalculatedOrCalculationGroup()))
    {
        var srcQuery = table.Partitions.First.Query;
        // Assume the first partition in the table specifies a query that looks like: "SELECT * FROM [schema].[table]"
        // where the schema and table name starts at character #14:
        var srcSchemaName = srcQuery.Substring(14).Split(".")[0];
        var srcTableName = srcQuery.Substring(14).Split(".")[1];

        var cmd = new SqlCommand(string.Format(getTableExtPropertySql, srcSchemaName, srcTableName), conn);
        table.Description = cmd.ExecuteScalar().ToString();

        // Loop through all data columns on the table:
        foreach(var column in table.Columns.OfType<DataColumn>())
        {
            var srcColumnName = column.SourceColumn;
            cmd = new SqlCommand(string.Format(getColumnExtPropertySql, srcSchemaName, srcTableName, srcColumnName), conn);
            column.Description = cmd.ExecuteScalar().ToString();
        }
    }
}
```

**Comment by otykier** [comment]
@benito2313 do you have any further questions or can we close this issue?
