### ISSUE TITLE
TabularEditor pipeline scripts error

### ISSUE THREAD

**Issue by mst42a** [otykier/TabularEditor#670]
Hi,
when i try to run pipeline with script I get an error:

c:\agent\_work\r3\a\BITabular\TabularArtifact\s\DeleteUnusedModelObject.csx(7,1): error CS0012: The type 'System.Xml.Serialization.IXmlSerializable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml, Version=4.0.0.0,  Culture=neutral, PublicKeyToken=b77a5c561934e089'.
--

How can I add this reference?

**Comment by otykier** [comment]
Try to add the following at the top of your script:

```csharp
#r "System.Xml"
```

**Comment by otykier** [comment]
@mst42a did you have any further questions or may we close this?

**Comment by mst42a** [comment]
Sorry for not responding earlier. We can close this question.
