### ISSUE TITLE
Using the ExportProperties and ImportProperties, how can we use latin chars (like "ã", "ç") 

### ISSUE THREAD

**Issue by ciistiado** [otykier/TabularEditor#675]
Not sure if it is a bug, a needed feature or if I am missing something on the manual.

I am using TabularEditor to export and import some properties along with new descriptions.
I managed to import the .tsv to excel using 65001:Unicode UTF-8 encoding and all is fine until I import it again, even with no more changes on the file. When imported, those "ã" and "ç" become �.

Is there a way to achieve this?

My system
Tabular Editor 2.12.4
Windows 10 Pro 19041.572 in English, locale Portuguese with Portuguese keyboard.

**Comment by otykier** [comment]
Can you please share the code you use for importing the tsv into Tabular Editor?

**Comment by ciistiado** [comment]
I am selecting the table and using this to export
var tsv = ExportProperties(Selected);
SaveFile("c:\\files\\Exported Properties 1.tsv", tsv);

and this to import.
var tsv = ReadFile("c:\\files\\Exported Properties 1.tsv");
ImportProperties(tsv);

**Comment by otykier** [comment]
You can view the implementation of `ReadFile` [here](https://github.com/otykier/TabularEditor/blob/bf9e6d86bd29fb7733a5ad3f6aaf9edb9815649f/TabularEditor/Scripting/ScriptHelper.cs#L234-L245). This uses the default settings for the `StreamReader` class, which on my machine is Windows-1252 encoding.

So if your tsv file is encoded with UTF-8, you must use the following code to load the tsv file:

```csharp
// Import using UTF-8:
var filePath = @"c:\files\Exported Properties 1.tsv";
string tsv;
using (var fileStream = new System.IO.FileStream(filePath, System.IO.FileMode.Open, System.IO.FileAccess.Read, System.IO.FileShare.ReadWrite))
using (var textReader = new System.IO.StreamReader(fileStream, System.Text.Encoding.UTF8))
{
    tsv = textReader.ReadToEnd();
}
ImportProperties(tsv);
```

**Comment by ciistiado** [comment]
Many thanks Daniel for your help debugging this issue.

Final solution:

//Export using UTF-8:
var tsv = ExportProperties(Selected);
System.IO.File.WriteAllText("c:\\files\\Exported Properties 1.tsv", tsv, System.Text.Encoding.UTF8);

Open file on Excel, in my case I used "65001 : Unicode (UTF-8)" as file origin

Make the changes, saving it as "Unicode Text (*.txt)". Now we have a *.tsv.txt on the folder, just import that one.

// Import using UTF-8:
var filePath = @"c:\\files\\Exported Properties 1.tsv.txt";
string tsv;
using (var fileStream = new System.IO.FileStream(filePath, System.IO.FileMode.Open, System.IO.FileAccess.Read, System.IO.FileShare.ReadWrite))
using (var textReader = new System.IO.StreamReader(fileStream, System.Text.Encoding.Default))
{
    tsv = textReader.ReadToEnd();
}
ImportProperties(tsv);

With this, the chars are well imported and the issue is solved.
