### ISSUE TITLE
Getting this error after executing the following script to create measures "CS1579 foreach statement cannot operate on variables of type object"

### ISSUE THREAD

**Issue by Ajeenkya369** [otykier/TabularEditor#679]
string daxexp = "Distinct(Table[Current Status])"; // returns distinct values 
var display= EvaluateDax(daxexp);

foreach(var m in display)
{
    Model.Tables["Measures Table"].AddMeasure("aging"+m,"CALCULATE([aging_in_status],Table[Current Status]="+m+")");
}

**Comment by otykier** [comment]
When the DAX statement provided to `EvaluateDax` returns a table, the method itself returns an object of type [DataTable](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=netframework-4.6.2) from the `System.Data` namespace. A DataTable has a `Rows` property which is a collection of [DataRow](https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow?view=netframework-4.6.2) objects. Each one represents a row in the table. In your case, this row will only have a single column, which you can access either by index or by name.

So in your case, the script should look like:

```csharp
using System.Data;

string daxexp = "Distinct(Table[Current Status])"; // returns distinct values
var display = EvaluateDax(daxexp) as DataTable;

// Loop through all rows of the table:
foreach(DataRow row in display.Rows)
{
    var m = row[0].ToString();   // Returns the value of the first (and only) column of the row
    // var m = row["Table[Current Status]"].ToString();   // Alternative way to get the value of the [Current Status] column
    Model.Tables["Measures Table"].AddMeasure("aging"+m,"CALCULATE([aging_in_status],Table[Current Status]=\""+m+"\")");
}
```
