### ISSUE TITLE
Can't save query into partition

### ISSUE THREAD

**Issue by liveandletbri** [otykier/TabularEditor#68]
I'm trying to create a new table and I'm having an issue saving the query. I right-clicked and created a new table, then renamed it. I clicked on the "..." button next to Partitions and tried to write my SQL query into the Query property of the partition. I see that Ctrl+Enter is supposed to save the query but it seems to do nothing. If I enter a query, press Ctrl+Enter, and then click on another property (such as Datasource), my query text disappears. If I enter a query, press Ctrl+Enter, press OK, then re-open the Partitions window by clicking "...", I see that the query text has disappeared. This all results in a table with no query and no columns.

**Comment by otykier** [comment]
This is a bug in the current build. Expect a new release where this is fixed very soon.

**Comment by otykier** [comment]
This was fixed in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
