### ISSUE TITLE
M-Query partition showing by default for new tables

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#683]
**Describe the bug**
Creating a new table creates an 'M-query partition by default. I'm pretty sure it used to create a legacy partition by default.

**To Reproduce**
1. Right click on 'Tables'
2. Create New -> Table

**Expected behavior**
Expected that the partition is a legacy partition.

**Observed behavior**
Default partition is an M-query partition.

**Application specifics**
 - Tabular Editor version: 2.13.0
 - Model Compatibility Level:1500
 - PBI Data Source Version: PowerBI_V1

**Additional context**
Also, I'm not sure there's a simple way to convert partitions from M-Query to Legacy. Perhaps through advanced scripting although haven't looked into it yet.

**Comment by otykier** [comment]
Does this happen when the model already contains a legacy data source, before a table is created?

**Comment by m-kovalsky** [comment]
If the model already contains a legacy data source, it creates the new table's partition as a legacy partition. If creating a table in a new model with no tables (in the manner described above), the new table's partition is an m-partition. Honestly I'm not 100% sure how this behaved before but I'm pretty sure it defaulted to legacy in either scenario.

**Comment by otykier** [comment]
It did indeed default to legacy before, automatically creating a legacy data source if the model did not already have any data sources defined. However, this workflow was not ideal for people who wanted to use Power Query partitions, as they do not need to have any data sources defined in the model. So in other words: If your model does not contain any explicit data sources, and the compatibility level is sufficiently high, Tabular Editor assumes you want to use Power Query when adding a new empty table. If you DO want to use Legacy, make sure to explicitly create the Legacy Data Source before adding the first table. Makes sense, no? :-)

**Comment by m-kovalsky** [comment]
In most cases of using legacy sources, one would (and should) use the import tables feature. However, it is unlikely that someone building a model from scratch in Tabular Editor would define their own M-partitions. People would create the model in PBI Desktop and then open it in Tabular Editor (already having many m-partitions and no real 'data sources'. That being the case, if M-partitions were already defined in the model it would make sense for new tables to default to M-partitions. If the model had legacy data sources then it would make sense to default to legacy partitions. If no tables exist, I still think it would make sense to default to legacy data sources because of my previous point - I don't think anyone is manually defining M-partitions when creating a new table. Just my thoughts :)

**Comment by otykier** [comment]
On second thoughts, I agree that the default should be to add legacy partitions, when starting from a blank model.

I have changed the logic such that PowerQuery partitions are only used when the model already contains a PowerQuery data source, or at least one other table holds a PowerQuery partition. In all other cases, creating a new table would add a Legacy partition (and also a Legacy data source, if that doesn't already exist).

This behaviour can be changed by setting the "UsePowerQueryPartitionsByDefault" property to "true" in the `%localappdata%\TabularEditor\Preferences.json` file.

https://github.com/otykier/TabularEditor/releases/tag/2.13.1

**Comment by m-kovalsky** [comment]
Thanks Daniel! One more thing - it may be preferable to add a checkbox to the preferences window within Tabular Editor itself (as opposed to having to edit the .json file.
