### ISSUE TITLE
Only the first 50 tables appear in Tabular Editor

### ISSUE THREAD

**Issue by Andrewsimmans** [otykier/TabularEditor#685]
I have a rather large model which has over 50 different Tables. When I use the External Tools / Tabular Editor facility only the 50 tables appear in the Tabular Editor - they appear to be the first 50 I created and do not include the latest ones.

I have the latest released version of Tabular Editor.

**Comment by otykier** [comment]
I'm not able to reproduce this behaviour at all. There's no limit to the number of tables Tabular Editor can display.

![image](https://user-images.githubusercontent.com/8976200/99569527-085abc80-29d1-11eb-96f7-a48c0f3f2cf5.png)

Maybe you have some hidden tables in your Power BI data model? Press CTRL+5 inside Tabular Editor to toggle display of hidden tables on/off.

**Comment by Andrewsimmans** [comment]
Thanks Otykier that is the cause - what it is that some tables I have hidden by hiding the whole table (to hide the columns) and then adding measures that are not hidden  (in which case in Power BI the table does NOT appear hidden but it does in Tabular Editor) and on other tables I had just hidden the individual columns (but not the whole table) in which case the table appears hidden in Power BI (if there are no visible columns or measures) but shows in Tabular Editor.  

I have been able to fix this by showing the tables using CTRL+5 and then editing the hidden tag for the table to be false - whilst leaving the hidden tag on the individual columns as True.

So not a bug - thanks for your help.
