### ISSUE TITLE
Copying text into BPA keeps formatting

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#686]
**Describe the bug**
Copying text from the Advanced Scripting window into the Rule Expression Editor of the BPA keeps the formatting from the Advanced Scripting window (font size, font, and color).

**To Reproduce**
1. Write code in the Advanced Scripting window
2. Copy some of the code
3. Open the BPA manager
4. Edit a rule
5. Ctrl-V to paste the code in the Rule Expression Editor

**Expected behavior**
It should reformat the text to be the standard format of the text in the Rule Expression Editor

**Application specifics**
 - Tabular Editor version: 2.13.0
![image](https://user-images.githubusercontent.com/29556918/99512526-3e2c8080-2992-11eb-9bff-331b0547f48e.png)

**Comment by otykier** [comment]
Fixed in [Tabular Editor 2.13.2](https://github.com/otykier/TabularEditor/releases/latest)
