### ISSUE TITLE
How can I create table in Tabular Editor?

### ISSUE THREAD

**Issue by HONG04X** [otykier/TabularEditor#688]
Hi, 
Can I create tables using Tabular Editor?
I have found the "Create new table" are disable (see figure as below), so how can I enable this?

![image](https://user-images.githubusercontent.com/15246999/99643084-3d294b00-2a87-11eb-8d64-342277fb69f4.png)

Thanks!

**Comment by otykier** [comment]
This is [not supported for models hosted in Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).
