### ISSUE TITLE
Use Tabular Editor to programmatically create Power BI dataset?

### ISSUE THREAD

**Issue by julianwissel** [otykier/TabularEditor#689]
First and for me a very important comment: we have been following your contributions and the development of tabular editor now for years and we really appreciate your willingness to share and to help the community!

I am currently involved in a project where we are building a low-code development platform for business users. Business users should be able to build customer apps directly in that tool. Since reporting on that custom made apps should be possible, we thought about creating a tabular model automatically based on the app's metadata. Actually most information that is required for the app (such as tables, columns, relationships) is available in the app's model.

We considered creating a folder with database.json and sub-folders as your Save to folder features does. But we have not found any way to build a Power BI report based on that information. Is that possible? Would you recommend any other approach to programmatically create Power BI data models?

**Comment by otykier** [comment]
Unfortunately, we can only create the data model (aka. dataset) using Tabular Editor and the .json files, not the report itself (pages, visuals, slicers, etc).

For programatically creating visual report content, you would have to look into the [Power BI Javascript API for Power BI embedded](https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html).

**Comment by otykier** [comment]
@julianwissel do you have any further questions or may we close this issue? Thanks!

**Comment by julianwissel** [comment]
yes, thank you very much for your help!
