### ISSUE TITLE
Wiki Link Broken: Save Custom Action

### ISSUE THREAD

**Issue by samaguire** [otykier/TabularEditor#691]
**Describe the bug**
Opens to a create a wiki page on the old documentation site https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting#creating-custom-actions

**To Reproduce**
click on the hyper link "online documentation" when in the "save custom action" dialogue box that pops up when saving an advanced script.

**Expected behavior**
Open a link to https://docs.tabulareditor.com/Advanced-Scripting.html.

**Observed behavior**

**Application specifics**
 - Tabular Editor version: 2.13.7634

**Additional context**
![image](https://user-images.githubusercontent.com/62320770/100205327-d9f95600-2f69-11eb-9d14-4878b98cb99e.png)

**Comment by warthurton** [comment]
Wiki has been removed.  All documentation now at https://docs.tabulareditor.com/index.html
Suggest closing.

**Comment by warthurton** [comment]
Created #701 to fix up the links.

**Comment by warthurton** [comment]
If there are any compilation errors it is due to not being able to build/compile the project.  This happened to me once before and I need to spend some time figuring out what is missing from this VS install.

**Comment by otykier** [comment]
Released in [Tabular Editor 2.13.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for your contribution, @warthurton
