### ISSUE TITLE
Search in source column

### ISSUE THREAD

**Issue by datacatsuk** [otykier/TabularEditor#692]
**Is your feature request related to a problem? Please describe.**
Whenever I need to search something in the source columns, I have to open the bim file in notepad++. When I find it, I copy the model field name and search it in Tabular Editor. This is obviously not an efficient way of working and sounds like against the very basic idea behind Tabular Editor.

**Describe the solution you'd like**
Can we not have this search feature where we filter the objects it also searches within the source column and includes the fields in the results?

**Describe alternatives you've considered**
Only solution is to open the bim file in a text editor and search for the source column name. When found, copy the model field name and search it in Tabular Editor.

**Comment by otykier** [comment]
Use [Dynamic LINQ search](https://docs.tabulareditor.com/Advanced-Filtering-of-the-Explorer-Tree.html#dynamic-linq-search).

For example, typing `:SourceColumn.StartsWith("Currency")` will find all columns whose source column value starts with "Currency":

![image](https://user-images.githubusercontent.com/8976200/100234474-6fc1c080-2f2b-11eb-9de3-4f6f2b0e13ad.png)

**Comment by datacatsuk** [comment]
Thanks a lot for the quick response. I wasn't even aware of such a feature.
Much obliged!
