### ISSUE TITLE
Creating & Changing Tables in Power BI Desktop

### ISSUE THREAD

**Issue by tobimax** [otykier/TabularEditor#693]
Creating & Changing Tables in Power BI Desktop

When connected to a Remote PBI XMLA Endpoint you can add new tables and change existing ones However if you are connected to a local Power BI Desktop Session you cannot make this work.

1. Open a new Power BI Model and add data to a table. Save the PBIX
2. Open TE and connect to the PBI Session
3. Duplicate the table or add a new one.
4. Power BI Shows the new table but also shows the message - There are pending changes in your queries that haven't  been applied.  Apply changes / Discard Changes
3. Apply Changes - Erases you changes from TE and removes the table.
4. Discard Changes - Does not work and the message remains.

It would be a very useful to be able to di this, especially for those of use who are using TE against PBI Premium models where you can no longer download the PBIX data model after implementing incremental refresh or editing the model via XMLA.

I'm not sure if this is a PBI Desktop Issue or a Tabular Editor issue.

Thanks

Toby.

**Comment by otykier** [comment]
Adding tables to a Power BI Desktop model through the external tools integration is [not supported](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).

If you would like to see support for adding tables (and other modelling operations) through external tools, please provide this feedback to Microsoft.

**Comment by tobimax** [comment]
Thanks, I posted at MS as well.
