### ISSUE TITLE
Running Script from BPA Analyzer doesn't seem to have made any model changes.

### ISSUE THREAD

**Issue by bibinbastian** [otykier/TabularEditor#695]
**What are you trying to achieve?**
I am trying to delete unused columns in model based on the script generated from BPA Tool.
As a sample,  I ran the following statement in advanced editor
   (Model.Tables["Opportunity"].Columns["IsDeleted"] as DataColumn).Delete();
But the output is showing as 'Script successfully Executed, 0 Model changes'

Please let me know what I may be doing wrong
Thanks in advance
Bibin
![Screenshot 2020-11-27 062209](https://user-images.githubusercontent.com/7856373/100459082-aefe2780-3079-11eb-869e-6d0e75968b65.jpg)

**Comment by otykier** [comment]
Looks like you are editing a Power BI Desktop model.

Deleting columns is not among the [supported write operations for external tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).

You can experiment by setting the File > Preferences > Allow unsupported Power BI features checkbox. This will let you make any kind of modelling change to your desktop model, potentially breaking the .pbix file (so make sure to keep a backup of it, and don't expect Microsoft support to help you if something doesn't work).
