### ISSUE TITLE
Editing Power BI files with live connection to SSAS

### ISSUE THREAD

**Issue by georgepetkov** [otykier/TabularEditor#698]
Currently, when the tabular editor is connected to a PBIX file, sourcing data through live connection to SSAS/AAS database, the tabular editor instance gets connected to the underlying database and the changes made are not local to the Power BI file but gets published to the database. It would be better if the user has the option to choose. Oftentimes, users want to be able to define measures that only exist within their Power BI file, and not on the server.

**Comment by otykier** [comment]
You can’t connect Tabular Editor to a Power BI report that uses Live Connect as such a report does not contain a local model that can be edited with Tabular Editor.

**Comment by georgepetkov** [comment]
@otykier, thanks for the swift response. I wonder, where those additionally defined measures are stored, and can't we build a module to edit that file. After all, their metadata must be stored somewhere.

**Comment by otykier** [comment]
There’s no officially supported way to do this.

**Comment by georgepetkov** [comment]
Thanks! Closing this, in that case.
