### ISSUE TITLE
Add view hidden to Table menu

### ISSUE THREAD

**Issue by matt40k** [otykier/TabularEditor#699]
**Is your feature request related to a problem? Please describe.**
When viewing the list of tables, it is obvious how to view the hidden tables

**Describe the solution you'd like**
When you r-click on the Table under model, you should have a view \ hide option

The only way to currently do it is View > Hidden Objects or Ctrl + 5 keyboard shortcut

**Comment by otykier** [comment]
The Model menu, Table menu and all other context-sensitive menus are intended to provide shortcuts for modelling operations based on the current context (i.e. the current selection in the tree). Toggling the display of hidden objects is not a modelling operation, and hence you won't find it in that menu.

To toggle the display of hidden objects, use the shortcut, the View > Hidden Objects menu or the button in the toolbar.

**Comment by matt40k** [comment]
@otykier I get what you mean, but people coming from the Power BI Desktop have it as an option

![image](https://user-images.githubusercontent.com/4136340/100874709-e404e280-349c-11eb-800a-4c0523f930aa.png)

**Comment by otykier** [comment]
That’s not an argument for adding it to the context menu in my opinion. If people feel strongly that a context menu option for toggling hidden objects is needed, I’m open to discussion, but this is the first time I’m hearing this.
