### ISSUE TITLE
Best Practice Analyzer: Data Sources

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#70]
When you set rules that apply to 'Data Source' it throws an exception error every time and it also doesn't let you delete that rule.

**Comment by otykier** [comment]
Bug has been identified and will be fixed with next release. Thanks for reporting!

**Comment by kalmenk** [comment]
Thanks Daniel! When can we expect the next release?

**Comment by otykier** [comment]
Since it seems the popularity of Tabular Editor is going up, I'm putting some more effort into creating unit- and integration tests. The project is growing, and I can no longer justify not having proper tests in place. I hope to have version 2.4 ready before the weekend.

**Comment by kalmenk** [comment]
Fantastic! Great to hear it's picking up steam.

**Comment by otykier** [comment]
This was fixed in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
