### ISSUE TITLE
Issue with date measures when using calculation groups for formatting

### ISSUE THREAD

**Issue by anderseik** [otykier/TabularEditor#703]
When setting up a calculation item to format a decimal number to percentage all date measures in the model is broken and returns the name of the date format instead of the date itself.

1. Go to tabular editor and create a new calculation group and item.
2. Expression = SELECTEDMEASURE ()
3. Format string Expression = "0.00000%"
4. Save the new items to the Power BI file
5. Add the calculation item as a filter to the visual where the decimal is set
6. Activate the calculation item

**Expected behavior**
The decimal measure should convert from decimal number to percentage format when the calculation item is active. No other changes to behavior expected

**Observed behavior**
When saving the calculation group and item created in TE the returned values in date measures are broken.

**Calculation group and item created, saved to power bi desktop**
![image](https://user-images.githubusercontent.com/47736868/100845918-2f5bc880-347e-11eb-8341-e9b2b015137c.png)

**Percentage formatting working properly, date measures returning "General Da e"**
![image](https://user-images.githubusercontent.com/47736868/100846158-7649be00-347e-11eb-876d-e2643a9e6f26.png)

**The selected date format for the dates**
![image](https://user-images.githubusercontent.com/47736868/100846383-bc068680-347e-11eb-99d5-6293d164c920.png)

**Changing the date format for the top measure**
![image](https://user-images.githubusercontent.com/47736868/100846621-06880300-347f-11eb-8c9d-41ada3cbda6e.png)

**New result of top measure after refreshing**
![image](https://user-images.githubusercontent.com/47736868/100846684-169fe280-347f-11eb-83b3-e91132d5f28c.png)

**Application specifics**
 - Tabular Editor version: 2.12.4 (also tested on 2.13.1)
 - Semantic Engine used: Power BI Desktop October 2020 (also tested on November 2020)
 - Model Compatibility Level: 1500?

**Additional context**
The date measures are always broken when saving the calculation group and item to the power bi model. The date measures go back to normal behavior if I delete the **calculation item**. 

I have tried to change the regional settings of the pbix from norwegian to English (United States) and English (United Kingdom)

Region settings in windows:
![image](https://user-images.githubusercontent.com/47736868/100848203-14d71e80-3481-11eb-8447-e0887328277c.png)

pbix file used
[dates.zip](https://github.com/otykier/TabularEditor/files/5628016/dates.zip)

**Comment by otykier** [comment]
It seems to be an issue with the AS engine and dynamic format strings on calc groups. Will reach to the AS engine team.

**Comment by marcosqlbi** [comment]
Update: the fix is in progress, but it will be deployed in February/March 2021.

**Comment by anderseik** [comment]
> Update: the fix is in progress, but it will be deployed in February/March 2021.

Thanks to you both Daniel and Marco, appreciate it

**Comment by otykier** [comment]
@anderseik did you have a chance to see if the issue is resolved with the February release of Desktop?

**Comment by anderseik** [comment]
@otykier checked now, not able to recreate issue. It's worth mentioning that I do not have access to the PC and the model I was working on at the time I raised the issue, but as far as I remember, this was a general issue with all models I tested it on.

thanks!
