### ISSUE TITLE
Can Tabular Editor read/import DAX Code from a file to update a model?

### ISSUE THREAD

**Issue by BAHMBBSA** [otykier/TabularEditor#704]
Hi, 

I would just like to say what a great tool Tabular editor is, thank you Daniel Otykier.

I would like to know if it is possible to import/stream DAX code (originally generated by Power BI query editor) from a csv/txt/xls file into a model?   I originally asked this question in [Power BI community ](https://community.powerbi.com/t5/Desktop/Is-it-possible-to-use-a-DAX-table-column-list-rows-to-generate/m-p/1488165#M618006) and was advised to try Tabular Editor  (version 2.12.4 installed) and running from external tool in Power BI desktop  (version  2.87.762.0 64-bit (November 2020) ). 
I have looked at the advanced scripting tutorials but I cant see a way to loop through a file to read in the generated DAX code and update model (1 new calculated table for each row read) -
![image](https://user-images.githubusercontent.com/36401776/101190588-77324980-3650-11eb-8cea-63b9dcff726a.png)

I can use Tabular editor to update the model manually one line at a time (offline in TE, which is still a big improvement on PBI Desktop) but,
![image](https://user-images.githubusercontent.com/36401776/101192924-b57d3800-3653-11eb-8180-74d2fa9b3c5e.png)
it would be great if I could loop/read though  the DAX_TABLES file above containing the DAX code to EOF... generating each of the 102 calculated tables I need to add in the model...

I hope this makes sense.

Many thanks.
Best regards,
Clive.

**Comment by otykier** [comment]
While adding calculated tables to a Power BI Desktop model is not among the [supported operations for external tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations), Tabular Editor's scripting engine can certainly read metadata from a file and add new calculated tables to a model based on this metadata.

Let's say I have a file, myfile.txt, with the following content:

```
table1 = {(1,2,3)}
table2 = {(4,5,6)}
```

A script that reads this file and creates one calculated table for each line in the file would look like this:

```csharp
var fileContent = ReadFile(@"c:\path\to\myfile.txt");
var lines = fileContent.Split('\n');
foreach(var line in lines)
{
    var equalsSignPosition = line.IndexOf("=");
    if(equalsSignPosition < 0) continue;
    
    var tableName = line.Substring(0, equalsSignPosition - 1).Trim();
    var daxExpression = line.Substring(equalsSignPosition + 1).Trim();
    
    Model.AddCalculatedTable(tableName, daxExpression).FormatDax();
}
```

**Comment by BAHMBBSA** [comment]
Hi Daniel,

**Fantastic**, your script code above worked a treat, Tabular Editor has so many benefits.
Thank you for all you efforts and replying so quickly.

Very much appreciated.
Best regards
Clive

**Comment by rvgfox** [comment]
Hi,
Is it possible from C# script run a DAX script that it's on a file?

**Comment by otykier** [comment]
Sorry, I’m not sure I understand the question.

Do you have a DAX query in a file, and you want to execute that query against a model? That is possible, but what do you want to do with the result of the query?
