### ISSUE TITLE
Possible to retrieve dax formulas stored as strings in data table?

### ISSUE THREAD

**Issue by ejheflin** [otykier/TabularEditor#706]
I am trying to figure out if there is a method by which to retrieve a dax expression stored as text in a sql database. My ultimate goal is to interact with canned report definitions to programmatically recreate them in excel. Consider this example table:

Line       Description          Formula
   1            SalesA
   2            SalesB
   3            SalesTotal        =CALCULATE([Measure],Table'Line' IN{1,2})

This isn't a working example but I think it helps illustrate my point. I would like to be able to parse values into variables to be used to construct my own dax expression. Thanks in advance!

**Comment by otykier** [comment]
This is definitely possible through scripting.

See [this example in the docs](https://docs.tabulareditor.com/Useful-script-snippets.html#generating-measures-from-a-file). To read the measure definitions from a database instead, you could use [SqlCommand](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand?view=netframework-4.7.2) from the .NET System.Data.SqlClient namespace.

**Comment by ejheflin** [comment]
for the sake of anyone else searching for this, I got a working script:
`string query = "EVALUATE VALUES('dimFormat'[Formula])";
 
using (var reader = Model.Database.ExecuteReader(query))
{
    // Create a loop for every row in the resultset
    while(reader.Read())
    {
        string val = reader.GetValue(0).ToString();
        val.Output();
    }
}`

I think it's odd that I can't find this ExecuteReader method documented anywhere. Perhaps I'm confused on what exactly is handling this but it is definitely a step in the right direction none-the-less.

**Comment by otykier** [comment]
ExecuteReader "documentation": https://docs.tabulareditor.com/Useful-script-snippets.html#querying-analysis-services

The method returns an **AmoDataReader** (see [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.amodatareader?view=analysisservices-dotnet))
