### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by htx-bex** [otykier/TabularEditor#708]
Describe the bug
From Read.me, selecting the link to download brings up a github 404 error. Link is below
https://github.com/otykier/releases/latest

To Reproduce
1. Go to https://github.com/otykier/TabularEditor
2. Scroll down to README.md
4. Click to open link - "Download Latest Tabular Editor for SQL Server 2016, 2017, 2019, Azure Analysis Services or Power BI Premium" > Link is here https://github.com/otykier/releases/latest
5. Takes you to "Page not Found"- GitHub

Expected behavior
I expected to see a page where I can download Tabular Editor.

**Comment by otykier** [comment]
Fixed! Thanks for reporting.
