### ISSUE TITLE
BPA cannot query as SingleColumnRelationship (e.g. FromColumn)

### ISSUE THREAD

**Issue by rwforest** [otykier/TabularEditor#71]
GetCollection() in Analyzer.cs is returning:
                case RuleScope.Relationship:
                    return Model.Relationships.AsQueryable();
Where Relationships is of type RelationshipsCollection2.

However, in BestPracticeRule.cs, it is getting the type straight from the name, making the *validation* of the rule resulting error:

var t = assembly.GetType("TabularEditor.TOMWrapper." + scope.ToString());

Should change the scope to SingleColumnRelationship to take advantage what the Analyzer has to offer.

**Comment by otykier** [comment]
Thanks for reporting this. In release 2.4 (which is just around the corner), I've changed the way the BPA works slightly. For example, it will be possible to define a single rule affecting multiple types of objects. When choosing "Relationships" as scope, the underlying type will be resolved as a SingleColumnRelationship (no longer dynamically inferred from the scope name), as SSAS currently does not have any other kinds of relationships.

Will let you know as soon as 2.4 is up.

**Comment by rwforest** [comment]
@otykier , great thanks! I was wondering why you built a parent relationship, were you preparing you SSAS 2020 😄

**Comment by otykier** [comment]
The wrapper classes I use have the same inheritance as the [corresponding classes in the TOM](https://msdn.microsoft.com/en-us/library/microsoft.analysisservices.tabular.singlecolumnrelationship.aspx?f=255&MSPPError=-2147217396), so it's actually not my idea :-)

Could be that Microsoft is planning to have different kinds of relationships in the future.

**Comment by otykier** [comment]
This was fixed in [release 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Feel free to reopen the issue if you have questions or if you encounter any problems.
