### ISSUE TITLE
Column's option "encodingHint" in pbix

### ISSUE THREAD

**Issue by jasonlaw997** [otykier/TabularEditor#712]
There is a option "encodingHint"  in column  when tabular editor connecting the model which is in ssas.
But  it is disappear   when tabular editor connecting the  pbix.
Could you add this feature .

![Snipaste_2020-12-14_10-53-40](https://user-images.githubusercontent.com/37357651/102035132-a425ef80-3dfa-11eb-8123-f51a74456081.png)

**Comment by otykier** [comment]
External Tools for Power BI Desktop only supports a [limited set of write operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations). Editing column properties is not supported.

However, if you go to File > Preferences and put a checkmark in "Allow unsupported Power BI features", you can unlock all modelling operations on your pbix files. But please be aware that this may cause your pbix file to become corrupt in which case Microsoft support will not be able to help you, so make sure to keep a backup of the original file.
