### ISSUE TITLE
Tabular Editor Opens the Model as read-only

### ISSUE THREAD

**Issue by SergioMurru** [otykier/TabularEditor#714]
When I launch the Tabular Editor 2.13.2 from Power BI External Tools menu i get the message 

Power BI Desktop model Read only.
Editing a Power BI Desktop model that does not use the Enhanced Model Metadata (V3) format is not allowed, unless you enable Experimental Power BI Features under File > Preferences
Tabular Editor will still load the model in read-only mode.

I already created Calculation Groups in older pbixes that still opens without errors and without setting the Enable Experimental Power BI Features.

I can replicate it launching the Tabular Editor from an empty pbix.

I don't report this as a bug but as a help request, since I'm almost sure that there must be something wrong that I'm doing, since it's too strange.

These are the About information from Power BI

Feedback Type:
Frown (Error)

Timestamp:
2020-12-14T13:36:30.4544016Z

Local Time:
2020-12-14T14:36:30.4544016+01:00

Session ID:
a8135473-6d4c-40b2-9a68-db08a17cf900

Release:
November 2020

Product Version:
2.87.1061.0 (20.11) (x64)

OS Version:
Microsoft Windows NT 10.0.19041.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 528372]

Peak Virtual Memory:
38.3 GB

Private Memory:
475 MB

Peak Working Set:
543 MB

IE Version:
11.630.19041.0

User ID:
<removed>

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Snapshot Trace Logs:
C:\Users\sergio\Microsoft\Power BI Desktop Store App\FrownSnapShot6728bbd2-4929-4d20-b23e-98eb6f668613.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
True

Performance Trace Logs:
C:\Users\sergio\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Enabled Preview Features:
PBI_NewWebTableInference
PBI_v3ModelsPreview

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_JsonTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_qnaLiveConnect
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_narrativeTextBox
PBI_dynamicParameters
PBI_anomalyDetection
PBI_newFieldList

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
125%

Supported Services:
Power BI

Formulas:

section Section1;

**Comment by otykier** [comment]
I believe you have to add at least a single table to the model through Power BI Desktop, before the model is upgraded to the V3 metadata format, which is required before Tabular Editor can make changes to the model in a supported way (V1 models can only be opened in read-only mode).

**Comment by SergioMurru** [comment]
Ok, after your reply I've found the problem: I was just adding tables using DAX. 
After adding a table with "Enter data", therefore with Power Query, it solved the issue.
Thank you.
