### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by Fayyaadh** [otykier/TabularEditor#715]
**Is your feature request related to a problem? Please describe.**
I think you need admin rights to install TE, would be nice to have a portable version like how DAX Studio offers.

**Describe the solution you'd like**
A portable version of TE that doesn't require installation or admin rights.

**Describe alternatives you've considered**
None.

**Comment by Fayyaadh** [comment]
Actually on 2nd look, it's seems there already is a portable version. Is this something new, never noticed it before.

**Comment by otykier** [comment]
A portable (.zip asset) version of TE has been available for every release within the past 2-3 years.
