### ISSUE TITLE
BPA - adding a line space

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#716]
**Describe the bug**
No longer able to add a line space in the BPA manager.

**To Reproduce**
1. Go to the 'Manage Best Practice Rules'
2. Edit a rule
3. Press 'Enter' within the Rule Expression Editor

**Expected behavior**
Pressing 'Enter' should enter a new line.

**Observed behavior**
Instead of generating a new line it saves the rule and closes the rule editor (going back to the Manage Best Practice Rules).

**Application specifics**
 - Tabular Editor version: 2.13.2

**Additional context**
I believe this is due to the fix of bug #686

**Comment by otykier** [comment]
Thanks for reporting. As a workaround, until I fix the issue, use CTRL+Enter to enter a new line.

**Comment by m-kovalsky** [comment]
Thanks for the workaround, Daniel.

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0). Thanks for reporting!
