### ISSUE TITLE
Deploy changes compatibility level and culture (from nl to us)

### ISSUE THREAD

**Issue by do-nation** [otykier/TabularEditor#717]
Deploying a existing model to a new model sometimes changes the compatibility level (from 1520 to 1465) and the culture (nl to us). Changing the culture of a model after the deployment is not possible. Any changes (for example comparing and updating the model in ALM Toolkit) will result in error messages (bad request). What is going wrong? Any help appreciated.

**Comment by otykier** [comment]
My understanding is that it is not possible (on the AS engine side) to upgrade the compatibility level of a model by executing a TMSL CreateOrReplace script (which is what Tabular Editor's Deploy functionality does). The same thing applies to the culture. I believe in this case, you would have to delete the model and do a clean re-deploy.

If you only need to change the compatibility level, I believe it can be done by connecting directly to the model from Tabular Editor (File > Open > From DB...), then setting the Compatibility Level to the new value and hit Save (CTRL+S). Unfortunately, this approach will not work for changing the model culture.

**Comment by do-nation** [comment]
Thank you for this. Am I understandig correctly that deploying to a new (non-existing) model via Tabular Editor could not have changed the compatibilty level and culture? It is a complete mystery to me why I get models with a different culture and comp.level. I never deliberately change it, could it be related to language settings in Windows? I only deploy in Tabular Editor or ALM toolkit.

**Comment by do-nation** [comment]
And they are all Power BI datasets

**Comment by otykier** [comment]
Are we talking about deploying to a Power BI Premium workspace through the XMLA endpoint?

In that case, deploying a fresh model (no pre-existing dataset with the same name in the workspace) should retain the compatibility level and culture specified in the metadata you're deploying from. If it doesn't, please provide a detailed step-by-step repro, and I'll be happy to look into it in more detail.

**Comment by do-nation** [comment]
Yes, it is Power BI Premium workspace through the XMLA endpoint (gen 2). The model is in a workspace and I am deploying to another workspace (both premium gen 2 large dataset storage format).

**Comment by do-nation** [comment]
It immediately gives the warning: the remote server turned an error (400) bad request. It has created a model, but as I mentioned it has the wrong comp level and culture.

**Comment by do-nation** [comment]
And to make matters more mysterious, sometimes the deploy succeeds without any errors. So sometimes when I delete the model and try again it works perfectly.

**Comment by do-nation** [comment]
For reproduction: I open Tabular Editor, I open a model in my [Test] workspace (Premium gen 2) called _universe datamodel_ then I click Model and Deploy. I choose another workspace [Development] (Premium gen 2), I log in and then change the name of the mode to _universe datamodel test_ then click Next, Next and Deploy and the errror pops up in a Tabular Editor message box.

**Comment by do-nation** [comment]
There is a model in the workspace [Development] also called __universe datamodel_ but not the new  _universe datamodel test_  that does not yet exist.

**Comment by otykier** [comment]
Which version of Tabular Editor are you using? Versions before 2.13.1 had an issue with Tabular Editor executing a database `create` TMSL statement, which doesn't work well with PBI Premium Gen2. This was fixed in 2.13.1 so it always uses the `createOrReplace` TMSL.

If upgrading to the latest version doesn't solve the issue, please report this as a bug with Microsoft, as this is definitely an issue on their end.

**Comment by do-nation** [comment]
Oh I feel stupid now for not checking if I needed the latest version. I feel that may be indeed the issue. Thank you so much for your time. Sorry to bother you with a problem that could have been resolved by updating to the latest version. I am very glad that it is solved and I am very thankful for your help.
