### ISSUE TITLE
Relationships for variations get messed up

### ISSUE THREAD

**Issue by dschingisab** [otykier/TabularEditor#718]
**Describe the bug**
The relationships for variations from a field to the dimensional table get messed up when you do changes (e.g. add another relationship in the model somewhere). 

**To Reproduce**
1. Set up a relationship for a variation in a field that is connected to another table. Deploy the model --> works
2. Add another relationship to the model that will be added before the relationship that is used for the variation.
3. When you try to deploy the deployment fails.
4.  You can fix this by setting up the relationship again for this variation and all subsequent variations.

**Expected behavior**
Error message after deployment: "The relationship for Variation 'xxxHierarchy' must be defined on the current table, when a relationship is specified."

**Observed behavior**
It seems that the added relationship increments the relationship counter. So the internal relationship number for the variation points to a completley different relationship that is not applicable for the variation.

**Application specifics**
 - Tabular Editor version: 2.13.2
 - Semantic Engine used: SSAS 2019
 - Model Compatibility Level: 1400

**Comment by otykier** [comment]
I'm not sure this is a Tabular Editor issue, but rather an issue with the TOM (as Tabular Editor does not keep any counters/internal IDs for tracking relationships). Could you provide a sample Model.bim file to illustrate the issue?

**Comment by dschingisab** [comment]
I'm using a serialized model and I think it has something to do with it. I've uploaded the folder:
[VariationModel.zip](https://github.com/otykier/TabularEditor/files/5729347/VariationModel.zip)

Here are the steps for reproduction a bit more in detail:
1. I open the serialized model that contains variations from a folder. Variation relationships are correct:
![image](https://user-images.githubusercontent.com/76444804/102879911-d1058280-444a-11eb-985c-b10d256ffa60.png)

2. I add a new relationship to the model that is pasted before the existing relationships that connect the variation field to the hierarchy table.
![image](https://user-images.githubusercontent.com/76444804/102879893-cc40ce80-444a-11eb-9c7d-c44bbb30c991.png)

3. I save and **reopen** the model. Now the relationships got messed up:
![image](https://user-images.githubusercontent.com/76444804/102879983-f09cab00-444a-11eb-98dc-617d7b8b7665.png)

Here are my serializiation settings:
![image](https://user-images.githubusercontent.com/76444804/102877649-5dae4180-4447-11eb-9b44-fe65440a71d4.png)

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0), by ensuring that Relationship Names/IDs gets included in the annotation serialization (but only if the model contains at least one variation). Thanks for reporting!
