### ISSUE TITLE
ODBC data sources show the password in properties

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#722]
**Describe the bug**
ODBC connections displays the actual password as part of the connection string within the Data Source properties window.

**To Reproduce**
1. Create ODBC data source
2. Click on the Data Source
3. Navigate to properties...connection string
4. See that the password shows

**Expected behavior**
For security purposes it should show *******

**Application specifics**
 - Tabular Editor version: 2.12.4

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0). Thanks for reporting!

**Comment by m-kovalsky** [comment]
thanks!
