### ISSUE TITLE
Sort By Column / Script to apply parent-child hierarchy in Tabular Editor  

### ISSUE THREAD

**Issue by natolira** [otykier/TabularEditor#723]
Is there any way to sort a column  by another column in Tabular Editor?

I´m new to it and couldn´t find this property.

My ultimate goal is to automatically generate the DAX PATTERN https://www.daxpatterns.com/parent-child-hierarchies/ through a Tabular Editor script.. but I have a requirement that the order of the columns of each level must be ordered by each Key (not alphabetically)

**Comment by zenzeinet** [comment]
Sort by property of columns. Look again :)

**Comment by natolira** [comment]
Yeah... I had to enable the Experimental Power BI features. Now I can see it :)

Thanks.
