### ISSUE TITLE
BPA - No scrollbar while editing best practice rule

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#725]
**Describe the bug**
Not sure if this is a bug or a new feature request. Thought there used to be a scrollbar in the Rule Expression Editor while editing a best practice rule.

**To Reproduce**
1. Go to 'Manage Best Practice Rules'
2. Click on 'Edit Rule'
3. See that no scrollbar appears. And, as such, no scrolling is possible.

**Expected behavior**
Thought there was a scrollbar before but could be mistaken. Would be helpful to have a scrollbar for rules that go beyond the default page size.

**Application specifics**
 - Tabular Editor version: 2.13.2

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0). Thanks for reporting!

**Comment by m-kovalsky** [comment]
Confirmed, thanks!
