### ISSUE TITLE
Unexpected error on deployment

### ISSUE THREAD

**Issue by marcitsmart** [otykier/TabularEditor#730]
**Describe the bug**
When attempting to deploy a specific Model.bim file to the server using tabular editor an error message is raised:
The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'An unexpected error occurred (file 'mddefaultmembers.cpp', line 355, function 'MDNaiveCoordCell::InitPrototype').'.
Subsequent attempts to deploy the model using both Tabular Editor and Visual studio continue to raise this error.
Deploying another model to the same server using Tabular Editor does not raise the error.

**To Reproduce**
1. Open the Model.bim file;
2. Select the 'Model' menu in the menu bar; 
3. Select the option 'Deploy';
4. Enter the server name and authentication method;
5. Select the preferred database to deploy to;
6. Select which elements to deploy;
7. Click 'Deploy'.

**Expected behavior**
I expected the model to deploy to the server.

**Observed behavior**
When clicking deploy the following error message is shown and deployment is stopped.
Screenshot of the error message
![image](https://user-images.githubusercontent.com/71496547/103919822-cc122580-5110-11eb-9d7d-f31a24dc7ac5.png)

**Application specifics**
 - Tabular Editor version: [2.13.2]
 - Visual Studio 2019 version: [16.8.3]

**Additional remarks**
If you want to see the Model.bim file that raises the error please let me know.

**Comment by otykier** [comment]
This seems to be an issue with Analysis Services. Please reach out to Microsoft Support for this. Remember to provide information about which version of SQL Server Analysis Services you're using.

If you can provide the Model.bim file or the `createOrReplace` TMSL script that fails (you can extract this using Tabular Editor's Deployment Wizard), I'd be happy to reach out to the product team on your behalf.

**Comment by marcitsmart** [comment]
Dear Daniel,

Thank you for your reply.
Too bad that it's an Analysis Services problem. Yesterday I discovered SSAS also has a problem with the newest version of SSIS, so I hope both these conflicts can be resolved in the next version of Analysis Services.
I've attached the TMSL script for the model in .txt format to this message and I'd appreciate it if you'd reach out to the product team.

Many thanks in advance.

Sincerely,
Marc




________________________________

**Comment by otykier** [comment]
@marcitsmart do you still have this issue using the [latest release of Tabular Editor](https://github.com/otykier/TabularEditor/releases/latest)? If so, which version of Analysis Services (build #) are you using?

**Comment by marcitsmart** [comment]
@otykier I've downloaded the latest release and tried deploying a new .bim file. The error does not appear anymore so it looks like it's fixed.
Thank you for your response and your time.

Marc

**Comment by kjoebie** [comment]
Hi,

I'm experiencing the same issue with TE 2.17.1. I'm deploying to a SSAS 2016 Tabular Server (build 13.0.6300.2). I pinpoint the issue down to a change of the property 'Available in MDX'. When I set it to False then the issue arises. When it is left at True than I can deploy the model. I've set this property for all of my dimension and fact keys.

**Comment by otykier** [comment]
Hi @kjoebie please note, this error has nothing to do with Tabular Editor.

The "Availabe in MDX" keyword is not supported on SSAS 2016, so you must leave it at its default value (true). More info here: https://blog.crossjoin.co.uk/2018/07/02/isavailableinmdx-ssas-tabular/

**Comment by kjoebie** [comment]
Excellent! Good to know...

**Comment by otykier** [comment]
@BI-PARVI I'm not familiar with that error, sorry. Considering that the error message references some of the Analysis Services internals (pcserialize.cpp), I think your best option is to raise a support ticket with Microsoft.
