### ISSUE TITLE
BPA: Maintenance spelled incorrectly

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#731]
**Describe the bug**
The BPA category of 'Maintainance' is spelled incorrectly. It should be 'Maintenance'.

**To Reproduce**
1. Go to the BPA Manager

**Application specifics**
 - Tabular Editor version: 2.13.2

**Comment by otykier** [comment]
Are you talking about the values available in the dropdown? These values are all based on whatever rules are currently loaded.  In other words, if you see "Maintainance", you must have one or more rules using this category - it's not a Tabular Editor default (in fact, when you have no rules loaded, Tabular Editor does not display anything in the dropdown).

**Comment by m-kovalsky** [comment]
Ah interesting. Thought it was a default category but apparently we must have added it ourselves. Can close this one out, thanks.
