### ISSUE TITLE
How create Calculation Items within calculation group?

### ISSUE THREAD

**Issue by jasiluka** [otykier/TabularEditor#733]
**What are you trying to achieve?**
Hi all , i am trying to create a sample calculation group on a blank new model via advanced editor. The script I got so far is:

var obj3 = Model.AddCalculationGroup("TestCalculatinGroup");
    obj3.AddCalculatedColumn("TestCalculatedColumn").Expression = "0";
    obj3.AddMeasure("BaseMeasure");

Question is: how do I create a new calculation item within this calculation group?
Can't seem to find the right syntax for it and there seems to be very little information on the internet around this.
Appreciate your help!

![image](https://user-images.githubusercontent.com/53556730/104600515-61fe0100-5679-11eb-82f3-adf1831f8c71.png)

**Comment by otykier** [comment]
You shouldn't add calculated columns to a calculation group unless you have a very specific need for them.

In order to add calc items, use the `.AddCalculationItem(<name>, <expression>)`-method on the Calculation Group (apparently, that method does not show up in the intellisense, which is a bug):

```csharp
var obj3 = Model.AddCalculationGroup("TestCalculationGroup");
obj3.AddCalculationItem("Current", "SELECTEDMEASURE()");
obj3.AddCalculationItem("YTD", "TOTALYTD(SELECTEDMEASURE())");
```
