### ISSUE TITLE
Longitude and Latitude in TabularEditor

### ISSUE THREAD

**Issue by mitrap** [otykier/TabularEditor#734]
How to change a data field to the data type either “Longitude” or “Latitude” under Tabular Editor? I looked under “data category” and didn't see any long or Lat option. Would you please let me know?

**Comment by otykier** [comment]
According to [this specification](https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssas-t/f85cd3b9-690c-4bc7-a1f0-a854d7daecd8) there are no definitions for Latitude / Longitude data categories. But if your client tool expects a certain string value you can simply enter it, as Tabular Editor allows you to enter any string as data category (the dropdown is simply populated with the values according to the specification).

**Comment by mitrap** [comment]
Thank you. My follow up question is: We are pulling data from SQL server into TabualarEditor, deploying on to Analysis Server, and building analytics on Power BI connecting Analysis server. What data categories should we select in TabualarEditor for long/Lat data fields that comes from SQL tables so that when we pull in Power BI, Power BI would identify them as Long/Lat? For example, if we pull SQL tables directly into Power BI, we select Long/Lat under Data Category. Please help.

**Comment by otykier** [comment]
I am not aware what annotation or data categories Power BI uses for long/lat fields. I suggest you try to apply those categories on a sample model that you create in Power BI Desktop, then open that model in Tabular Editor and see what settings have been applied to the relevant columns.

**Comment by otykier** [comment]
Closing this issue as the question itself is unrelated to Tabular Editor since the tool is completely agnostic to data categories.
