### ISSUE TITLE
Saving a Custom Action with 'act' parameter

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#735]
**Describe the bug**
It is not possible to save a custom action if there is a parameter called 'act' in the script.

**To Reproduce**
1. Go to the Advanced Scripting window
2. Type in the following code:

string act = "hello";
act.Output();

3. Click the 'plus' sign to save the custom action
4. See this error

![image](https://user-images.githubusercontent.com/29556918/104932627-837c2700-59b0-11eb-821e-671328ab97bf.png)

**Observed behavior**
Changing the parameter name to something else (i.e. actv) fixes the issue.

**Expected behavior**
Would expect this to work. Think there must be some system parameter called 'act' which makes this have a conflict. Just a guess.

**Application specifics**
 - Tabular Editor version: 2.13.2

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0).
