### ISSUE TITLE
Deploy without roles

### ISSUE THREAD

**Issue by rdodworth** [otykier/TabularEditor#737]
**What are you trying to achieve?**
I want to use the command line of Tabular Editor to deploy a model without roles 
We have roles embedded in the model because most of our deployments are on prem 
But when trying to deploy to Azure I would like to deploy the model.bim without the on prem roles which makes the model deployment fail
Or if thats not possible I would like to specify the new Azure roles overriding whats in the bim 

**What have you tried so far?**
Nothing really because although I can see you can specify an -R argument i can't seen an example of how you use it

**Comment by otykier** [comment]
By default, Tabular Editor will not let you deploy on top of an existing database, unless you specify the `-O` (override) switch. When doing this, all model roles, their members, as well as existing model data sources and partitions are untouched. You'll have to explicitly specify switches for each of these types of objects, if you want to update them to match what's in the Model.bim file.

Thus, the following command will deploy on top of an existing database **without** deploying the model roles:

`start /wait TabularEditor.exe Model.bim -D servername databasename -O`

To include roles but retain members of those roles, as already specified on the server, use the `-R` switch but omit the `-M` switch:

`start /wait TabularEditor.exe Model.bim -D servername databasename -O -R`

To update the members on the server to match those that are defined in the .bim file, also add the `-M` switch:

`start /wait TabularEditor.exe Model.bim -D servername databasename -O -R -M`

[Command line documentation](https://docs.tabulareditor.com/Command-line-Options.html).

**Comment by rdodworth** [comment]
This is great stuff Daniel thanks

**Comment by rdodworth** [comment]
Just omitted the R parameter and it worked a treat ! Thanks
