### ISSUE TITLE
Advanced Scripting - Trying to Set "Do NOT Summarise" to Selected Columns

### ISSUE THREAD

**Issue by Jabba1963** [otykier/TabularEditor#741]
Hi,

Trying to create a Custom Script under Advanced Scripting in the Tabular Editor to Set Column Summarization to "Do Not Summarise" for all selected columns.

I checked the bim file and noted that it uses the string "none" so tried using that in a script as follows:

foreach(var c in Selected.Columns)
{
    c.SummarizeBy = "none";
}
 
However I am getting a data type error msg as follows:

CS0029 - cannot implicitly convert type "string" to TabularEditor.TOMWrapper.AggregateFunction

Any assistance to get this working will be much appreciated 🙂

**Comment by otykier** [comment]
```csharp
foreach(var c in Selected.Columns)
{
    c.SummarizeBy = AggregateFunction.None;
}
```
