### ISSUE TITLE
Composite models and field/table renaming

### ISSUE THREAD

**Issue by DaniilMaslyuk** [otykier/TabularEditor#742]
Let's say I've got a composite model.

In Power BI Desktop, I can

- Create a new measure
- Rename a table

In Tabular Editor, I

- Can create a new measure
- Can**not** rename a table

Is this expected?

**Comment by otykier** [comment]
I must admit I haven't gotten around to testing composite models with Tabular Editor.

My immediate thought is that you're launching Tabular Editor as an external tool for Power BI Desktop - in that case, Tabular Editor will by default block [all modelling operations that are not supported by Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations), such as renaming tables. Did you allow unsupported Power BI features in Tabular Editor's preferences (File > Preferences)?

**Comment by DaniilMaslyuk** [comment]
You're right -- it works when you enable unsupported Power BI features. Thanks!
