### ISSUE TITLE
Find and Replace Issue

### ISSUE THREAD

**Issue by jebellingham** [otykier/TabularEditor#744]
Hello & firstly thank you @otykier for creating such a useful application - I am not a developer, so please forgive my use of incorrect terms etc. My issue is with using Find and Replace. I am trying to use this feature to replace one element of an expression and what I am discovering is that whilst the Find feature will find the string of text, Find and Replace will not highlight the same text, or will not find it at all.

To trigger the error;
1. I click on the measure with the text I want to replace
2. Click within the Expression Editor
3. Find / Find and Replace become available
4. I click the Find icon and enter the text, then click Find, it finds the text as expected
5. However, if I copy the text I entered into the Find function, close the dialog box, then click on Find and Replace, it does not find the same text. It tends to highlight text on the same row before the text it should highlight, on other expressions with the same text string, it may not find anything at all
6. Sometimes clicking on the Format Dax icon and toggling between Long Line and Short Line seems to temporarily fix the issues, but not always

Expected behaviour would be for the finding part of Find and Replace to work the same as Find.

There are no error messages

Thank you once more for developing this very useful application, apologies for my poor use of terminology. 

I am using version 2.13.7643.22890 which I believe is the most recent version
Power BI Desktop Version is 2.88.1385.0 (December 2020)

**Comment by jebellingham** [comment]
<img width="772" alt="1-Find" src="https://user-images.githubusercontent.com/74017787/106137592-d0a38a00-6162-11eb-8bc1-855e99899558.png">
<img width="767" alt="2-Find_and_Replace" src="https://user-images.githubusercontent.com/74017787/106137609-d600d480-6162-11eb-853b-0a4c3e0e058f.png">

**Comment by otykier** [comment]
Fixed in [2.14.0](https://github.com/otykier/TabularEditor/releases/tag/2.14.0).
