### ISSUE TITLE
Tabular Editor 3 Public preview is not accessible

### ISSUE THREAD

**Issue by Ratnababu85** [otykier/TabularEditor#746]
**What are you trying to achieve?**
I am trying to access public preview for latest version of Tabular Editor 3. 

**What have you tried so far?**
I tried to access through link https://github.com/TabularEditor3/PublicPreview, but its not accessible.
Could you please guide me to right path.

![image](https://user-images.githubusercontent.com/77418690/106366499-24dc7480-62f1-11eb-9d89-5fbf114acf6a.png)

**Comment by otykier** [comment]
You have to be logged in to GitHub using the account that received the invitation the preview.

**Comment by Ratnababu85** [comment]
I have raised request for public preview, but I didn't get invitation link yet. Could you please help me to get invitation link?

**Comment by otykier** [comment]
We were overwhelmed with the number of people who signed up for the preview, so unfortunately we were not able to send the invitation link to everyone. We will send out more invitations during the next few weeks, but I can't guarantee that you'll be selected. In any case, once Tabular Editor 3 is finally released, there will be an option for evaluating the product, so even if you didn't get in to the preview, you will still have a chance to try it out for free.
