### ISSUE TITLE
CalculationGroupTable misspelling in Custom Actions

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#751]
**Describe the bug**
The 'e' is cut off from 'CalculationGroupTabl' within saving a custom action.

**To Reproduce**
1. Enter code in the Advanced Scripting window.
2. Click on the 'plus sign' icon to save a custom action.
3. Scroll to the right and see 'CalculationGroupTabl'

![image](https://user-images.githubusercontent.com/29556918/106857670-216a3400-66c9-11eb-8cb4-1e224ada9bd5.png)

**Expected behavior**
Looks like it's supposed to be 'CalculationGroupTable' but the 'e' is cut off.

**Observed behavior**

**Application specifics**
 - Tabular Editor version: 2.14.0

**Comment by otykier** [comment]
Fixed in [2.14.1](https://github.com/otykier/TabularEditor/releases/tag/2.14.1). This was actually a matter of columns being too narrow for the full text to display. I increased the column width and also the height of the dialog, to get rid of the scrollbar.
