### ISSUE TITLE
Show/Hide partitions state not persisted

### ISSUE THREAD

**Issue by Thinqer77** [otykier/TabularEditor#754]
**Describe the bug**
When I close and re-open the app, the state of the 'Show/Hide Partitions' option is not persisted - it seems to reset to 'Show'. All of the other visibility settings are persisted (e.g. show/hide columns, show/hide hierarchies etc).

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the 'Show/Hide Partitions' option to hide partitions (do this via the UI, not the shortcut keys Ctrl+6)
2. Close the app
3. Reopen the app
4. Check the state of this setting

**Expected behavior**
The state should be whatever it was set to when the app was closed.

**Observed behavior**
State is not persisted.

**Application specifics**
 - Tabular Editor version: 2.14.0
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: n/a

**Comment by otykier** [comment]
Fixed in [2.14.1](https://github.com/otykier/TabularEditor/releases/tag/2.14.1).
