### ISSUE TITLE
No option to run c# code in Advanced scripting editor

### ISSUE THREAD

**Issue by learn2excel** [otykier/TabularEditor#755]
**What are you trying to achieve?**
I am tring to run the below script via the scripting editor
System.Net.WebClient w = new System.Net.WebClient(); 

string path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData);
string url = "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json";
string downloadLoc = path+@"\TabularEditor\BPARules.json";
w.DownloadFile(url, downloadLoc);

**What have you tried so far?**
Copied the code to the scripting editor.
![ScriptingEditor](https://user-images.githubusercontent.com/32434277/107038217-26c59c80-67f7-11eb-8e62-458e1c8597f7.png)

**Comment by otykier** [comment]
You must have a model loaded to run a script - even if the script doesn't touch the model metadata. In other words, you can simply "Ctrl+N" to create a new blank model before running the script.

**Comment by learn2excel** [comment]
Thanks. Appreciate the feedback.Can i point this to a power bi file.

**Comment by learn2excel** [comment]
I wanted to point this to a power bi file. not sure if that is what this is designed to do. Closing this

**Comment by otykier** [comment]
The script you tried to execute does not impact the model metadata at all. It is simply a script that downloads a set of Best Practice Analyzer rules to your local machines. Once these rules are downloaded, they will show up in the Best Practice Analyzer for every subsequent data model loaded in Tabular Editor (including Power BI files).
