### ISSUE TITLE
Calculation Table with support the icons

### ISSUE THREAD

**Issue by rafaelxkr** [otykier/TabularEditor#756]
Dax code with result icon
![image](https://user-images.githubusercontent.com/31570331/107120270-6d54de80-686b-11eb-8023-66709236433e.png)

Created rules 
![image](https://user-images.githubusercontent.com/31570331/107120328-d3416600-686b-11eb-8e10-2254b4cd8ac3.png)

Don't work  - "error when rendering the report"
![image](https://user-images.githubusercontent.com/31570331/107120308-b2791080-686b-11eb-829d-378331f5b9a6.png)

 
![image](https://user-images.githubusercontent.com/31570331/107120414-3af7b100-686c-11eb-9836-1250d78ed37d.png)

**Comment by otykier** [comment]
This question does not seem to be related to Tabular Editor.
