### ISSUE TITLE
Can a calculation item be hidden?

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#757]
**What are you trying to achieve?**
It appears that the 'Calculation Item' is the only object in the table construct that cannot be hidden. Is this a limitation in tabular or Tabular Editor?

**What have you tried so far?**
Edited the .bim file in notepad and added a clause to the calculation item for IsHidden = true. However, then the .bim file couldn't load into tabular editor. That being the case, I would think this is a limitation within tabular, not Tabular Editor.

**Comment by otykier** [comment]
Calc items cannot be hidden. They are rows in a table - if you want certain calc items to not be visible in a slicer, then add a calc column to the calc group table and use that column to filter your slicer.

**Comment by m-kovalsky** [comment]
Got it, makes sense. Thanks!
