### ISSUE TITLE
Dynamically Create a measure with different names in Tabular editor

### ISSUE THREAD

**Issue by kmostafa89** [otykier/TabularEditor#760]
Hey Daniel,

I have a scenario where I want to create a measure dynamically for each year between 2010 and 2020. 

my measure looks like this and I want 2020 to be a dynamic value based on a loop that loops through 2010 to 2020. 

on a more advanced level, I want to have a nested loop and pass on different values to each calculate method.

Thank you for all your work in the tabular editor, it's a great tool and I'm very keen on doing fancy stuff with it.

measure_2020 = 
VAR logicTest = 
COUNTROWS(DISTINCT(
    FILTER(
        ALLSELECTED(YEARS[YEAR]),
        YEARS[YEAR] =2020 )
                   )
        ) = 1
VAR TypeTest = 
COUNTROWS(DISTINCT(
    FILTER(
        ALLSELECTED('Type'[Type]),
        'Type'[Type] ="Total ILR" )
                   )
        ) = 1
var adjustType = SELECTEDVALUE('include cat'[Type])
return 
IF(
    AND(logicTest,TypeTest),
        SWITCH(adjustType,
            "Including CATs",
            CALCULATE(
                'Total ILR'[Total ILR],
                final_data[yoa_attrition] = "2020"),
            "Excluding CATs",
            CALCULATE(
                'Total ILR'[ILR (excl. cat)],
                final_data[yoa_attrition] = "2020"),
            "Excluding Specifics",
            CALCULATE(
                'Total ILR'[Total ILR],
                final_data[yoa_attrition] = "2020")),
        BLANK()
    )

**Comment by otykier** [comment]
Sorry for the late reply.

Take a look at some of the [sample C# scripts](https://docs.tabulareditor.com/Useful-script-snippets.html) that can be executed within Tabular Editor.

In your case, the general idea would be to store the "template" DAX code for the measure in a variable using some placeholder syntax for the values you want to replace when creating the actual measures. Then perform the loop over some array that specifies what to replace.

```csharp
// Your template DAX expression. Double-quotes have to be escaped by specifying them twice: " --> ""
// Here, I use the special placeholder %YEAR% to denote 2010, 2011, etc. but you can add more placeholders and call them whatever you like.
// Also, you should probably format your DAX code using daxformatter.com before adding it here, to make it more readable.
var templateDax = @"
VAR logicTest =
  COUNTROWS(DISTINCT(FILTER(ALLSELECTED(YEARS[YEAR]), YEARS[YEAR] = %YEAR% ))) = 1
...
";
var years = new[] { "2010", "2011", "2012", /* ...etc... */ "2020" };
foreach(var year in years)
{
    var measureName = "measure_" + year;
    Selected.Table.AddMeasure(
        measureName,
        templateDax.Replace("%YEAR%", year)
    );
}
```

Running this script while a table is selected will create one measure for each of the years specified in the array. Of course you will need to modify this example to your specific needs, using the full DAX code of your measures, adding additional logic, nested loops, etc. based on your requirements.
