### ISSUE TITLE
Convert .BIM to .PBIT

### ISSUE THREAD

**Issue by jasonhendrix** [otykier/TabularEditor#763]
With the recent release of Power BI Premium Per User, we have several instances where we want to migrate away from Azure Analysis Services and use Power BI Premium Per User instead to save costs and increase model size limits.

Using Tabular Editor, I have been able to deploy a .BIM file to the Power BI Service using the XMLA endpoint for Power BI Premium Per User, however that is not exactly what my organization requires.  Because we develop Power BI Template Apps, this method will not work for us.  Currently, you are not able to choose "Include in app" for the Dataset in a Template App Workspace if it was created in this way.

![image](https://user-images.githubusercontent.com/1486174/108095039-0ee6e780-7045-11eb-808f-3143bed20154.png)

Instead, I need a way to create a PBIX or PBIT file from a .BIM file so I can treat it as normal Power BI Dataset that would be compatible with the Template App process.

In Tabular Editor, I can open a PBIT file, save it as a folder, open the folder in Tabular Editor, then go to File... Save As and I'm given the option to save as either a .PBIT or .BIM file, however the reverse is not true.

In Tabular Editor, if I open a BIM file, save it as a folder, open the folder in Tabular Editor, then go to File... Save As I am only given the option to save as a .BIM file, not a .PBIT file.

I do understand that there would be some things that may not be directly transferable, but I have hundreds of objects to convert for many models so enabling a sort of degraded conversion process rather than no conversion process would be helpful if it is possible to do.

Is there a better way to convert a .BIM file to a .PBIT/.PBIX file?

**Comment by otykier** [comment]
Microsoft does not provide a way for third party tools to convert bim files to pbit or to create pbit files from scratch. Until they do, I’m afraid there’s nothing we can do in Tabular Editor to make this work.

**Comment by marcosqlbi** [comment]
The PBIT file has other elements other than the data model, and these parts are not modified by Tabular Editor. Hence, the limitation you see.
However, you can do the following:

1. Create a Power BI file with the connection required to retrieve the data of your model
2. Save the PBIT file
3. Open the PBIT file with an instance of Tabular Editor (A)
4. Open the BIM file with another instance of Tabular Editor (B)
5. Copy the tables in (B) 
6. Paste the tables in (A)
7. Fix the connections in (A) - this could be the real challenge and I'm not sure about the steps involved here, it really depends on your connections.
8. Save the PBIT file in A

This procedure usually works very well for a Date calculated table, which doesn't have the issue of binding with the data source.

**Comment by jasonhendrix** [comment]
@marcosqlbi @otykier When I click Copy on a table in Tabular Editor (B - the .BIM file), then go to Tabular Editor (A - the .PBIT file) and go to Edit, the Paste option is disabled.

![image](https://user-images.githubusercontent.com/1486174/108098521-1a3c1200-7049-11eb-9dd7-8e187fdc0d49.png)

**Comment by marcosqlbi** [comment]
Right-click the Tables folder.

**Comment by jasonhendrix** [comment]
@marcosqlbi When I right click the Tables folder, I do not see a Paste option:

![image](https://user-images.githubusercontent.com/1486174/108102101-b700ae80-704d-11eb-9cc8-e6e4903a1718.png)

Also, if the Tables folder is selected, the Edit... Paste option is still disabled.

**Comment by marcosqlbi** [comment]
Sorry - click on Tables (like you did) and then go to Edit - you will Paste enabled.

**Comment by jasonhendrix** [comment]
@marcosqlbi Paste is still disabled for me when Tables is highlighted:

![image](https://user-images.githubusercontent.com/1486174/108102864-bfa5b480-704e-11eb-88fc-644cdbb5c4db.png)

**Comment by marcosqlbi** [comment]
It is enabled when you have in the clipboard a table copied from another model. 
Repeat exactly the sequence 1..8 making sure you use this technique at step 6. to paste the table.
I know, it's not intuitive at the beginning, it's an area of improvement for Daniel! :)

**Comment by otykier** [comment]
@jasonhendrix to unlock full editing of a pbit file you have to enable unsupported Power BI features under File > Preferences. Otherwise, Tabular Editor blocks modeling operations that are not supported by Power BI Desktop, which could potentially break your pbit file (so always make sure to keep a backup).

**Comment by jasonhendrix** [comment]
Thanks for the help.  Enabling unsupported Power BI features did allow the copy/paste operation to work.

**Comment by rnevenvf** [comment]
> The PBIT file has other elements other than the data model, and these parts are not modified by Tabular Editor. Hence, the limitation you see. However, you can do the following:
> 
> 1. Create a Power BI file with the connection required to retrieve the data of your model
> 2. Save the PBIT file
> 3. Open the PBIT file with an instance of Tabular Editor (A)
> 4. Open the BIM file with another instance of Tabular Editor (B)
> 5. Copy the tables in (B)
> 6. Paste the tables in (A)
> 7. Fix the connections in (A) - this could be the real challenge and I'm not sure about the steps involved here, it really depends on your connections.
> 8. Save the PBIT file in A
> 
> This procedure usually works very well for a Date calculated table, which doesn't have the issue of binding with the data source.

Is this still the easiest way to convert my AAS cubes with ODBC connections to Snowflake to Power BI Premium Datasets using the native Snowflake connector instead? Quite the hassle! Or does anyone have an easier solution? :)

Thanks in advance!

**Comment by Robbevl90** [comment]
Hi @otykier , 
I am currently generating custom BIM files, based upon my database schema. 
I have several customers I would like to offer this BIM file in the form of a Power BI dataset. 

I have tried many things, but I cannot seem to find an automated or Semi-automated way to generate a PBIT/PBIX file from the generated BIM file. 

Any idea how this could be possible? Is this something that could become available in Tabular editor? ( Saving to BPIT file for example).  I hope to have any solution here, as it is basically our last resort! :) 

Robbe

**Comment by otykier** [comment]
@Robbevl90 there is no supported way to achieve this, as the pbit/pbix file formats are proprietary/not documented.

That said, take a look at [pbi-tools](https://pbi.tools).
