### ISSUE TITLE
Status message is misspelled.

### ISSUE THREAD

**Issue by KenLoewen** [otykier/TabularEditor#764]
**Describe the bug**
The status message at the lower-left corner of the Tabular Editor window indicates "Connected succesfully." 

**To Reproduce**
Open Tabular Editor and connect to a model.

**Expected behavior**
The correct spelling is "Connected successfully."

**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor version: 2.14.1
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: unknown

**Additional context**

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!
