### ISSUE TITLE
Advanced scripting not deploying changes

### ISSUE THREAD

**Issue by qureshq** [otykier/TabularEditor#766]
**What are you trying to achieve?**
I open an instance of tabular editor (2.14.1) through power bi desktop and copy script from generate fix script for a BP issue , when I paste script in advance scripting and run, bottom right says **Script executed successfully , 0 model changes,** which I assume mean nothing had been changed in the model. This is my first attempt at running scripts via Advance Scripting I am not sure why its not working, i save changes to connected database nothing on power bi model.

I tried running other scripts such as put a single measure in a new folder and it runs perfectly and records it as 1 model change on bottom right .

**What have you tried so far?**
I have updated my TE to latest version  any other changes I do e.g. creating measures, editing them hide/unhide column are being deployed back to power BI Desktop however I cant run script from generate fix script or rather it would run but says 0 model changes,

**Comment by otykier** [comment]
Most likely the script is trying to modify a property that is not among the [supported write operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations) for external tools. You can change this behavior in Tabular Editor by going into File > Preferences and putting a check mark in the "Allow unsupported Power BI features" checkbox. This unlocks all modelling operations which could potentially break your PBIX file, so make sure to keep a backup of the file before applying changes through Tabular Editor.

**Comment by qureshq** [comment]
Thanks that worked appreciate your help on this.

**Comment by ARCAfreeze** [comment]
Hello

For some reason, I could not get to work with the BPA in Tabular Editor

I get the script below, but I would not see the Advanced Scripting window to paste  it. Please advise

System.Net.WebClient w = new System.Net.WebClient(); string path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData);string url = "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json";string downloadLoc = path+@"\TabularEditor\BPARules.json";
w.DownloadFile(url, downloadLoc);

**Comment by otykier** [comment]
The tab is called **C# Script** (it was called Advanced Scripting in earlier versions of Tabular Editor):

<img width="638" alt="image" src="https://github.com/user-attachments/assets/401b3e52-b760-412e-95b7-53d5dab8b32a">

However, you don't need that script to load the BPA rules. It's easier to just go to the **Tools** > **Manage BPA Rules**, then click on the **Add...** button, choose **Include Rule File from URL**, and paste in the URL to the BPARules.json:

```
https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json
```

![image](https://github.com/user-attachments/assets/4d1adec5-3a10-4aeb-89ba-b0b66837ca32)

![image](https://github.com/user-attachments/assets/9db51892-8463-4270-9207-43c679c66a2c)

![image](https://github.com/user-attachments/assets/a85c7b6e-596d-4326-85a1-ed48f8ce9d35)

**Comment by ARCAfreeze** [comment]
@otykier, thank you a great for the note. That did the trick! God bless
