### ISSUE TITLE
Check of BPA Rules only on Request

### ISSUE THREAD

**Issue by SalCag** [otykier/TabularEditor#768]
I work with a large model with over 200 tables.
I loaded the BPA Rules from Microsoft into TE.
Now the rules are checked after each modification. This takes at least 10 minutes.
As soon as I set all the rules to Ignore, I can work normally.

I would like to have a button to start the check of the BPA rules.
Preferably I would love to have the ability to get a list of the available rules and start only the check of the selected rules.
Another way is to have a setting in which I can enable or disable the automatic check of the rules.

At the moment I need to open the BPA Settings, click on Show Ignored and Enable the rules.

I hope that you can add some of these features in TE as the functionality of the BPA rules is great.

Regards
Salvatore

**Comment by otykier** [comment]
You can disable background scan for Best Practice issues under File > Preferences.

**Comment by SalCag** [comment]
Thank you.
That's what I searched for.
Now I can check the rules on demand. Perfect.
