### ISSUE TITLE
Available in MDX property not visible?

### ISSUE THREAD

**Issue by FrankPreusker** [otykier/TabularEditor#769]
I wanted to follow the Best Practice Analyzer recommendation to set the IsAvailableInMdx property to false on some of my hidden columns. According to the blog post from Chris Web (https://blog.crossjoin.co.uk/2018/07/02/isavailableinmdx-ssas-tabular/) this property should be seen under the "Other" property category. However, in my TE version (2.14.1) I don't see that category at all.
Has it moved somewhere else?
![image](https://user-images.githubusercontent.com/74618614/108345844-05918280-71df-11eb-846b-673f845f4059.png)

**Comment by FrankPreusker** [comment]
Found it myself in the meantime. While reading some of the other issues/questions raised here, I've noted that there is a setting for Experimental features. Once enabled, it makes the "Available in MDX" property visible as well.
Why is this feature only available as experimental? Is it, or is it not officially supported?

**Comment by otykier** [comment]
Changing any column property is at the moment not supported by Power BI Desktop.

[Supported write operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).
