### ISSUE TITLE
Customize format strings

### ISSUE THREAD

**Issue by liveandletbri** [otykier/TabularEditor#77]
I see that in the latest release, there's a dropdown menu for format strings. I love that, as I can't write format strings from memory because it's just a bunch of gibberish to me. However, I noticed that you now can't write a custom format string. I'm trying to make a format string for currency with no decimal places showing. The format string for this, as generated by SSDT, is: \$#,0;(\$#,0);\$#,0. The Format String property is only allowing me to pick from the dropdown menu, and the only currency option there seems to have two decimal places. Can you add in the ability to write your own format string? Or maybe change the formatting properties to be more similar to SSDT, which use plain English in the UI but generate the string behind the scenes?

**Comment by otykier** [comment]
This is a bug in the current build, which will be fixed shortly :-)

In the mean time, could you try the following:

1. Go to the Advanced Scripting tab.
2. Write: `Selected.Measures.FormatString = "\$#,0;(\$#,0);\$#,0";`
3. Select some measures in the Explorer Tree and hit F5 to run the script.
4. Check if the FormatString property of the selected measures has been changed accordingly.

By the way, you can save that script as a Custom Action, which will add it to the Right-click menu after you restart Tabular Editor, so you have an easy way of setting the desired format string going forward.

**Comment by otykier** [comment]
[Release 2.5](https://github.com/otykier/TabularEditor/releases/latest) features a new String Format builder, which is more similar to the way Format Strings can be customized in Power BI and Visual Studio. The String Builder adapts to the data type of the column or measure in question. Give it a spin, and let me know what you think.
