### ISSUE TITLE
Description of "Data Type" property contains invalid HTML code

### ISSUE THREAD

**Issue by FrankPreusker** [otykier/TabularEditor#770]
TE 2.14.1
The description for the Data Type property is displaying:

For a DataColumn, specifies the data type. See **<see href="... .aspx** for a list of supported data types.

Issue visible at the bottom of the screenshot:
![image](https://user-images.githubusercontent.com/74618614/108411908-72ca0580-7229-11eb-8c97-e3c7138455be.png)

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!
