### ISSUE TITLE
Accessing TOM CalculationGroups/Items

### ISSUE THREAD

**Issue by jeffersonrand** [otykier/TabularEditor#772]
Thanks to @otykier  for this wonderful tool!

I use the Advanced Scripting feature to automate addition and configuration of measures. I cannot find documentation on doing the same for Calculation Items or Groups. I heard Master Otykier say in his Scripting video that anything that can be done in the interface can be scripted, but I've tried for two days and can't figure out how.  Other TOM class access seems fine.

**_Does anybody know if this is supported?? If so, what am i missing?_**  

Hopefully there exists a code snippet that can demonstrate how to add/delete a CalculationGroup and another to do same for Items.

Kind regards,
Jeff

**Comment by otykier** [comment]
```csharp
var cg = Model.AddCalculationGroup("New Calc Group");
cg.AddCalculationItem("Current", "SELECTEDMEASURE()");
cg.AddCalculationItem("MTD", "TOTALMTD(SELECTEDMEASURE(), 'Date'[Date]");
cg.AddCalculationItem("YTD", "TOTALYTD(SELECTEDMEASURE(), 'Date'[Date]");
```

**Comment by jeffersonrand** [comment]
Many thanks!

**Comment by jeffersonrand** [comment]
**_But how do I add a calculation item to an existing cg?_**  I can't seem to get the method for the references i've tried:
Model.Tables["myCG"] or Model.CalculationGroups["myCG") or ModelCalculationGroups.First(cg =>...,) and many other attempts.  It seems the AddCalculationItem method is not a part of any class i can find...

Sorry for the trouble - i subscribed to GitHub and am learning C# in order to become a more proficient modeller using your tool...should i have reopened this issue or opened a new one (or stopped bothering you :)

**Comment by otykier** [comment]
No worries, and I apologise that it's not better documented.

The [`CalculationGroupTable`](https://github.com/otykier/TabularEditor/blob/9eb6a0d9ff28d8db743d5d6ab9860f267b62c0ed/TOMWrapper/TOMWrapper/CalculationGroupTable.cs#L18) class, which is a subclass of `Table`, is the one that holds the [`AddCalculationItem()`](https://github.com/otykier/TabularEditor/blob/9eb6a0d9ff28d8db743d5d6ab9860f267b62c0ed/TOMWrapper/TOMWrapper/CalculationGroupTable.cs#L27) method.

When you call `AddCalculationGroup` it returns a reference to the newly add `CalculationGroupTable` (which is the one I stored in the `cg` variable in the script above). If you want to reference an already existing calculation group, do this:

```csharp
var cg = Model.Tables["myCG"] as CalculationGroupTable;   // Explicit cast necessary
cg.AddCalculationItem(...);
```

**Comment by jeffersonrand** [comment]
No apologies necessary, we are all grateful for your work.  
Thanks for the support - it must be quite some work to respond to all the posts.
Thank you also for the thoughtful links to the code lines.  I guess I need to use explicit casting for all TOM Wrapper classes?
My C# skills are still primitive but improving!

**Comment by bendfeldt** [comment]
Pretty cool, but how would you e.g. add a Description to the item or control the ordinal? As far as i can see the function "AddCalculationItem" only have two arguments, name and expression.

**Comment by otykier** [comment]
The `AddCalculationItem` (like all the other `Add***` methods, returns a reference to the newly created object. So to add a description or change the ordinal do this:

```csharp
var cg = Model.Tables["myCG"] as CalculationGroupTable;
var ci = cg.AddCalculationItem(...);
ci.Description = "Hello";
ci.Ordinal = 3;
```

**Comment by bendfeldt** [comment]
That is pretty cool.. thanks
