### ISSUE TITLE
Addition of applied step in Power Query unhides column that was hidden in Tabular Editor

### ISSUE THREAD

**Issue by gabrielsmelchor** [otykier/TabularEditor#774]
**Describe the bug**
Hiding a column in Tabular Editor (as opposed to modeling view in Power BI) and then adding an applied step to that query in Power Query within Power BI Desktop unhides the column. 

**To Reproduce**
1. Set a column's isHidden property to 'True' within Tabular Editor
2. Save changes back to model
3. Open Power Query window (Transform Data)
4. Insert applied step into query that contains the column from step 1
5. Close and apply query window
6. Column in step 1 has has its isHidden property reverted

**Expected behavior**
The column that was hidden in Tabular Editor will remain hidden even after adding new applied steps in the query editor.

**Observed behavior**
The column becomes unhidden after adding a new applied step.

**Application specifics**
Working with Power BI Desktop version 2.88.1682.0 (64 Bit) and Tabular Editor 2.14.7712.29256.

**Additional context**
This problem does not occur when a column is hidden in Power BI Desktop modeling view as opposed to Tabular Editor.

**Comment by otykier** [comment]
Currently, setting column properties in a .pbix file through Tabular Editor, is [not among the supported write operations of External Tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations). Closing this, but feel free to reopen if the issue persists once Microsoft announces full modelling support for external tools.

**Comment by gabrielsmelchor** [comment]
Thanks for bringing that to my attention @otykier !
