### ISSUE TITLE
Average of items - calculation groups

### ISSUE THREAD

**Issue by PierreBergerons** [otykier/TabularEditor#775]
Hello, I have a question about calculation groups in tabular editor with Power Bi Desktop. I created a list of items and a measure with SELECTEDMEASURE() and everything works fine. Now, I want the average of each item. I tried with a new measure in the calculation group like DIVIDE(SELECTEDMEASURE(),[Year number]), doesn't work. And I tried to create a new calculation group with only this measure, and change the precedences. No result. 

The final objective is when I select the measure in power bi, it shows the value in a chart and it shows the average in a table beside.

Thanks a lot
Pierre

**Comment by otykier** [comment]
Hi Pierre.
This question is not related to Tabular Editor but rather to the workings of Calculation Groups, which is a feature of Analysis Services (the data modelling engine running underneath Power BI Desktop). Before you create Calculation Groups, make sure you fully understand how they work. I recommend the videos and articles on the topic by sqlbi.com: https://www.sqlbi.com/calculation-groups/
