### ISSUE TITLE
Wrong description on "Group By Columns" property

### ISSUE THREAD

**Issue by paulsanders400** [otykier/TabularEditor#776]
I am trying to set the TOM metadata allowing me to Sort a column by another, and Group a column by another. 
- For Sort By, I need to enable "Unsupported experimental features"  Why is this - Sort By is a supported property, exposed in Power BI Desktop?
- For Group By,  I assume this is editing the TOM property https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.relatedcolumndetails?view=analysisservices-dotnet
If so, you might want to expand the definition, rather than just say this forms the composite key. Anyone familiar with AMO/SSAS might think this is like the Key of an attribute. I don't think it is - it is a directive to clients that if the user asks to group on the column, they should also include these GroupBy columns as well. So I don't think it effects the behavior of DAX, or even Excel - though the PBI visuals do respect the property

**Comment by otykier** [comment]
- External Tools for Power BI Desktop currently [only supports a limited subset of modelling operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools). Setting column properties (such as the Sort By property), is not among the supported write operations.
- Great insight on the Group By property - I wasn't aware of that! Will make sure to update the description. Thanks!

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!
