### ISSUE TITLE
Misspelling on the 'Return Error Values As Null' property

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#781]
**Describe the bug**
Misspelling on the 'Return Error Values As Null' property.

**To Reproduce**
1. Click on 'Model'
2. Within the properties, go to 'Data Access Options' -> Return Error Values As Nulll
3. 'Nulll' should be 'Null'

![image](https://user-images.githubusercontent.com/29556918/109410544-23f83a80-79a4-11eb-907d-1c7ac04ddbd0.png)

**Application specifics**
 - Tabular Editor version: 2.14.1

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!

**Comment by m-kovalsky** [comment]
Thanks!
