### ISSUE TITLE
'DAX Identifier' capitalization

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#782]
**Describe the bug**
'Identifier' should be capitalized in the 'DAX Identifier' property for tables, columns, measures etc.

**To Reproduce**
1. Click on a Table/Column/Measure
2. Go to the 'DAX identifier' property

![image](https://user-images.githubusercontent.com/29556918/109410573-66217c00-79a4-11eb-8149-b5022e607305.png)

**Application specifics**
 - Tabular Editor version: 2.14.1

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!

**Comment by m-kovalsky** [comment]
Thanks!
