### ISSUE TITLE
Syncing issues when renaming a measure from Tabular Editor

### ISSUE THREAD

**Issue by kevinzous** [otykier/TabularEditor#784]
**Describe the bug**
Syncing issues in a PBI Desktop report when renaming a measure from Tabular Editor. 

**To Reproduce**
1. Go to 'Tabular Editor
2. Connect Tabular Editor to a PBI report locally
3. Click on a measure and Click F2 to rename it (Name_1 to Name_2)
4. Save (Ctrl + s)
5. Go on the PBI report : the measure has been renamed 
6. Rename it again this time on PBI (double click on the measure)  (Name_2 to Name_3)
7. the name displayed on the field pane does not change is Name_3
**8. the name displayed on the DAX formula pane is Name_2**

**Expected behavior**
8. the name displayed on the DAX formula pane should be Name_3

**Observed behavior**
8. the name displayed on the DAX formula pane is Name_2

**Application specifics**
 - Tabular Editor version:  2.11.6
 - Semantic Engine used:. Power BI Desktop Feb 2021
 
![PBIDesktop_geXt92i4dw](https://user-images.githubusercontent.com/24707976/109663015-ef36df80-7b6b-11eb-99a1-f35a771ec40f.png)

**Comment by otykier** [comment]
@kevinzous make sure you're using the newest version of Tabular Editor ([2.14.2](https://github.com/otykier/TabularEditor/releases/latest) at the time of writing this), then let me know if the issue persists.

**Comment by kevinzous** [comment]
@otykier  am not able to reproduce this bug with the new version. Closing this ticket. 
Thanks and sorry for your time.
