### ISSUE TITLE
Enable Intellisense for object/class variables

### ISSUE THREAD

**Issue by jeffersonrand** [otykier/TabularEditor#785]
**Is your feature request related to a problem? Please describe.**
Not problem-related.  Not a need to have, but a very nice to have.

**Describe the solution you'd like**
For example, when declaring "var cg = Model.Tables["_Table_"] as CalculationGroupTable;", then using that variable in subsequent code lines, the Intellisense for the relevant object type should be available when entering "cg."

**Describe alternatives you've considered**
Today, one can simply enter the object in its own line (i.e. no variable declaration) and view the available properties/methods, then carefully duplicate the property/method name in the desired code line, but this is inefficient and can be error-prone.

**Comment by otykier** [comment]
Changing this to bug, since it works for an expression such as:

```csharp
var t = Model.Tables["Sales"];
```

Typing `t.` on the next line actually shows the dropdown for a Table object. The problem in your example is that it doesn't work if there's an explicit cast.

**Comment by jeffersonrand** [comment]
Ah, indeed I can confirm same in my instance 2.14.2.  Sorry I didn't notice that.

**Comment by otykier** [comment]
IntelliSense with explicit casts now works in [2.15.0](https://github.com/otykier/TabularEditor/releases/tag/2.15.0).
