### ISSUE TITLE
RoleMembers collection in advanced scripting

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#786]
**Describe the bug**
I usually use the 'Members' collection, but for some reason tried the 'RoleMembers' collection. When the following code is executed, it returns a new output for every letter of every role member. As an example, if I have a role member of "hello@world.com" in the Reader role, it would output 'H'...'e'...'l'...'l'...'o'... etc. It's pretty strange. Think the solution is to just use the Members collection but figured I would raise this as an issue.

foreach (var m in Model.Roles["Reader"].RoleMembers.ToList())
{
    m.Output();
}

**Application specifics**
 - Tabular Editor version: 2.14.2

**Comment by otykier** [comment]
RoleMembers is a string (which is just the combined list of members separated by newline characters). When you call .ToList() on a string, you get a list of every single character in the string. So in other words, it's a feature, not a bug ;-)

**Comment by m-kovalsky** [comment]
I see ahaha, thanks :)
