### ISSUE TITLE
Unable connect to pbix file with PowerBI datasets

### ISSUE THREAD

**Issue by janeyc5712** [otykier/TabularEditor#787]
My pbix file is live connecting to PowerBI datasets. When I tried to connect with Tabular Editor, it showed " This instance does not contain any databases, or the user does not have access. " Can you suggest in this situation, can i still use 
Tabular Editor? 
Many thanks!
JC

**Comment by otykier** [comment]
No. A report in live connect mode does not hold a tabular model so it cannot be edited using Tabular Editor.
