### ISSUE TITLE
Compare Multiple Collections in Best Practice Analyzer

### ISSUE THREAD

**Issue by Gezahegne** [otykier/TabularEditor#79]
I am wondering if it is possible to compare two collections in Best Practice Analyzer. For example, I want to list out all the Data Columns (one collection) which are not contained in Relationships (another collection).

**Comment by otykier** [comment]
The Dynamic LINQ query language used to define Best Practice Rules unfortunately does not support advanced collection methods such as Join, Union, etc. However, there are ways to do what you want. For example, you can create a rule on Data Columns with the following code:

`Model.Relationships.None(FromColumn = outerIt) and Model.Relationships.None(ToColumn = outerIt)‘

This expression will list all Data Columns who are not used as the FromColumn or ToColumn property on any relationship. The `outerIt‘ keyword in the expression refers to the data column on which the rule is being validated, and the `None(...)‘ method returns true only if none of the objects in the preceding collection satisfies the given criteria.

Another way to create the same rule, would be to use one of the convenient collections provided by the TOMWrapper library. For example, every Column and Table object has a UsedInRelationships property, which lists the relationships in which the given object participates. In a Best Practice rule on Data Columns, you could then simply use the expression:

`UsedInRelationships.None()‘

...to identify Data Columns that are not used in any relationships.

Hope this helps, but please let me know if you have any further questions.

**Comment by otykier** [comment]
Hi @Gezahegne - I made a mistake in my comment above, using the LINQ method `None()`, which is not available in the current build of Tabular Editor. Instead, we can use the `Any()` method, which is simply the negation of `None()`, meaning we have to add a `not` in front to get the same result.

Let me know if this works as you expect.

**Comment by Gezahegne** [comment]
Hi Daniel,

Thanks a lot for the solution! It worked for me with the Any() method.

Thanks,
Gezahegne
