### ISSUE TITLE
Editing a Pbix File (Dataset) in a premium workspace directly with Tabular Editor

### ISSUE THREAD

**Issue by cfkperso** [otykier/TabularEditor#792]
Hi, 
I have a pbix located in Power BI Premium workspace. As we have XMLA endpoint activated, I use TabularEditor to connect and edit my pbix file with the url powerbi://api.powerbi.com/v1.0/myorg/XXXX.
![edit_tb](https://user-images.githubusercontent.com/71018635/110113189-07e50680-7db3-11eb-88c8-4cc3dc2876b5.png)
The issue i'm facing is that after editing the dataset with Tabular Editor (adding a new measure for example), after publishing my changes with tabulard editor, it's not possible to download the pbix file of the dataset anymore. I have the error message below.  
![pbi_export](https://user-images.githubusercontent.com/71018635/110113915-1b44a180-7db4-11eb-9670-8acd2af08d3b.png)

Moreover, If i have a pbix file connected to the dataset edited by Tb, i'm also facing the same issue. Not able to download it anymore. Same error message as above.

is it something you aware off ? is it a normal behavior from your point of view ?

Thanks for you feedback about this point

Cedric

**Comment by otykier** [comment]
This is documented here: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#power-bi-desktop-authored-datasets

**Comment by vikashbikkina** [comment]
Hi,
I made changes to the published (Premium) power bi dataset using the XMLA Endpoint.
Is there a way, the same changes  could be applied to my pbix file, specially when I can no longer download it ?? This ensures, both the local and the published versions are in sync.

Vikash

**Comment by otykier** [comment]
Hi Vikash. Maybe [ALM Toolkit](https://www.sqlbi.com/tools/alm-toolkit/) can be used in this case?

**Comment by otykier** [comment]
Closing this issue as it is not related to Tabular Editor.
