### ISSUE TITLE
Unable to set annotations on measures

### ISSUE THREAD

**Issue by jeffersonrand** [otykier/TabularEditor#795]
**Describe the bug**
Using mymeasure.SetAnnotation("aaa","1") does not result in the creation of an annotation.

**To Reproduce**
In the following script, everything works without the WHERE clause, but with the WHERE clause it can't find any measures with the AUTOGEN annnotation = "1"
This script for the most part lifted from useful snippets.

var MacroTable = Model.Tables["_Macro measures"]; //table holding the measures to be created
**_foreach(var m in MacroTable.Measures.Where(m => m.GetAnnotation("AUTOGEN") == "1").ToList())  //This result in zero model changes, since the annotations are not being created in the line later below_**
{
     m.Delete();
}

string query = "EVALUATE 'Fred metadata'";  //table of measure names, format strings, default aggregations, folder names

using (var reader = Model.Database.ExecuteReader(query))
{
    while(reader.Read())
    {
        string mySeriesID = reader.GetValue(0).ToString();
        string myMeasureName = reader.GetValue(19).ToString();
        string myAggregation = reader.GetValue(18).ToString();
        string myCategory = reader.GetValue(20).ToString();
        string myFormatString = reader.GetValue(21).ToString();
        string myExpression = 
            "VAR DS = FILTER('Fred datasets',[SeriesID] = \"" + 
            mySeriesID + "\")VAR myResult = " + 
            myAggregation + "(DS,[Value]) RETURN myResult";
        var myNewMeasure = MacroTable.AddMeasure(myMeasureName, myExpression, myCategory);
            myNewMeasure.FormatDax();
            myNewMeasure.FormatString = myFormatString;
            **_myNewMeasure.SetAnnotation("AUTOGEN","1");   //this seems not to run_**
    }
}

**Expected behavior**
Annotations against all measures in the table with Name = "AUTOGEN" and Value = "1".

**Observed behavior**
It seems that no annotations are being created, so the WHERE filter is returning an empty list.

**Application specifics**
 - Tabular Editor version: 2.14.2]
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: not sure, but should be quite recent

**Additional context**
Hopefully I'm over looking something simple, like a syntax error, in which case, sorry for troubling you...

**Comment by jeffersonrand** [comment]
Tried simpler test and still zero model changes.  If Annotations are successfully created, will I be able to see it in the properties pane of the measure or will I have to query?  Here is the simpler script:

_var myTable = Model.Tables["_MacroMeasures"];
foreach(var m in myTable.Measures.ToList())
{
    m.SetAnnotation("AUTOGEN","1");
}_

**Comment by otykier** [comment]
You have to enable unsupported Power BI features under File > Preferences, as [annotations are not among the currently supported write operations of the External Tools integration of Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations) (although adding new annotations are unlikely to break anything, as long as you don't modify the annotations used by Power BI).

**Comment by jeffersonrand** [comment]
Great, thanks.  I must have missed that somewhere.  Everything worked as advertised.
Clearly this is not a bug but I can't figure out how to change the label, so I'll just close the issue.
