### ISSUE TITLE
Delete KPI if exists

### ISSUE THREAD

**Issue by rvgfox** [otykier/TabularEditor#796]
Hi I'm creating a KPI in an Advanced Script with:

foreach(var currentM in Selected.Measures)
{
// Delete if exists

  var kpi = currentM.AddKPI();
.....
}

But I cannot delete it prevously if exists.

How can I make that?

Thanks in advance...

**Comment by otykier** [comment]
```csharp
currentM.KPI = null;
```

**Comment by rvgfox** [comment]
Perfect

Thaks Daniel ;-)
