### ISSUE TITLE
The FormatDax() doesn't works in a custom Action

### ISSUE THREAD

**Issue by rvgfox** [otykier/TabularEditor#797]
I've a script with:

......
kpi.FormatDax();
.....

And It works fine. But if it assign to a custom action it doesn't works....

**Comment by otykier** [comment]
When you say it doesn't work, do you see an error message or does nothing happen?

It could be an issue with the global `CallDaxFormatter();` method not being called automatically, when the script is used as a custom action. This method is normally called automatically at the end of every script, to "flush" the queue of items that needs to be formatted. Could you try to add a call to that method at the end of your script, to see if this solves the issue, when the script is saved as a custom action? Thanks!

**Comment by rvgfox** [comment]
Thanks Daniel

Using CallDaxFormatter() it works.

Thanks

**Comment by otykier** [comment]
Leaving this open as having to call `CallDaxFormatter()` manually is still a bug.

**Comment by otykier** [comment]
Fixed in [2.15.0](https://github.com/otykier/TabularEditor/releases/tag/2.15.0).
