### ISSUE TITLE
Using the master model pattern with PowerBI

### ISSUE THREAD

**Issue by Oliver-Sheaky** [otykier/TabularEditor#798]
I would love to use the [Master Model Pattern](https://docs.tabulareditor.com/Master-model-pattern.html) with powerBI.

I have managed to get it working almost as described, but using the -B parameter to build it to a .bim rather than deploy (see [here](https://docs.tabulareditor.com/Command-line-Options.html)). I don't have a local SSAS server to deploy to (as far as I am aware).

I used MasterModel.cs to split Master.bim into Product.bim, using the following command line call `start /wait /d "c:\Program Files (x86)\Tabular Editor" TabularEditor.exe "C:\Users\Oliver Sheaky\Documents\Master.bim" -S "C:\Users\Oliver Sheaky\Documents\MasterModel.cs" -B "C:\Users\Oliver Sheaky\Documents\Product.bim" -O -R` (see attached files at the bottom).

However, there appears to be no way to [convert a .bim to a .pbit](https://github.com/otykier/TabularEditor/issues/763).

I have tried creating an empty .pbit and copying the relationships and tables across from product.bim in tabular editor. However Power Bi refuses to open it because the partition is of type M. 

![image](https://user-images.githubusercontent.com/36473581/110651070-00f33500-81b3-11eb-8974-f4be958d1d5f.png)

Am I missing something here? type M seems to be imported and is the type we usually use.

Is there a neat trick I can use to get .bim working in PowerBI desktop?

Can I leverage the deployment somehow to save the result as a .pbit or .pbix?

any other ideas?

**Comment by Oliver-Sheaky** [comment]
I got the copy from product.bim to a .pbit in tabular editor working in powerBI.

The trick is to load a table from the same source as the others, and then save as a nearly empty .pbit.

Then delete that one table in tabluar editor, then copy across the tables, then relationships from product.bim. Save the .pbit, and then open with powerBI desktop.

I am going to leave this open for now, incase anyone has any suggestions for a better workflow, please let me know :)

**Comment by otykier** [comment]
Adding tables, partitions, etc. to a Power BI file [is not among the currently supported write operations for the External Tools integration](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).
