### ISSUE TITLE
DAX Formatter calls don't specify app/version

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#8]
I've seen that the code in DaxFormatter.cs don't have the property CallerApp and CallerVersion assigned - however, the code to do that is commented. It would be nice to be able to get statistics from calls made using Tabular Editor, but the current calls don't allow to get detailed info.
Is there a reason for which you commented out the code? Is there something I can do to help?

Thanks!

**Comment by otykier** [comment]
Hi Marco,
I was receiving error 500 with the API call, when including the CallerApp and CallerVersion. However, I just tried again this morning, and now everything seems to work (perhaps I was calling an older version of the API earlier?). Anyway, I've uncommented the code and released a new version ([2.0.6176](https://github.com/otykier/TabularEditor/releases/tag/2.0.6176)) where this is fixed.

Could you please try and let me know if you correctly receive the statistics with this release?

Thank you.

**Comment by marcosqlbi** [comment]
I confirm it works well!
When I have time, I will publish a public dashboard with the statistics from DAX Formatter (in Power BI of course!).
Thanks!

Marco
