### ISSUE TITLE
Documentation for 3rd party plugin architecture

### ISSUE THREAD

**Issue by dybzon** [otykier/TabularEditor#80]
Is there any documentation available for the new 3rd party plugin architecture? If so, where is it located?

**Comment by otykier** [comment]
I'm working on a tutorial, but in the mean time, please check out the sample plugin project: https://github.com/otykier/TabularEditor/tree/master/PluginTest.

Basically, the idea is that you create a new .NET Class Library (C# or VB), and add a reference to the TOMWrapper.dll file, which is located in your %AppData%\..\Local\TabularEditor folder. I recommend cloning the entire Tabular Editor solution from GitHub, and adding your plug-in as a class library to this solution. Set the Build Output folder of your class library to the bin\Debug folder of TabularEditor. This will make it easier to debug your plug-in.

In your class library, you must provide a class that implements the `ITabularEditorPlugin` interface. This is a very simple interface, with just two methods:

```cs
public interface ITabularEditorPlugin
{
    void Init(TabularModelHandler handler);
    void RegisterActions(Action<string, Action> registerCallback);
}
`

The first method, `Init(TabularModelHandler handler)` is called when a model is loaded in the Tabular Editor UI. You can obtain a reference to the currently loaded model through the `Model` property on `handler`, [as illustrated here](https://github.com/otykier/TabularEditor/blob/master/PluginTest/Class1.cs#L20).

The second method, `RegisterActions(Action<string, Action> registerCallback)` is called once when Tabular Editor is starting up. The delegate `registerCallback` should be called inside this method for every action you want your plug-in to support, [as shown here](https://github.com/otykier/TabularEditor/blob/master/PluginTest/Class1.cs#L23). For now, actions registered this way will show up in the Tools-menu of the Tabular Editor UI, but in the future, there will be more ways to customise how a plug-in interacts with the UI.

![image](https://user-images.githubusercontent.com/8976200/29059021-dc11bc0a-7c13-11e7-8ef4-8a6377df40c9.png)

Hope this is enough to get you started, but don't hesitate to ask if you have any further questions.

**Comment by dybzon** [comment]
Cool - looks good. I'll try set some time aside to look into this soon :-)
