### ISSUE TITLE
Refresh mode within Script Refresh

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#800]
**Describe the bug**
After using the 'Script Refresh' feature within Tabular Editor (to generate the TMSL for processing a table), it saves the refresh mode for the next time you script a refresh. However, the refresh mode within the right click properties doesn't actually change - it always says 'automatic'.

**To Reproduce**
1. Right click on a table 
2. Click on 'Script'
3. Click on 'Refresh'
4. Change the Refresh Mode to 'DataOnly'
5. Click 'To clipboard'
6. Paste the output in a text editor.
7. Right click on a table.
8. Click on 'Script'
9. Click on 'Refresh'
10. **Notice how Refresh mode still says 'automatic'**
11. Click 'To Clipboard'
12. Notice how the processing type matches step 1 (DataOnly) and does not match step 10.

**Expected behavior**
The 'Refresh Mode' within the 'clicking sequence' should update so that it matches the last refresh mode selected.

**Application specifics**
 - Tabular Editor version: 2.14.2

**Comment by otykier** [comment]
Fixed in [2.15.0](https://github.com/otykier/TabularEditor/releases/tag/2.15.0).

**Comment by m-kovalsky** [comment]
Confirmed, thanks!
