### ISSUE TITLE
Renamed Measure fails to sync with visuals

### ISSUE THREAD

**Issue by AJ3I** [otykier/TabularEditor#806]
**Describe the bug**
I was bulking editing measures in Tabular editor, Renamed quite a few measures in tabular editor and saved.  New names were reflected in Power BI but All the related visuals failed expecting for the previous measure name.

**To Reproduce**
Steps to reproduce the behaviour:
1. Rename a measure in tabular editor
2. Save and the changes are seen in Power BI tables i.e new name is applied at table level
3. all the visuals failed expecting previous measure name

**Expected behaviour**
New Names must have applied to the visuals as like we rename  a measure in Power BI and should not break the visuals

**Observed behaviour**
All the visuals are broken and shows error expecting for previous measure name.

**Application specifics**
 - Tabular Editor version: 2.11.7499
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: latest power bi model

**Comment by otykier** [comment]
This is not possible. Please see #455 and #672 for more details.
