### ISSUE TITLE
Exporting column and measure names and display folders with a script

### ISSUE THREAD

**Issue by rvgfox** [otykier/TabularEditor#809]
If I've in a table several display folders to group columns and measures, and change the query in Power Bi to for example add a new column, all the folders are deleted.

I'm trying to export my current folder structure with:

```
// Declarar variables
string Carpeta="d:\\TEMP\\";
string Archivo="EXPORT_PBI_DisplayFolder.tsv";

// Exportar los nombres y Display Folder de los objetos seleccionados
var tsv = ExportProperties(Selected, "Name,DisPlayFolder");
SaveFile(Carpeta + Archivo, tsv);
```
But the DisplayFolder property doesn't export for columns.

Can you help me?

**Comment by otykier** [comment]
Please note that setting column properties (such as the column DisplayFolder) is not among the [supported write operations for Power BI External Tools](http://aka.ms/externaltools#supported-write-operations). It should work fine for Measures though.

As to your 2nd question, please note that the property names are case sensitive, so please change `DisPlayFolder` to `DisplayFolder`.

**Comment by rvgfox** [comment]
Thanks.

This works fine, but I'm trying this:

```
// Declarar variables
string Carpeta="d:\\TEMP\\";
string Archivo="EXPORT_PBI_DisplayFolder.tsv";

// Exportar los nombres y Display Folder de los objetos seleccionados
var tsv = ExportProperties(Selected.Table.Columns, "Name,DisplayFolder");
var tsv2 = ExportProperties(Selected.Table.Measures, "Name,DisplayFolder");
SaveFile(Carpeta + Archivo, tsv+tsv2);
```

But I need the file without the column names for tsv2

How can I fix it?

Thanks in advance

Ramon

**Comment by otykier** [comment]
// Declarar variables
string Carpeta="d:\\TEMP\\";
string Archivo="EXPORT_PBI_DisplayFolder.tsv";

var objects = new List<ITabularNamedObject>();
objects.AddRange(Selected.Table.Columns);
objects.AddRange(Selected.Table.Measures);

// Exportar los nombres y Display Folder de los objetos seleccionados
var tsv = ExportProperties(objects, "Name,DisplayFolder");
SaveFile(Carpeta + Archivo, tsv);

**Comment by rvgfox** [comment]
Solved with:

```
// Declarar variables
string Carpeta="d:\\TEMP\\";
string Archivo="EXPORT_PBI_DisplayFolder.tsv";

// Lista de columnas y Medidas de la tabla seleccionada:
var objects = Selected.Table.Measures.Where(m => !m.IsHidden && !m.Table.IsHidden).Cast<ITabularNamedObject>()
      .Concat(Selected.Table.Columns.Where(c => !c.IsHidden && !c.Table.IsHidden));

// Exportar los nombres y Display Folder de los objetos seleccionados
var tsv = ExportProperties(objects, "Name,DisplayFolder");
SaveFile(Carpeta + Archivo, tsv);
```

**Comment by suketududhat** [comment]
@otykier, is there a way to do this with multiple tables selected? Currently, the script can only handle a single selected table.
![image](https://github.com/user-attachments/assets/d2cad0d3-e62a-4c56-a16f-bd786ab0824d)

Changing to below only exports the table properties and "Tables" does not seem to have the same add-ons as "Table".
objects.AddRange(Selected.Tables);

**Comment by otykier** [comment]
@suketududhat 

```csharp
objects.AddRange(Tables.SelectMany(t => t.Measures));
objects.AddRange(Tables.SelectMany(t => t.Columns));
```

**Comment by suketududhat** [comment]
Works like a charm! Also added some additional QOL to open explorer window with file selected and even open when the script runs! Thank you for your help as this will help us automate some of our upcoming work!

```
// Select tables in TOM Explorer and click green execute button to run script:
// Keyboard shortcut to comment: Ctrl + /

var objects = new List<ITabularNamedObject>();

// Comment objects lines that are not needed for bulk export
foreach(var table in Selected.Tables)
{
    objects.AddRange(table.Measures);
    objects.AddRange(table.DataColumns);
    objects.AddRange(table.CalculatedColumns);
    //objects.AddRange(table.Partitions);
}

var tsv = ExportProperties(
    objects 
    // Default properties exported below; uncomment to add or remove as needed, e.g. "Name, Expression" or "Name, DisplayFolder, IsHidden"
    //,"Name, Description, SourceColumn, Expression, FormatString, DataType"
);

// Edit file location if you want to save it in a different folder as it will save by default to "C:\Program Files\Tabular Editor 3"
string file = @"C:\Program Files\Tabular Editor 3\Export_Metadata.tsv";
SaveFile(file, tsv);

// Will open the .tsv file
//System.Diagnostics.Process.Start("explorer.exe", file);

// Will open the folder with .tsv file selected
//string open_folder = "/select, \"" + file +"\"";
//System.Diagnostics.Process.Start("explorer.exe", open_folder); 
```
