### ISSUE TITLE
Show dependencies to include Sort By Column

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#810]
If I have a column that is referenced in the 'Sort By Column' field of another column, it would be nice if this reference was also displayed in the 'Show Dependencies' window. From memory this feature is currently driven by TOM so maybe not trivial to include.

![image](https://user-images.githubusercontent.com/2540043/112219648-03549500-8c71-11eb-90de-cb23213a60b7.png)

**Comment by otykier** [comment]
Great suggestion! The dependency view in Tabular Editor is inferred from the DAX code on objects, so it should be a minor change to add a dependency when a column is sorted by another.

**Comment by otykier** [comment]
Fixed in [2.15.2](https://github.com/otykier/TabularEditor/releases/latest).
