### ISSUE TITLE
Bookmarks to model - predefined filter set

### ISSUE THREAD

**Issue by benito2313** [otykier/TabularEditor#813]
**What are you trying to achieve?**
In powerbi you can add bookmarks, is this also something that can be added to the model ?
What i'm trying to do is to give certain people a predefined set of filters. Now when somebody is trying to create a report they dont know what to filter to get a specific result and there are always some specific filters that are needed to create a report.

Bookmark 1
![image](https://user-images.githubusercontent.com/3872421/112472706-bc989500-8d6d-11eb-98df-54384758180b.png)
Bookmark 2
![image](https://user-images.githubusercontent.com/3872421/112472746-c8845700-8d6d-11eb-950d-fc62b891c43a.png)

Kind regards,
Ben

**Comment by otykier** [comment]
Nope. Bookmarks are not defined within the model metadata. They live entirely within the visual layer of the .pbix file, and as such, Tabular Editor has no way to access or modify these. Sorry!
