### ISSUE TITLE
import Json Code

### ISSUE THREAD

**Issue by logik360** [otykier/TabularEditor#814]
hi ,
 I can understand that TEditor is mainly a UI tool but having the ability to import JSON code is essential.
Imaging a scenario (i have it offen) where I can copy paste measures (with small changes ) and put them in folders.

I can create something like that even in excel and then import the Json in TEditor.
I used this technik many times in SSAS in Visual Studio and you can create a large model in no time (and change it as well)
best
A.B

**Comment by otykier** [comment]
Closed as duplicate of #69
