### ISSUE TITLE
Initial Catalog property is required to connect to Power BI Pro Workspace

### ISSUE THREAD

**Issue by gabrielsmelchor** [otykier/TabularEditor#815]
**What are you trying to achieve?**
@otykier 

We are utilizing Azure DevOps to deploy model updates to a dataset hosted in a Power BI Premium workspace. We are running hundreds of deployments at once, and most of them succeed. However, I'm getting intermittent issues regarding the lack of an initial catalog property in the connection string. From my understanding, this initial catalog corresponds to the dataset name within the workspace. We have this defined as an environment variable within the release task (it is a static name, consistent across all workspaces).

**What have you tried so far?**
Here is the error output:

>  Tabular Editor 2.15.1 (build 2.15.7748.27962) -------------------------------- Loading model... Loaded script: _EnquireBIDevOps-CI\scripts\c#\SetConnectionStringFromEnvPQ.cs Executing script 0... Deploying... ##vso[task.logissue type=error;]Deployment failed! Initial catalog property is required in order to connect to Power BI Pro workspaces. ##vso[task.complete result=Failed;]Done.

Here is the argument list as provided for this failed deployment.

`_\drop\Model.bim -S "_EnquireBIDevOps-CI\scripts\c#\SetConnectionStringFromEnvPQ.cs" -D "Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/<workspace>;User ID=<username>;Password=<password>" "<dataset_name>" -O -C -P -V -E -W`

The fact that this is happening for some, but not all, workspaces in the release is confusing me.

**Comment by otykier** [comment]
Tabular Editor uses the TOM/AMO client libs to connect to any flavor of Analysis Services. As such, I have a suspicion that this is a bug either with the client libs or the Power BI service. I'm also thinking that there could be some permission issues? Does the credentials specified in the connection string belong to a user with admin access to each workspace?

**Comment by TarekSalha** [comment]
I can confirm this behaviour. The problem is specific to pro workspaces, because there the XMLA endpoint, that allows for connections on server level is not available. It works with premium workspaces though.
