### ISSUE TITLE
Image-URL available in Data Category

### ISSUE THREAD

**Issue by PowerBI-QUEST** [otykier/TabularEditor#816]
Hi, 

Currently there seems to be no option to change the **Data Category** to **Image-URL**.  I would like to display product images in a table (in a Power BI report). Can this option be made available or is there any other solution?

![](https://www.sqlshack.com/wp-content/uploads/2020/04/change-data-category.png)

**Comment by otykier** [comment]
Currently, changing column properties such as the Data Category, is not among the supported write operations for external tools: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#data-modeling-operations

as such, Tabular Editor does not allow changing this property by default. However, you can unlock the full set of modeling operations under File > Preferences > Allow unsupported Power BI features. Just make sure to keep a backup of your pbix file, as you could potentially make changes which would break the file.

**Comment by PowerBI-QUEST** [comment]
Hi Otykier,

Thanks for your quick response!
