### ISSUE TITLE
Unable to Edit PBIX Model with new measures or calculation groups

### ISSUE THREAD

**Issue by fkmalik** [otykier/TabularEditor#817]
**What are you trying to achieve?**
Have a model in PBIX file, published to power BI premium per user workspace. I have been using Tabular editor extensively for new measures, Best practice analyzer, calculation groups etc. 
It was all working well until recently I started to get error messages and unable to add/copy any measure or calculation group or calculation item in the model. error message image attached, wording is like as follows

"The collection of Measure Objects of the 'XXX Table Name' contains duplicated data lineage tags 'd9c.......' 

**What have you tried so far?**
I have tried to to see what type of changes i can still make through tabular editor. So I can hide the columns, change ordinal of calculation groups, add a new calculation group but cant add calculation item into.

Appreciate help and guidance. Tabular editor is an amazing tool. Thanks for that :)

Appr
<img width="366" alt="Tabular Editor Screen Shot" src="https://user-images.githubusercontent.com/68479887/112861490-44fc9a00-90ce-11eb-8a7a-514eb8512e89.PNG">

**Comment by otykier** [comment]
Which version of Tabular Editor are you using? This issue should have been fixed since [v. 2.15.0](https://github.com/otykier/TabularEditor/releases/latest).

**Comment by fkmalik** [comment]
Upgraded Tabular Editor to V. 2.15.0. and boom, problem solved :). Thanks.
