### ISSUE TITLE
Editing legacy data source / connection properties

### ISSUE THREAD

**Issue by sashk8** [otykier/TabularEditor#818]
Hi,

I've noticed that the connection properties window for legacy data sources (opened using the three dots "..." next to the connection string) is no longer available since version 2.15.1. 

Is this by design so? It was very convenient to set the connection details in the properties window. You must edit the connection string directly now. 

[three dots](https://imgur.com/I4uvuhi)
[connection properties](https://imgur.com/hVIdICV)

**Comment by otykier** [comment]
That's a bug. Thanks for reporting!

**Comment by otykier** [comment]
This has been fixed in [2.15.3](https://github.com/otykier/TabularEditor/releases/tag/2.15.3). Turns out the issue also affected other properties, which also had a three-dot button previously (Display Folder, Sort By Column and Group By Columns).
