### ISSUE TITLE
Dynamically Select Which Calculation Items Appear in calculation Groups

### ISSUE THREAD

**Issue by fkmalik** [otykier/TabularEditor#820]
Hi, 
I am using combination Calculation Groups and Matrix visual to produce a pivoted financial statements table. Like usual P&L statements with Period on top and individual items being shown as rows . Each calculation item in the calculation group is used as column in matrix to show comparative periods like PY, Target, CY etc & their comparison columns like CY vs PY, CY vs Target etc. This is fine till here. However, we need to change the columns on every reporting like may be this months scenario requires to show PY, Target 1, Target 2, CY & consequently different comparison columns as well. Requirement is dynamic and changes frequent. 

**What have you tried so far?**
So far for every new column to appear or be re-arranged, I am making a new calculation group by cloning an existing one with addition, deletion of a calculation Item. However, this workaround is resulting into a an increasing numbers of calculation groups which will soon become too many to handle. Is there another workaround where we can selective show or hide calculation selection based upon a slicer or filter.

Appreciate your advise.

**Comment by otykier** [comment]
This question doesn't seem to be related to the functionality of Tabular Editor. It may be better posted on the Power BI forums.

That being said, adding additional calculation groups definitely seems like the wrong approach. Are you aware that you can filter the calculation items shown by using the visual-level filter on the matrix? As such, you can decide exactly which combinations of calculation items should appear for every matrix in your report. You can even add one or more Calculated Columns to your calculation group, then put some logic into each calc column that would provide a value (Yes/No), to make it easier to filter a predefined set of calculation items in the visual. Hope this helps!

**Comment by fkmalik** [comment]
Thank you. I will follow the advise.
