### ISSUE TITLE
Blank line before VAR and RETURN statements

### ISSUE THREAD

**Issue by bernatagulloesbrina** [otykier/TabularEditor#822]
This is strictly to make DAX code easier to read by humans. 
I think the default formatting is too condensed (for me of course!)
It would be nice to be able to toggle a setting to get a more ample formatting which includes blank lines before each VAR and RETURN statements. I always add them manually, but if I format again they are all gone.

**Comment by otykier** [comment]
Tabular Editor uses the daxformatter.com web service for formatting DAX code. Please direct this suggestion there: https://www.daxformatter.com/ (use the discussion at the bottom of the page or report it as a bug).

**Comment by bernatagulloesbrina** [comment]
yes, I just realized that, sorry!
