### ISSUE TITLE
AlternateOf BaseColumn/BaseTable for count summarizations

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#825]
**Describe the bug**
When you set the Summarization on an AlternateOf property to Count, it changes the AlternateOf property to BaseTable - even if it was previously set as BaseColumn with a BaseColumn value.

**To Reproduce**
1. Add 'AlternateOf' to a column.
2. Set the Base Column value.
3. Set the 'Summarization' on the AlternateOf property to 'Count'
4. The 'BaseColumn' value is removed and the property reverts to 'BaseTable'.

**Expected behavior**
Currently it's not possible to have a BaseColumn value and have the Summarization set to Count. This should be possible.

**Application specifics**
 - Tabular Editor version: 2.15.3

**Comment by otykier** [comment]
Could you elaborate on the need to set BaseColumn simultaneously with Summarization = Count? My understanding was that this summarization only works for the entire table - not for individual columns. Do we have any documentation that says otherwise?

**Comment by otykier** [comment]
Fixed in [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0).

**Comment by m-kovalsky** [comment]
Thanks Daniel!
