### ISSUE TITLE
Partitions added or removed on deploy to Power BI Premium regardless of deploy option selected for incremental refresh tables

### ISSUE THREAD

**Issue by jpresley15** [otykier/TabularEditor#826]
**Describe the bug**
Regardless if the "Deploy Table Partitions" option box is checked or not, partitions are added or removed when deploying a model to Power BI Premium if the partitions are part of a table which has incremental refresh applied. Partitions in tables that do not have incremental refresh applied are unaffacted.

**To Reproduce**
Use a model with a table which has incremental refresh applied and contains multiple Power BI service generated partitions.
1. In Tabular Editor, copy and paste one of the existing partitions or remove a partition from an incrementally refreshed table
2. In SSMS, review the existing partitions in the selected table.
3. Deploy the model from Tabular Editor ensuring the option "Deploy Table Partitions" is not selected.
4. In SSMS, review the partitions in the selected table and partitions will be added or removed depending on the action in step 1.

**Expected behavior**
On deploy with the option "Deploy Table Partitions" not selected, the model should have deployed with no change to partitions.

**Observed behavior**
Partitions in incremental refresh tables will reflect any changes made in Tabluar Editor regardless of the "Deploy Table Partitions" option selected.

**Application specifics**
 - Tabular Editor version: 2.15.3
 - Power BI Premium
 - Model Compatibility Level: 1520

**Additional context**
I did export the build and confirmed the Model.deploymentoptions contains the flag <PartitionDeployment>RetainPartitions</PartitionDeployment>

I attached some captioned screen captures showing that partitions had been removed regardless of the deployment options selected as well as the Model.deploymentoptions file for related deployment.

[Model.deploymentoptions.txt](https://github.com/otykier/TabularEditor/files/6312547/Model.deploymentoptions.txt)
[SSMS Partition Review.pdf](https://github.com/otykier/TabularEditor/files/6312548/SSMS.Partition.Review.pdf)

**Comment by otykier** [comment]
Fixed in [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0). Thanks for reporting!
