### ISSUE TITLE
Unable to Connect with Power BI Service when workspace name with special characters

### ISSUE THREAD

**Issue by gpaulocorrea** [otykier/TabularEditor#827]
Until version 2.14.2, I connected in power bi using a encoded url for a workspace name with special characters.

For example:
From: powerbi://api.powerbi.com/v1.0/myorg/#XXXX - XXXX - XXXX / XXXX - XXX
To: powerbi://api.powerbi.com/v1.0/myorg/%23XXXX+-+XXXX+-+XXXX+%2F+XXXX+-+XXX

Version 2.15.3 does not allow the connection to the encoded url.
When trying to connect with the default Power BI url (No encoded), an error is displayed:

- Initial catalog property is required in order to connect to power BI Pro worksapces.
![image](https://user-images.githubusercontent.com/614356/114779554-a66a6d00-9d4c-11eb-90e5-952d04ae4b0c.png)

**Comment by otykier** [comment]
[2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0) has some improvements to how Power BI connection strings are treated. Could you please try again with this version to see if the issue is fixed?

**Comment by gpaulocorrea** [comment]
After encountering a similar problem in Power BI Desktop, we found that the problem is directly related to the # character in the workspace name. Apparently, any text after the # character is disregarded in the url.
It is a behavior that has changed in the library mentioned above, but we are able to get around by encoding only the # character instead of encoding the entire name of the workspace in the url.
As this problem is not internal to TabularEditor, I will close the bug.
