### ISSUE TITLE
Service principal not able to connect 

### ISSUE THREAD

**Issue by MelaniaC87** [otykier/TabularEditor#828]
Hi, 

I went through all steps to enable a SPN to connect to TabularEditor via cmd line, but I am still getting a Bad Request error. 
The connection we need is not AS but a dataset that has been created via SQL import. 

![image](https://user-images.githubusercontent.com/77968510/115009887-1132ba00-9ead-11eb-9543-4b96ced67fd3.png)

I am definitely able to connect with my account and password, but not with SPN. Is there any missing right/setting we should add?

**Comment by otykier** [comment]
Which version of Tabular Editor are you using? With latest version [2.15.3](https://github.com/otykier/TabularEditor/releases/tag/2.15.3) I'm not able to reproduce the issue.

Also, check the following:

- [Service Principal access to your Power BI tenant is enabled by your Power BI admin](https://docs.microsoft.com/en-us/power-bi/guidance/admin-tenant-settings#developer-settings)
- [XMLA read/write endpoint enabled on your Premium capacity](https://powerbi.microsoft.com/en-us/blog/announcing-the-general-availability-of-read-write-xmla-endpoints-in-power-bi-premium/)
- [The Service Principal must be added as an administrator of the workspace](https://powerbi.microsoft.com/en-us/blog/announcing-support-for-service-principals-using-the-xmla-endpoint-in-power-bi-premium/)

**Comment by MelaniaC87** [comment]
Hi,

Yes all these checks have been done. Working now with 2.15.3 with same issue.

The SPN I am working with is even able to access power BI via PowerShell Power BI management module and retrieve information on everything belonging to the workspace I am working with.
AS I said, I am completely able to access, change and save things on the datasets by using the following cmd string with my account:
start /wait TabularEditor.exe "Data Source=powerbi://api.powerbi.com/v1.0/myorg/WorkspaceName;User ***@***.******@***.***;Password=XXXXX>" WorkspaceID

It is exactly something we are missing from SPN rights perspective but I really cannot figure out what it is. Any suggestion?

**Comment by otykier** [comment]
There was a new version released yesterday, [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0). Would you mind trying that version as well?

![image](https://user-images.githubusercontent.com/8976200/115712884-a2a2a000-a375-11eb-8cdc-dc155bc7f488.png)

**Comment by MelaniaC87** [comment]
Confirmed,

Also in this case SPN not able to access.

**Comment by otykier** [comment]
Could you please provide some additional details:

- Are you able to connect with DAX Studio or SQL Server Management Studio using the same service principal?
- What is the full Command-Line syntax you're using (please blank out any sensitive strings)?
- What error message are you getting?

**Comment by MelaniaC87** [comment]
Hi,

  *   Are you able to connect with DAX Studio or SQL Server Management Studio using the same service principal?
To be sincere, never tried to connect. Can you provide a string I can adapt to test? Thank you

  *   What is the full Command-Line syntax you're using (please blank out any sensitive strings)?
After a bit of research on this, I am now using the string you can find in here
https://github.com/DaveRuijter/BestPracticeAnalyzerAutomation/blob/v1.0-beta.1/BPAA.ps1
line 232
exec { cmd /c """$TabularEditorPortableExePath"" ""Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/$workspaceName;User ID=app:$PowerBIServicePrincipalClientId@$PowerBIServicePrincipalTenantId;Password=$($credential.getNetworkCredential().password)"" ""$datasetName"" -A ""$TabularEditorBPARulesPath"" -TRX ""$DatasetTRXOutputPath""" } @(0, 1) $True #| Out-Null } }
Variables defined as you see through the code

This one is not working, unless I give my organizational credentials: ***@***.***  instead of app:$PowerBIServicePrincipalClientId@$PowerBIServicePrincipalTenantId and my org PWD. The latter works.

Here’s the error for SPN:
***@***.***D73A92.1AC4CBA0]
It seems that despite of all rights given, something is still missing there!
Could it be because the SPN doesn’t have the access to underlying data?

Thank you in advance
Best
Melania

**Comment by otykier** [comment]
To connect with DAX Studio or SQL Server Management Studio, provide the connection details as follows:

![image](https://user-images.githubusercontent.com/8976200/116066182-0f74ad80-a688-11eb-9871-7b7bec3b7de9.png)

where the username is app:<spn application id>@<tenant id> and password is the spn app secret.

If this works, then Tabular Editor should be able to as well. If it doesn't work, then you are probably missing some setting or permission on the Power BI service. Refer back to the links I sent earlier. Specifically, ensure that the SPN has Admin permission on the workspace, in order for it to access the data.

**Comment by MelaniaC87** [comment]
no access even from SQL then. 

- XMLA read-write enabled for the node
- SPN is admin for the Workspace
- the only thing that is not under my knowledge is within tenant settings: somebody ensured that Service Principal access to your Power BI tenant is enabled by your Power BI admin is granted, for that SPN being added to security group. 

What I cannot understand, apart from the points above that should be all that is needed for TE connection, is: the same SPN is connecting via Powershell PowerBI MGMT module: correctly finding the dataset, dropping it and re-publishing. The only thing that seems not to work is connection, either with TE or SQL and I guess the problem will be still there with DAX studio.

**Comment by otykier** [comment]
The PowerShell PowerBI management module does not use the XMLA endpoint for connectivity, so if the configuration on the Power BI service has not been made correctly, it is possible that the SPN can connect through PowerShell, but not through XMLA (which is what Tabular Editor, SSMS and DAX Studio uses).

So if you're not able to connect through SSMS, then this is not a Tabular Editor issue, but an issue with your Power BI service configuration. Consider opening a support ticket with Microsoft to get this resolved. Feel free to reopen the issue if it turns out that other tools (SSMS, DAX Studio) are able to connect through XMLA, but Tabular Editor isn't.

**Comment by MelaniaC87** [comment]
FYI,

This was missing
***@***.***D73C2C.3B2F4460]
Somehow, XMLA endpoint enabling is linked to Analyze in Excel. To complete XMLA endpoint configuration for SPN, also that one should be checked.




From: Carfagna, Melania (KT)
Sent: Monday, April 26, 2021 11:49 AM
To: otykier/TabularEditor ***@***.***>; otykier/TabularEditor ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [otykier/TabularEditor] Service principal not able to connect (#828)

Hi,

  *   Are you able to connect with DAX Studio or SQL Server Management Studio using the same service principal?
To be sincere, never tried to connect. Can you provide a string I can adapt to test? Thank you

  *   What is the full Command-Line syntax you're using (please blank out any sensitive strings)?
After a bit of research on this, I am now using the string you can find in here
https://github.com/DaveRuijter/BestPracticeAnalyzerAutomation/blob/v1.0-beta.1/BPAA.ps1
line 232
exec { cmd /c """$TabularEditorPortableExePath"" ""Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/$workspaceName;User ID=app:$PowerBIServicePrincipalClientId@$PowerBIServicePrincipalTenantId;Password=$($credential.getNetworkCredential().password)"" ""$datasetName"" -A ""$TabularEditorBPARulesPath"" -TRX ""$DatasetTRXOutputPath""" } @(0, 1) $True #| Out-Null } }
Variables defined as you see through the code

This one is not working, unless I give my organizational credentials: ***@***.******@***.***>  instead of app:$PowerBIServicePrincipalClientId@$PowerBIServicePrincipalTenantId and my org PWD. The latter works.

Here’s the error for SPN:
***@***.***D73C2C.3B2F4460]
It seems that despite of all rights given, something is still missing there!
Could it be because the SPN doesn’t have the access to underlying data?

Thank you in advance
Best
Melania
