### ISSUE TITLE
Duplicate user role exception

### ISSUE THREAD

**Issue by datacatsuk** [otykier/TabularEditor#829]
**Describe the bug**
When adding an Azure Ad user to a role, if the user already exists in the list, it throws an exception and we loose all the other entries because it doesn't give us a chance to save the changes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Roles
2. Click on a role, members, Add Azure AD Member
3. Add Member Name which already exists in the role
4. Click Okay
5. See error

**Expected behaviour**
This exception needs to handled properly with a custom message that prevents adding an existing entry and preventing the crash.

**Observed behaviour**
![image](https://user-images.githubusercontent.com/20473345/115015475-9cab4b80-9eab-11eb-8814-875ac7aed20f.png)

**Application specifics**
 - Tabular Editor version: [e.g. 2.15.3]
 - Semantic Engine used: [Azure Analysis Services]
 - Model Compatibility Level: [1500]

**Comment by otykier** [comment]
Fixed in [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0).
