### ISSUE TITLE
Duplicating measure not working on Power BI model

### ISSUE THREAD

**Issue by nielsvdc** [otykier/TabularEditor#830]
When trying to duplicate a measure when connected to a Power BI model, a pop-up warning is shown "An object with lineage-tag \<guid\> already exists in the collection.
![te-error](https://user-images.githubusercontent.com/10850600/115038236-9f1f9c80-9ecf-11eb-982c-8e7bd292af8c.jpg)

**Comment by otykier** [comment]
Duplicate of #803. Please make sure you're using the [latest version of Tabular Editor](https://github.com/otykier/TabularEditor/releases/tag/2.15.3).

**Comment by nielsvdc** [comment]
Please see attached video for version 2.13.1

https://user-images.githubusercontent.com/10850600/115106553-c9239e00-9f65-11eb-852f-8d8a8a854262.mp4

**Comment by otykier** [comment]
I'm not able to reproduce this issue in [2.15.3](https://github.com/otykier/TabularEditor/releases/tag/2.15.3). Did you try that version?

**Comment by nielsvdc** [comment]
I checked and it's working again with version 2.15.3.
