### ISSUE TITLE
Error when removing an Annotation or Extended Property

### ISSUE THREAD

**Issue by caabrust** [otykier/TabularEditor#832]
Description:  When attempting to remove an annotation from a table or measure using the Annotation Collection Editor (or ExtendedProperty Collection Editor for extended properties), I receive an error stating "Object reference not set to an instance of an object" when I click the OK button at the bottom of the collection editor dialog box.  There seems to be no workaround.

To reproduce:  
1.  Start with a brand new model
2.  Create a new table
3.  Add an annotation to the table (Name = "test", Value = "123") by clicking on the "..." button to open the Annotation Collection Editor dialog box and clicking the Add button.  Exit the collection editor by clicking the OK button.
4.  Go back into the Annotation Collection Editor dialog box and Remove the annotation you just created.  Click OK.  The error message "Object reference not set to an instance of an object" appears.  I
5. There is even a more severe bug when attempting to remove an annotation _immediately_ after creating it and before clicking the OK button.

Expected behavior:
I would expect that, upon removing the annotation and clicking OK, that there would be no error and the Annotation count would be reduced by the number of annotations I removed.  Upon re-opening the collection dialog box, I would see that the annotation I removed would not be there.

Observed behavior:
Receive the error message.  Annotations cannot be removed.  The only way to exit the collection dialog box is to cancel out.  Note that I can ADD new annotations from this screen and successfully click Okay, but I can not remove items.

Application specifics:
 - Tabular Editor version: 2.15.3
 - Semantic Engine used: SSAS 2019,
 - Model Compatibility Level: 1500

**Comment by otykier** [comment]
Fixed in [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0).

**Comment by caabrust** [comment]
Wow, that was FAST!  Thank you, sir.  I absolutely love this product.

On Apr 21, 2021, at 2:36 PM, Daniel Otykier ***@***.******@***.***>> wrote:



Fixed in 2.16.0<https://github.com/otykier/TabularEditor/releases/tag/2.16.0>.
