### ISSUE TITLE
Unable to obtain authentication token using Service Principal

### ISSUE THREAD

**Issue by JEBlank18** [otykier/TabularEditor#835]
**Describe the bug**
On version 2.16.0, our Azure DevOps Pipeline is failing due to the error message "Unable to obtain authentication token using the credentials provided". The same exact code and Service Principal worked on version 2.15.3. It occurs when running via the command line and passing in these arguments (with sensitive values replaced) `-LOGIN app:***@*** ***` .  I also tried it locally on my machine and get the same result.

**To Reproduce**
1. Deploy to an existing model/workspace using the command line
2. Authenticate using the -LOGIN command and a Service Principal
2. Deploy to a Power BI Premium v2 workspace

**Expected behavior**
Authentication is successful and the deployment/command works as usual

**Observed behavior**
```
Tabular Editor 2.16.0 (build 2.16.7781.40242)
--------------------------------
Loading model...
Deploying...
##[error]Deployment failed! Unable to obtain authentication token using the credentials provided.
```

**Application specifics**
 - Tabular Editor version: 2.16.0
 - Semantic Engine used: Power BI Premium v2
 - Model Compatibility Level: 1520 / 1540 (fails on 2 different models)

**Additional context**
I know the AppId and secret are coming through correctly because other actions are performed succesfully. Changing nothing but the version of Tabular Editor that is downloaded has a different result. I'd be happy to provide any other necessary info.

**Comment by otykier** [comment]
Possible duplicate of #828

**Comment by JEBlank18** [comment]
> Possible duplicate of #828

I'm fairly certain it is not. I read through that one beforehand and from what I can tell, I'm seeing a different error message.

I did go ahead and try to connect via SSMS using the SPN and I was able to connect. When I try to connect to the same Workspace in Tabular Editor, I get the same error as I do in the command prompt: "unable to obtain authentication token".

**Comment by otykier** [comment]
Seems like a regression in 2.16.0. Will take a closer look. In the mean time, could you try specifying the "server" argument in the CLI as follows, instead of passing credentials via -LOGIN:

```
Data Source=powerbi://api.powerbi.com/v1.0/myorg/<workspace name>;User ID=app:<app id>@<tenant id>;Password=<app secret>
```

**Comment by JEBlank18** [comment]
Using the server argument as suggested did allow it to work as expected both in the Command Line and in the GUI.

**Comment by otykier** [comment]
[2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1) should fix the issue, allowing you to use the same syntax as earlier versions of Tabular Editor. Could you please confirm and revert? Thanks!

**Comment by JEBlank18** [comment]
@otykier I can confirm it is working now. Thank you!
