### ISSUE TITLE
database name field is not automatically pre-selected

### ISSUE THREAD

**Issue by jperod** [otykier/TabularEditor#837]
**Describe the bug**
When you deploy changes to a destination server, the Database Name field is no longer automatically pre-selected. It used to in previous versions.

**To Reproduce**
1. Hit Deploy
2. Select Destination Server & Authenticate
3. Select Database menu. It does not pre-select automatically the database.

**Expected behavior**
In previous versions, the menu auto selected, small detail but it was very nice.

**Observed behavior**
 pre-select automatically the database name.

**Application specifics**
 - Tabular Editor version: [e.g. 2.16.0]
 - Semantic Engine used: [Azure Analysis Services]
 - Using Compatibility Levels: [1400, 1500]

**Comment by dmgdotnet** [comment]
I also noticed related to this one, if I open Tabular Editor and go through the deploy process, I can click the database name in the window the first time to populate the database name but subsequent deployments to other servers this doesn't work and the click action has no affect. If I close and re-open tabular editor I can click and populate the name for deployment again.

![image](https://user-images.githubusercontent.com/2540043/116477694-4fbe7080-a8c0-11eb-98b4-ef6ffbc03a6b.png)

**Comment by otykier** [comment]
Fixed in [2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1).
