### ISSUE TITLE
Allow changing show hidden by default

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#84]
Right now every start TE assumes that we don't want to see hidden however as devs I always want to see hidden. 

So please either change the default to be show hidden by default or provide a pref to allow us to set this. Personally I would vote for the former for simplicity.

**Comment by otykier** [comment]
Yes, this is one of those "nice-to-have" things that I've been postponing to make room for other more important features. I bet there are lots of other customisations that would be equally useful, such as showing/hiding display folders or "other object types" by default. Will make sure this is handled in a future release.
