### ISSUE TITLE
Text box for SourceExpression in Table settings Refresh Policy

### ISSUE THREAD

**Issue by kamart0** [otykier/TabularEditor#840]
The text box to write SourceExpression in Table settings under Refresh Policy would be really handy to have since the Power Query expressions contain usually multiple rows. Currently copy-pasting Power Query expressions without modifications is impossible since the SourceExpression doesn't allow line breaks.

This kind of text box is already available for Description in Table settings under Basic settings so the implementation should be quite straightforward.

**Comment by otykier** [comment]
Fixed in [2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1).
