### ISSUE TITLE
Progress information during SSAS deployment

### ISSUE THREAD

**Issue by SalCag** [otykier/TabularEditor#845]
**Is your feature request related to a problem? Please describe.**
While deploying a model to SSAS only Deploying... is shown in the Window.

**Describe the solution you'd like**
More detailed progress information in the Deploying window would be very helpful.
The information could show the deploying steps on which TE is working on.

It would be very nice if all the steps could be shown and which step is already done, on which TE is working and which step is still due.

**Comment by otykier** [comment]
There’s only one step really, which is the execution of the CreateOrAlter TMSL script that Tabular Editor generates. It’s executed within a transaction on the server, so I don’t even think it’s possible to retrieve additional details through Analysis Services XEvents/traces.

**Comment by SalCag** [comment]
Hello

That's sad.
I hoped that there are multiple steps during deployment. It would have helped to see what happens if there were multiple steps.
Thank you for the information.
Regards
Salvatore
