### ISSUE TITLE
BPA - Extend FixExpression capability to leverage model objects

### ISSUE THREAD

**Issue by alwortman** [otykier/TabularEditor#846]
I'd like to be able to specify FixExpression rules that reference the object on which they are being run.

For example for the rule PARTITION_NAMES_SHOULD_MATCH_TABLE_NAMES.

Setting the FixExpression to:
`"FixExpression": "Name=MyRenamedPartition"` generates a C# script of:
```
// Fix for rule: Partition names should match table names
(Model.Tables["Pandora Access"].Partitions["Partition"] as Partition).Name="MyRenamedPartition"
```

I would like to be able to specify something like:
`"FixExpression": "Name=outerIt.Name"`
or
`"FixExpression": "Name=Table.Name"`
and have it generate a C# script like this:
```
// Fix for rule: Partition names should match table names
(Model.Tables["Pandora Access"].Partitions["Partition"] as Partition).Name=(Model.Tables["Pandora Access"].Partitions["Partition"] as Partition).Table.Name
```
or
```
// Fix for rule: Partition names should match table names
(Model.Tables["Pandora Access"].Partitions["Partition"] as Partition).Name=(Model.Tables["Pandora Access"] as Table).Name
```

**Comment by otykier** [comment]
This has been discussed before. See #721. We can't allow arbitrary script executions, but based on your suggestion, I made a change that allows us to use the keyword `it` in the FixExpression, to generate a reference to the current object being analysed.

Thus, for your example, you can set the FixExpression as follows:

```json
"FixExpression": "Name = it.Table.Name"
```

This syntax will be possible with version 2.16.1, which will be released shortly.

**Comment by otykier** [comment]
[2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1) allows to use the `it` keyword as described above.

**Comment by m-kovalsky** [comment]
Since the scope of this rule is on the table, I believe the following code will work as the FixExpression now. Just tried it out and it works.

"FixExpression": "Partitions[0].Name = it.Name"

**Comment by m-kovalsky** [comment]
@alwortman by the way, the Best Practice Rules were updated to leverage this capability:

https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules
