### ISSUE TITLE
Detect changes in files/new files in underlying folder and prompt for reload

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#85]
With source control methods, when merging changes from other branches when you still have the model open there is a real danger of accidentally (and silently) undoing the merge in the tabular model. This has already happened to us once in just a few days of using the tool in folder mode.

.e.g. I have tabular editor open in branch X, I merge from branch Y into branch X. tabular editor still has the old model in memory. If I now save the model in tabular editor I will overwrite Y's changes. In this case I have to be aware and reopen the database.json folder.

This is very error prone,

To solve perhaps put a filesystemwatcher and detect any changes/additions/deletes from the folders and prompt on what to do (just like VS does). 

It can also indicate if there are unsaved changes in the current model and provide options to ignore, overwrite etc. In this case the user may want to save the version currently in memory to a backup location and run a File compare between the two folders to merge changes that may not have been captured.

**Comment by otykier** [comment]
I see - good observation. The load from/save to folder functionality definitely still needs some work. At our company, we have a different workflow, where we exit Tabular Editor before each merge/fetch, so we haven't run into this issue.

But I agree that Tabular Editor should react to changes in the files and folders, and not just silently overwrite files. In fact, it even silently deletes files and folders that shouldn't be there, compared to what's in the currently loaded model. It's something to be aware about for sure. Hope it hasn't caused you too much trouble.

**Comment by otykier** [comment]
An update on this: A solution based on FileSystemWatcher will not make it for the 2.6 release. However, Tabular Editor will now check when a file was last written to, and prompt the user when attempting to Save a file that was changed while the model was loaded in Tabular Editor:

![image](https://user-images.githubusercontent.com/8976200/31251938-e2c91cf2-aa1f-11e7-80b3-c81b4a2d9307.png)

This also works when loading from/saving to a Folder Structure when individual files have changed. Hope this will be useful for now.

**Comment by o-o00o-o** [comment]
Thanks Daniel that is a great interim solution

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
