### ISSUE TITLE
Enable BPA rule file URLs for repos that require authentication

### ISSUE THREAD

**Issue by alwortman** [otykier/TabularEditor#850]
I'm trying to get our team to use a set of slightly customized BPA rules. We maintain this file in source control (GitLab Enterprise).

When I add the file to a project that has visibility set to "Public", I am able to add the URL in TE/TE3 without issue. However, when trying to add it to a project where visibility is "Internal" (any logged in enterprise user), the rules are not loaded.

I assume this has something to do with how TE is requesting the file data (anonymously).

I would like to be able to use a non-public repo rule file URL in TE.

Currently, I'm having the team specify a local rules file, pointing to their locally mapped source control branch, but that allows rules to be modified and saved back to the file, which I want to avoid.

**Comment by otykier** [comment]
TE is simply performing a web request to the provided URL. Adding custom authentication would be quite an overhead, as the web supports MANY different authentication schemes.

Specifically for Git repositories, I believe you can provide credentials as part of the URL. For example, for a file hosted on GitHub, you can do the following (I would assume something similar is possible with GitLab):

Token authentication:
```url
https://raw.githubusercontent.com/project/repository/master/README.md?token=ACEPOSG3QKN4V2XXXXXXXXXXXXXXX
```

Username/password authentication:
```url
https://username:password@raw.githubusercontent.com/project/repository/master/README.md
```

Have you tried that?

**Comment by alwortman** [comment]
@otykier as usual you're totally right. I had to do a little more digging on our specific on-prem version of GitLab, but in the end the solution was essentially what you suggested :)
