### ISSUE TITLE
BPA Scan not working in the Version 2.16.0

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#851]
**Describe the bug**
I installed the Latest version of TE today on the agent Machine which runs CI/CD Process.
I tried running the BPA Scan using CLI and it always says No rules violated, TE UI shows the Violations correctly but from CLI It doe not work.
Previous Version i.e 2.15.3 is working fine 

**To Reproduce**
Run the BPA Scan using Command-Line.
**Example :**
TabularEditor.exe "Model File Path\Model.bim" -A -V

**Expected behavior**
It should highlight Violations, 

**Screenshots:**
2.16.0 Version BPA Scan result -
![image](https://user-images.githubusercontent.com/55327056/118404864-64f21800-b692-11eb-9b3b-6d2bad37e1c6.png)

2.15.3 Version BPA Scan result -

![image](https://user-images.githubusercontent.com/55327056/118404885-7b986f00-b692-11eb-89f5-8869711611d6.png)

**Application specifics**
 - Tabular Editor version: 2.16.0
 - Semantic Engine used: Azure Analysis Services
 - Model Compatibility Level: 1400 and 1500

**Additional Issue**

While trying to roll back to previous versions I could not download them as all previous releases were pointing to the latest version link: https://github.com/otykier/TabularEditor/releases/latest/download/TabularEditor.Installer.msi .
Finally understood the previous version link was in the format: https://github.com/otykier/TabularEditor/releases/download/Version/TabularEditor.Installer.msi
It would be great if the Previous release  Links could be corrected.

**Comment by alwortman** [comment]
It might help to provide the .bim file if possible. I checked and we're running the 2.16.0 portable version in our release pipelines without issue.
![image](https://user-images.githubusercontent.com/13524879/118559658-1d649e00-b71d-11eb-8ca1-5e2e5c4a97ba.png)

**Comment by debashish10** [comment]
Hi @alwortman ,

Thanks for checking.
It actually is not working for any bim file from CLI from the latest version.
I am not using the portable version, can you also test it using the standard version and let me know if it works.

**Comment by otykier** [comment]
Sounds like a bug that was introduced when providing the new -AX option (see #821).

@debashish10 are rules defined within the model itself, are you referencing an external URL or file containing the rules, or do you rely on a rules for the local user/local machine?

If you can send a screenshot of what the "(Effective rules)" look like on the Tools > Manage BPA Rules dialog, that would be really helpful.

![image](https://user-images.githubusercontent.com/8976200/118770230-603f8680-b881-11eb-80b5-1c4c7ee62737.png)

**Comment by otykier** [comment]
Thanks! I located the error and will provide an update shortly (2.16.0 ignores local user/local machine files, which is a bug).

**Comment by debashish10** [comment]
Thanks a lot @otykier

**Comment by otykier** [comment]
Fixed in [2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1).
