### ISSUE TITLE
Incorrect DAX Syntax Error Warning

### ISSUE THREAD

**Issue by edhans** [otykier/TabularEditor#856]
!!! Please make sure you're using the latest version of Tabular Editor before submitting a bug !!!

**Describe the bug**
The measure below in the Repro steps shows an error with the NOT operator.

**To Reproduce**
This measure is in the Contoso database:
`As a Pct Of A Datum Sales = VAR varTotalADatum =
    CALCULATE(
        [Total Net Sales],
        NOT Products[Brand]
            IN {
            "A. Datum",
            "Contoso"
        }
    )
VAR RESULT =
    DIVIDE(
        [Total Net Sales],
        varTotalADatum,
        0
    )
RETURN
    varTotalADatum`

![image](https://user-images.githubusercontent.com/45298358/119692914-ac9a4180-be00-11eb-8e95-63a5abfcd257.png)

That measure is valid and works. No syntax error shown in Power BI Desktop or DAX.do.

**Expected behavior**
No syntax error shown.

**Observed behavior**
Syntax error  shown.

**Application specifics**
 - Tabular Editor version: 3.0 beta 18.4
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: 

**Additional context**

**Comment by otykier** [comment]
Transferred to Tabular Editor 3 issue tracker: https://github.com/TabularEditor/TabularEditor3/issues/5

**Comment by TabularEditor** [comment]
@edhans FYI this has been fixed in [BETA-18.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/BETA-18.5). Thanks for reporting!
