### ISSUE TITLE
SQL AS AMO Library Version Error

### ISSUE THREAD

**Issue by jroeder10** [otykier/TabularEditor#858]
I just upgraded from a previous version, installing v2.16.1.  When I run it, I get a "SQL AS AMO Library" error:

![image](https://user-images.githubusercontent.com/84877939/119731810-01f44400-be3d-11eb-8be1-b1c294bdc978.png)

1. Run C:\TabularEditor.exe (or run it through Power BI external tools)

I also installed the latest versions of the AMO and ADOMD libraries, downloaded from here (windows installer versions): https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=azure-analysis-services-current

I tried uninstalling tabular editor, and reinstalling. Also tried uninstalling AMO and reinstalling. Also tried rolling back Tabular Editor to previous versions from 2020. None of those worked. 

Finally, it appears this issue was reported years ago. https://github.com/otykier/TabularEditor/issues/172 The resolution was using the msi installer, which I did (just using the latest version). 

Thank you for your help.

**Comment by otykier** [comment]
Could you try to install the tool to a different location? In general, you shouldn't install applications into your `C:\` root. Specifically, Tabular Editor would need admin rights to load the dll's that are included with both the portable version and the installer, if you install it to this location.

**Comment by jroeder10** [comment]
Thanks for your quick response. The odd thing is, I chose to install it at the default location, which is C:\Program Files (x86)\Tabular Editor: 

![image](https://user-images.githubusercontent.com/84877939/119828714-10d00a80-bec0-11eb-8f8c-f53136d4faf4.png)

Once it finishes installing, it shows up in the root of C, and there is nothing in the program files location. I've never seen anything like that. 

I uninstalled and reinstalled this morning, with the same result. (The screenshot above is from this morning's install.) 

Here it is, in C:
![image](https://user-images.githubusercontent.com/84877939/119829027-6a383980-bec0-11eb-9104-6ac9b15cf80c.png)

Here is where it should be, but is not: 
![image](https://user-images.githubusercontent.com/84877939/119829124-88059e80-bec0-11eb-888b-3aef13ab3624.png)

**Comment by otykier** [comment]
Okay something VERY weird is going on with your machine. Your C: root folder also contains many other files that have nothing to do with Tabular Editor...

Anyway, could you try to download the portable version, unzip it and place the resulting folder and its contents within your Program Files (x86)? Then run the .exe file from there.

**Comment by jroeder10** [comment]
That worked, thank you!
