### ISSUE TITLE
Editing DAX expressions causes useless \r characters to be added to file.

### ISSUE THREAD

**Issue by danshryock** [otykier/TabularEditor#86]
If I edit a measure or column that was defined using the SSDT model editor, all lines in the expression get modified to include a \r suffix.  This causes problems when commiting model files to version control and trying to audit the changes that were made.

I was able to correct the issue in a local build by changing 2 lines in the `UIController_ExpressionEditor.cs` file:

in the `ExpressionEditor_AcceptEdit` method I changed:
```csharp
                ExpressionEditor_Current.Expression = UI.ExpressionEditor.Text;
```
to
```csharp
                ExpressionEditor_Current.Expression = UI.ExpressionEditor.Text.Replace("\r","");
```

and in the `ExpressionEditor_IsDirty` property I changed:
```csharp
                    return ExpressionEditor_Current.Expression != UI.ExpressionEditor.Text;
```
to
```csharp
                    return ExpressionEditor_Current.Expression.Replace("\r", "") != UI.ExpressionEditor.Text.Replace("\r", "");
```

I'm not sure if this is the best way to correct the issue, that's why I'm opening up an issue instead of a pull request.

Thanks!

**Comment by otykier** [comment]
Thanks for reporting this. One thing I would like you to check: Before and after editing a measure in Tabular Editor: Is the expression split into multiple lines in the Model.bim-file like so?

```json
Expression = [
    "First line in my expression",
    "Second line in my expression", 
    ...
]
```

Or is stored as just one multiline string in your Model.bim file? In the former case, are the `\r`s appended to each string in the array or how are they appearing for you?

**Comment by danshryock** [comment]
Before editing in Tabular Editor it looks like:
```javascript
"expression":[
  "line 1",
  "line 2",
  "line 3"
]
```

After editing in tabular editor, it looks like:
```javascript
"expression":[
  "line 1\r",
  "line 2\r",
  "line 3"
]
```

Thanks!
