### ISSUE TITLE
DAX parser and DAX editor availability

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#863]
Hello Daniel,
Big up to you and your team for TE3 !
You announced recently your DAX parser and DAX editor will be shared with DAX studio team. 
Will you share the source as well ? Otherwise, will it be possible to reuse DLLs in other software ? I might be interested in using your DAX parser in Power BI Sidetools external tool.
Thanks in advance for your reply.
Have a good day.

**Comment by otykier** [comment]
Hi Didier,
Please send me an e-mail at daniel@tabulareditor.com. It's a complex discussion that I'd rather have offline.
