### ISSUE TITLE
Translations not visible in PBI desktop

### ISSUE THREAD

**Issue by Dickkieee** [otykier/TabularEditor#865]
Hi,

Just added translations to the model, saved it and refreshed the data in Power BI desktop.
I expected to see all the added translations, but unfortunately they arent visible.
So we tried to set the region settings and the browser language to dutch, but both didnt work.
Perhaps Im doing something wrong or this is a bug. 

Some information

We are using Power BI Version: 2.93.981.0 64-bit (may 2021)
The version of the tabular editor that we are currently using is 2.16.7809.21202

![image](https://user-images.githubusercontent.com/42411261/120754482-05f32680-c50d-11eb-8637-0a8b052d1582.png)

**Comment by Dickkieee** [comment]
> Hello,
> If you want to see translations in the desktop, the browser setting will change nothing. Tabular Editor make it's work ; it's a desktop issue.
> 
> As explained in the video in this post, it worked in the past. I think there was a regression in the last desktop updates : https://thebipower.fr/index.php/2020/04/12/automatic-translation-of-tabular-model/
> 
> You may install March or April version to make it work.
> 
> More information in this series : https://thebipower.fr/index.php/category/power-bi-desktop/translations/

**Comment by Dickkieee** [comment]
@didierterrien Thanks for you reply!

So, I changed the version of PBI 
![image](https://user-images.githubusercontent.com/42411261/120807104-e0374300-c547-11eb-8bf4-7e95292cdc11.png)

and checked the links that you shared with me. For some reason I get the same situation like above when using the example files with this version of PBI.  Im wondering what is going wrong.

Kind regardz,

Dickkieee

**Comment by didierterrien** [comment]
Did you change the regional settings in desktop's options like I did in the video ?

**Comment by didierterrien** [comment]
According to issue #864, you need to revert to February desktop version

**Comment by Dickkieee** [comment]
Good afternoon Didier,

Youre right. The February desktop version is showing the translation.  Thanks for your help. Now lets hope a future release of PBI will support the translations again.
