### ISSUE TITLE
Saving new CALCULATION GROUP/ITEM removes default summarization and data type from fact table columns

### ISSUE THREAD

**Issue by phasedephase** [otykier/TabularEditor#871]
![Screenshot 2021-06-17 181515](https://user-images.githubusercontent.com/8108706/122482816-489e0f80-cf9f-11eb-9c9c-23424b98c448.jpg)
**Describe the bug**
After saving for the first time a new calculation group with 1 calculation item, the default summarization and data type from fact table columns disappear and breaks existing measures using these columns.  In the screenshot, all the sum symbols in the red boxes disappear. This is the first time I use a calc group, so it is a try with a simple calc item.

**To Reproduce**

I assume prior installing of Tabular Editor Open Source as an external tool inside Power BI.

1. Open a current Power BI report.
2. Click on External Tools in menu bar.
3. Click on Tabular Editor icon (launch TE).
4. In TE: Right click on Tables and select Create New --> Calculation Group.
5. Rename the calculation group using the info pane that appears on the right when the group is selected.
6. Right click Calculation Items and select New Calculation Item.
7. Rename the calculation item by using the info pane that appears on the right.
8. Rename the Name column of the calculation group using the info pane on the right.
9. Write DAX code in the Expression Editor.
10. Save by clicking the 3rd icon from the left in the toolbar.
(11. Don't remember if at this point TE asks to update the Power BI model. But if it does, I always accept and click Yes or OK.)

At which point, the new calculation group appears as a new table in the table list in Power BI. 

**Expected behavior**
I expect the aforementioned actions not to change the column definitions in my already existing fact tables.

**Observed behavior**
The calculation item works. But the actions mentioned above break existing measures because columns that were defined as Whole Number types with an assigned default Summarization suddenly do not have the same type and have no summarization assigned any more.

As a result, I can't use calculation groups.

**Application specifics**
 - Tabular Editor version:  2.16.7809.21202
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: 1500

**Additional context**
No additional context.

**Comment by marcosqlbi** [comment]
Implicit measures are not supported in calculation groups. This is by design in Power BI and it's not a Tabular Editor bug.
Read more here: https://www.sqlbi.com/blog/marco/2019/03/01/calculation-groups-in-dax-first-impressions/

**Comment by phasedephase** [comment]
@marcosqlbi Thank you Marco for taking the time to respond. Duly noted.
