### ISSUE TITLE
Calculated Table Columns Not Recognised

### ISSUE THREAD

**Issue by jaywalkar** [otykier/TabularEditor#872]
Version: Tabular Editor 3 v3.0.6
Semantic Engine used: Power BI 
Model Compatibility Level: 1500

I have created a calculated table using NATURALLEFTOUTERJOIN, and any column or the right side of the join is not displayed in tabular editor. These columns are therefore not possible to work with in Tabular editor, but more importantly, whenever I push an update to my model in Power BI, the relationship that has been created between one of these columns and a column from another table in my model dissappears.

Not sure if this is expected behaviour (if so this can be moved from bug to enhancement).

**Comment by otykier** [comment]
Moving issue to [TabularEditor3](https://github.com/TabularEditor/TabularEditor3/issues/103)
