### ISSUE TITLE
Object Dependency list double click stops refreshing Expression Editor

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#88]
After a few uses of the Dependency editor and doubleclicking on a measure, changing the dax, and repeating a few times, I found that the field was being selected in the exporer pane but the Expression editor stopped getting updated. I had to find the field in the explorer (that was highlighted due to the double click from dependencies) and double click on the field in explorer for the Expression Editor to update.

It would be great if this could be made more reliable as the dependency feature is awesome.
Thanks

**Comment by o-o00o-o** [comment]
Thinking about it It might be because I didn't click the accept changes tick icon at the top of the expression editor.. but if so this isn't very intuitive I would expect automatic acceptance (or prompting) if I'd changed the expression but not clicked the tick or cross?

**Comment by otykier** [comment]
Yeah, the expression editor and the accepting/rejecting of an expression change is indeed something I would like to redesign to make it more intuitive. In early releases of Tabular Editor, clicking a different object in the tree pane would immediately save any changes to the currently selected object's expression, and then switch to view you the expression of the newly selected object.

The reason I changed this, was that I would like to be able to drag and drop measures/columns/tables into the expression editor, while editing the expression of an object. And in order for this to work, I had to "freeze" the selected object in the expression editor.

But perhaps the drag and drop into the expression editor isn't at all that useful (especially if I manage to get some simple IntelliSense working at some point). And in that case, it would probably be more intuitive to have the expression editor always show the expression of the currently selected obects, and auto-commit any changes whenever you switch between objects.

Worst case, I could make this a user-preference...

**Comment by o-o00o-o** [comment]
Yeah personally I don't find the dragging and drop code creation very useful as I prefer to have hands on the keyboard all the time but I can imagine this could be nice for some. 

However I would expect you can detect the difference between a drag event than a click event so would have thought that you can have both without the need for an accept/reject confirmation button?

If someone clicks without dragging then yes it would commit the current code, but if they drag then it can leave the current measure active?

**Comment by otykier** [comment]
> If someone clicks without dragging then yes it would commit the current code, but if they drag then it can leave the current measure active?

This was exactly what I initially intended. The reason it wasn't implemented this way, was because the Tree-component is a 3rd party component which doesn't distinguish between clicks and click-and-drag. At the time, I didn't want to get too deep into modifying the 3rd party component, but since then I've already made some changes, so might as well revisit this now. I agree completely that this would be a more intuitive way of working.
