### ISSUE TITLE
Dependencies list doubleclick doesn't always highlight the intended target

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#89]
I have the following dependency list
![image](https://user-images.githubusercontent.com/13693159/29405916-4c9048a0-8337-11e7-8976-4370e899336d.png)
When I doubleclick on [Transactions Anonymous] it actually selects [Transactions Anonymous TY YTD]
![image](https://user-images.githubusercontent.com/13693159/29405945-6bdac37a-8337-11e7-8e17-3ea705d9dd47.png)
I think this is because doubleclicking also expands the sub dependencies and as a result of this change in lists whatever is underneath my mouse at the point after the expand/collapse seems to be the target for the invocation in the explorer.
I think this becuase if I then doubleclick on Transactions Anonymous again (with the subdep expanded) it then selects [Tracked Sales Barcoded Identified Net] which is what is under my mouse after the double-click causing the collapse.
![image](https://user-images.githubusercontent.com/13693159/29406066-d9453a12-8337-11e7-8f2a-6613d71c53b3.png)
Hope this is enough information to repro

**Comment by otykier** [comment]
Should be an easy fix - will get back to you :-)
