### ISSUE TITLE
Dependencies feature does not consider relationships to other tables

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#91]
Currently if I click on a Dimension table and use the dependencies method it will not tell me if another table depends on it or vice versa based on a relationship. This would be very useful as although you can generally identify the many table side from the relationships list the "one" side of the relationship is not orderable. It would be very useful if both sides were considered in the Dependencies feature.

**Comment by otykier** [comment]
Although this is a good suggestion, I would like to keep the "Show dependencies" feature as it is, since strictly speaking, you could have a relationship between two tables without there being a dependency from a DAX point of view. Removing a dimension table from a model, for example, would generally not break anything, unless you have calculated columns or measures that explicitly reference columns from that dimension - and in that case, they would appear in the "Show dependencies" box.

So if all you need, is a quick way to determine what relationships exist on any given table, I suggest you simply type the name of the table into the Filter-box and hit [Enter], and you should see only relationships in which that table participates (enclose the table name with single quotes to avoid partial matches):

![image](https://user-images.githubusercontent.com/8976200/29935009-9c9b1eb4-8e7d-11e7-891b-2502126c0848.png)

Do you think this is workable?

**Comment by TravisKale** [comment]
otykier, in my opinion relationships should be shown in the dependencies.  Relationships are a part of the model and when I use the dependencies feature I want to see everything that references the object.  I'm not understanding why seeing the relationships in the dependency view would be a bad thing.  I would think that if we don't care about the relationship part, we could just ignore that information.

If you prefer not to  show relationships in the 'dependencies' list, how about a 'find all usages' feature?

Just my opinion, thanks for providing this great tool to the community.  It's outstanding.

**Comment by o-o00o-o** [comment]
I understand what you are saying that a relationship isn't strictly a dependency however the dependencies does provide a very useful recursive model which would be a very useful developer tool. And you already have a great UI for this ready and waiting. 

The way that I see it is that us developers will want to know what we are likely to break given a certain change in structure and we use the Dependencies feature to find this out . Now DAX will be an immediate break which is what it shows and we would need to fix that, but the relationships would be a "hidden" break that could just break peoples reports that are based on our reports. It would be very useful to see this without having to remember to check in this other way also..

I guess we can manually go through multiple layers of relationships by using the filter as you suggest but this is very cumbersome especially in complex models with multiple layers of tables. Having a different icon to show a relationship "dependency" seemed to be a nice solution to this.

Is this a lot of work or is there some other reason why you don't really want to implement this?

**Comment by otykier** [comment]
Thanks for the comments, both of you. It's not a lot of work, I guess I just never saw much need for this myself. I see your point, though, but I have some concerns:

- The icons in the UI show what type of objects are involved in the dependencies, not the type of the dependency between them, which would make it difficult to distinguish between DAX dependencies and relationships.
- Directionality - when a relationships exists between two tables, the notion of "Show objects on which X depend" versus "Show objects that depend on X" would be confusing, I think. Especially for relationships using bi-directional filtering.
- Should the UI represent relationships between two columns as dependencies between the two, or rather as dependencies between their parent tables?
- Should inactive relationships be shown as well?

In fact, thinking about this, I guess the best option would be to add a 3rd radio button, "(o) Show relationships starting from X". When clicked, the UI would simply show a tree starting with the currently selected object (column or table), and as you expand the tree you can follow the relationships outward as deep as you need. I guess inactive relationships could be indicated visually.

Kindly let me know what you think about this?

**Comment by o-o00o-o** [comment]
Yeah i think your suggestions are exactly where i was going as you posed the questions. Thinking further it might be useful to indicate [1..*] [*..1] or [1..1] perhaps at the beginning of the node name and also filter direction somehow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by otykier** [comment]
Hi all,
I have been working on adding this feature to the "Show dependencies" box. Currently, it looks like this:

![image](https://user-images.githubusercontent.com/8976200/30227857-9016db9c-94db-11e7-8db9-6368e1729df3.png)

The 1's and n's indicate cardinality between the parent node's table and the child table, the arrow indicates filter direction and gray text indicates an inactive relationship. Tooltip shows the name of the relationship, indicating which columns participate. For now, this only works when a table object is selected in the Explorer Tree.

Would this be useful in your case?

**Comment by o-o00o-o** [comment]
Looks great! Do you have a double ended arrow for bi-directional filter?

**Comment by otykier** [comment]
Sure - I just use these unicode symbols:

←
→
↔

![image](https://user-images.githubusercontent.com/8976200/30232468-87fcad00-94f0-11e7-952c-1ea2daaccbe3.png)

**Comment by o-o00o-o** [comment]
Looks great!

One thought on this, it would be really useful if we could copy and paste as text and this is represented as an indented hierarchy. Also it would be useful to be able to exclude inactive relationships.

We maintain a document for our analysts that lists the active relationships and it would be great if this was a simple copy/paste job

Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by otykier** [comment]
Added a right-click menu to the dialog, and a checkbox to show/hide inactive relationships:

![image](https://user-images.githubusercontent.com/8976200/30830499-7db46dea-a244-11e7-9561-d329e337efa6.png)

You have two options for exporting the tree. The first (Ctrl+C) is just a simple indented hierarchy, similar to what you see on the screen. In the clipboard it will look like this:

```
(1 → n) 'Internet Sales'
    (n ← 1) 'Customer'
        (n ← 1) 'Geography'
    (n ← 1) 'Product'
        (n ← 1) 'Product Subcategory'
            (n ← 1) 'Product Category'
    (n ← 1) 'Promotion'
    (n ← 1) 'Sales Territory'
    (n ← 1) 'Currency'
```

The JSON option will provide more details about the relationships and the involved objects:

```json
{
  "ObjectType": "Table",
  "ObjectName": "Internet Sales",
  "RelatedTo": [
    {
      "ObjectType": "Table",
      "ObjectName": "Customer",
      "ByRelationship": {
        "DisplayName": "'Internet Sales'[CustomerKey] --> 'Customer'[CustomerKey]",
        "IsActive": true,
        "FromColumn": "'Internet Sales'[CustomerKey]",
        "FromCardinality": "Many",
        "ToColumn": "'Customer'[CustomerKey]",
        "ToCardinality": "One",
        "CrossFilteringBehavior": "OneDirection"
      },
      "RelatedTo": [
        { ... }
      ]
    }
  ]
}
```

The JSON output could be pulled into a tool such as Power Query, to easily extract whatever information you need from it.

**Comment by o-o00o-o** [comment]
Fantastic, that lools awesome thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
