### ISSUE TITLE
Allow calling 3rd party code through Advanced Scripting

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#92]
The [.Output() function is useful for debugging scripts](https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting#debugging-scripts) in Tabular Editor, but it could also be used for documentation purposes.

For example, the following script will output the names and expressions of all measures in the currently selected tables, as a string with one measure per line:
 
```csharp
String.Join("\r\n", Selected.Tables.SelectMany(t => t.Measures)
    .Select(m => m.DaxObjectName + "\t" + m.Expression).ToArray()).Output();
```
Which looks like this:
![image](https://user-images.githubusercontent.com/8976200/29942330-cea171b6-8e95-11e7-87f2-d4ec430b01c0.png)

From this window, the text can be copied and inserted into an Excel sheet, for example. However, for multi-line expressions, this doesn't work very well. An alternative is to let the script output the documentation directly to a file, using `System.IO.File.WriteAllLines( ... )`, for example.

Originally, I wanted to improve the functionality of the `.Output()` method, but since Tabular Editor 2.5 now has some plug-in support, I think it would be better to allow scripts to reference code in the plug-in DLLs directly. This way, a developer could create his own library of extension methods for use in scripting and Tabular Editor Custom Actions. A documentation plug-in could then be easily created, which could, for example, provide methods for generating documentation in various formats, displaying relationship diagrams on the screen, based on which tables are selected in the Explorer tree, etc.

**Comment by o-o00o-o** [comment]
This is a great idea and along the lines of something that I was just looking into. We want to be able to automate a soft-breaking change process, for example when we rename a field we create a new field with the new name, hide the old one, then give a 2/4 week period of parallel running to allow report writers to change their reports to use the new field before we delete it.

I would like to be able to use annotations drive this but also to produce reports of the current versions breaking changes to use for communication, probably as an XML format file
