### ISSUE TITLE
Best Practice Analyzer Exception issue

### ISSUE THREAD

**Issue by SQLBent** [otykier/TabularEditor#97]
Creating a  rule in the Best Practice Analyzer and it contains an error it throws and exception and therefore it does not enable the edit button the rule.

When this happens it is no longer possible to edit or remove rules in the interface

**Comment by otykier** [comment]
I am not able to reproduce this in 2.6, as you can see in this screenshot, the rule contains an error (shown at the bottom of the screen), and the "Edit rule..." button is still enabled:

![image](https://user-images.githubusercontent.com/8976200/31329729-c7f59662-acdb-11e7-9835-0e8899f46068.png)

Could you provide more details on how to reproduce the bug?

**Comment by otykier** [comment]
Could you please provide more details on how to reproduce this bug? Otherwise, the issue will be closed.
