### ISSUE TITLE
Model level Expressions and their Dependencies

### ISSUE THREAD

**Issue by jawa-the-hutt** [otykier/TabularEditor#99]
I've inherited a complex (to me anyways) model that has a lot of expressions built into it that essentially are shared functions that are used across the model among multiple tables and/or partitions.

These expressions may reference multiple other expressions.  For instance, a partition on a table may contain a generic create table expression/function that takes in several parameters.  This expression/function may in turn call other built in as well as custom expression/functions that do things like Add Columns, Rename Columns, etc.

The point I'm getting at is in Tabular Editor, I don't see how to get access to these deeper level functions that are referenced by the partition creation function.  I can see and edit the top level partition creation function just fine in the Expression Editor, but nothing underneath that may be used within that called expression/function.

example of this top level partition creation function:
```
let
    Source = MakeTable(param1, param2, param3, param4, param5)
in
    Source
```

the MakeTable function could have something like this in it:
```
    ColumnNameTrimmed = Text.Trim(if Text.EndsWith(param4, "Date") then Text.Start(param4, Text.Length(param4) - 4) else param4),
    Exceptions = Text.ToList("z"),
    ModelTableNameSplit = SplitName(param3, Exceptions),
    ColumnNameTrimmedSplit = SplitName(ColumnNameTrimmed, Exceptions)
```

The deeper level expression/functions like `SplitName` don't show up anywhere that I can see.  So, need to see if this is possible today and if not, then have it added as a feature request.  The expression/functions are all there in the model.bim file, so I guess it's a matter of walking the json to define all the functions and then from a dependency standpoint, you'd have to do some recursion to figure out where it's being used to help track where to add it.

**Comment by jawa-the-hutt** [comment]
Guess I should add that I'm using v2.6-1400 and the model itself is 1400 level compatibility.

**Comment by otykier** [comment]
I tried creating a new model in Visual Studio based on M functions similar to what you describe. However, it seems that Visual Studio is generating one table for each M query I create - also for functions, etc. In the Visual Studio UI, these show up as empty tables with no columns... In Tabular Editor, I was able to locate the M expressions under "Table Partitions" - it looks like this:

![image](https://user-images.githubusercontent.com/8976200/31375200-0a9ec180-ada1-11e7-9bb0-17730c6b1103.png)

I couldn't find a way to create these "hidden" expressions that you're mentioning. Any chance you could send me some more information? If not the entire Model.bim file, then just the parts of it concerning the expressions that do not show up in Tabular Editor?

**Comment by jawa-the-hutt** [comment]
@otykier  what's the best way to send you the model.bim file privately?

**Comment by otykier** [comment]
Feel free to drop me an e-mail: do@kapacity.dk

**Comment by otykier** [comment]
After investigating closer, I see that Compatibility Level 1400 models contain a collection called "Expressions" at the Model level, which holds the information you're missing. This is [not in documentation](https://msdn.microsoft.com/en-us/library/microsoft.analysisservices.tabular.model.aspx) for the TOM, so I was unaware of this collection until now.

Anyway, I will provide an updated build of Tabular Editor, where the Expressions collection is exposed in the explorer tree, directly under the "Model" node. When you expand the Expressions collection, Tabular Editor will show the individual NamedExpression objects. Each of these have the following properties (which will be visible and editable in the Property Grid):

- Annotations
- Description
- Expression (duh)
- Kind (only one option: "M")
- Name

**Comment by jawa-the-hutt** [comment]
Awesome.  Thanks for taking a look at this so quickly.  Looking forward to the new features down the road.

**Comment by otykier** [comment]
A new pre-release is now available for download [here](https://github.com/otykier/TabularEditor/releases/tag/2.6.1). You will have the honor of testing this functionality, to see if it suits your needs :-)

Below is how it will look in the UI. Note that the "Show Dependencies" box does not consider these expressions, as currently Tabular Editor can only resolve dependencies between DAX expressions:
![image](https://user-images.githubusercontent.com/8976200/31409006-b4e6db46-ae0a-11e7-8533-d86386cac25a.png).

**Comment by jawa-the-hutt** [comment]
ok, i'll grab this later this evening (my time) and take a look. thanks again for the quick turn around.

I think ultimately for this to be fully functional, it will need the ability to walk the dependencies and warn the user that if they delete shared expression, that it is used by other expressions and then list the dependency tree.

**Comment by jawa-the-hutt** [comment]
Tested with the pre-release build this evening and everything appears to function as I would expect.  Good job on getting this added so quickly.

**Comment by otykier** [comment]
Thanks - parsing of M expressions (in order to establish dependencies between expressions and between table columns and partition queries) is on the backlog.
